### ISSUE TITLE
FormatException: Method cannot be patched. Reason: Invalid IL code

### ISSUE THREAD

**Issue by dymanoid** [pardeike/Harmony#105]
I have a very strange issue. Using Harmony 1.1.0.
This is again a patch for the **Cities:Skylines** game.

I have an x64 assembly that perfectly works on my system: Windows 10 64bit. No issues, the patching works very well.
A Steam user reports an exception with the same assembly on his machine: Windows 10 64bit, same game version, same binary of my assembly.

The exception is:

```
System.FormatException: Method WorldInfoPanel.UpdateBindings() cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) WorldInfoPanel:UpdateBindings_Patch1 (object): IL_007f: stfld     0x0000001f

  at Harmony.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, Harmony.PatchInfo patchInfo, System.String instanceID)
  at Harmony.PatchProcessor.Patch ()
  at Harmony.HarmonyInstance.Patch (System.Reflection.MethodBase original, Harmony.HarmonyMethod prefix, Harmony.HarmonyMethod postfix, Harmony.HarmonyMethod transpiler) 
```

Again, I cannot reproduce this on my machine. The game recompiles the assemblies with Mono, so I thought the user has a Mac or a Linux version and that causes some binary incompatibility. But no - Windows 10 64bit, exactly like mine. There are hundreds of other users having no issues too.

What can we do to diagnose this issue and find a solution?

Maybe this is somewhat similar to #38, but the exception is **FormatException** in my case.

**Comment by pardeike** [comment]
Could easily be another mod that user has installed, also changing this method and leading to incompatibilities.

**Comment by dymanoid** [comment]
Do you mean a "direct" patch?

**Comment by pardeike** [comment]
I think the IL code of that message could be changed by another mods transpiler before or after you change it. Have you tried to turn on the debug log of Harmony to see the result of your transpiler and to verify if it produces correct IL code?

**Comment by dymanoid** [comment]
Now having the same exception with another game method:

    System.FormatException: Method WeatherManager.SimulationStepImpl(System.Int32) cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) WeatherManager:SimulationStepImpl_Patch1 (object,int): IL_0025: stfld     0x00000009

I'm not using any transpilers in my patches, just plain prefixes and postfixes. Does a debug log help in this case?

**Comment by pardeike** [comment]
Yes. Use `HarmonyInstance.DEBUG = true` before the patch assignment an it will give you a log file on your desktop. Post the part that shows the IL of your patched original method. Thanks

**Comment by dymanoid** [comment]
And another comment: the user reports that sometimes it works.

In the log file, I see that there are multiple mods that load different Harmony assemblies:
0Harmony, Version=1.0.9.1
0Harmony, Version=1.1.0.0 (my mod)
0Harmony, Version=1.1.1.0

Could the invalid IL be caused by some conflict of which Harmony version "wins"?

**Comment by pardeike** [comment]
Please test again with the latest HEAD. I made a few changes and bug fixes regarding loading and unloading of mods and patches. Specifically, transpilers were not correctly removed.

**Comment by dymanoid** [comment]
Unfortunately I cannot test it actually. On my dev machine, I cannot reproduce the exceptions. But I'm not willing to deploy a not-yet-released library to 15,000+ players just to see if something became better. I have to wait for the next official Harmony release.

**Comment by dymanoid** [comment]
Okay, the 1.2.0.1 is out. Despite it has a bug that potentially might lead to a crash due to a `MissingFieldException` (see #115), I will roll out this version and let the players test whether the `FormatException´ described in the original post is fixed.

**Comment by dymanoid** [comment]
Okay, I didn't check the `Traverse` implementation, my bad. There will be no `MissingFieldException`. However, due to a potential hash collision, the Harmony code might get a wrong version field value (0). I cannot say what happens then, but it's a thing I'm not expecting in a library that messes with the IL code on such a low level.

**Comment by dymanoid** [comment]
This issue seems to be fixed. No more user complaints with version 1.2.0.1.
