### ISSUE TITLE
Regression - Simple Prefix patch broken

### ISSUE THREAD

**Issue by EchterAgo** [pardeike/Harmony#106]
I've bisected a problem I had with extremely simple prefix patching to 4785d765c1ba15e8bf514f4d2188c5668ded0a81

I tried to patch a method with this signature:

```c#
protected override void OnDeserialization(object sender)
```

using this patch:

```c#
[HarmonyPatch(typeof(MyType))]
[HarmonyPatch("OnDeserialization")]
class MyTypePatch
{
	static bool Prefix(MyType __instance, object sender)
	{
		return false;
	}
}
```

and I got an exception saying

`Exception: Parameter "sender" not found in method Namespace.OnDeserialization(System.Object)`

Of course the sender parameter exists, and reverting to f281d3d3424a4ba25c0a30c6a749cc5aecb6a6e3 makes my code work fine.

**Comment by pardeike** [comment]
Hmm, I would be surprised if that commit would have broken simple argument name lookups because that would certainly break most if not all usages of Harmony. Are you sure that the only thing you changed was the different versions in the commit history?

And just to be sure: since you do not provide any Type[] in your annotation that patch would match an existing OnDeserialization() method that has no arguments.

**Comment by EchterAgo** [comment]
I am sure I only changed the Harmony, I used git bisect to arrive at the bad commit. I can make the behaviour consistently appear and disappear by switching between 4785d765c1ba15e8bf514f4d2188c5668ded0a81 and f281d3d3424a4ba25c0a30c6a749cc5aecb6a6e3.

I had the type argument in the beginning, but I removed it because the documentation states it is optional if there are no overloaded methods with the same name.

I'll try to isolate a test case for this.

**Comment by EchterAgo** [comment]
Here you go, same issue, minimal program.

[HarmonyIssue106Test.zip](https://github.com/pardeike/Harmony/files/2185526/HarmonyIssue106Test.zip)

**Comment by EchterAgo** [comment]
Even smaller:

```c#
using Harmony;
using System;
using System.Reflection;

namespace HarmonyIssue106Test
{
    class Program
    {
        public class TestClass
        {
            public void OnDeserialization(object sender)
            {
                Console.WriteLine("In TestClass.OnDeserialization");
            }
        }

        [HarmonyPatch(typeof(TestClass))]
        [HarmonyPatch("OnDeserialization")]
        class TestClassPatch
        {
            static bool Prefix(TestClass __instance, object sender)
            {
                Console.Write("In TestClassPatch.Prefix");
                return false;
            }
        }

        static void Main(string[] args)
        {
            var harmony = HarmonyInstance.Create("net.loping.patch");
            harmony.PatchAll(Assembly.GetExecutingAssembly());

            var derived = new TestClass();
            derived.OnDeserialization(new object());
        }
    }
}
```

**Comment by EchterAgo** [comment]
`GetArgumentIndex` returns -1 even though `originalParameterNames` contains "sender" and `patchParam` is a `ParameterInfo` with `Name` "sender". I'm not really sure what that function is supposed to be doing, but it doesn't seem right for me, and the function was touched in 4785d765c1ba15e8bf514f4d2188c5668ded0a81

**Comment by wasabii** [comment]
Was just about to report this. Had it happen against 1.1.1 just a second ago. Reverted to 1.1.0 and the problem went away.

**Comment by pardeike** [comment]
I'll have a look and fix it asap. Thanks for the test case.

**Comment by EchterAgo** [comment]
@chaintip

**Comment by pardeike** [comment]
Please verify that https://github.com/pardeike/Harmony/commit/b8f62a997ac2e56128110026d88c4f0eb1a93db8 fixes this problem.

**Comment by EchterAgo** [comment]
Yes, b8f62a997ac2e56128110026d88c4f0eb1a93db8 seems to have fixed the problem. However, master build is broken right now:

`HarmonyMethod.cs(15,10,15,20): error CS0246: The type or namespace name 'MethodType' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by pardeike** [comment]
My bad. I had uncommited changes and did not see the reference. Latest master builds and tests fine for me.

**Comment by chaintip** [comment]
@EchterAgo, ChainTip was down but is up again now. In case you missed it, there is a message [here](https://github.com/chaintip/talking-in-public/issues/235) for if you still wish to fund this issue.

**Comment by chaintip** [comment]
I missed that this was already closed, so you probably don't still want to fund it :) Hope it works better for you next time. Sorry about that!
