### ISSUE TITLE
[Suggestion] Unpatching methods

### ISSUE THREAD

**Issue by zatherz** [pardeike/Harmony#11]
I went through the wiki and some of the source code and I can't find any method for doing this. Would it be feasible to implement an interface for removing a hook from a method?

**Comment by Beowulfe222** [comment]
Agreed, this would be a very useful function... If it's already in place, would great to have some information on how to handle it.

**Comment by pardeike** [comment]
I will consider this in the next release unless it breaks stuff. But I am confident that it does not.

**Comment by pipe01** [comment]
Any updates on this?

**Comment by pardeike** [comment]
I’m stuck in West Sahara right now, so this has to wait until next month. Sorry.

**Comment by pipe01** [comment]
That's cool, don't worry. Enjoy your visit...?

**Comment by pardeike** [comment]
Hi again. My trip was... interesting :-)
I close this issue because I just added two API calls:
```csharp
public void RemovePatch(MethodBase original, HarmonyPatchType type, string harmonyID = null);
public void RemovePatch(MethodBase original, MethodInfo patch);
```
to `HarmonyInstance`. The first one scans for all patches matching the last two parameters (harmonyID "*" is a wildcard and null means current instance only). The second one takes a patch method and removes it.

Enjoy

**Comment by pipe01** [comment]
That's awesome, thanks! But how would I get that `harmonyID`?

**Comment by pardeike** [comment]
You probably do not need to. If you have the MethodInfo of your patch, just use the second form of RemovePatch(). If you want to remove some elses patch, you need to find out what ID they use to instantiate Harmony. Or you use the GetPatchInfo() function to list all patches. Each patch has the methodinfo and of course the harmony ID too.

**Comment by pipe01** [comment]
Alright, thanks again!
