### ISSUE TITLE
C:S won't build assembly with harmony

### ISSUE THREAD

**Issue by toxicaliengf** [pardeike/Harmony#112]
Hi,
When trying to use harmony in cities:skylines, I run into compile errors: https://i.gyazo.com/4f102c3b43f13b5e0066ed03f8926b3f.png

However, in visual studio, 0harmony seems to be referenced properly, no errors appear, and intellisense works correctly:
https://i.gyazo.com/d489c8e5f28317474ce92e95857d8e1c.png

Am I missing something obvious? If this isn't relevant to harmony, lmk & my apologies. thanks🌱

**Comment by pardeike** [comment]
You need to add 0Harmony.dll to your mod and make sure that CS loads it too (before your code is executed).
