### ISSUE TITLE
Don't use string hashes to test for equality

### ISSUE THREAD

**Issue by dymanoid** [pardeike/Harmony#115]
Found in commit 848940bc6430ba169b2b92785f8b371f3c327bb7.

You cannot use string hashes to test for equality. This is dangerous! E.g. read [here](https://stackoverflow.com/questions/4249064/using-gethashcode-to-test-equality-in-equals-override) and [here](https://blogs.msdn.microsoft.com/ericlippert/2010/03/22/socks-birthdays-and-hash-collisions/).

**Comment by dymanoid** [comment]
A hash collision **might** lead to a wrong behavior and in fact is slower that a simple string comparison.

Why using a potentially faulty and slower implementation?

**Comment by pardeike** [comment]
Fixed in 
https://github.com/pardeike/Harmony/commit/c219c62cea0f2b8297f5357c9e0aab24bbcf6935
