### ISSUE TITLE
Not compatible with ARM architecture

### ISSUE THREAD

**Issue by Lyt99** [pardeike/Harmony#118]
I'm trying to use Harmony on some Unity game, but when I installed the game to my mobile phone, it crashed with System.ExecutionEngineException: SIGILL.

So I think it may not be compatible with CPU of ARM architecture.
And according to [this](https://github.com/easy66/MonoHooker/blob/master/Assets/Scripts/UnityHooker/MethodHooker.cs#L78), I modified WriteJump() in Harmony.ILCopying.Memory to add
```c#
memory = WriteBytes(memory, new byte[] { 0x04, 0xF0, 0x1F, 0xE5 });
memory = WriteLong(memory, destination);
```
for arm64 and
```c#
memory = WriteBytes(memory, new byte[] {0x04, 0xF0, 0x1F, 0xE5});
memory = WriteInt(memory, (int)destination);
```
for arm32, it works fine.

But I couldn't find a appropriate way to get the CPU architecture (I use the method provided by Unity), so I just only post an issue :D

**Comment by pardeike** [comment]
Could this be of help?
https://stackoverflow.com/a/45373756/3351794

**Comment by Lyt99** [comment]
I've read about that before, and also other answers. And it's not applied to .NET Framework below 4.7.1, and enum ImageFileMachine has no ARM before .NET 4.5. It returns I386 in Unity on my mobile phone(the runtime is roughly equivalent to .NET 3.5).

I'll try to do more tests and find out some more common approach.

**Comment by jeason1997** [comment]
> I've read about that before, and also other answers. And it's not applied to .NET Framework below 4.7.1, and enum ImageFileMachine has no ARM before .NET 4.5. It returns I386 in Unity on my mobile phone(the runtime is roughly equivalent to .NET 3.5).
> 
> I'll try to do more tests and find out some more common approach.

Has this problem been solved?
Does it support the Android platform?

**Comment by jeason1997** [comment]
大佬，我才发现你是国人，请问你这个方法支持安卓手机吗？我想给我的安卓游戏做MOD支持

**Comment by Lyt99** [comment]
> 大佬，我才发现你是国人，请问你这个方法支持安卓手机吗？我想给我的安卓游戏做MOD支持

啊不，我就是个提issue的，我觉得问题目前没解决，我没找到更好的办法来判断cpu架构，并且我电脑一个多月前炸了，没再继续研究。如果有进度我会再提的

I don't think the problem has been solved, and I couldn't find some way to detect the architecture. What's more, my laptop has been broked a month ago and it let my work stucked. If there's any progress, I will come up with it (may be a pull request?) again.
