### ISSUE TITLE
Patch HttpWebRequest.GetResponse() is not working

### ISSUE THREAD

**Issue by vime500** [pardeike/Harmony#119]
I want to intercept HttpWebRequest.GetResponse()  for trace, my code:

```
public class Program
{
    static void Main(string[] args)
    {
        HarmonyInstance.DEBUG = true;
        var harmony = HarmonyInstance.Create("com.test");
            
        var targetMethod = AccessTools.Method(typeof(HttpWebRequest), nameof(HttpWebRequest.GetResponse));
        var prefixMethod = typeof(Program).GetMethod(nameof(PrefixGetResponse));
        var postfixMethod = typeof(Program).GetMethod(nameof(PostfixGetResponse));

        var m = harmony.Patch(targetMethod, new HarmonyMethod(prefixMethod), new HarmonyMethod(postfixMethod));

        var request = WebRequest.Create("https://www.google.com");
        var response = request.GetResponse();
        response.Close();

    }

    public static void PrefixGetResponse()
    {
        Console.WriteLine("PrefixGetResponse");
    }

    public static void PrefixGetResponse()
    {
        Console.WriteLine("PostfixGetResponse");
    }
}
```
but PrefixGetResponse and PrefixGetResponse not work. .net framework 4.6.1. 
Can anyone help me?

**Comment by pardeike** [comment]
Classes inheriting from MarshalByRefObject are kind of special and the JITed code and the stubs for them are also special cases that are not really implemented yet in Harmony. They also differ between .NET versions.

**Comment by Evengard** [comment]
It also may be that the AppDomain is different.

**Comment by pardeike** [comment]
Yeah, I’m inclined to close this as the original report is pretty vague and lacks information about the circumstances.

**Comment by pardeike** [comment]
After testing this case myself, I am pretty confident that classes and methods that inherit from `MarshalByRefObject ` are not patchable at runtime. Since MarshalByRefObject acts as a proxy class, I assume that simply pointing the assembler to a new implementation won't do it.

So unfortunately, this means that this issue will be a WON'T-FIX. Sorry.
