### ISSUE TITLE
Patching Private Generic Method - Example?

### ISSUE THREAD

**Issue by pkay42** [pardeike/Harmony#121]
In the game RimWorld, there are, in Verse/Widgets.cs

    public static class Widgets {
      ...
      private static bool IsPartiallyOrFullyTypedNumber<T>(ref T val, 
                          string s, float min, float max)
      {
        ....
      }
      private static bool IsFullyTypedNumber<T>(this string s) {
        ....
      }
      ....
    }

Could you give examples of how to use the Harmony annotation to patch both of these functions, assuming that I am only interested in patching when T is float?

I think this would cover many use cases that might be confusing.

Thank you very much!

**Comment by pardeike** [comment]
The annotations in Harmony don’t support generic methods. You would need to annotate with an empty annotation and add a TargetMethod() method to your patch class.

In there you use normal reflections to get the MethodInfo of the target and use MakeGenericMethod(type).

**Comment by pkay42** [comment]
You've stated

> [HarmonyPatch(Type, Type[])] Defines the type that contains the method to be patched (optional Type[] for generics)

Is that possible, or would one need to do something like
```C#
[HarmonyPatch()] // patch Verse.Widgets.IsPartiallyOrFullyTypedNumber
class Patch_Class {
  static MethodInfo TargetMethod() {
    return typeof(Verse.Widgets)
		.GetMethod("IsPartiallyOrFullyTypedNumber",
		           BindingFlags.NonPublic | BindingFlags.Static)
		.MakeGenericMethod(typeof(float));
  }
  static void PostFix() {} //etc
}
```

**Comment by pardeike** [comment]
The array in `[HarmonyPatch(Type, Type[])]` is for argument types and not generics. Currently, the only way to use generics is, as you already stated, to use `TargetMethod()`.

**Comment by pardeike** [comment]
Can I close this issue?

**Comment by pkay42** [comment]
So one would create something like:

```C#
[HarmonyPatch]
class My_Patch_Class {
  static System.Reflection.MethodBase TargetMethod() {
    // refer to C# reflection documentation:
    return typeof(...).GetMethod(...).MakeGenericMethod(typeof(float));
  }
  static bool Prefix() { /* etc */ } //etc //etc
}
```

Thank you, and yes, if I've got that right, please close.
