### ISSUE TITLE
Exception due to case-insensitive types (classes) during repatching

### ISSUE THREAD

**Issue by CabbageCrow** [pardeike/Harmony#123]
It happened when multiple mods with harmony patches targeting the same class, causing repatching/merging. 
One of the mods uses obfuscation to rename classes with the same names both upper and lower case e.g. K and k.
After turning test-wise the obfuscation off (all class names unique, even if case would be ignored) it works with no problems.
Harmony Version: 1.1.0

**Comment by pardeike** [comment]
I don’t understand what you mean when you write “One of the mods uses obfuscation to rename classes”. Can you clarify?

**Comment by pardeike** [comment]
A mod that is used *during* compiling. Like a compiler mod? I still do not understand at all what you mean.

**Comment by CabbageCrow** [comment]
No, I just meant when the mod was compiled, it got obfuscated. So the dll used later to mod the game has the replaced class and method names.

**Comment by pardeike** [comment]
Ok. You said in your first comment that one of the mods uses obfuscation to rename classes. So what about the other mod? Do you mean that once both mods are used after obfuscation you get the exception (what is the full exception)?

**Comment by CabbageCrow** [comment]
Full Exception:
> SerializationException: Could not find method 'IEnumerable\`1 Transpiler(IEnumerable\`1)' in type 'A.K'
>   at System.Reflection.MemberInfoSerializationHolder.GetRealObject (StreamingContext context) [0x00000] in <filename unknown>:0 
>   at System.Runtime.Serialization.ObjectRecord.LoadData (System.Runtime.Serialization.ObjectManager manager, ISurrogateSelector selector, StreamingContext context) [0x00000] in <filename unknown>:0 
>   at System.Runtime.Serialization.ObjectManager.DoFixups () [0x00000] in <filename unknown>:0 
>   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadNextObject (System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0 
>   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObjectGraph (BinaryElement elem, System.IO.BinaryReader reader, Boolean readHeaders, System.Object& result, System.Runtime.Remoting.Messaging.Header[]& headers) [0x00000] in <filename unknown>:0 
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.NoCheckDeserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) [0x00000] in <filename unknown>:0 
>   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) [0x00000] in <filename unknown>:0 
>   at Harmony.PatchInfoSerialization.Deserialize (System.Byte[] bytes) [0x00000] in <filename unknown>:0 
>   at Harmony.HarmonySharedState.GetPatchInfo (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
>   at Harmony.PatchProcessor.Patch () [0x00000] in <filename unknown>:0 
>   at Harmony.HarmonyInstance.<PatchAll>b__7_0 (System.Type type) [0x00000] in <filename unknown>:0 
>   at Harmony.CollectionExtensions.Do[Type] (IEnumerable\`1 sequence, System.Action\`1 action) [0x00000] in <filename unknown>:0 
>   at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <filename unknown>:0 
>   at TestProject_Harmony.xxx_Loader..ctor () [0x00000] in <filename unknown>:0

A -> namespace
K, k -> Patch classes with Annotations
It is patched with `PatchAll`
A.k contains a transpiler while A.K contains a postfix.
Yet it looks for a transpiler in A.K rather than A.k

Harmony Version: 1.1.0

```
namespace A
{
	[HarmonyPatch(typeof(SiloSlotUI))]
	[HarmonyPatch("Update")]
	internal class K
	{
		private static void Postfix(SiloSlotUI __instance)
		{
			__instance.bar.maxValue = (float)SRMMConfig.Instance.StorageLimit;
		}

		public K()
		{
		}
	}
}
```

```
namespace A
{
	[HarmonyPatch(typeof(PlayerState))]
	[HarmonyPatch("ApplyUpgrade")]
	internal class k
	{
		public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
		{
			// ...
		}
	}
}
```

```
[HarmonyPatch(typeof(PlayerState))]
[HarmonyPatch("ApplyUpgrade")] 
public class Patch_PlayerState_ApplyUpgrades
{
	static void Prefix(PlayerState __instance)
	{
		Console.WriteLine("Patch_PlayerState_ApplyUpgrades");
	}
}
```

**Comment by pardeike** [comment]
I have absolutely no idea if this is fixable at all.

**Comment by CabbageCrow** [comment]
I don't understand why the issue was closed. 
Was it fixed? Will it (maybe) in the future? Is it a "wont fix"?

**Comment by pardeike** [comment]
It’s definitely a special case and has no clear solution. There is no point in keeping it open and I therefore closed it. 

I can open it again if you can make a minimal test case and propose a solution.
