### ISSUE TITLE
Need to have possibility to declare method patch via argument type signatures instead of argument names

### ISSUE THREAD

**Issue by 6opoDuJIo** [pardeike/Harmony#124]
Use case is pretty simple : I need same patch be applied to several methods that issue method with same type arguments : 
`JobOnThing(Pawn, Thing, bool)`
The trouble is that different methods in different types declare those method arguments with different names, therefore, my patch method can't be applied to every method : 
`public static void JobOnThing(Pawn pawn, Thing thing, bool forced, ref Job __result)`
Possible solution : 
Method attribute that changes th way target method overload is located to "via type signature", but forces user to declare patch method have every argument be at the same place as within the target method argument list : 
```
/*target method*/public virtual Job JobOnThing(Pawn pawn, Thing t, bool forced = false):
/*patch method*/[MatchBySig] public static void JobOnThing(Pawn pawn, Thing thing, bool forced, ref Job __result);
```

**Comment by pardeike** [comment]
Is this really such a big issue? How many different versions of that method do you want to patch? If it's like three then simply repeating the patch class is a simple workaround.

**Comment by pardeike** [comment]
This is also pretty difficult to combine with other things like field injection and other injected arguments as it becomes unclear how to order them properly.

**Comment by 6opoDuJIo** [comment]
I suggest injected fields to be set up after last method argument. About the issue : well, currently, it's only 2 versions of that method in vanilla game, but I also want to cover other mods (talking about RimWorld context) with this patch, that might implement another "RimWorld.WorkGiver_Scanner" inheritee.

**Comment by pardeike** [comment]
Seems like too much code for too little effect. For now I think this will be a wontfix. I have to be careful to not put too much stuff into Harmony. It bloats the API, the documentation and my maintenance.

**Comment by 6opoDuJIo** [comment]
Second workaround might be even simplier : just allow us to return collection from CalculateMethod

**Comment by pardeike** [comment]
Reopen if you have a case that makes it really difficult to find a workaround.
