### ISSUE TITLE
Hope can support android platform

### ISSUE THREAD

**Issue by jeason1997** [pardeike/Harmony#13]
I just want to make some mods for an android unity game

**Comment by pardeike** [comment]
More information?

**Comment by jeason1997** [comment]
I'm so sorry for reply to you so late, and I want it to support the Android platform because I want to make MOD support for a sandbox game developed with unity. I can't expect you to make time for this feature. I just want to know if there's any possibility of supporting the Android platform, and what techniques should I need? I'll study it myself. Thank you very much.
