### ISSUE TITLE
Verbose tutorials with verbose examples

### ISSUE THREAD

**Issue by rainbowdesign** [pardeike/Harmony#134]
Hei,
When starting off with Harmony People tend to tell you to look at the sourcecode of existing mods.

It would be good to include a List of tutorials in a new page at the end of the GithubWiki that go into detail on how and what and why and have several examples of full code that explain it well for every aspect of Harmony. My experience is that the examples tend to be too short for beginners.

**Comment by pardeike** [comment]
Good idea.

**Comment by rainbowdesign** [comment]
I looked a bit and found some examples where a bit more documentation would be nice:

A full example or two on how to access private fields on a class or in a method.
Some bigger examples on how to use Patch parameters.
How to access the Parameter from a Method when i patch it.
How to access the constructor Method of a class.

A link to the transpiler tutorial. And an addition to the tutorial: For what is a transpiler good at all in which situations do i use it.

**Comment by rainbowdesign** [comment]
Code injection is a bit more advanced stuff in programming i think and as such its not that easy to learn even with the best of tutorials.

**Comment by rainbowdesign** [comment]
Is there a way to append enums? I found some enums that would be rather nasty to work around they are often used and i think messing with the return values might be hard on the performance.

If not it would be a wish. If yes please tell me and add to the tutorial wish.

**Comment by rainbowdesign** [comment]
I guess its a no it cannot be just simply manipulated or a maybe with a transpiler or something? Nomatter i decided to not do that modification, i found a different way.

What REALLY needs a tutorial are access tools, you write almost nothing about them.

**Comment by pardeike** [comment]
I will add this to my todo list for documentation
