### ISSUE TITLE
The way to do a patch only if the original method has not been changed in the new version.

### ISSUE THREAD

**Issue by DarkoreXOR** [pardeike/Harmony#136]
I need a way to do a patch only if the original method has the same calculated hash (that I will calculate from `IEnumerable<CodeInstruction>`) that was in the previous version of the assembly. Something like a `Transpiler` with a `IEnumerable<CodeInstruction>` parameter, but to initialize the __state parameter for the prefix / postfix.

Something like this:

```C#
class PatchState
{
    public bool Enabled { get; set; }
    ...
}

[HarmonyPatch(...)]
class SomePatch
{
    static PatchState Initialize(IEnumerable<CodeInstruction> instructions)
    {
        // hash calculation or other things here...
        
        return new PatchState(...);
    }

    static bool Prefix(PatchState __state)
    {
        if (!__state.Enabled)
        {
            return true;
        }

        // the code will not be executed here if __state has the flag disabled

        ...

        return false;
    }

    ...

}
```

**Comment by pardeike** [comment]
You already have a Prepare method that can return a boolean. If that returns false, your patches are not executed. All you need to do is to load the CodeInstructions yourself and create and use a hash yourself.

Use
```cs
List<ILInstruction> PatchFunctions.GetInstructions(ILGenerator generator, MethodBase method);
```
to get all codes and write a hash calculation. You need to create a dummy ILGenerator that is used to create those temporary local variables, it's required for generating CodeInstructions.

**Comment by DarkoreXOR** [comment]
Looks like what I need. Thanks. But not quite understand what kind of temporary local variables you are talking about. Should I create a DynamicMethod with the same signature as in the original method? And pass the ILGenerator of my DynamicMethod to PatchFunctions.GetInstructions and the second parameter should be the type of the original method? If I understood everything correctly, I could not see the difference when I passed the first parameter ILGenerator = null and ILGenerator = DynamicMethod.GetILGenerator(). Returned list of instructions are the same kind of like. Maybe my method does not use something specific and I did not see the difference? What is the ILGenerator used for in this case?

**Comment by pardeike** [comment]
To get a list of all CodeInstructions, Harmony has to interpret the binary data the method consist of. Part of that binary data are local variables that are used as arguments in the CodeInstructions. The only way to create those is via a ILGenerator even if you are not using those variables any further because all you want is to do a checksum on all instructions. 

Your tasks of making a reliable checksum is not easy as many arguments are not 1:1 extractable from the original method. Lots of meta data that can only extracted by creating new objects that match the meta data. Doing a naiv checksum for that might make it change without the method itself changing.

**Comment by DarkoreXOR** [comment]
Operands in CodeInstruction are actually not so important for me right now, it can also be ILInstruction without operands or even bytearray with OpCodes only. What If I just get the MSIL byte array through MethodBody.GetILAsByteArray () and send it to the hash function, then this will be enough for me if it will work. If you have any experience with this, tell me, will it be more reliable or not? Can the compiler generate MSIL in different ways in different versions of the same assembly, even if the code has not been changed? If I am mistaken in something you can offer the best way to determine the hash of the code.

**Comment by pardeike** [comment]
I have no idea if the bytes are stable between recompiles and different dlls. You probably have to test this yourself. There are meta tokens involved, so there is a risk that this isn’t a fixture.

**Comment by DarkoreXOR** [comment]
I read that the __state parameter exists only in Prefix and Postfix. Can I somehow initialize it in the Prepare method (I tried, but the Prepare method is not invoked then and I understand that it is impossible)? For example, if I determine in the Prepare method which version of the code is used in the build and I make different patches for each version. I assume that I have to use several separate classes with patches for each version and in each class I have to decide in Prepare whether I need to make a patch or not? But maybe I can somehow do everything in one class?

**Comment by pardeike** [comment]
Prepare and Transpiler are methods that are run during preparation, Prefix and Postfix are run during execution. That’s like saying “can the cookbook writer know which temperature my oven has”.

**Comment by pardeike** [comment]
For more intricate patches like you have in mind, I rather go and do all patches manually with `Patch(original, prefix, postfix, transpiler)`.

**Comment by pardeike** [comment]
Can you provide cal stacks for each of your Prepare calls? It shouldn’t happen.

**Comment by DarkoreXOR** [comment]
First call:
```
Test.Patch.Prepare() in HarmonyLib, HarmonyLib.dll
[Native to Managed Transition]
RuntimeMethodInfo.UnsafeInvokeInternal() in System.Reflection, mscorlib.dll
RuntimeMethodInfo.Invoke() in System.Reflection, mscorlib.dll
MethodBase.Invoke() in System.Reflection, mscorlib.dll
PatchProcessor.RunMethod<Harmony.HarmonyPrepare, bool>() in Harmony, 0Harmony.dll
PatchProcessor.PrepareType() in Harmony, 0Harmony.dll
new PatchProcessor() in Harmony, 0Harmony.dll
HarmonyInstance.<PatchAll>b__9_0() in Harmony, 0Harmony.dll
CollectionExtensions.Do<System.Type>() in Harmony, 0Harmony.dll
HarmonyInstance.PatchAll() in Harmony, 0Harmony.dll
Test.Init() in HarmonyLib, HarmonyLib.dll
App.Run() in HarmonyLib, HarmonyLib.dll
Program.Main() in HarmonyApp, HarmonyApp.exe
```
Second call:
```
Test.Patch.Prepare() in HarmonyLib, HarmonyLib.dll
[Native to Managed Transition]
RuntimeMethodInfo.UnsafeInvokeInternal() in System.Reflection, mscorlib.dll
RuntimeMethodInfo.Invoke() in System.Reflection, mscorlib.dll
MethodBase.Invoke() in System.Reflection, mscorlib.dll
PatchProcessor.RunMethod<Harmony.HarmonyPrepare, bool>() in Harmony, 0Harmony.dll
PatchProcessor.Patch() in Harmony, 0Harmony.dll
HarmonyInstance.<PatchAll>b__9_0() in Harmony, 0Harmony.dll
CollectionExtensions.Do<System.Type>() in Harmony, 0Harmony.dll
HarmonyInstance.PatchAll() in Harmony, 0Harmony.dll
Test.Init() in HarmonyLib, HarmonyLib.dll
App.Run() in HarmonyLib, HarmonyLib.dll
Program.Main() in HarmonyApp, HarmonyApp.exe
```

Program class:
```C#
    class Program
    {
        static void Main(string[] args)
        {
            var app = new App();
            app.Run();
        }
    }
```

App class
```C#
    public class App
    {
        public void Run()
        {
            TestMe(10, true);
            TestMe(20, false);

            Test.Init();

            TestMe(10, true);
            TestMe(20, false);

            Console.ReadLine();
        }

        public void TestMe(int x, bool y)
        {
            var z = x;
            var q = z + x * 2;

            if (y) z = x * 2;
                      
            Console.WriteLine($"x: {x}, y: {y}, z: {z}, q: {q}");
        }
    }
```

Test & Patch classes:

```C#
    public class Test
    {
        public static void Init()
        {
            var harmony = HarmonyInstance.Create("com.github.harmony.rimworld.mod.example");

            try
            {
                harmony.PatchAll(Assembly.GetExecutingAssembly());
            }
            catch (Exception e)
            {
                Console.Write(e);
            }
        }

        [HarmonyPatch(typeof(App))]
        [HarmonyPatch("TestMe")]
        class Patch
        {
            static void Prepare()
            {
                Console.WriteLine("prepare");
            }

            static void Prefix()
            {
                Console.WriteLine("prefix patch");
            }

            static void Postfix()
            {
                Console.WriteLine("postifx patch");
            }
        }
    }
```

Console output:
```
D:/dev/HarmonyTests/HarmonyApp/HarmonyApp/bin/Debug/HarmonyApp.exe
x: 10, y: True, z: 20, q: 30
x: 20, y: False, z: 20, q: 60
prepare
prepare
prefix patch
x: 10, y: True, z: 20, q: 30
postifx patch
prefix patch
x: 20, y: False, z: 20, q: 60
postifx patch
```

**Comment by pardeike** [comment]
Prepare() is first called from PrepareType() to allow for a general way to run code before the your patch class is considered at all. Next, it is called again for every method that this patch class defines. A patch class can have TargetMethods() returning a list of methods to patch with the same prefix/postfix/transpiler.

**Comment by DarkoreXOR** [comment]
I think this is something implicit and you need to add more information to the wiki about it. I still do not fully understand what makes the first Prepare call. What will happen if the first Prepare() call returns true, and in the second -> false? And vice versa if the first returns false? What will it affect?

**Comment by DarkoreXOR** [comment]
Is it a good idea to use a private static local property or field as a state instead of __state so that access is in all methods or are there any pitfalls?

**Comment by pardeike** [comment]
The two (or more) calls are sequential. If the first call returns false, nothing more will happen: no patching and no extra calls to Prepare().

**Comment by pardeike** [comment]
Using shared state depends on how the original methods are called. You might end up with concurrent access or other ordering problems. I don’t know what you want to do so I can’t recommend something

**Comment by DarkoreXOR** [comment]
I want to work with Unity. It seems like there is only one thread. But for multithreading application should I use Lazy<T> or synchronized methods?

**Comment by DarkoreXOR** [comment]
I think I have no more questions. You can close the issue if necessary.

**Comment by pardeike** [comment]
You are always welcome to join the discord server. Take care.
