### ISSUE TITLE
Harmony and .NET Core

### ISSUE THREAD

**Issue by mlynch** [pardeike/Harmony#139]
I am not sure if .NET Core 2 is supported, I found an old github comment saying it wasn't, but I found some references to .NET Core in the source.

When calling `Patch`, this exception is thrown on .NET Core 2:

```c#
System.MissingMethodException: Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.
   at Harmony.HarmonySharedState.GetState()
   at Harmony.HarmonySharedState.GetPatchInfo(MethodBase method)
   at Harmony.PatchProcessor.Patch()
   at Harmony.HarmonyInstance.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler)
```

Happening on this line: https://github.com/pardeike/Harmony/blob/653b9c95a57502b057c3ba2cb8ab112c4110e747/Harmony/HarmonySharedState.cs#L22

According to this SO post, there's a new way of calling `DefineDynamicAssembly`: https://stackoverflow.com/questions/36937276/is-there-any-replace-of-assemblybuilder-definedynamicassembly-in-net-core

Apologies if .NET Core 2 is not supported.

**Comment by pardeike** [comment]
Seems like we (at least) have to wait for 
https://github.com/dotnet/corefx/issues/29715 to be fixed which will be in .NET Core 3

**Comment by pardeike** [comment]
Latest master builds and tests fine with latest .Net Core 3

**Comment by A51UK** [comment]
Hi I have try to use Harmony on .net core 3 preview 5, it fails giving out error:

"System.Runtime.Serialization.SerializationException: 'Type 'System.Reflection.RuntimeMethodInfo' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.'"   

On Patch.cs line 46 - "formatter.Serialize(streamMemory, patchInfo);"

**Comment by pardeike** [comment]
Seems we need a way to serialise a MethodInfo. I have tested using the assembly tokens and the assembly name string instead and it converts back and forth but has no time to add it to master yet. Not even sure it’s a good idea. Strangely, master tests seemed to run fine on Core 3 when I tested but I think that’s because I use the extra Emit nuget package as a reference.

**Comment by A51UK** [comment]
It would be better than nothing at all, have a look at the problem it looks like it may only be a problem with binary serialization and there many be other type that have the same problem. One idea that I did read but have not tested or go through is  to serialization  the data in to a different format (e.g. json) then remake the object. I not sure if that would work or possible. Anyway you have done a great job. (:

**Comment by A51UK** [comment]
The test does fail when you remove all other framework in .csproj  (e.g.     <TargetFrameworks>netcoreapp3.0</TargetFrameworks>) it looks like the test project was not running on .net core 3 but one other .net framework.

**Comment by pardeike** [comment]
I’m pretty sure that each test was evaluated for all targets. I will double check that.

**Comment by scalablecory** [comment]
Have we determined if Harmony works in 3.0 yet? Preview 7 is out the door with a 99% stable API so it's a good time to try.

**Comment by pardeike** [comment]
The project builds with .NET 3 but requires the Emit package as a nuget import. But: I think the latest Unity will have no support for Emit and I am not sure you can simply add it. Also: Microsoft already works on the next unification of .NET and I’ve heard that Unity was interesting. So maybe everything changes again.

**Comment by alexhelms** [comment]
Pulled and used the current master and I am getting the same "not marked as serializable" exception. This is in the shipped version of .net core 3.

Anybody have any updates on having this being fixed?

**Comment by wangjia184** [comment]
Referenced System.Reflection.Emit 4.6.0 in my .NET Core 3.0 project, still receive this error.

**Comment by pardeike** [comment]
I've made Core 3.0 and 3.1 build and test. Please verify.

**Comment by pardeike** [comment]
With the latest contribution fo MonoMod.Common, this is fixed.
