### ISSUE TITLE
Patching nonexistant child override function crashes RimWorld

### ISSUE THREAD

**Issue by pkay42** [pardeike/Harmony#143]
If a child does not provide an override function for a parent virtual function, patching that override function crashes the game RimWorld.

ThingComp has
`		public virtual void CompTickRare()
		{
		}
`

CompRefuelable : ThingComp does not override CompTickRare(), but I can still get a MethodInfo for the method.  Patching CompRefuelable's CompTickRare() seems to crash RimWorld.

    [HarmonyPatch(typeof(RimWorld.CompRefuelable), "CompTickRare")]
    class Patch_CR_CompTickRare
    {
        static bool Postfix() {
            Log.Error("Patched CompTickRare for CompRefuelable");
    }

The game will load, but as soon as time starts moving, the game crashes to desktop.

**Comment by pardeike** [comment]
As you already said, you are trying to patch a nonexisting method. Which version of Harmony are you using? I think the latest uses only declared methods which would not fall back to the base class’s method. 

In general you can only patch methods that exist (a decompiler shows IL code for such methods).

**Comment by pkay42** [comment]
I had been misled by the existence of a MethodInfo object for the nonexisting method.  I have no idea if it's even possible to create such an override in C#.

I believe I do have Harmony version 1.2.0.1 (thanks for the private field access, btw).

I don't know if there's a way Harmony can throw an exception if naive modders attempt this sort of thing?

I will work around using CompTick().  Thank you v much!

**Comment by pardeike** [comment]
Fixed in https://github.com/pardeike/Harmony/commit/5d151ea14539d22dde2775853d4cbc4adeec940b
