### ISSUE TITLE
Is there any elegant way to define a label in transpiler?

### ISSUE THREAD

**Issue by headlesszou** [pardeike/Harmony#144]
Or is there any way to jump to an instruction without a label? I'm stuck with it now.

By the way, I don't know how to create an operand for stloc.s either.

**Comment by pardeike** [comment]
Jumping to an instruction without a label would be unstable in a multi mod situation. Harmony is designed to work with multiple changes to the same method. 

Creating a label is pretty easy:

1) inject `ILGenerator` into the arguments of your transpiler function (name does not matter)

2) Using the generator, create a label and store it in a local variable in your transpiler

3) use it in an operand of the jump instruction to define a jump to it

4) add it to a CodeInstruction’s `labels` array to define the destination

This procedure is very similar to how you would do it when `Emit`ing ordinary IL code and is well documented by Microsoft and on stackoverflow. 

Same goes for `stloc` - you want to use the generator to create a “local variable reference” which represents that variable in your il code. Just create it with the help of the generator object and use it as the operand of stloc and ldloc.

**Comment by headlesszou** [comment]
Oh thanks it worked!

I didn't expect ILGenerator could be passed to the transpiler function so I missed the description in the wiki.
