### ISSUE TITLE
HarmonyArguments don't work when there are multiple Harmony versions loaded

### ISSUE THREAD

**Issue by Zetrith** [pardeike/Harmony#145]
These lines are using references to assembly-specific attribute types: https://github.com/pardeike/Harmony/blob/master/Harmony/MethodPatcher.cs#L157-L203

**Comment by pardeike** [comment]
Annotations don’t work when the library you link against is not the runtime library.

**Comment by Zetrith** [comment]
Yes, but the patch with HarmonyArguments might be processed by another Harmony version anyway no matter what I link against, for example in RimWorld.

**Comment by pardeike** [comment]
Please test with the current master and let me know if it solves your issue.
