### ISSUE TITLE
NullReferenceException when Postfix has object and original method has "int" or "bool"

### ISSUE THREAD

**Issue by SergeyLukashevich** [pardeike/Harmony#148]
An original method is:
```public string PublicMethodWithParameters(string param1, int param2, Object param3)```

Postfix:
```public static void Postfix(object param1, object param2, object param3)```

Trying cast `param2` to int - NullReferenceException is raised.
The same issue using bool instead of int.

At the same time, `param1` and `param3` are OK.
If change `param2` type in Postfix to int, then it becomes reachable too.

Example: 
[ConsoleApplication1.zip](https://github.com/pardeike/Harmony/files/2746211/ConsoleApplication1.zip)

**Comment by pardeike** [comment]
This is to be expected. Parameter names and types need to be the same.

**Comment by pardeike** [comment]
Or to be more exact: patch arguments that Harmony should inject need to be of type that the values in them can be casted to.

**Comment by SergeyLukashevich** [comment]
If objects are not allowed, it means that documentation is missleading

https://github.com/pardeike/Harmony/wiki/Patching
>Patch parameters must use the exact same name and type as the original method (**object is ok too**)

**Comment by erdelf** [comment]
object is ok when the type can be cast to an object. That is not the case for int or bool.
