### ISSUE TITLE
 HarmonyInstance.PatchAll not being able to find methods with [HarmonyPatch] attribute

### ISSUE THREAD

**Issue by jutocz** [pardeike/Harmony#151]
Seems like change 63bc97836dfa20e6a7ea37222fd1a0e800ae7d44 in HarmonyMethod.cs in `GetHarmonyMethods` including lines:
https://github.com/pardeike/Harmony/blob/63bc97836dfa20e6a7ea37222fd1a0e800ae7d44/Harmony/HarmonyMethod.cs#L186-L187 resulted in `HarmonyInstance.PatchAll(Assembly assembly)` not being able to find methods with `[HarmonyPatch]` attribute (I'm following example from Wiki page). 

Reverting to previous revision of `GetHarmonyMethods` where attribute search was not done using string comparison (`.Where(attr => attr is HarmonyAttribute)`) fixes it for me.

**Comment by pardeike** [comment]
Yes, that is work in progress I started just before I got sick. Getting better, I am working on making attributes work across multiple assemblies. 

I’ll keep this open until I have fixed it.

**Comment by pardeike** [comment]
Fixed with the latest commits to master
