### ISSUE TITLE
Clarify that __state parameter needs to be marked as out in prefix in Patching wiki

### ISSUE THREAD

**Issue by ManlyMarco** [pardeike/Harmony#154]
Currently the wiki reads:
> Patches can use a parameter named __state to store information in the prefix method that can be accessed again in the postfix method. Think of it as a local variable. It can be any type and you are responsible to initialize its value in the prefix

This can be confusing if you don't know to add `out` in prefix since there's no errors and in postfix you always get null.

An example with the __state parameter used would be nice too.

**Comment by DingoDjango** [comment]
I've only ever used it as `ref` not `out`

**Comment by pardeike** [comment]
I don't put more time in the current Wiki in favour and preparation of the new documentation at https://harmony.pardeike.net - it's for Harmony 2.0b only but that's how it is.
