### ISSUE TITLE
Can't patch method (with overloads) in generic type

### ISSUE THREAD

**Issue by alexb5dh** [pardeike/Harmony#156]
Code below logs a lot of different `List<T>.Add` calls where `T` is not a `string`.
```
[HarmonyPatch(typeof(List<string>), new[] { typeof(string) })] // generic type
[HarmonyPatch(nameof(List<string>.Add), typeof(string))] // method
static class ListAddPatch
{
    public static void Prefix(List<string> __instance) => Console.WriteLine(__instance);
}

static class Program
{
    public static void Main() => HarmonyInstance.Create("patch").PatchAll();
}
```

Removing `string` from `List<string>` (since it's already passed as type parameter):
```
[HarmonyPatch(typeof(List<>), new[] { typeof(string) })] // generic type
[HarmonyPatch(nameof(List<string>.Add), typeof(string))] // method
```
gives
```
System.ArgumentException: No target method specified for class ConsoleTest.ListAddPatch (declaringType=System.Collections.Generic.List`1[T], methodName =Add, methodType=, argumentTypes=(System.String))
```

Trying to use `TargetMethod` also doesn't help:
```
[HarmonyPatch]
static class ListAddPatch
{
    private static MethodBase TargetMethod() => AccessTools.Method(typeof(List<string>), "Add", new[] { typeof(string) });
    public static void Prefix(List<string> __instance) => Console.WriteLine(__instance);
}
```
giving same result as in the first case.

**Comment by pardeike** [comment]
Generic methods can only be patched one specific type at a time. You need to use TargetMethod() as you do, but to get a valid MethodInfo, you need to first get the MethodInfo of the generic method, then apply MakeGenericMethod(type) to get the specific method info for a given type. 

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.makegenericmethod?view=netframework-4.7.2

**Comment by alexb5dh** [comment]
Thanks. This probably should be added to the docs. Maybe as part of #88.

**Comment by pardeike** [comment]
A “No target method specified” error is afaik only thrown if your MethodInfo is null. So I assume your TargetMethod() returns null. Please double check that.

**Comment by pardeike** [comment]
https://github.com/pardeike/Harmony/blob/6cb008dbdf0ba78a52e8294d8e647316c236f98b/Harmony/Public/PatchProcessor.cs#L198

**Comment by alexb5dh** [comment]
Yeah, the  “No target method specified” is a problem with the seconds approach in the first comment.
The main issue is Harmony patching all `List<>.Add` methods.

I found some interesting thing while investigating that seems to be related to reference/value types:
Patch for `List<int>.Add(int)` works as expected:
```
class ListAddPatch<T>
{
    private static MethodBase TargetMethod() => AccessTools.Method(typeof(List<T>), "Add", new[] { typeof(T) });
    public static void Prefix(object __instance) => Console.WriteLine(__instance);
}

[HarmonyPatch]
class ListAddIntPatch: ListAddPatch<int> { }
```
But changing `T` to `string` or `int[]` makes it patch everything.

**Comment by pardeike** [comment]
Probably a side effect of .net trampoline assembler code that groups all those methods into one assembler entry and resolves the different types inside the assembler code. Since Harmony only patches method starts it cannot predict or change the logic in the assembler parts of the method call chain. All this is also highly different for different .net versions, operating systems and cpu processor versions.

**Comment by pardeike** [comment]
Oh and completely undocumented

**Comment by alexb5dh** [comment]
I'm currently using a simple type check in the patch method:
```
if(__instance is List<string> list) return;
```
Maybe this approach can be incorporated in the Harmony as part of IL rewriting as a workaround?
