### ISSUE TITLE
Does it work with Unity3d?

### ISSUE THREAD

**Issue by game-libgdx-unity** [pardeike/Harmony#164]
Please provide me a working sample if it does.

 I tried the code like this:
static Main()
{
var harmony = HarmonyInstance.Create("com.github.harmony.rimworld.mod.example");
harmony.PatchAll(Assembly.GetExecutingAssembly());
}
I imported 0Harmony.dll
But it says the methods isn't found. does the API change?

Unity 2018.2.6

**Comment by pardeike** [comment]
All my RimWorld mods use these lines. Example: https://github.com/pardeike/CameraPlus/blob/master/Source/Main.cs

Sure, the main method is different in RimWorld but that shouldn’t matter in relation to your problem that the method is not found. 

Did you include the dll file as a dependency in your runtime?

**Comment by game-libgdx-unity** [comment]
Ah I need to import the pdb files from debug dll. Now the method is found.

I just tried Object.Destroy to detect when an object is destroy in unity, it throws this exception, is this intended?

System.Exception: Exception from HarmonyInstance "com.github.harmony.rimworld.mod.example" ---> System.ArgumentException: Method UnityEngine.Object.Destroy(UnityEngine.Object, System.Single) has no body

**Comment by game-libgdx-unity** [comment]
Forget about it, I got an working sample code now

`
public class Something
{
    public void DoIt()
    {
        Debug.Log("DoIt");
    }
}

[InitializeOnLoad]
class HarmonyTest
{
    static HarmonyTest()
    {
        var harmony = HarmonyInstance.Create("com.github.harmony.rimworld.mod.example");
        harmony.PatchAll(Assembly.GetExecutingAssembly());

        Debug.Log("Hello");

        Something o = new Something();

        o.DoIt();
    }
}

[HarmonyPatch(typeof(Something))]
[HarmonyPatch("DoIt")]
[HarmonyPatch(new Type[] {})]
class Patch
{
    static void Prefix()
    {
        Debug.Log("Something happened");
    }
}`
