### ISSUE TITLE
Some correctness questions

### ISSUE THREAD

**Issue by mcpiroman** [pardeike/Harmony#173]
These questions refer to mainly Memory class
1. When calling `VirtualProtect`, why is the `dwSize` argument always 1? It refers to the size of target memory block, in bytes, and the code writes more than 1 byte. Actually this affects whole page, but if written block sits between two pages, then, I think, the second one is still not unprotected.
2. [Microsoft docs](https://docs.microsoft.com/en-us/windows/desktop/api/memoryapi/nf-memoryapi-virtualprotect#remarks) and [this code (very simillar to yours)](https://github.com/wledfor2/PlayHooky/blob/7c2564eceae01dfe2457c91425d9af2a938e77bc/HookManager.cs#L191) claim that calling `FlushInstructionCache` winapi function is required after modifing program's code. Is the lack of this intended?
3. The code replaces first bytes of generated native code of function with two instructions (`mov` and `ret`, ain't it?) which is just few bytes. But what if the original function was even shorter than that? E.g. single `ret`? Wouldn't this override some other memory structure? Is that situation even possible?
4. You only unprotect memory on Windows. What with other systems? Is it already read-write-execute?

**Comment by pardeike** [comment]
Hi,
these are all valid questions but I don't have clear answer to them since my understanding of the mechanics behind it is sort of limited. Some of this code was contributed and some I was happily
copying from different articles. I did my best to review it but that only goes so long.

With that in mind:

1. the current code is probably wrong
2. Did not know that. I think I can add this.
3. It is my understanding that this case does not exist.
4. So far, the need to improve this has not come up. Most systems that are more restrictive do not execute managed code anyway.

**Comment by mcpiroman** [comment]
Thanks for responding.
Here are my thoughts about the questions:

1. Assuming typical page size is 4096 bytes and you write 6 bytes (on 32bit system), then there is (6-1)/4096 which is 1 to 819 chance that single method deture will crash due to invalid memory access. And this is not the case (right?). So I suppose this is becouse of method aligment done by runtime, which (if it happends) matches with page sizes that are usually 1) quite big and 2) power of 2. But this is not something to rely on so I suggest you pass the real amount of bytes you write to the `VirtualProtect`.
2. This is presumably closely related to multithreading and processor architecture (especially `weak`  architectures which x86 does not belong to), so it is very likely that the current implementation works just fine, as multithreading is rare with Unity. Neverthenless I suggest adding the `FlushInstructionCache` anyways, just in case.
3. I have seen similar libraries to Harmony and none of them care about this, so I assume its ok (it just works). Once again, it is very likely that runtime aligns methods, and the alignment is at least 16 bytes.
4.  Here is the kind of strange one. E.g. Linux (Unix?) has very similar mechanics with memory protection so I was wondering why only Windows requires to unprotect it. It may be that runtime which has to have write and execute rights to actually write JITed method to memory, after doing so protects the memory to execute only, but only on Windows. But why? Also this behaviour seems to be shared between all .net runtimes.

I have my own [project](https://github.com/mcpiroman/UnityNativeTool) that is based on Harmony but it focuses exclusively on `DllImport` methods. As it works fine on Windows, I have noticed some rare crashes on Linux (only on VM so far). I know this is not the scope of Harmony, but the `DllImport` methods seem to behave in similar way to regular ones, so that's why I'm so suspicious. Or mayby they have stronger security priority? But why is it not deterministic?

**Comment by pardeike** [comment]
Thanks for the detailed reply. I’ll add the fixes suggested.

**Comment by mcpiroman** [comment]
Also, is there any reason why code in Memory.cs uses `long` instead of `IntPtr`?
