### ISSUE TITLE
Harmony causing ArgumentExceptions?

### ISSUE THREAD

**Issue by Hi-ImKyle** [pardeike/Harmony#176]
Ok so first I need to say that the exception may not be directly caused by Harmony, but I have reason to believe it is in some way.

So I'm using Harmony on Terraria, a XNA Framework Game. It's my first time using Harmony and I've looked through the wiki and seen the small tutorials on RimWorld and such, and I've gotten my code to work. Very basic, just telling me when a method is being called and when it's finished with the `Prefix` and `Postfix` methods. 

Terraria doesn't have an open method to call to just run the game, it's private, as it should be. So using reflection I call it and the game seems to launch fine for the most part. 

Until it hits a point when the game needs to make use of a compare method, which is being called by `Terraria.UI.ItemSorting.SetupWhiteLists()`

```
System.ArgumentException: Unable to sort because IComparer.Compare() 
method returns inconsistent results. Either a value does not compare equal 
to itself, or one value repeatedly compared to another value yields different results.
```

When trying to debug my program with dnSpy to see if dnSpy could show me at what point the exception was caused, nothing was shown. Neither does Visual Studio know other than to just tell me, instead of showing.

Here is my code, https://pastebin.com/8NSe2n8g - It's just in a console window project and being run next to Terraria

The reason why this issue is here is because obviously the game doesn't run into this issue, and I was hoping maybe someone with Terraria or maybe just if you know the issue, to possibly point me in the right direction. I'd like to fix this on my own as any programmer learning would, but I can't figure out why or what would be causing this to happen. 

Sorry if this isn't the place to ask for help, I'm just not sure where else I can ask.

**Comment by pardeike** [comment]
I probably helps if you list which methods you patch with Harmony.

**Comment by Hi-ImKyle** [comment]
Of which I'm only patching one method. `Terraria.Main.Initialize()`, I thought that would've been obvious given that I gave you the code I'm using. Unless you wanted something else in which case I'm not sure what you mean.

**Comment by pardeike** [comment]
Sorry, was reading this on my phone and missed the pastebin link. Does this also happen when you simply run the same code but without instantiating and using Harmony?

I don't have the code for SetupWhiteLists() and the custom compare, maybe you can post it.

**Comment by Hi-ImKyle** [comment]
It does happen without Harmony being used. I guess I never thought about that. My apologies. 

In which case I'm at a loss with this project immediately and I guess I'll stick to what I was doing originally unless you have an idea of what could be causing this. https://pastebin.com/SpfinGYe Here is the entire class containing SetupWhiteLists()

**Comment by pardeike** [comment]
Well, I had a look at that but to be honest, that looks rather complicated and substantial so I have to pass (especially since it's not Harmony related).
