### ISSUE TITLE
Request: 'Context' or 'Tag' property on HarmonyInstance

### ISSUE THREAD

**Issue by zeffy** [pardeike/Harmony#178]
I think it would be very useful to be able to attach an arbitrary object to `HarmonyInstance` that could be accessed via a public property in `Prepare` or `TargetMethod(s)` overloads that take a HarmonyInstance. This way I could pass an object e.g. an `Assembly` to these methods without having to use a static property in a separate class.

Or even further, this contextual object could be injected into patches its own parameter e.g. `object __context` or similar. This part wouldn't be super important to me, but maybe other people would find it useful.

**Comment by pardeike** [comment]
Having a __context injected into each patch is really tricky because of cross-assembly problems. I don't think I will implement it, sorry.

**Comment by zeffy** [comment]
No worries, thanks for at least taking the time to consider it.
