### ISSUE TITLE
Getting this error, how to fix System.InvalidProgramException: Invalid IL code

### ISSUE THREAD

**Issue by shahin231** [pardeike/Harmony#187]
while trying to run one .exe file with wine the getting the below error, Please help me to fix this issue.
Unhandled Exception:
System.InvalidProgramException: Invalid IL code in aaed365967264a2fb69737b8479ee57c/ac94d755f7cf44deb473434993231683<a7362980a11b432a8090b8334da2068d_REF>:dd93169ef7014011ad13587cd8676754 (): IL_0022: switch    (IL_002f, IL_007f)

  at aaed365967264a2fb69737b8479ee57c.c30086b52b5441c59003d11eb2dff88e () [0x00000] in <0519b39f231b4054bb98da0fcc778120>:0
  at a201fc2515ff4131ae5909f2bb8872a8.a7a34213431444cc8702349ac337389d (System.String[] ) [0x0084c] in <0519b39f231b4054bb98da0fcc778120>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in aaed365967264a2fb69737b8479ee57c/ac94d755f7cf44deb473434993231683<a7362980a11b432a8090b8334da2068d_REF>:dd93169ef7014011ad13587cd8676754 (): IL_0022: switch    (IL_002f, IL_007f)

  at aaed365967264a2fb69737b8479ee57c.c30086b52b5441c59003d11eb2dff88e () [0x00000] in <0519b39f231b4054bb98da0fcc778120>:0
  at a201fc2515ff4131ae5909f2bb8872a8.a7a34213431444cc8702349ac337389d (System.String[] ) [0x0084c] in <0519b39f231b4054bb98da0fcc778120>:0

**Comment by pardeike** [comment]
I would need more information and background on what you are trying to do. Original method, patch methods, Harmony version etc

**Comment by shahin231** [comment]
I am installing a windows .exe file on Ubuntu with the help of wine command.

wine /home/shahin/Documents/Setup.exe

in return its throwing error.
System.InvalidProgramException: Invalid IL code in aaed365967264a2fb69737b8479ee57c/ac94d755f7cf44deb473434993231683<a7362980a11b432a8090b8334da2068d_REF>:dd93169ef7014011ad13587cd8676754 (): IL_0022: switch (IL_002f, IL_007f)

as stated earlier.

Setup.exe is windows software. How can I fix this issue?

Thanks
Shahin

**Comment by erdelf** [comment]
What exactly does harmony have to do with that?
Are you the one doing the patching? 
If so what are you patching, what does your patch look like ?

**Comment by pardeike** [comment]
Closing this because of too little information
