### ISSUE TITLE
Access __state via Transpiler

### ISSUE THREAD

**Issue by lilwhitemouse** [pardeike/Harmony#189]
So it's possible to create/define and access a new local variable in the Transpiler:
1. Specify an ILGenerator parameter to the transpiler:
static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions,
                                                       ILGenerator generator) { //etc
2. Use the ILGenerator to create a local variable: LocalBuilder myVar=generator.DeclareLocal(typeof(etc));
3. Store to and access it: yield return new CodeInstruction(OpCodes.Stloc_S, myVar); //etc

Is it possible to access the __state variable defined in the prefix?  If not, could that be available at some point?

**Comment by pardeike** [comment]
`__state` is referring to a private local variable that Harmony uses internally. Exposing it to transpilers makes things unnecessary complicated. If you already use transpilers, just skip prefixes/postfixes and add your own code inside the transpiler instead.

**Comment by lilwhitemouse** [comment]
Understood - I didn't think it would be so complicated.  Local variables all the way then and perhaps calling a postfix direct if we don't want to write in IL.

Thank you!
