### ISSUE TITLE
Using HarmonyPrepare seems to throw exceptions

### ISSUE THREAD

**Issue by Vectorial1024** [pardeike/Harmony#193]
**Describe the bug**
A `TargetParameterCountException` is thrown when attempting to patch with the use of `HarmonyPrepare` attribute. (This is found when developing a RimWorld mod.)

**To Reproduce**
1. The original method to patch is from RuntimeGC, another RimWorld mod. I am attempting to patch `RuntimeGC.WorldPawnCleaner::GC`. The full source of the type and the method can be found here: https://github.com/user19990313/RimWorld-RuntimeGC/blob/master/src/RuntimeGC/RuntimeGC/WorldPawnCleaner.cs
The signature of the method is `public int GC(bool verbose = false)`.
Both the type `RuntimeGC.WorldPawnCleaner` and the method `GC` is `public`, so anyone should be able to access the method without any errors.
2. I intend to detect the presence of RuntimeGC with the use of `HarmonyPrepare`, so that I can prevent the patch if RuntimeGC is not found, as demonstrated below:
```
using Harmony;
using RuntimeGC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using Verse;

namespace Desynchronized.Compatibility.RuntimeGC
{
    [HarmonyPatch(typeof(WorldPawnCleaner))]
    [HarmonyPatch("GC", MethodType.Normal)]
    public class Transpiler_WorldPawnCleaner_GC
    {
        [HarmonyPrepare]
        public static bool DetectRuntimeGC(HarmonyInstance instance)
        {
            foreach (ModContentPack pack in LoadedModManager.RunningMods)
            {
                //Log.Error("Current ModContentPack: " + pack.Name);
                if (pack.Name.Contains("RuntimeGC"))
                {
                    return true;
                }
            }
            
            return false;
        }

        [HarmonyPostfix]
        public static void TestFunc()
        {
            // foo bar foo bar
        }
    }
}
```
3. HugsLib reports this error when the RimWorld title screen finally shows up:
```
[HugsLib][ERR] Failed to apply Harmony patches for HugsLib.com.vectorial1024.rimworld.desynchronized. Exception was: System.Reflection.TargetParameterCountException: parameters do not match signature
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.RunMethod[HarmonyPrepare,Boolean] (Boolean defaultIfNotExisting, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.Patch () [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.<PatchAll>b__9_0 (System.Type type) [0x00000] in <filename unknown>:0 
  at Harmony.CollectionExtensions.Do[Type] (IEnumerable`1 sequence, System.Action`1 action) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <filename unknown>:0 
  at HugsLib.ModBase.ApplyHarmonyPatches () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
HugsLib.Utils.ModLogger:Error(String, Object[])
HugsLib.ModBase:ApplyHarmonyPatches()
HugsLib.HugsLibController:EnumerateChildMods(Boolean)
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```
As reference, here's the full log: https://gist.github.com/07b949dccd9120703eac4a907034eb8f
(The `desyncpsycho` error can be ignored; it shouldn't affect this error we are currently investigating.)

**Expected behavior**
No errors/exceptions should be thrown if I use `HarmonyPrepare`.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64-bit
 - (...how do I check which version of .NET is running?)
 - Harmony version: 1.2.0.1
- Name of game or host application: RimWorld

**Additional context**
There are a number of occurrences of `HarmonyPrefix`, `HarmonyTranspiler`, and `HarmonyPostfix` in my mod. Those occurrences do not make use of `HarmonyPrepare`. They are all loaded successfully without any errors.

I was originally planning to use `HarmonyPrepare` with `HarmonyTranspiler` to modify the method, but it seems that merely using `HarmonyPrepare` caused errors.

**Comment by pardeike** [comment]
Harmony 1.2.0.1 expects the prepare method to have exactly one argument: a MethodInfo of the original method. 

So if you change your code to `public static bool DetectRuntimeGC(MethodInfo original)` it should work.

**Comment by Vectorial1024** [comment]
I have updated my code according to your suggestions, but encountered yet another error.

**My code**
```
using Harmony;
using RuntimeGC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Text;
using Verse;

namespace Desynchronized.Compatibility.RuntimeGC
{
    [HarmonyPatch(typeof(WorldPawnCleaner))]
    [HarmonyPatch("GC", MethodType.Normal)]
    //[HarmonyPatch]
    public class Transpiler_WorldPawnCleaner_GC
    {
        // Will be useful when everything settles down
        /*
        [HarmonyTargetMethod]
        public static MethodInfo TargetRuntimeGC()
        {
            return AccessTools.Method("RuntimeGC.WorldPawnCleaner:GC");
        }
        */
        
        [HarmonyPrepare]
        public static bool DetectRuntimeGC(MethodInfo original)
        {
            // Supposedly the original method should be loaded.
            Log.Error("Is the original method null? " + (original == null));
            return original != null;
        }

        [HarmonyPostfix]
        public static void TestFunc()
        {

        }
    }
}
```
**Expected result**
An error message is dumped into the debug log, showing whether the `MethodInfo` is null, so I may decide whether the patch will happen.

**Actual result**
An exception is thrown. Debug log does not contain the intended error message. Full log: https://gist.github.com/e41d76ef059c4642e362ce5d7cc3d02f
(Again, ignore the `desyncpsycho` error.)

**Stacktrace**
```
[HugsLib][ERR] Failed to apply Harmony patches for HugsLib.com.vectorial1024.rimworld.desynchronized. Exception was: System.ArgumentException: failed to convert parameters
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.RunMethod[HarmonyPrepare,Boolean] (Boolean defaultIfNotExisting, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.PrepareType () [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor..ctor (Harmony.HarmonyInstance instance, System.Type type, Harmony.HarmonyMethod attributes) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.<PatchAll>b__9_0 (System.Type type) [0x00000] in <filename unknown>:0 
  at Harmony.CollectionExtensions.Do[Type] (IEnumerable`1 sequence, System.Action`1 action) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <filename unknown>:0 
  at HugsLib.ModBase.ApplyHarmonyPatches () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
HugsLib.Utils.ModLogger:Error(String, Object[])
HugsLib.ModBase:ApplyHarmonyPatches()
HugsLib.HugsLibController:EnumerateChildMods(Boolean)
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```

**Comment by pardeike** [comment]
Have you tried to use `MethodBase` instead of `MethodInfo`? MethodBase is the base class where MethodInfo and ConstructorInfo inherit from and Harmony uses that instead to also allow constructor patches.

**Comment by Vectorial1024** [comment]
Now, as a quick sanity check, I changed my code to use `MethodBase`, but also changed the target method to a RimWorld vanilla method:

**My code**
```
// Desynchronized.Compatibility.RuntimeGC.TestPatcher
using Harmony;
using System.Linq;
using System.Reflection;
using Verse;

[HarmonyPatch(typeof(Building))]
[HarmonyPatch("Draw", MethodType.Normal)]
public class TestPatcher
{
        [HarmonyPrepare]
	public static bool DetectArbitrary(MethodBase original)
	{
		return LoadedModManager.RunningMods.Any();
	}
}
```

However, I still got an exception. It's basically the same:
```
[HugsLib][ERR] Failed to apply Harmony patches for HugsLib.com.vectorial1024.rimworld.desynchronized. Exception was: System.ArgumentException: failed to convert parameters
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.RunMethod[HarmonyPrepare,Boolean] (Boolean defaultIfNotExisting, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.PrepareType () [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor..ctor (Harmony.HarmonyInstance instance, System.Type type, Harmony.HarmonyMethod attributes) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.<PatchAll>b__9_0 (System.Type type) [0x00000] in <filename unknown>:0 
  at Harmony.CollectionExtensions.Do[Type] (IEnumerable`1 sequence, System.Action`1 action) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <filename unknown>:0 
  at HugsLib.ModBase.ApplyHarmonyPatches () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
HugsLib.Utils.ModLogger:Error(String, Object[])
HugsLib.ModBase:ApplyHarmonyPatches()
HugsLib.HugsLibController:EnumerateChildMods(Boolean)
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```

**Comment by pardeike** [comment]
The prepare code in Harmony 1.2.0.1 is kind of broken. If you look at the implementation https://github.com/pardeike/Harmony/blob/422b16fcd8d86351118aa602fd13b4e171b719e6/Harmony/PatchProcessor.cs#L242
```cs
T RunMethod<S, T>(T defaultIfNotExisting, params object[] parameters)
{
	if (container == null)
		return defaultIfNotExisting;

	var methodName = typeof(S).Name.Replace("Harmony", "");

	var paramList = new List<object> { instance };
	paramList.AddRange(parameters);
	var paramTypes = AccessTools.GetTypes(paramList.ToArray());
	var method = PatchTools.GetPatchMethod<S>(container, methodName, paramTypes);
	if (method != null && typeof(T).IsAssignableFrom(method.ReturnType))
		return (T)method.Invoke(null, paramList.ToArray()); // ### THIS IS WRONG ###

	method = PatchTools.GetPatchMethod<S>(container, methodName, new Type[] { typeof(HarmonyInstance) });
	if (method != null && typeof(T).IsAssignableFrom(method.ReturnType))
		return (T)method.Invoke(null, new object[] { instance });

	method = PatchTools.GetPatchMethod<S>(container, methodName, Type.EmptyTypes);
	if (method != null)
	{
		if (typeof(T).IsAssignableFrom(method.ReturnType))
			return (T)method.Invoke(null, Type.EmptyTypes);

		method.Invoke(null, Type.EmptyTypes);
		return defaultIfNotExisting;
	}

	return defaultIfNotExisting;
}
```
You see that Harmony tries to find and call the method three different ways. First with a (broken) implementation with [instance, arguments]. Second, just with [instance] and finally without arguments. The bug in the first try is because the code does not use `parameters` at all but instead calls the invoke with the parameter types as arguments (marked by my extra comment).

This part of the code is completely overhauled in the upcoming Harmony 2.0 so until then you probably need to adapt and only send the instance or no arguments at all.

**Comment by Vectorial1024** [comment]
Just for the sake of documentation, this time, I tested the `HarmonyPrepare` with no parameters. The game still gives an exception.

**My code**
```
// Desynchronized.Compatibility.RuntimeGC.TestPatcher
using Harmony;
using System.Linq;
using Verse;

[HarmonyPatch(typeof(Building))]
[HarmonyPatch("Draw", MethodType.Normal)]
public class TestPatcher
{
    [HarmonyPrepare]
    public static bool DetectArbitrary()
    {
        return LoadedModManager.RunningMods.Any();
    }
}
```

**Result**
```
[HugsLib][ERR] Failed to apply Harmony patches for HugsLib.com.vectorial1024.rimworld.desynchronized. Exception was: System.Reflection.TargetParameterCountException: parameters do not match signature
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.RunMethod[HarmonyPrepare,Boolean] (Boolean defaultIfNotExisting, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor.PrepareType () [0x00000] in <filename unknown>:0 
  at Harmony.PatchProcessor..ctor (Harmony.HarmonyInstance instance, System.Type type, Harmony.HarmonyMethod attributes) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.<PatchAll>b__9_0 (System.Type type) [0x00000] in <filename unknown>:0 
  at Harmony.CollectionExtensions.Do[Type] (IEnumerable`1 sequence, System.Action`1 action) [0x00000] in <filename unknown>:0 
  at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <filename unknown>:0 
  at HugsLib.ModBase.ApplyHarmonyPatches () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
HugsLib.Utils.ModLogger:Error(String, Object[])
HugsLib.ModBase:ApplyHarmonyPatches()
HugsLib.HugsLibController:EnumerateChildMods(Boolean)
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```

However, if I use the alternative way (by `static bool Prepare()`), it works without any errors.

**Working code**
```
// Desynchronized.Compatibility.RuntimeGC.TestPatcher
using Harmony;
using System.Linq;
using Verse;

[HarmonyPatch(typeof(Building))]
[HarmonyPatch("Draw", MethodType.Normal)]
public class TestPatcher
{
        // Using method name Prepare instead of attribute [HarmonyPrepare]
	public static bool Prepare()
	{
		return LoadedModManager.RunningMods.Any();
	}
}
```

**Comment by pardeike** [comment]
Kind of surprising since the Invoke is the same in both cases. Question: is your real class larger than the one shown in your code examples? In other words, is there a chance that Harmony sees a different `[HarmonyPrepare]` when it looks for the method?

**Comment by pardeike** [comment]
Another possibility would be that you compile your mod against a different Harmony than the supplied runtime version that comes from HugsLib and as such the search for the attribute (which is compiled with *your* version of Harmony) against an attribute type that comes from the runtime version of Harmony makes this happen.

**Comment by Vectorial1024** [comment]
> Kind of surprising since the Invoke is the same in both cases. Question: is your real class larger than the one shown in your code examples? In other words, is there a chance that Harmony sees a different `[HarmonyPrepare]` when it looks for the method?

Negative. I wrote the code, compiled it, then used ILSpy to obtain "back" the code, which is shown above.

> Another possibility would be that you compile your mod against a different Harmony than the supplied runtime version that comes from HugsLib and as such the search for the attribute (which is compiled with _your_ version of Harmony) against an attribute type that comes from the runtime version of Harmony makes this happen.

As of now, HugsLib bundles the v1.2.0.1 Harmony library with itself, and I myself am also using v1.2.0.1, so that shouldn't be happening.

Btw, I checked, and both HugsLib and Harmony is using runtime v2.0.50727 .

**Comment by pardeike** [comment]
Until I know exactly what’s going on, I’ll keep this open

**Comment by lbmaian** [comment]
I believe you've misdiagnosed the bug. `PatchTools.GetPatchMethod`. The `method.Invoke` call looks fine - it's being passed the parameter list prepended with the `HarmonyInstance`.

I think the culprit is `PatchTools.GetPatchMethod`. If it finds a `HarmonyPrepare` attributed method, it returns it without checking that it has the correct parameters. Contrast with the code branch where no such attributed method is found, where the `AccessTools.Method(patchType, name, parameters)` call does check for the correct parameters.

Furthermore, RunMethod<HarmonyPrepare, bool> is called twice if using the `HarmonyPrepare` attribute:
* `RunMethod<HarmonyPrepare, bool>(true, original)` in `Patch()` (called for both `PatchAll` mode and manual patching)
* `RunMethod<HarmonyPrepare, bool>(true)` in `PrepareType()` (called from constructor that's only used in `PatchAll` mode)

The fact that it's called twice already doesn't look right to me. But another consequence of this is that the `HarmonyPrepare` attributed method is always called with different number of arguments.

Which means that I don't think the `HarmonyPrepare` attribute can ever work right now. You have to use the non-attributed `Prepare` method.

**Comment by pardeike** [comment]
This is an old 1.2.0.1 bug that I fixed in 2.0b (not released yet). And that it is called twice is actually a feature and intended. Once for the whole class and once for each target method. Which can be many if you use TargetMethods().

**Comment by lbmaian** [comment]
Right, I thought you weren't sure what the exact bug was in 1.2.0.1:
> Until I know exactly what’s going on, I’ll keep this open

I was replying specifically to this:
> The bug in the first try is because the code does not use `parameters` at all but instead calls the invoke with the parameter types as arguments (marked by my extra comment).

Since the `Invoke` is being called with the parameter list prepended with `HarmonyInstance`, not the parameter types as you thought here.

`HarmonyPrepare` being "run twice" was confusing to me, since I'd also expect `HarmonyCleanup` to be called "twice" as well. That is, there's no `RunMethod<HarmonyCleanup>` in `PrepareType()`. Should there be?

Regardless, the fact that `HarmonyPrepare` is being "run twice" in different ways, combined with the buggy `PatchTools.GetPatchMethod` scanning for attributed methods, results in `HarmonyPrepare` attributed methods simply not working in 1.2.0.1. There's no way to have such a method without triggering a "parameters do not match signature" either during `PrepareType()` (which expects the signature to be `(HarmonyInstance)`) or during `Patch()` (which expects the signature to be `(HarmonyInstance, MethodBase)`).

In 1.2.0.1, as I understand it, you must use the non-attributed specifically-named `Prepare(...)` method.

**Comment by pardeike** [comment]
Correct
