### ISSUE TITLE
I can't use Harmony on Android

### ISSUE THREAD

**Issue by utf69** [pardeike/Harmony#196]
When I try to patch methods in any Unity game on Android, Harmony can't find methods from System.Core or mscorlib.

1. Patch literally any method from any Unity game (.NET 3.5) on Android.
2. When you check the logcat you will see the following exception:
`E/Unity   ( 4361): System.MissingMethodException: Method not found: 'System.Diagnostics.StackTrace..ctor'.
E/Unity   ( 4361):   at Harmony.HarmonyInstance..ctor (System.String id) [0x00000] in <filename unknown>:0
E/Unity   ( 4361):   at Harmony.HarmonyInstance.Create (System.String id) [0x00000] in <filename unknown>:0`

**Expected behavior**
I expected the patch to actually work.

**Runtime environment:**
 - OS: Windows 10, 64bit
 - .NET: 3.5
 - Harmony version: 1.2.0.1
- Hackers: The Game

**Comment by pardeike** [comment]
Currently Android is not supported. Adding it will take too much time so I close this for now with a #wontfix.

**Comment by pardeike** [comment]
Sorry, mainly a priority thing. Hopefully someone can contribute to the project and add it.

**Comment by utf69** [comment]
np

**Comment by hiradyazdan** [comment]
My understanding is IL2CPP platforms won't support harmony as it uses DynamicMethod,  and needs `System.Reflection.Emit` which is not supported on c++. Correct me if I am wrong @pardeike

**Comment by pardeike** [comment]
Correct

**Comment by pardeike** [comment]
But there is a slight chance to use Cecil to create an dll in memory and via byte stream read it with Load(). There is another project where the author and I have some cooperation and a common lib refactored from that project could become the base to power both our projects.

**Comment by friuns2** [comment]
is this implemented yet? this maybe usefull https://blog.unity.com/technology/il2cpp-internals-method-calls
