### ISSUE TITLE
Duck Game mod not recognized when "Using Harmony;" is added to Mod.cs. Everything Builds.

### ISSUE THREAD

**Issue by iamPres** [pardeike/Harmony#197]
0harmony is in Mods/Mod/build/. reference is correct.

Duck game detects the mod when the reference is formed, but when I add "Using Harmony;", it does not detect my mod.

I have tried reinstalling 

Code:
`
     using System;
     using System.Collections.Generic;
     using System.Linq;
     using System.Text;
     using System.Reflection;
     using Harmony;

     // The title of your mod, as displayed in menus
     [assembly: AssemblyTitle("My Custom Mod")]

     // The author of the mod
     [assembly: AssemblyCompany("Me, The Creator")]

      // The description of the mod
      [assembly: AssemblyDescription("This Mod Does All The Things!")]

       // The mod's version
      [assembly: AssemblyVersion("1.0.0.0")]

      namespace DuckGame.MyMod
     {
         public class MyMod : Mod
         {

        // The mod's priority; this property controls the load order of the mod.
        public override Priority priority
		{
			get { return base.priority; }
		}

		// This function is run before all mods are finished loading.
		protected override void OnPreInitialize()
		{
			base.OnPreInitialize();
        }

        // This function is run after all mods are loaded.
        protected override void OnPostInitialize()
        {
            base.OnPostInitialize();
            Debug.Log("Initializing...");

            List <Thing> blocks = new List<Thing>();
            List<Thing> items = new List<Thing>();
            List<Thing> ducks = new List<Thing>();

            if (Level.current != null)
            {
                blocks.AddRange(Level.current.things[typeof(Block)]);
                items.AddRange(Level.current.things[typeof(LSItem)]);
                ducks.AddRange(Level.current.things[typeof(Duck)]);
            }
        }
        static void Prefix()
        {

        }
    }
    }

`

**Comment by pardeike** [comment]
Did you copy the Harmony dll you reference into the Assemblies folder like your mod dll?

**Comment by pardeike** [comment]
If you can, try to clone one of my mods for Rimworld and compare them with your project: https://github.com/pardeike/CameraPlus

Also: I am not familiar with the Duck Game . Does it support mod loading? Harmony is for patching so you still need a game that loads your mod or you need to use some kind of code injection to get started.

**Comment by willox** [comment]
Duck  Game copies the binary of your mod into memory and loads it in a way that it will not find Harmony's library.

I know that you can use something like ILRepack to get around it (as we do in https://github.com/Jvs34/DuckGame.Nametags/blob/master/build/Nametags.csproj#L24.) but there may be better methods.

This of course comes with the downside of slighting bloating the dll.
