### ISSUE TITLE
Patches for particular method cause crash to desktop in linux.

### ISSUE THREAD

**Issue by spacehamster** [pardeike/Harmony#198]
**Describe the bug**
In the game Pathfinder Kingmaker, the following patch causes a crash to desktop when the method is called. The crash doesn't occur on windows.

**To Reproduce**
1. The original method and its signature and class
https://gist.github.com/spacehamster/7a9db8f1d86f7315f93b05e4e15c2ed2
2. The patch code
```csharp
[HarmonyPatch(typeof(InteractionHighlightController), "Tick")]
public static class InteractionHighlightController_Tick_Patch
{
	static void Postfix()
	{
		FileLog.Log("Hello");
	}
}
```
3. The output of the Harmony debug log
https://gist.github.com/spacehamster/5bdff9f91af5ba95c4409ee9c1f796bd
4. The stacktrace or other errors
Player.log file contains the following error
```
the exception the in the log file is
Receiving unhandled NULL exception
#0  0x007fdd38c429c0 in funlockfile
#1  0x007ffc92495398 in (Unknown)
#2  0x007ffc924953a8 in (Unknown)
#3  0x007ffc924953b8 in (Unknown)
#4  0x007ffc924953c8 in (Unknown)
#5  0x007ffc924953d8 in mono_print_method_from_ip
#6  0x007ffc92495700 in mono_perfcounter_foreach
#7  0x007ffc92495750 in mono_runtime_invoke
#8  0x007ffc924957e0 in operator delete(void*)
#9  0x007ffc92495810 in operator delete(void*)
#10 0x007ffc92495830 in operator delete(void*)
#11 0x007ffc92495990 in operator delete(void*)
#12 0x007ffc924959d0 in operator delete(void*)
#13 0x007ffc92495b40 in operator delete(void*)
#14 0x007ffc92495cb0 in operator delete(void*)
#15 0x007ffc92495d30 in zcfree
#16 0x007ffc92496320 in __libc_start_main
#17 0x007ffc924963e0 in zcfree
```
**Expected behavior**
When loading into a particular game save, the game should not crash to desktop, and should print hello to the log file repeatedly.

**Screenshots / Code**
The full code of the mod that is causing issues: https://gist.github.com/spacehamster/e1fb06d82eeb10b20abe457127d1163f

**Runtime environment (please complete the following information):**
 - OS: Ubuntu 19.04 desktop amd6464
 - .NET version: 4.6
- Harmony version: Both 1.2.0.1 and 2.0.0.0
- Name of game or host application: Pathfinder Kingmaker

**Additional context**
The crash occurs no matter if its a Postfix, Prefix or Transpiler patch. The problem seems to be linked to the particular method that was patched, as other methods don't seem to have the same issue.

**Comment by pardeike** [comment]
Empty methods are probably inlined or optimised away so there isn't much Harmony can work on.
