### ISSUE TITLE
Harmony should support MS .NET and not only Mono. (was: Error trying to override int getter)

### ISSUE THREAD

**Issue by llaughlin** [pardeike/Harmony#2]
Target class:
```
public sealed class VisualFind
{
    private int _waitForElementsTimeout;

    public int WaitOnElementsTimeout
    {
      get
      {
        return this._waitForElementsTimeout;
      }
      set
      {
        this._waitForElementsTimeout = value;
    }
}
```

Patcher:
```
internal class HarmonyPatcher
{
        private static readonly Logger _Log = LogManager.GetCurrentClassLogger();

        public static HarmonyInstance Initialize()
        {
            _Log.Info($"Initializing harmony patches");
            HarmonyInstance harmony = HarmonyInstance.Create("com.test");
            harmony.PatchAll(Assembly.GetExecutingAssembly());
            return harmony;
        }
}
```

Patch:
```
[HarmonyPatch(typeof(VisualFind))]
[HarmonyPatch("get_WaitOnElementsTimeout")]
public class VisualFindPatch
{
        private static readonly Logger _Log = LogManager.GetCurrentClassLogger();

        [HarmonyPrefix]
        static void BeforeGet()
        {

        }
}
```

I get the following error: 
```
2017-02-06 14:18:45.0133 INFO Test.Ui.Patches.HarmonyPatcher.Initialize(Main.cs:19)   Initializing harmony patches
2017-02-06 14:18:45.0653 FATAL Test.Ui.Utility.Test.BaseTest.Initialize(BaseTest.cs:114) System.NotSupportedException: Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported
   at System.Reflection.Emit.DynamicMethod.CheckConsistency(MethodAttributes attributes, CallingConventions callingConvention)
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod, StackCrawlMark& stackMark)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
   at Harmony.DynamicTools.CreateDynamicMethod(MethodBase original, String suffix) in C:\repo\Harmony\Harmony\Tools\DynamicTools.cs:line 22
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, List`1 prefixes, List`1 postfixes, List`1 processors) in C:\repo\Harmony\Harmony\MethodPatcher.cs:line 51
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) in C:\repo\Harmony\Harmony\PatchFunctions.cs:line 70
   at Harmony.PatchProcessor.Patch() in C:\repo\Harmony\Harmony\PatchProcessor.cs:line 57
   at Harmony.HarmonyInstance.<PatchAll>b__5_0(Type type) in C:\repo\Harmony\Harmony\HarmonyInstance.cs:line 60
   at Harmony.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action) in C:\repo\Harmony\Harmony\Tools\Extensions.cs:line 45
   at Harmony.HarmonyInstance.PatchAll(Assembly assembly) in C:\repo\Harmony\Harmony\HarmonyInstance.cs:line 53
   at Test.Ui.Patches.HarmonyPatcher.Initialize() in C:\repo\Test.Ui\Patches\Main.cs:line 21
```

To my knowledge, it should be working properly. What am I missing?

I have also tried changing the signature to `static bool BeforeGetWait` and `static bool AfterGetWait`, with same behavior and error message.

**Comment by pardeike** [comment]
Can you specify your settings? Which Mono version, OS or application? Did you use the release version of Harmony or the latest master? I agree, it should work.

It is a bit weird that your stack trace points to the creation of the DynamicMethod. At that time, nothing has been created or patched yet so it is not related to how you patch. I never had that error "Only public, static, standard supported". Sounds like your runtime is non-standard.

**C:\repo\Harmony\Harmony\Tools\DynamicTools.cs:line 22**
```csharp
var method = new DynamicMethod(
	patchName,
	MethodAttributes.Public | (original.IsStatic ? MethodAttributes.Static : 0),
	CallingConventions.Standard,
	AccessTools.GetReturnedType(original),
	paramTypes,
	original.DeclaringType,
	true
);
```

You can clearly see that it is *public* and *standard* and in my environment it adding *static* or not does not matter. A dynamic method is by nature static with a possible instance parameter as the beginning. One thing you could to, is to test if you succeed by removing the optional "original.IsStatic" and always have "MethodAttributes.Public |  MethodAttributes.Static" instead:

```csharp
var method = new DynamicMethod(
	patchName,
	MethodAttributes.Public | MethodAttributes.Static,
	CallingConventions.Standard,
	AccessTools.GetReturnedType(original),
	paramTypes,
	original.DeclaringType,
	true
);
```

Let me know your findings,
Andreas

**Comment by llaughlin** [comment]
Well, I'm not using Mono, and that may be the problem. I'm using a unit test framework on .NET 4.5.1, but I thought it might work the same.

**Comment by pardeike** [comment]
Yes, it might even be that it works different outside of unit testing. Anyway, you should really try to do the edit I suggested and see if that works.

**Comment by llaughlin** [comment]
Hey, that seems to have worked partially! I now get an error in `DynamicTools.cs:line 75`. It's not finding the `CreateDynMethod` method on the `DynamicMethod` class. Inspecting it, I couldn't find that method either. It may be due to a change in the structure of `DynamicMethod` past .NET 3.5. I'll continue digging.

**Comment by llaughlin** [comment]
Should the line be 
```
typeof(DynamicTools).GetMethod("CreateDynamicMethod", BindingFlags.NonPublic | BindingFlags.Instance);
```

 instead of 
```
typeof(DynamicMethod).GetMethod("CreateDynMethod", BindingFlags.NonPublic | BindingFlags.Instance);
````
?

**Comment by pardeike** [comment]
No. That line actually gets a private method inside DynamicMethod to compile it. Pretty certain it is Mono specific.

**Comment by llaughlin** [comment]
Well, that might be the problem then :P. I wonder if I can find something suitable to use outside of Mono...

**Comment by pardeike** [comment]
I prioritized Mono but that does not mean that with a few checks one could add .NET compatibility. I think I address this in the future or let someone else do it in a pull request. I am pretty sure that it is possible to have one version of Harmony that supports both environments.

**Comment by pardeike** [comment]
"couldn't" it should be

**Comment by dr4cul4** [comment]
In .NET CreateDynMethod doesn't exist in DynamicMethod class and I see no similar construct. But even if you surpass this problem then you get against next wall which is native calls to mono libs. At this point I just gave up.

I rally would like to use this library, shame.

**Comment by pardeike** [comment]
In my early experiments, I had a different strategy to force creation of the dynamic method: I simply "pre-run" them by calling them. Since it's a dynamic method one could add a small IL header to the method that simply returns directly and then call into your newly build method. The trick is then to find the right start point in the resulting assembler code after that immediate return. Use that as the destination of the assembler jump from the original method and you're done.

Alternatively, one could add IL code using a static "firstTime" bool to do the same. This will remove the need to find a different start in the assembler but at the cost of an extra if-check which makes it a slower approach. 

Finally, the mono calls are just for getting the jit-ed assembler code starting location. I think that this can be done in MS.NET too but in a different way.

**Comment by pardeike** [comment]
Please try the latest changes that were merged into the master and report back any findings.

**Comment by antonberezan** [comment]
@pardeike it works now for me, thanks!

**Comment by pardeike** [comment]
Excellent!

**Comment by bcmpinc** [comment]
When will this fix be released?

**Comment by pardeike** [comment]
Releases are rather sparse because they require a very good quality level. Mostly because of other applications and communities depend on a stable version. 

I am working towards a v1.1 release within the coming weeks.
