### ISSUE TITLE
Prefix Documentation

### ISSUE THREAD

**Issue by rainbowdesign** [pardeike/Harmony#200]
I did read that you had a project to improve the documentation the effort is appreciaded.
Here is something i cannot find in the documentation.
You write this:

> This method defines the code that is executed before the original method. Execution will be skipped if an earlier prefix indicates it wants to skip the original method. 

I want to do exactly this:
`
    [HarmonyPatch(typeof(AutoMiner), "RefreshDiggableCell")]
    public class __RefreshDiggableCell
    {
        public static void Prefix(AutoMiner __instance)
        {
            if (__instance.width == 60 && __instance.height == 8)
            {...
            // if this condition is valid skip the execution of the original method otherwise execute it
            }
        }
    }
`
The problem is i cannot find any more Documentation in the wiki about this features.
And you Should link to it here:
> Execution will be skipped if an earlier prefix indicates it wants to skip the original method.

**Comment by DenJur** [comment]
More up to date can be found here: https://harmony.pardeike.net/articles/patching-prefix.html#changing-the-result-and-skipping-the-original

**Comment by rainbowdesign** [comment]
Thats neat i did not know this documentation, Thankyou :)
