### ISSUE TITLE
Generic method patch gets called for all types

### ISSUE THREAD

**Issue by spacehamster** [pardeike/Harmony#201]
**Describe the bug**

When patching a generic method with a concrete type, the patch gets called for all types instead of just the concrete type specified. If the method is patched twice with two different concrete types, only the last patch is called. This causes a lot of errors as the original method is also called with the wrong type.

**To Reproduce**
1. The original method and its signature and class
https://gist.github.com/spacehamster/6be85e6c7ecdcdabf9d371e1d589ab4d
2. The patch code
```csharp
[Harmony12.HarmonyPatch()]
static class ResourcesLibrary_TryGetResource_EquipmentEntity_Patch
{
	static MethodBase TargetMethod()
	{

		return AccessTools.Method(typeof(ResourcesLibrary), "TryGetResource").MakeGenericMethod(typeof(EquipmentEntity));
	}
	static void Postfix(MethodBase __originalMethod, string assetId, UnityEngine.Object __result)
	{
		try
		{
			ResourcesLibrary.LibraryObject.ResourceNamesByAssetId.TryGetValue(assetId, out var text);
			var resultType = __result != null ? __result.GetType().Name : "Null";
			Main.Log($"{__originalMethod} called {assetId} {text}({resultType})");
		}
		catch (Exception ex)
		{
			Main.Error(ex);
		}
	}
}
```
3. The output of the Harmony debug log
https://gist.github.com/spacehamster/d36deda52e179586ddb28bf6f7afe8de
4. The stacktrace or other errors
No exceptions thrown as a direct result, return value of null causes errors later.

**Expected behavior**

When patching a concrete instance of a generic type, the patch should only be called for instances of `EquipmentEntity`. Output log should not contain references to other types, such as `PortraitPacks`.

Example of output
```
[HarmonyGenerics] Kingmaker.Visual.CharacterSystem.EquipmentEntity TryGetResource[EquipmentEntity](System.String, Boolean) called 35faad2de585b734a998c46cfb1cd66e PlayerWizard03_Portrait(Null)
Closing file archive:/CAB-5d18a46ab0d2f1b972888b401fc5462c/CAB-5d18a46ab0d2f1b972888b401fc5462c.resS
 
(Filename:  Line: 481)

Could not open file archive:/CAB-5d18a46ab0d2f1b972888b401fc5462c/CAB-5d18a46ab0d2f1b972888b401fc5462c.resS for read
 
(Filename:  Line: 56)

async texture load: failed to load sactx-1024x1024-BC7-PlayerWizard03_Portraits_Atlas-9aef41ac from archive:/CAB-5d18a46ab0d2f1b972888b401fc5462c/CAB-5d18a46ab0d2f1b972888b401fc5462c.resS
[HarmonyGenerics] Kingmaker.Visual.CharacterSystem.EquipmentEntity TryGetResource[EquipmentEntity](System.String, Boolean) called e7b2c1a3db9264042a3520250489f971 Shandra_Portrait(Null)
[HarmonyGenerics] Kingmaker.Visual.CharacterSystem.EquipmentEntity TryGetResource[EquipmentEntity](System.String, Boolean) called 5a0a2a2f0c8081e4b846f2226b85ea11 EE_Head_Face01_M_TF(EquipmentEntity)
```
**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version: .Net Framework 4.6
 - Harmony version Both 1.2.0.1 and 2.0.0.0
- Name of game or host application: Pathfinder Kingmaker

**Additional context**

If I try to patch the generic method with two different concrete types, only the last patch that is applied is called. In this example, ResourcesLibrary_TryGetResource_EquipmentEntity_Patch.Postfix is never called.
```csharp
[Harmony12.HarmonyPatch()]
static class ResourcesLibrary_TryGetResource_EquipmentEntity_Patch
{
	static MethodBase TargetMethod()
	{

		return AccessTools.Method(typeof(ResourcesLibrary), "TryGetResource").MakeGenericMethod(typeof(EquipmentEntity));
	}
	static void Postfix(MethodBase __originalMethod, string assetId, UnityEngine.Object __result)
	{
		try
		{
			ResourcesLibrary.LibraryObject.ResourceNamesByAssetId.TryGetValue(assetId, out var text);
			var resultType = __result != null ? __result.GetType().Name : "Null";
			Main.Log($"{__originalMethod} called {assetId} {text}({resultType})");
		}
		catch (Exception ex)
		{
			Main.Error(ex);
		}
	}
}
[Harmony12.HarmonyPatch()]
static class ResourcesLibrary_TryGetResource_PortraitPack_Patch
{
	static MethodBase TargetMethod()
	{

		return AccessTools.Method(typeof(ResourcesLibrary), "TryGetResource").MakeGenericMethod(typeof(PortraitPack));
	}
	static void Postfix(MethodBase __originalMethod, string assetId, UnityEngine.Object __result)
	{
		try
		{
			ResourcesLibrary.LibraryObject.ResourceNamesByAssetId.TryGetValue(assetId, out var text);
			var resultType = __result != null ? __result.GetType().Name : "Null";
			Main.Log($"{__originalMethod} called {assetId} {text}({resultType})");
		}
		catch (Exception ex)
		{
			Main.Error(ex);
		}
	}
}
```
The output of the Harmony debug log https://gist.github.com/spacehamster/6b2969d0f604fd959bf3ed2b2f67c3ff

**Comment by pardeike** [comment]
That is a limitation of how Harmony patches the assembler. Without more detailed knowledge of how the jitter creates the assembler glue code this isn’t solvable. And I have no expertise of this undocumented area.

**Comment by spacehamster** [comment]
Would it be possible to document somewhere that generic patches aren't well supported? I thought it was an issue with my code for a while.

**Comment by pardeike** [comment]
The problem is that I even can’t say that it does not work at all.

**Comment by mcpiroman** [comment]
[Documentation](https://github.com/pardeike/Harmony/wiki/Target-Method-Annotations#generic-methods) states that the provided approach should work, right?
Would you mind clarifying whether this (should) always work, sometimes work or never work? I'm quite confused now.

**Comment by pardeike** [comment]
Different .NET versions on different platforms have different JITer implementations that add logic on the assembler level that is not documented.

**Comment by mcpiroman** [comment]
Ok, so I assume this falls into 'sometimes works'

**Comment by drok** [comment]
@spacehamster did you ever find a solution, workaround, or any further information?

I find that even the pro-tip of patching with dynamic generics does not work; given the enumeration below, a generic member `public List<T> GetImplementations<T>() where T : class` of a non-generic class is only patched with the last generic type. Ie, calling `GetImplementations<ICities.IUserMod>()` results in a call to a prefix/postfix where ___result is `List<ICities.IThreadingExtension>`, although it should be `List<ICities.IThreadingExtension>`

```CS
        private static IEnumerable<MethodBase> TargetMethods()
        {
            yield return AccessTools.Method(typeof(PluginManager), "GetImplementations").MakeGenericMethod(typeof(object));
            yield return AccessTools.Method(typeof(PluginManager), "GetImplementations").MakeGenericMethod(typeof(ICities.IUserMod));
            yield return AccessTools.Method(typeof(PluginManager), "GetImplementations").MakeGenericMethod(typeof(ICities.IThreadingExtension));
        }
```

I'd love to find a way, even hackish, that "sometime works" in this particular case. I'm willing to jump through some hoops, but have no idea how to get the generic type at runtime, from inside the prefix/postfix.

**Comment by spacehamster** [comment]
@drok I have not found a solution or workaround. It apparently involves undocumented runtime details, so I did not bother looking for further information.
