### ISSUE TITLE
Minor issue in UnitTests

### ISSUE THREAD

**Issue by maf123sp** [pardeike/Harmony#203]
The unit tests:
- StaticPatches::TestMethod2()
- StaticPatches::TestMethod2()
- StaticPatches::TestMethod4()
have a failure. For x64 the patchedCode is not read correctly for all methods with an offset value (Debug mode or Debugger attached; 0xe9)

I've changed the lines
from
************* original *************
	unsafe
			{
				var patchedCode = *(byte*)originalMethodStartPre;
				if (IntPtr.Size == sizeof(long))
					Assert.IsTrue(patchedCode == 0x48);
				else
					Assert.IsTrue(patchedCode == 0x68);
			}
**********************************

to

*********** proposed changes ***
unsafe
			{
				var patchedCode = *(byte*) originalMethodStartPre;
				if (IntPtr.Size == sizeof(long))
				{
					if (patchedCode == 0xe9)
					{
						// add offset (1 for marker byte and 4 bytes for int offset value);
						originalMethodStartPre += 5 + *(int*) (originalMethodStartPre + 1);
						patchedCode = *(byte*) originalMethodStartPre;
					}

					Assert.IsTrue(patchedCode == 0x48);
				}
				else
					Assert.IsTrue(patchedCode == 0x68);
			}
***********************************

Now all combination of x86|x64 and Debug|Release using Debugger, no Debugger and Unit tests are working fine.

Great project!!

**Comment by pardeike** [comment]
Thanks. I’ll add the changes when I have time!

**Comment by pardeike** [comment]
I removed that section because I don't see much value in it.
