### ISSUE TITLE
Easy method replacement

### ISSUE THREAD

**Issue by maf123sp** [pardeike/Harmony#204]
Is it possible to add a patch attribute, which allows an easy replacement of an existing method?

Currently there are Prefix and Postfix. But some return values do not allow easy changes (like Enumerables in combination with yield).
In this case I could imagine having two more attributes:

[HarmonyReplace] - can be used as attribute for methods, which completely replaces the originla method

and 
[HarmonyOriginal] - is a declaration, which is being replaced by the original method itself; this allows to call the original method at any stage of the user flow within a replacement

**Comment by pardeike** [comment]
For those cases I recommend using a pass through postfix:
```cs
static IEnumerable<Foo> Postfix(IEnumerable<Foo> someName, ....normal arguments...)
{
//...
}
```
The pass through postfix is defined by that the return type is equal to the type of the first argument (name not important). If you never read from the input it will never run the original, which basically gives you an easy replacement strategy.
