### ISSUE TITLE
Constructor can't be patched

### ISSUE THREAD

**Issue by maf123sp** [pardeike/Harmony#205]
Following the documentation the attribute HarmonyPatch(new Type[]{}) should allow to patch a constructor. I used this in combination with a postfix method, but the system tells me, that no method has been found.

**Comment by pardeike** [comment]
You need to use the attribute(s) with MethodType arguments.

**Comment by pardeike** [comment]
For example:

```cs
[HarmonyPatch(typeof(Foo))]
[HarmonyPatch(new Type[] { ... })]
[HarmonyPatch(MethodType.Constructor)]
```
