### ISSUE TITLE
Add a strong name key to nuget

### ISSUE THREAD

**Issue by Danielku15** [pardeike/Harmony#210]
**Is your feature request related to a problem? Please describe.**
I cannot consume the library for our project as we use strong name keys for our assemblies but the Nuget package of Harmony doesn't. You will end up with an exception like

```
System.IO.FileLoadException: Could not load file or assembly '0Harmony, Version=1.2.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044).
```

It would be great if Harmony could add a strong name to their officially released libraries. 

**Describe the solution you'd like**
Simply create a Strong Name Key, add it to the repostiory and use it in your build / publish chain. 
https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

**Describe alternatives you've considered**
There are ways to disable strong name verification in certain setups, but usually this is not desired. 

https://stackoverflow.com/questions/21763822/how-to-disable-strong-name-verification-for-all-net-assembly

**Additional context**
Adding a SNK which is even part of the git repository might not add any level of security or trust to Harmony, but it simply solves the issue that you cannot use the library in environments where strong names they are still used. 

Please note that strong-name keys are not the same as fully signed DLLs where a code signing certificate needs to be bought. It is a simple .net assembly signing system.

**Comment by apobekiaris** [comment]
for such cases we use https://github.com/dsplaisted/strongnamer

**Comment by Danielku15** [comment]
I was able to get Harmony running in my environment using this helper package. But it is quite annoying maintaining it in all your projects. strongnamer does not work with transitive dependencies and I am trying to use Harmony within our unit/integration tests depending on some settings. I currently need to add it to all our unit test projects to not break it. 

I am still hopeing for a strong named assembly 😀

**Comment by pardeike** [comment]
@Danielku15 And you never know what happens next. I am preparing for release of 2.0 and guess what, I added strong naming! Please verify.

**Comment by pardeike** [comment]
Strong naming led to too many other conflicts. I suggest using your own tool to sign Harmony.
