### ISSUE TITLE
Harmony 2 on Nuget?

### ISSUE THREAD

**Issue by apobekiaris** [pardeike/Harmony#212]
We use this great lib in many of our packages however now we have to build manually and include the assembly as a file which is totally inconvenient what are your plans on this?

**Comment by erdelf** [comment]
Harmony 2 isn't released yet, before that happens there won't be a release on nuget

**Comment by apobekiaris** [comment]
how about a prelease or a beta then as MS does for their packages, I only see gain from such an action

**Comment by apobekiaris** [comment]
or is it ok that we publish it it ourselves under our brand name? e.g. `Lib.Harmony.Xpand` ?

**Comment by pardeike** [comment]
Why would you want to create strong dependencies on an unfinished product?

**Comment by apobekiaris** [comment]
we ave more than 100 packages that depend on it, and with the official version we had problems while the code from master works fine. Many times due to the custom scripts our packages break so we have to instruct the users to donwload the source of our repos where the assembly binary lives. We can avoid all this mess with an out of the book nuget process

**Comment by apobekiaris** [comment]
futher more it will be much easier for anybody else to else to help u test the lib if u decide yourself to publish a prelease

**Comment by pardeike** [comment]
I will create a prerelease as soon as 2.0b gets API stable - hopefully rather soon.
