### ISSUE TITLE
Traverse.Property doesn't work for static properties

### ISSUE THREAD

**Issue by ManlyMarco** [pardeike/Harmony#213]
**Describe the bug**
Traverse.Property doesn't work for static properties when using the Type overload of Traverse.Create instead of the instance overload.

**To Reproduce**
1. Have a class with a static property.
2. Use Traverse.Create(typeof(MyClass)).Property to get the static property.
3. Property check fails at https://github.com/pardeike/Harmony/blob/master/Harmony/Tools/Traverse.cs#L272 while the field check works fine.

**Expected behavior**
Traverse.Property should work for static types like Traverse.Field does.

**Comment by pardeike** [comment]
Fixed in master
