### ISSUE TITLE
Traverse.Property does not find properties from base types

### ISSUE THREAD

**Issue by ManlyMarco** [pardeike/Harmony#215]
**Describe the bug**
Traverse.Property does not find properties from base types of the object instance passed in to Traverse.Create.

**To Reproduce**
```cs
class A : B { }
class B { public bool Test {get;} = true; }

Traverse tr = Traverse.Create(new A());
var prop = tr.Property("Test");
prop.GetValue<bool>() // Fails silently
```

**Expected behavior**
Traverse.Property should find properties from base classes. When passing in an instance it's not possible (or desirable) to specify the correct type to get the property.

**Runtime environment (please complete the following information):**
 - Windows 10, 64bit
 - .NET 4.5 in Unity 2018
 - Harmony version 2.0.0.0

**Comment by pardeike** [comment]
I am willing to make Traverse look for inherited fields, properties and methods but I am a bit sceptical about backwards compatibility. I think within the frame of the 2.0 release it's ok.

**Comment by pardeike** [comment]
Fixed in https://github.com/pardeike/Harmony/commit/6b7b691b8c2d6047e59c466a4dc0ff3a251d3b0a
