### ISSUE TITLE
AccessTools.all and AccessTools.allDeclared should be split into static and non-static and give the user a chance to choose between them

### ISSUE THREAD

**Issue by jojorne** [pardeike/Harmony#216]
**Is your feature request related to a problem? Please describe.**

AccessTools.all and AccessTools.allDeclared should be split into static and non-static and give the user a chance to choose between them. Issue: https://github.com/pardeike/Harmony/issues/218

It's related to a problem where you can't get fields and properties from base class in a patch:
```csharp
[HarmonyPostfix, HarmonyPatch(typeof(Test), "Init")]
private static void Test_Init_Postfix(ref string ___FieldInBaseType)
```

**Describe the solution you'd like**
All AccessTools methods should give a chance to choose between static and non-static, declared and non-declared.

**Comment by pardeike** [comment]
AccessTools.all is really only a shortcut for **all** flags. If you need specific behaviour, use your own. I think I won't change `all` but that does not mean that I won't change the behaviour of the methods in AccessTools related to the other Issues filed.
