### ISSUE TITLE
Get fields, properties and methods from base class in a patch

### ISSUE THREAD

**Issue by jojorne** [pardeike/Harmony#217]
**Is your feature request related to a problem? Please describe.**

It's related to a problem where you can't get fields and properties from base class in a patch:
```csharp
[HarmonyPostfix, HarmonyPatch(typeof(Test), "Init")]
private static void Test_Init_Postfix(ref string ___FieldInBaseType)
```

**Comment by jojorne** [comment]
I don't understand why everything has to be declared only because most of the time we can access stuff from base...
AccessTools.FieldRefAccess = declared
AccessTools.FirstConstructor = declared
AccessTools.FirstMethod = declared
AccessTools.FirstProperty = declared
AccessTools.GetFieldNames = declared
AccessTools.GetMethodNames = declared
AccessTools.GetPropertyNames = declared
AccessTools.Method = declared

**Comment by pardeike** [comment]
There is a real difference between some runtime reflection when you call AccessTools methods and an implicit access to base class fields inside IL code of a patched and replaced method. While it's possible to implement I suspect its error prone to generate the correct IL codes.

As a workaround I suggest you use AccessTools.FieldRefAccess to create ref's for specific fields for almost native read/write access.
