### ISSUE TITLE
AmbiguousMatchException: Ambiguous match found

### ISSUE THREAD

**Issue by jojorne** [pardeike/Harmony#218]
**Describe the bug**

Using AccessTools.Constructor and AccessTools.DeclaredConstructor on a class constructor that has a static constructor throws AmbiguousMatchException like:
```csharp
public class Test
{
    static Test() { }
    public Test() { }
}
```

**Expected behavior**

AccessTools.Constructor and AccessTools.DeclaredConstructor internally uses AccessTools.allDeclared which has the BindingFlags.Static which will get the static constructor and throw the AmbiguousMatchException

**Comment by pardeike** [comment]
fixed in master (with a boolean flag to the methods)
