### ISSUE TITLE
Potential Bug in MethodBodyReader

### ISSUE THREAD

**Issue by Sunrunner37** [pardeike/Harmony#22]
MethodBodyReader exposes a static function GetInstructions(MethodBase).  If this is called, there is potential to throw a null pointer for ShortInlineVar and InlineVar operand types because "variables" will be undefined.  I fixed this locally by setting "reader.locals = null" in GetInstructions; however, I do not believe this is the correct long term fix.

**Comment by pardeike** [comment]
I fail to understand your scenario. Would you mind explaining the location of the exception and going backwards how this is related to MethodBodyReader?

**Comment by Sunrunner37** [comment]
The exception can occur in MethodCopier.cs line 428:

 `                               instruction.argument = variables[lvi.LocalIndex];`

In the above code snippet, the array "variables" is initialized in the DeclareVariables() function.  If you reach this line via the MethodBodyReader.GetInstructions() code path then it will throw a NullreferenceException because "variables" was never initialized. 

The static function MethodBodyReader.GetInstructions() will not work when the method has a ShortInlineVar or InlineVar operand.

**Comment by pardeike** [comment]
Ah, that is indeed an oversight. I'll look into it.

**Comment by pardeike** [comment]
Fixed. Although I could not easily make it work with fake local variables. As a result, you need to supply the current ILGenerator of the method you are building (or a fake one if you know what you do and filter out the IL codes containing references to the fake generator).
