### ISSUE TITLE
Exception while patching a method when prefix and postfix are defined in different classes while using the __state special parameter

### ISSUE THREAD

**Issue by sullivanmj** [pardeike/Harmony#225]
**Describe the bug**
When calling `Harmony.HarmonyInstance.Patch(MethodInfo original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler)` where:
- `original`, `prefix`, and `postfix` are all non-null, and `transpiler` is null
- `prefix` and `postfix` are represent methods declared in different classes
_and_
- The `__state` special parameter is in use.

An exception is thrown.

The exception indicates that a key was not found.

**To Reproduce**
1. Create a new C# console application.
2. Add a reference to 0Harmony.dll, version 1.2.0.1.
3. Paste the code from [this Gist](https://gist.github.com/sullivanmj/4a53d9fa8ce960dc35698b9ab9196fde) into the Program.cs file.
4. Run the program.

**Expected behavior**
One of the following would be nice:
 - The `Patch` operation would succeed. The `__state` would be correctly passed from the prefix to the postfix.
_or_
 - The exception would be more descriptive, indicating that the operation is not allowed, and this behavior would be documented. I am not sure if patching prefixes and postfixes from different classes should always be disallowed, or if it should only be disallowed when the `__state` special parameter is in use. There could also be issues with the other special parameters - I did not check.

**Screenshots / Code**
Code that will reproduce the issue:
https://gist.github.com/sullivanmj/4a53d9fa8ce960dc35698b9ab9196fde

**Runtime environment**
 - OS: Windows 10 Enterprise, 64 bit, Update 1903
 - .NET version: 4.6.1
 - Harmony version: 1.2.0.1
 - Proprietary commercial software

**Workaround**
The workaround is to declare the prefix method and postfix method in the same class.

**Additional context**
I discovered this issue while trying to better organize some of my code. My specific use case was that I wanted a base class that did some shared prefix work, and did postfix work for _synchronous_ methods. I wanted a derived class to have some different postfix work for _asynchronous_ methods.

Possibly related to #17. At least according to [this comment](https://github.com/pardeike/Harmony/issues/17#issuecomment-303370231) by @pardeike, which indicates that prefix and postfix methods should be declared in the same class.

**Comment by pardeike** [comment]
When you do manual patching there are no restrictions on patch methods except that they are static. So the above example should work just fine.

**Comment by pardeike** [comment]
Ah, the is purely related to `__state`. Seems like an oversight in storing the state (it’s done by full class name)

**Comment by sullivanmj** [comment]
Yes, otherwise, it seems to work as you've indicated.

**Comment by pardeike** [comment]
I think this will, for the time being, classify as a documentation issue. I have no intend to enhance __state. If you need more, use a Transpiler.
