### ISSUE TITLE
Bug in ILInstruction Class

### ISSUE THREAD

**Issue by Sunrunner37** [pardeike/Harmony#23]
There is a bug in the ILInstruction class's GetCodeInstruction() function.  The function does not directly copy the operand to the given code instruction.

The code instruction object is initialized with the following statement on line 24:

`var instr = new CodeInstruction(opcode, argument);`

As you can see, it passes 'argument' in as the operand.  'argument' is not guaranteed to contain the correct operand value in all codes paths because operand is a public member variable that is modified outside of this class.

An example of where this blows up is in MethodCopier.cs in ResolveBranches() line 120.  ILInstruction's public member variable 'operand' is directly written to - this will cause problem later for anyone wanting to convert the ILInstructions into CodeInstructions.

**Comment by pardeike** [comment]
There is no conflict. That code branch only happens during the initial phase from CreatePatchedMethod() and the resulting CodeInstruction's contain the correct information.

GetCodeInstruction() is used to initialize the very first batch of instructions but manipulations that follow all use operand instead of argument.

**Comment by Sunrunner37** [comment]
This was really old so I lost most context on it.  However, we were using this code path to perform some unit testing (this is part of the public api so should not be stateful).  I believe this is patched in the Nitrox branch to function as I describe above.

**Comment by pardeike** [comment]
I see. I am just too lazy to fix the logic to satisfy the tests. If you can give me a use case that breaks then I'll reopen this.
