### ISSUE TITLE
How to check if the target is patched by other harmony instance?

### ISSUE THREAD

**Issue by MestreKarin** [pardeike/Harmony#231]
Hi, as the title says, there is any way to check? For example, a game has a method `Player.Kill` and, **mod_a.dll** and **mod_b.dll** patches that function, but, **mod_b.dll** crashes since `Player.Kill` is already patched by **mod_a.dll**.

**Comment by pardeike** [comment]
Check the methods on the harmony instance you create. You can list all patched methods and get information about each of them. Methods are shared between all mods just like files are so you always get all patches, not just yours. That’s also why you need to supply an ID when you create a harmony instance: for identification.

**Comment by pardeike** [comment]
Discussions are better held at the discord: https://discord.gg/xXgghXR
