### ISSUE TITLE
Generic method cannot be passed as __originalMethod

### ISSUE THREAD

**Issue by LunarWhisper** [pardeike/Harmony#232]
**Describe the bug**
If the __originalMethod is declared in the prefix, an error will occur when the method is called:
```System.ArgumentException: 'Cannot resolve method Void Add(Int32) because the declaring type of the method handle System.Collections.Generic.List`1[T] is generic. Explicitly provide the declaring type to GetMethodFromHandle. '```

**To Reproduce**
1. The original method:
`typeof(List<Int32>).GetMethod("Add")`

2. The prefix method:
`static void InvalidPrefix(MethodInfo __originalMethod, Int32 item) => Console.WriteLine(item);`

3. The patch code: 
```
var original = typeof(List<Int32>).GetMethod(nameof(List<Int32>.Add));
var prefix = typeof(Program).GetMethod(nameof(InvalidPrefix));
instance.Patch(original, prefix: new HarmonyMethod(patchMethod));
```

4. The output of the Harmony debug log:
```### Harmony id=test, version=2.0.0.0, location=T:\ConsoleApp44\bin\Debug\0Harmony.dll
### Started from System.Void ConsoleApp44.Program.Main(System.String[]), location T:\ConsoleApp44\bin\Debug\ConsoleApp44.exe
### At 2019-12-23 07.30.15
Self-patching started (v2.0.0.0)
Potential methods to upgrade:
Self-patched 0 out of 0 methods (0 skipped) in 19ms
### Patch System.Void System.Collections.Generic.List`1<System.Int32>.Add(System.Int32)
L_0000: ldtoken System.Void System.Collections.Generic.List`1<System.Int32>.Add(System.Int32)
L_0005: call System.Reflection.MethodBase System.Reflection.MethodBase.GetMethodFromHandle(System.RuntimeMethodHandle)
L_000a: ldarg 1
L_0010: call System.Void ConsoleApp44.Program.InvalidPrefix(System.Reflection.MethodInfo, System.Int32)
L_0015: // start original
L_0015: ldarg.0
L_0016: ldfld Int32 _size
L_001b: ldarg.0
L_001c: ldfld Int32[] _items
L_0021: ldlen
L_0022: conv.i4
L_0023: bne.un Label1
L_0028: ldarg.0
L_0029: ldarg.0
L_002a: ldfld Int32 _size
L_002f: ldc.i4.1
L_0030: add
L_0031: call System.Void System.Collections.Generic.List`1<System.Int32>.EnsureCapacity(System.Int32)
L_0036: Label1
L_0036: ldarg.0
L_0037: ldfld Int32[] _items
L_003c: ldarg.0
L_003d: ldarg.0
L_003e: ldfld Int32 _size
L_0043: stloc.0
L_0044: ldloc.0
L_0045: ldc.i4.1
L_0046: add
L_0047: stfld Int32 _size
L_004c: ldloc.0
L_004d: ldarg.1
L_004e: stelem System.Int32
L_0053: ldarg.0
L_0054: ldarg.0
L_0055: ldfld Int32 _version
L_005a: ldc.i4.1
L_005b: add
L_005c: stfld Int32 _version
L_0061: // end original
L_0061: ret
DONE
```

4. The stacktrace or other errors:
```
System.ArgumentException: Cannot resolve method Void Add(Int32) because the declaring type of the method handle System.Collections.Generic.List`1[T] is generic. Explicitly provide the declaring type to GetMethodFromHandle. 
   at System.Reflection.MethodBase.GetMethodFromHandle(RuntimeMethodHandle handle)
```

**Expected behavior**
The method works correctly, information about the calling method (not Generic) is passed to the __originalMethod argument.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET Framework 4.7.2
 - Harmony version: sources of 14 nov 2019

**Comment by pardeike** [comment]
Can you provide a full stacktrace (or at least several of the topmost elements). I can’t see how Harmony would cause such an error unless it’s actually you calling the contents of __originalMethod (Harmony never calls it itself). Sounds like a user error and not actually a bug in Harmony. But the stacktrace will tell.

**Comment by LunarWhisper** [comment]
Unfortunately, this is a full stack that Visual Studio displays.

And this is full code to confirm:
```csharp
Harmony.DEBUG = true;
var instance = new Harmony("test");

var original = typeof(List<Int32>).GetMethod(nameof(List<Int32>.Add));
var prefix = typeof(Program).GetMethod(nameof(InvalidPrefix));
instance.Patch(original, prefix: new HarmonyMethod(patchMethod));

static void InvalidPrefix(MethodInfo __originalMethod, Int32 item) => Console.WriteLine(item);
```

**Comment by pardeike** [comment]
The fix for this is to make the logic around https://github.com/pardeike/Harmony/blob/53f5182aef326863f9fdd5d4193df137f985ae28/Harmony/Internal/MethodPatcher.cs#L306  
a bit smarter so it can handle generics.

**Comment by pardeike** [comment]
Fixed in latest master. Please verify.
