### ISSUE TITLE
Cannot patch method with generic result

### ISSUE THREAD

**Issue by LunarWhisper** [pardeike/Harmony#233]
**Describe the bug**
If the method returns a generic type, an error will occur during the patch.

**To Reproduce**
1. The original method and its signature and class:
```csharp
typeof(List<Int32>).GetMethod("GetEnumerator");
```
2. The prefix method:
```csharp
static void ConsoleWriteLine() => Console.WriteLine(Environment.StackTrace);
```
3. The patch code:
```csharp
var original = typeof(List<Int32>).GetMethod("GetEnumerator");
var patch = typeof(Program).GetMethod(nameof(ConsoleWriteLine));
instance.Patch(original, prefix: new HarmonyMethod(patch));
```

4. The output of the Harmony debug log:
```
### Harmony id=test, version=2.0.0.0, location=T:\ConsoleApp44\bin\Debug\0Harmony.dll
### Started from System.Void ConsoleApp44.Program.Main(System.String[]), location T:\ConsoleApp44\bin\Debug\ConsoleApp44.exe
### At 2019-12-23 08.17.01
Self-patching started (v2.0.0.0)
Potential methods to upgrade:
Self-patched 0 out of 0 methods (0 skipped) in 17ms
### Patch System.Collections.Generic.Enumerator<System.Int32> System.Collections.Generic.List`1<System.Int32>.GetEnumerator()
```

5. The stacktrace or other errors
```
System.ArgumentException: The specified Type must not be a generic type definition.
Parameter name: t
   at System.Runtime.InteropServices.Marshal.SizeOf(Type t)
```

**Expected behavior**
The patch is correctly applied.

**Screenshots / Code**
![image](https://user-images.githubusercontent.com/26382228/71337730-ec029580-255d-11ea-9895-b5d586b12422.png)

**Runtime environment (please complete the following information):**
- OS: Windows 10, 64bit
- .NET Framework 4.7.2
- Harmony version: sources of 14 nov 2019

**Additional context**
It isn't enough just to fix this place. If you do it, errors will occur later.

**Comment by LunarWhisper** [comment]
If we go next:
```csharp
### Patch System.Collections.Generic.Enumerator<System.Int32> System.Collections.Generic.List`1<System.Int32>.GetEnumerator()
L_0000: ldloca 0 (System.Collections.Generic.List`1+Enumerator[System.Int32])
L_0002: initobj System.Collections.Generic.List`1+Enumerator[System.Int32]
L_0008: call System.Void ConsoleApp44.Program.ConsoleWriteLine()
L_000d: // start original
L_000d: ldarg.0
L_000e: newobj Void .ctor(System.Collections.Generic.List`1[System.Int32])
L_0013: // end original
L_0013: stloc 0 (System.Collections.Generic.List`1+Enumerator[System.Int32])
L_0014: ldloc 0 (System.Collections.Generic.List`1+Enumerator[System.Int32])
L_0015: ret
DONE
```

![image](https://user-images.githubusercontent.com/26382228/71338430-f6725e80-2560-11ea-8b76-34cd53d00fab.png)

**Comment by pardeike** [comment]
Note to myself: make this work with generic return types:

https://github.com/pardeike/Harmony/blob/0d3fc740a76579c294edecfdc4cb6a251195f5bc/Harmony/Internal/NativeThisPointerCheck.cs#L16

**Comment by pardeike** [comment]
Fixed in latest master. Please verify.

**Comment by pardeike** [comment]
Please note though: While I fixed the exception in Harmony I tried to write a test case for your example. And could not get it to patch anything. In general, patching methods directly in mscorlib gives you mixed results. Some are pure native and cannot be IL patched some have weird optimizations.

So: the bug is fixed but your example will probably never patch.
