### ISSUE TITLE
Using Harmony with a Mono Injector

### ISSUE THREAD

**Issue by redstonekasi** [pardeike/Harmony#234]
So I made a little mod for a game, now i want to further mod it without directly modifiying the Assembly-CSharp.dll.
I already coded a little patch, but I just can't seem to find the location where I need to put the 0Harmony.dll.

```csharp
using Multiplayer;
using System.Reflection;
using Harmony;

namespace KasiMod
{
    class Patcher
    {
        public static void Patch()
        {
            var harmony = HarmonyInstance.Create("de.kasi.kasimod");
            harmony.PatchAll(Assembly.GetExecutingAssembly());
        }
    }

    [HarmonyPatch(typeof(NetGame), "OnClientReceive")]
    class KickPatch
    {
        static bool Prefix(object connection, NetStream stream)
        {
            NetMsgId msgId = stream.ReadMsgId();
            if (msgId == NetMsgId.Kick && Main.instance.toggleUnkickable) return false;

            return true;
        }
    }
}
```

**Comment by redstonekasi** [comment]
Just to clarify: When the mod loads it gives a FileNotFoundException for the Assembly.
I tried putting the 0Harmony.dll in the games root directory, the `Managed` directory and in the directory where my injector is.

**Comment by pardeike** [comment]
You need to find out how the injector loads your and other dlls. Since I don’t know anything about your loader I cannot help you here. The only option I can think of is to ILMerge your dll and 0Harmony.dll into one dll file. That will certainly work.

**Comment by xsilent007** [comment]
You could maybe try Fody.Costura to embed references as resources

**Comment by redstonekasi** [comment]
Thanks for the help, I tried using Fody.Costura and seems to be working perfectly.
Only problem is that my injector is currently not working but thats a problem on my side.
Thanks !
