### ISSUE TITLE
Unable to patch methods located inside the GlobalType (aka. <Module>)

### ISSUE THREAD

**Issue by xsilent007** [pardeike/Harmony#235]
**Describe the bug**

When a method is resolved inside the GlobalType (this is only possible via `Module.ResolveMethod(int MDToken)`) its `DeclaringType` property is `null` and when an attempt is made to patch the method, a NRE will get thrown in this function: [GeneralExtensions.FullDescription(this MethodBase method)](https://github.com/pardeike/Harmony/blob/master/Harmony/Tools/Extensions.cs#L66)

**To Reproduce**
1. Resolve a method via its metadata token that is inside `<Module>` (or also known as the globaltype)
2. Try to apply any patch to it

**Expected behavior**
The patch gets applied

**Screenshot**
![Image](https://cdn.discordapp.com/attachments/361891646742462467/662319438799962132/unknown.png)

**Runtime environment:**
 - OS: Windows 10, 64bit
 - .NET version 4.8
 - Harmony version 1.2.0.1

**Comment by pardeike** [comment]
Thanks for the analysis. I am in no means an expert in C# and the concept of a GlobalType is totally new to me. I guess I have to look over my use of `DeclaringType` in the whole project. Thanks.

**Comment by pardeike** [comment]
Fixed in latest master. Please verify.
