### ISSUE TITLE
NullReferenceException Thrown but the method don't have any posible code to cause such Exception

### ISSUE THREAD

**Issue by martinrhan** [pardeike/Harmony#244]
I am making a plugin for a Unity game with BepInEx which implemented Harmony.
I made some patches for some original methods of the game.
`

    public static class Patcher_SetPostion_HScene {
        [HarmonyPatch(typeof(HScene), "SetPosition", new Type[] { typeof(Transform), typeof(Vector3), typeof(Vector3), typeof(bool) })]
        [HarmonyPrefix]
        static bool Prefix0() {
            Debug.Log("SetPosition0 prefix");
            return true;
        }

        [HarmonyPatch(typeof(HScene), "SetPosition", new Type[] { typeof(Transform), typeof(Vector3), typeof(Vector3), typeof(bool) })]
        [HarmonyPostfix]
        static void Postfix0() {
            Debug.Log("SetPosition0 postfix");
        }

        [HarmonyPatch(typeof(HScene), "SetPosition", new Type[] { typeof(Vector3),typeof(Quaternion), typeof(Vector3), typeof(Vector3), typeof(bool) })]
        [HarmonyPrefix]
        static bool Prefix1() {
            Debug.Log("SetPosition1 prefix");
            return true;
        }
        [HarmonyPatch(typeof(HScene), "SetPosition", new Type[] { typeof(Vector3), typeof(Quaternion), typeof(Vector3), typeof(Vector3), typeof(bool) })]
        [HarmonyPostfix]
        static void Postfix1() {
            Debug.Log("SetPosition1 postfix");
        }
    }
`
As you can see,  these methods only have Debug.Log with them which is not posible to cause NullReferenceException. However that Exception was thrown and the log indicates that it came form one of those methods.
Here is the info given to me.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) HScene.SetPosition_Patch2(HScene,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Vector3,UnityEngine.Vector3,bool)
HScene+<ChangeAnimation>c__Iterator2.MoveNext () (at <f4958b724c854ed5912569402c4ebffa>:0)
UniRx.Observable+<WrapEnumerator>c__Iterator2.MoveNext () (at <d29e112a84654c2295f6648cf23dffb0>:0)
--- End of stack trace from previous location where exception was thrown ---
I really cannot figure out what's the cause of this.

**Comment by pardeike** [comment]
I cannot reproduce with master. Added a test in https://github.com/pardeike/Harmony/commit/5596ac60d748c64a40a41c85fc62ca099317dd52 to verify (as close as I could get to your example without having the actual original code) and it tests just fine.

**Comment by martinrhan** [comment]
> I cannot reproduce with master. Added a test in [5596ac6](https://github.com/pardeike/Harmony/commit/5596ac60d748c64a40a41c85fc62ca099317dd52) to verify (as close as I could get to your example without having the actual original code) and it tests just fine.

I solve the problem already, actually the exception occured at orginal SetPosition method, not one of the prefix or postfix. Sorry for distrubing.
