### ISSUE TITLE
Should static methods returning structs be NativeThisPointer fixed too

### ISSUE THREAD

**Issue by pardeike** [pardeike/Harmony#252]
Verify if static methods returning structs can require a native return pointer fix too. Relevant line: https://github.com/pardeike/Harmony/blob/6c27e98b741d96ab19f37b619c8244d3234325b5/Harmony/Internal/NativeThisPointerCheck.cs#L66

**Comment by pcfantasy** [comment]
Hi, I find a issue with this NeedsNativeThisPointerFix. 

My patch is like this(works fine with harmony1.2.0.1)

        public static void Postfix(ushort buildingID, ref Building data, InfoManager.InfoMode infoMode, ref Color __result)

Orginal method is 

        public override Color GetColor(ushort buildingID, ref Building data, InfoManager.InfoMode infoMode)

Color is a struct in unity3D

Error shows something wrong in  

     var size = SizeOf(returnType);

goes deeper, error is in this line.
  
      size = (int)dm.Invoke(null, null);




I local build harmony, and force firstArgIsReturnBuffer to false as a workround.

      var firstArgIsReturnBuffer = false;//NativeThisPointer.NeedsNativeThisPointerFix(original);



Hope there are enough clue for you to debug, thanks.

**Comment by pardeike** [comment]
Fixed in upcoming 2.0.0.2

**Comment by pardeike** [comment]
Actually fixed (for static methods) in 2.0.0.4
