### ISSUE TITLE
Question? multi prefix patchs on one method

### ISSUE THREAD

**Issue by pcfantasy** [pardeike/Harmony#256]
I have a question about multi prefix patchs on one method.

If two mods offer two prefix on one method, one return false to skip excute orginal method, one return true to allow excute orginal method.

What will happen in this case? Will the orginal method be excuted or not? Thanks.

**Comment by pardeike** [comment]
The first Prefix that returns `false` will skip the original and all following Prefixes.

**Comment by pcfantasy** [comment]
OK, I see.
