### ISSUE TITLE
Version(s): none

### ISSUE THREAD

**Issue by eksynn** [pardeike/Harmony#265]
probably just a minor oversight, since it still seems to work, but when looking at the mod's load order list in-game, it says the 'version' is 'none'
as a result, any mods that require harmony to be added to the game don't see it, even if it does seem to function.

screenshots:
"none"
https://cdn.discordapp.com/attachments/560138667059052555/684493658699202586/unknown.png

"RJW"
https://cdn.discordapp.com/attachments/560138667059052555/684494575838298112/unknown.png

(there was another mod that this happened to, but i removed it since i didn't really need it. then i installed rjw and noticed the similarities in the error after also downloading harmony separately - figured i'd report it)

**Comment by pardeike** [comment]
That does not look like the official Harmony version.

**Comment by pardeike** [comment]
Also, wrong repository.
