### ISSUE TITLE
Color Struct Unity Error

### ISSUE THREAD

**Issue by l-404-l** [pardeike/Harmony#267]
**Describe the bug**
Same issue as [#170](https://github.com/pardeike/Harmony/issues/170)

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET 3.5
 - Harmony version 2.0.0.8

**Comment by pardeike** [comment]
I would need a minimal test case.

**Comment by l-404-l** [comment]
Currently running tests with 2.0.0.4 ill send you the with the 

`### Patch: static UnityEngine.Color VRCPlayer::GetDefaultNameplateColor(VRC.Core.APIUser ILAJLDDDONH)` is all it would output for a log then crash 

I tried with "ref and without" it only happens with color.

**Comment by l-404-l** [comment]
Original Method 
`	public static Color GetDefaultNameplateColor(APIUser ILAJLDDDONH)
	{
		if (ILAJLDDDONH == null)
		{
			return VRCPlayer.mutedNamePlateColor;
		}
		return VRCPlayer.GetDefaultNameplateColor(ILAJLDDDONH, ILAJLDDDONH.hasVIPAccess);
	}`
PatchMethod:
`        private static bool ColorTest(APIUser __0, ref Color __result)
        {
            __result = Color.red;
            return false;
        }`

Works on 2.0.0.4 but not on 2.0.0.8

**Comment by pardeike** [comment]
I just added the following code to the Harmony unit tests and it passes for all platforms:
```cs
public struct UnityColor
{
	public float r;
	public float g;
	public float b;
	public float a;
}

public class APIUser
{
}

public class Class18
{
	[MethodImpl(MethodImplOptions.NoInlining)]
	public static UnityColor GetDefaultNameplateColor(APIUser user)
	{
		return new UnityColor() { r = 0, g = 0, b = 0, a = 0 };
	}
}

[HarmonyPatch(typeof(Class18))]
[HarmonyPatch(nameof(Class18.GetDefaultNameplateColor))]
public static class Class18Patch
{
	public static bool prefixExecuted = false;

	public static bool Prefix(APIUser __0, ref UnityColor __result)
	{
		_ = __0;
		prefixExecuted = true;
		__result = new UnityColor() { r = 1, g = 1, b = 1, a = 1 };
		return false;
	}
}

[Test]
public void Test_Class18()
{
	var instance = new Harmony("test");
	Assert.NotNull(instance, "instance");
	var processor = instance.CreateClassProcessor(typeof(Class18Patch));
	Assert.NotNull(processor, "processor");

	var methods = processor.Patch();
	Assert.NotNull(methods, "methods");
	Assert.AreEqual(1, methods.Count);

	Class18Patch.prefixExecuted = false;
	var color = Class18.GetDefaultNameplateColor(new APIUser());

	Assert.IsTrue(Class18Patch.prefixExecuted, "prefixExecuted");
	Assert.AreEqual((float)1, color.r);
}
```

**Comment by pardeike** [comment]
Please verify if PL #276, which is now on master, fixes this issue
