### ISSUE TITLE
Extremely slow patching due to FastInvokeHandler usage.

### ISSUE THREAD

**Issue by m22spencer** [pardeike/Harmony#271]
**Describe the bug**
Usage of FastInvokeHandler during deep copy of instructions results in extremely slow patching.
Currently, on RogueTech (a BattleTech mod pack), application startup consists of over 25 seconds spent in `Harmony.CodeTranspiler::ConvertToGeneralInstructions`.

Most of this time (80-90%) is due to the usage of `FastInvokeHandler` in `DeepCopy`. The construction of the delegate massively exceeds any gains from calling it. (At least in regards to the instruction deep copy.)

As a hack, replacing the body of `MethodInvoker::Handler` with `return methodInfo.Invoke` (reflection) drops 20 seconds off of BattleTechs load times.

**To Reproduce**
Apply any patch.

**Expected behavior**
Much faster patching.

**Screenshots / Code**
Without hack ~3.1s spent patching with majority of time spent creating delegates:
![fastinvoke-enabled](https://user-images.githubusercontent.com/844938/77752929-7ee81b80-6ff6-11ea-91b7-45d3c9e08a39.PNG)

With hack ~.6s:
![fastinvoke-disabled](https://user-images.githubusercontent.com/844938/77752933-80b1df00-6ff6-11ea-9bca-f36cac620cca.PNG)

**Runtime environment (please complete the following information):**
- Windows 10, 64bit
- .NET 4.7.2
- Harmony 1.2.0.1 (Also tested with a wrapper that converts to Harmony 2.x)
- BattleTech ?

** Additional
I'm not sure BT will ever be able to update to 2.0 due to how many legacy mods exist, but just wanted to note this issue in case you're unaware of it.  BT in particular tends to do a crazy amount of patches, which makes this issue far more impactful than in the more common usages.

If you need any additional information, please let me know.
Thank you.

**Comment by pardeike** [comment]
The design in 1.2.0.1 was chosen because of a reason. CodeInstruction isn’t assignable across Assembly boundaries but 2.0 has an optimisation that prevents the otherwise necessary deep copy in case it’s within the same Assembly. 

Harmony 1.2.0.1 is basically no longer supported but feel free to fork it if necessary.

**Comment by m22spencer** [comment]
Had the same issue when converting all the patches on the fly to Harmony2, so I was probably doing it in a way that bypasses the new optimizations.  I'll have to double check that.

Thanks for the tip.
