### ISSUE TITLE
Still Meet Color Struct Unity Error

### ISSUE THREAD

**Issue by pcfantasy** [pardeike/Harmony#272]
The Same with #267  
And I report this issue in the comment of #252 , but seems you waive it.

Test it in new 2.0.0.8 still failed

Hi, I find a issue with this NeedsNativeThisPointerFix. 

My patch is like this(works fine with harmony1.2.0.1)

        public static void Postfix(ushort buildingID, ref Building data, InfoManager.InfoMode infoMode, ref Color __result)

Orginal method is 

        public override Color GetColor(ushort buildingID, ref Building data, InfoManager.InfoMode infoMode)

Color is a struct in unity3D

Error shows something wrong in  

     var size = SizeOf(returnType);

goes deeper, error is in this line.
  
      size = (int)dm.Invoke(null, null);

I local build harmony, and force firstArgIsReturnBuffer to false as a workround.

      var firstArgIsReturnBuffer = false;//NativeThisPointer.NeedsNativeThisPointerFix(original);

Hope there are enough clue for you to debug, thanks.

**Comment by pcfantasy** [comment]
Blow is crash code.

0x00007FFAA4D31158 (mono) set_vprintf_func
0x00007FFAA4D3117C (mono) set_vprintf_func
0x00007FFAA4D51775 (mono) mono_class_get_full
0x00007FFAA4E420D2 (mono) mono_set_break_policy
0x00007FFAA4E53F6C (mono) mono_set_defaults
0x00007FFAA4E55037 (mono) mono_set_defaults
0x00007FFAA4E55655 (mono) mono_set_defaults
0x00007FFAA4E558CB (mono) mono_set_defaults
0x00007FFAA4DA8499 (mono) mono_runtime_invoke
0x00007FFAA4DAE9A7 (mono) mono_runtime_invoke_array
0x00007FFAA4D6CE3F (mono) mono_domain_finalize
0x00000000086EB0C0 (Mono JIT Code) (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
0x00000000086EABDD (Mono JIT Code) System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
0x00000000086EAA00 (Mono JIT Code) System.Reflection.MethodBase:Invoke (object,object[])
0x000000001E649311 (Mono JIT Code) System.Reflection.Emit.DynamicMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
0x00000000086EAA00 (Mono JIT Code) System.Reflection.MethodBase:Invoke (object,object[])
0x000000001E648F55 (Mono JIT Code) HarmonyLib.StructReturnBuffer:SizeOf (System.Type)
0x000000001D4AF5B2 (Mono JIT Code) HarmonyLib.StructReturnBuffer:NeedsFix (System.Reflection.MethodBase)
0x000000001D4AE8C6 (Mono JIT Code) HarmonyLib.MethodPatcher:.ctor (System.Reflection.MethodBase,System.Reflection.MethodBase,System.Collections.Generic.List`1<System.Reflection.MethodInfo>,System.Collections.Generic.List`1<System.Reflection.MethodInfo>,System.Collections.Generic.List`1<System.Reflection.MethodInfo>,System.Collections.Generic.List`1<System.Reflection.MethodInfo>,bool)
0x000000001D4AC3C3 (Mono JIT Code) HarmonyLib.PatchFunctions:UpdateWrapper (System.Reflection.MethodBase,HarmonyLib.PatchInfo)
0x000000001D4AAD0F (Mono JIT Code) HarmonyLib.PatchClassProcessor:ProcessPatchJob (HarmonyLib.PatchJobs`1/Job<System.Reflection.MethodInfo>)
0x000000001D4A9924 (Mono JIT Code) HarmonyLib.PatchClassProcessor:BulkPatch (System.Collections.Generic.List`1<System.Reflection.MethodBase>,System.Reflection.MethodBase&)
0x000000001D4420DF (Mono JIT Code) HarmonyLib.PatchClassProcessor:Patch ()
0x000000001D4415D0 (Mono JIT Code) HarmonyLib.Harmony:<PatchAll>b__10_0 (System.Type)
0x000000001D441538 (Mono JIT Code) HarmonyLib.CollectionExtensions:Do<object> (System.Collections.Generic.IEnumerable`1<object>,System.Action`1<object>)
0x000000001D441448 (Mono JIT Code) HarmonyLib.Harmony:PatchAll (System.Reflection.Assembly)
0x000000001D440DCF (Mono JIT Code) RealCity.Util.HarmonyDetours:Apply ()
0x000000001D440BC0 (Mono JIT Code) RealCity.Loader:HarmonyInitDetour ()
0x000000001D440A12 (Mono JIT Code) RealCity.RealCity:OnEnabled ()

**Comment by pardeike** [comment]
I suspected that the calculations are different on different platforms and .NET versions. Fixing this can be tricky because of keeping it working for all other versions.

**Comment by pcfantasy** [comment]
I use NET35

**Comment by 0x0ade** [comment]
The issue here is not an "issue" with Harmony, but rather an underlying issue with Unity's outdated version of Mono. It's a Mono JIT bug, but luckily there's a workaround.

MonoMod.Common contains an extension method for `Type` named `GetManagedSize` which does the same thing as Harmony's `SizeOf`, but differently: using a single generic method instead of generating a new dynamic method per type. From my experience, it's less prone to crashes and switching to it might be worth trying - especially because it replicates .NET's own `Unsafe.SizeOf` helper that just isn't available everywhere.

Feel free to compare [.NET's SizeOf](https://github.com/dotnet/runtime/blob/829baa4dcfe8c32034ebb4cf867dff07d853c04a/src/libraries/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L165-L171) against [MonoMod's GetManagedSize](https://github.com/MonoMod/MonoMod.Common/blob/39281f4cfcec98832696afe9445f20c4d201496c/Utils/Extensions.Unsafe.cs#L69-L79) and [Harmony's SizeOf](https://github.com/pardeike/Harmony/blob/master/Harmony/Internal/StructReturnBufferCheck.cs#L86).

**Comment by boformer** [comment]
Just a heads up. I compiled a custom version of harmony that uses `GetManagedSize` and it resolved the issue for me:

```
static int SizeOf(Type type)
{
	if (sizes.TryGetValue(type, out var size))
		return size;

	size = type.GetManagedSize();

	sizes.Add(type, size);
	return size;
}
```

**Comment by pardeike** [comment]
It’s VERY easy to break the logic for all other cases. Does your version still pass all CI ?

**Comment by boformer** [comment]
> It’s VERY easy to break the logic for all other cases. Does your version still pass all CI ?

All unit tests for all targets are running through

**Comment by pardeike** [comment]
That’s not enough. Since the test runner only covers a partial number of architectures it is necessary to run all Azure, Travis and AppVeyor CI tests or else Harmony will fail on those cases.

**Comment by boformer** [comment]
how can I trigger them? I guess create a PR?

**Comment by pardeike** [comment]
Yes. It will run the tests for the PR
