### ISSUE TITLE
Patching internal sealed class

### ISSUE THREAD

**Issue by CaledoniaProject** [pardeike/Harmony#273]
I'm trying to patch an `internal class` with an annotation like this

```
[HarmonyPatch(typeof(XXX), "YYY")]
```

But VS won't compile and raises `CS0122`, because XXX is an internal class.

What should I do now?

**Comment by pardeike** [comment]
You should either use manual patching or a patch class annotated with just `[HarmonyPatch]` that contains a `TargetMethod` method where you use ordinary reflections (or AccessTools helper) to get the correct MethodInfo from a type that you get by name.

**Comment by bqio** [comment]
Use that methods to access internal class fields:
```c#
Traverse.CreateWithType("CLASS_STRING_NAME").Field("FIELD_STRING_NAME").GetValue<FIELD_TYPE>();
Traverse.CreateWithType("CLASS_STRING_NAME").Field("FIELD_STRING_NAME").SetValue<FIELD_TYPE>();
```

**Comment by pardeike** [comment]
> Use that methods to access internal class fields:
> 
> ```cs
> Traverse.CreateWithType("CLASS_STRING_NAME").Field("FIELD_STRING_NAME").GetValue<FIELD_TYPE>();
> Traverse.CreateWithType("CLASS_STRING_NAME").Field("FIELD_STRING_NAME").SetValue<FIELD_TYPE>();
> ```

Not quite. This is about patching, not calling.

**Comment by pardeike** [comment]
Use `TargetMethod` as described in the [documentation](https://harmony.pardeike.net/articles/patching-auxilary.html#targetmethod) for methods that are not supported by the default annotation system.

**Comment by CaledoniaProject** [comment]
I just remove the internal attribute with ILSpy, and it compiles. Simple trick.

**Comment by pardeike** [comment]
That works of course too. There is even a tool for that: https://github.com/CabbageCrow/AssemblyPublicizer
