### ISSUE TITLE
The type initializer for 'HarmonyLib.AccessTools' threw an exception

### ISSUE THREAD

**Issue by CaledoniaProject** [pardeike/Harmony#275]
I'm getting this exception while calling PatchAll:

```
System.TypeInitializationException: The type initializer for 'HarmonyLib.AccessTools' threw an exception. ---> System.TypeLoadException: Access is denied: 'MonoMod.Utils.Cil.ILGeneratorShim'. 
```

What does it mean?

**Comment by pardeike** [comment]
Can you complete your report with all the details about your environment and also which version of everything and a full stacktrace. Thanks.

**Comment by CaledoniaProject** [comment]
Windows 2012 R2 + .NET 4.5.1

![screen 2020-03-31 at 14 43 05](https://user-images.githubusercontent.com/1357701/77995404-50ec3980-735e-11ea-804a-d1b1725a6c85.jpg)

The target class is an internal class. With ILSpy I updated the `IsPublic` attribute to `true`, does it matter?

**Comment by pardeike** [comment]
No idea. Maybe @0x0ade can help a bit more

**Comment by CaledoniaProject** [comment]
Tried manual patching, no difference

![exception-manual](https://user-images.githubusercontent.com/1357701/77998572-e0481b80-7363-11ea-9837-4a025edae1bd.jpg)

**Comment by boformer** [comment]
This happened to me when I tried to use the Harmony nuget package from a blacnk .Net 3.5 console application

**Comment by Sattaboni** [comment]
if the game is pirate just put the folder in other local (no desktop)
If you play trough steam, just verify files in games properties!
It's work

**Comment by Sattaboni** [comment]
if the game is pirate just put the folder in other local (no desktop)
If you play trough steam, just verify files in games properties!
It's work

**Comment by pardeike** [comment]
> if the game is pirate just put the folder in other local (no desktop) If you play trough steam, just verify files in games properties! It's work

Sorry Sattaboni but I need to warn you. Please refrain from talking about pirated games in relation to Harmony. Of course, the responsibility for that is everyone’s personal but I cannot accept taking about illegal use cases in my channels or here on GitHub.
