### ISSUE TITLE
Update patch documentation to include __0...__n variables for functions

### ISSUE THREAD

**Issue by danbopes** [pardeike/Harmony#279]
As explained in title, the documentation [here](https://github.com/pardeike/Harmony/wiki/Patching) could be updated better:

>Patch parameters must use the exact same name and type as the original method (object is ok too)

This is not exactly true. You can use `__0`, `__n` to specify the parameter order. This was quite useful when I was applying patches for methods used in an array, where the handlers had different names for their arguments.

**Comment by pardeike** [comment]
Documented in Harmony 2.0 documentation:
https://harmony.pardeike.net/articles/patching-injections.html#--argument-names
