### ISSUE TITLE
I don't understand how to access a private attribute

### ISSUE THREAD

**Issue by OctaviusMods** [pardeike/Harmony#282]
I'm very new to C# so I hope it's okay to ask for help. Thanks in advance!

I need to access a private static attribute of the class of the method I want to patch and I have no clue how. Let's say the private static attribute looks like this:

`private static RandomType _name = new RandomType(SomeParameter)`

And I want to access it in a prefix:

```
static bool Prefix(ClassType __instance) {
  
}
```
How do I access `_name `? I read something about triple underscores but `RandomType .____name` doesn't seem to work.

**Comment by OctaviusMods** [comment]
I think I understand better now, I should add `ref RandomType ____name` to the Prefix parameters?

**Comment by pardeike** [comment]
Yes. Btw, use the Discord server for discussing usage questions.
