### ISSUE TITLE
Search function instead of transpiler

### ISSUE THREAD

**Issue by LecrisUT** [pardeike/Harmony#284]
**Is your feature request related to a problem? Please describe.**
Not necessary a problem, but it would be great if there was a simpler method than using transpiler to search if a certain method calls/utilizes some field or method. It would also help keep log files clean, as the transpilers that do nothing would not be included in the log file.

**Describe the solution you'd like**
A transpiler like method, but instead of changing the code instruction, it can simply return if a function is satisfied.

**Describe alternatives you've considered**
The alternative is using the transpiler, but choosing/identifying if the transpiler did anything or not.

**Additional context**
I'm currently implementing an automatic patching in Rimworld to substitute stats depending on a list of conditions. [Link for reference](https://github.com/Jellypowered/SurvivalTools/blob/Development-WIP/Source/SurvivalTools/HarmonyPatches.cs). The only problem with that is it might not be as efficient and it [spams the log file](https://gist.github.com/HugsLibRecordKeeper/345c5c3c07e937add0b33e21a72d712f) if a lot of mods are loaded.

**Comment by pardeike** [comment]
You mean like 
https://harmony.pardeike.net/api/HarmonyLib.PatchProcessor.html#HarmonyLib_PatchProcessor_ReadMethodBody_System_Reflection_MethodBase_

**Comment by LecrisUT** [comment]
I'll try it, thanks for pointing it out. I think that is exactly what I would need.

**Comment by LecrisUT** [comment]
Thank you @pardeike, after some dabling around a bit I got it to work with the method you have mentioned. A helper method would also be appreciated to simplify the code for newcomers.

**Comment by LecrisUT** [comment]
So I thought about reopening this issue since `ReadMethodBody` gives the original code instructions. Is there an alternative for the patched method?

**Comment by pardeike** [comment]
No there isn’t. The codes for each patched method exist only while patching and are not stored anywhere.

**Comment by LecrisUT** [comment]
Hence, reopening the issue. Could you consider making a function that searches the patched Method? Right now I can get by by transpiling and unpatching, but that's not optimal.

**Comment by pardeike** [comment]
It’s not possible to get the IL codes of a patched method and I don’t fancy the two only options to get them: 

- running all existing transpilers again (will also miss any prefixes/postfixes)
- Store all IL codes *somehow*

**Comment by LecrisUT** [comment]
> - running all existing transpilers again (will also miss any prefixes/postfixes)

This is not actually a problem since the usecase I think it's applicable to is to search a method and determine if a transpile is necessary (given that other transpilers haven't already overwritten that part).

E.g. I'm automatically changing all StatDefs to my own and searching through all JobDrivers. I want to make sure others have not already done this, which of course can only be done using transpilers (in most cases).

So a pseudo-transpiler that stores the IL or results of a search would do the trick. The problem with using regular transpilers is that they are logged as having patched a method and the logs can quickly become overwhelming.
