### ISSUE TITLE
Improve docs for methods which only throw

### ISSUE THREAD

**Issue by 96andrei** [pardeike/Harmony#285]
```
public SomeType MyMethod()
{
    throw NotImplementedException()
}
```
This method ends in dead code which may cause `System.InvalidProgramException: Common Language Runtime detected an invalid program.`

This was discussed on the discord server and the (github) issue serves as a tracking item for updating the docs with possible workarounds (finalizer, transpiler).

**Comment by pardeike** [comment]
Fixed in next update
