### ISSUE TITLE
InvalidProgramException when patching from generic base class method with different generic parameters

### ISSUE THREAD

**Issue by Tyler-IN** [pardeike/Harmony#286]
**Describe the bug**
If a generic class containing a method to be used as a prefix patch is applied, it succeeds the first time, but subsequent invocations from other descendant classes fail with InvalidProgramException.

**To Reproduce**

We have a base generic class AgentWeaponEquippedPatch<TPatch>, it has a  prefix patch method to be applied, then there are child classes BowMountedArcherPatch and CrossbowCavalryPerkPatch (and others, but we never get that far).

From Bannerlord Community Patch debug logging;
```
CommunityPatch: Applied Patch: BowMountedArcherPatch
[3]CommunityPatch: Error while applying patch: CrossbowCavalryPerkPatch
[3]CommunityPatch: :0:0: InvalidProgramException: Common Language Runtime detected an invalid program.
[3]CommunityPatch:    at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
```
The first application through BowMountedArcherPatch applies it's own patch, then invokes base.Apply and succeeds. CrossbowCavalryPerkPatch comes next and does the same thing, and while it's own patch succeeds, the one in base.Apply fails.

In the first scenario, AgentWeaponEquippedPatch<TPatch> is AgentWeaponEquippedPatch<BowMountedArcherPatch > and in the second scenario it's AgentWeaponEquippedPatch<CrossbowCavalryPerkPatch>.

**Expected behavior**
Generic type base classes should not cause a problem if they're actually complete generic types with different type signatures.

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version: Fw 4.8 compat?
 - Harmony version: 2.0.0.9
- Name of game or host application: M&B II: Bannerlord

**Additional context**
I'll try to provide a small concise code example when I got time, but I might just work around it instead.

**Comment by pardeike** [comment]
Generics in .NET are black magic and the assembler trampoline code involved isn‘t documented.

So with the help of some uber intelligent expert that knows how to handle this, this is a WONTFIX.

My suggestion: try different ways to patch the method: sometimes, patching the non-specific method works (then the patch receives all calls and need to use __instance to identify which type the current call is. Sometime (in my opinion the more common case) you can only patch every specific type for itself (so if T can be 20 types, you need 20 patches).

It becomes more complicated if you have generics for both: the method and the type it is declared in.

**Comment by Tyler-IN** [comment]
I created a trampoline on the outer class.

```cs
    [UsedImplicitly]
    // workaround for https://github.com/pardeike/Harmony/issues/286
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void CallWeaponEquippedPrefix(ref Agent __instance,
      EquipmentIndex equipmentSlot,
      ref WeaponData weaponData,
      ref WeaponStatsData[] weaponStatsData,
      ref WeaponData ammoWeaponData,
      ref WeaponStatsData[] ammoWeaponStatsData,
      ref GameEntity weaponEntity,
      bool removeOldWeaponFromScene,
      bool isWieldedOnSpawn)
      => WeaponEquippedPrefix(ref __instance,
        equipmentSlot,
        ref weaponData,
        ref weaponStatsData,
        ref ammoWeaponData,
        ref ammoWeaponStatsData,
        ref weaponEntity,
        removeOldWeaponFromScene,
        isWieldedOnSpawn);
```

**Comment by Tyler-IN** [comment]
Going to clean this up and use this workaround, dynamic forwarder method, just be sure to copy parameter names and make sure the metadata token is accessible (no pure dynamic methods);

```cs
    public override void Apply(Game game) {
      if (AgentWeaponEquippedPatched) return;

      var t = GetType();

      var typeName = $"{t.FullName ?? t.Name}.{nameof(WeaponEquippedPrefix)}";
      var createdType = DynMod.GetType(typeName, false);

      var method = createdType?.GetMethod("Forwarder");
      if (method == null) {
        var tb = DynMod.DefineType(typeName);
        var e = Emit<WeaponEquippedPrefixDelegate>.BuildStaticMethod
          (tb, "Forwarder", MethodAttributes.Public | MethodAttributes.Final);
        //var mb = e.MtdBuilder;
        var paramInfos = PatchMethodInfo2.GetParameters();
        for (ushort i = 0; i < paramInfos.Length; i++) {
          e.LoadArgument(i);
        }

        e.Call(PatchMethodInfo2);
        e.Return();
        var mb = e.CreateMethod();
        for (ushort i = 0; i < paramInfos.Length; i++) {
          var pi = paramInfos[i];
          mb.DefineParameter(i + 1, pi.Attributes, pi.Name);
        }

        createdType = tb.CreateTypeInfo();
        method = createdType.GetMethod("Forwarder");
      }

      CommunityPatchSubModule.Harmony.Patch(AgentWeaponEquipped, new HarmonyMethod(method));
      //CommunityPatchSubModule.Harmony.Patch(AgentWeaponEquipped, new HarmonyMethod(PatchMethodInfo));
      AgentWeaponEquippedPatched = true;
      Applied = true;
    }
```

**Comment by pardeike** [comment]
I am not sure I follow. What are you trying to proxy? The code you posted replaces the prefix method with a method that calls the prefix method. What does this solve and how?

**Comment by Tyler-IN** [comment]
The prefix method is on the parent class, it is a generic class. The definition of the method is on the generic type definition (GTD) instead of the generic class.

Creating a dumb forwarder that doesn't have a generic signature is able to avoid the GTD trampoline.

That's the theory anyway.
