### ISSUE TITLE
Passing context between patcher and patches

### ISSUE THREAD

**Issue by shdwp** [pardeike/Harmony#288]
I need to pass some kind of context object between caller of `Harmony.Patch()` and static patch itself, in order to figure out who requested that specific patch. Something along those lines:

```cs
public static void Prefix(string __context) {
    // __context == 'net.shdw.Example'
}
```

```cs
harmony.Patch(methodBase, prefix: Prefix, context: "net.shdwp.Example");
```

I've skimmed through the documentation a few times, but haven't figured out a way to do this.

Pretty much anything would fly, integers, strings, identifier can be known at compile-time. I've thought that patch factory may cover this particular issue, but it's all-static as well and not called during `Patch` call therefore I can't use a static variable in order to distinguish who made that patch.

One way of doing it may be to generate assembly with patches on the fly (that way I can hardcode the context string during IL generation), but it seems a little bit excessive.

Thanks.

**Comment by pardeike** [comment]
Unfortunately, that isn't supported in Prefix/Postfixes. But you can incorporate that function in a transpiler where you inject a string in the codes. Your ownly option are to use LDSTR or LDC.I4 at the moment.

The main problem here is backwards compatibility. When you call Patch() the fixes are stored in global state as MethodInfo and while adding primitive types that don't need serialization might work, I have currently no plan to tackle the possible break in backwards compatibility that results from the change.

**Comment by shdwp** [comment]
Thanks!

I'm already using `ldstr` for similar things in another part of the application, but I was hoping to replace that as well with approach that is a little bit more proper (without using static variables and relying on harmony runtime to run transpilers when I expect it to).

If that's the case I will probably redo my prefixes as transpilers then.
