### ISSUE TITLE
Performance issue with Traverse

### ISSUE THREAD

**Issue by rheirman** [pardeike/Harmony#289]
**Describe the bug**

Using Traverse to access a private field in a patch that is called every tick in Rimworld, has a significant impact on performance (measured in additional execution time in ms per tick). The example patch below adds a 10ms to sometimes 30ms to the execution time, while when avoiding using Traverse (by accessing the field through other public fields), it takes only a fraction of a millisecond to execute. 

**To Reproduce**

See *Additional context* on how I measured the performance. 

1. The original method and its signature and class
Rimworld.Pawn_HealthTracker.HealthTick

2. The patch code
`        
    [HarmonyPatch(typeof(Pawn_HealthTracker), "HealthTick")]
    static class Pawn_HealthTracker_HealthTick
    {
        static void Postfix(Pawn_HealthTracker __instance)
        {

            Pawn pawn = Traverse.Create(__instance).Field("pawn").GetValue<Pawn>();
            if (!pawn.RaceProps.IsMechanoid)
            {
                return;
            }
            //performance is measured without any mechs on the map, so the rest of the patch is irrelevant (can even be empty)

`

3. The output of the Harmony debug log
https://gist.github.com/888112a35d621016755ec972e05e0a7c
4. The stacktrace or other errors

**Expected behavior**
 In the [Traverse documentation](url), it is stated that 'It works with static types and caches lookups which makes it pretty fast.'. So I would't expect it to have such large impact (of tens of milliseconds) on patch execution time. 

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version 4.7.2
 - Harmony version: 2.0.0.8
- RimWorld

**Additional context**
I've used [Dubs performance analyzer](https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626) for measuring performance and made sure to enable advanced mode in the mod options. Then in the analyzer window, it reports the performance of harmony patches in the update/harmony patches menu item.

**Comment by pardeike** [comment]
Traverse isn't designed to be used in methods that have high calling frequencies. You should use FieldRef or field injection instead. In the example above, you can simply write

`static void Postfix(Pawn_HealthTracker __instance, Pawn ___pawn)`

I am closing this issue because there is nothing to fix.

**Comment by rheirman** [comment]
Thanks for pointing me to the field injections. However, it might still be a good idea to update the Traverse documentation with this info. It actually states that it's "quite fast" due to caching and static typing being used. "Quite fast" to me sounds like it may be usable in methods with high calling frequencies.

**Comment by pardeike** [comment]
Compared to normal reflections.

**Comment by rheirman** [comment]
Thanks for completing the sentence. If you do the same in the documentation and add the other info you shared with me, it would be much better already. You may think that I'm nitpicking, but I believe the problem is quite big. Many modders aren't aware and misuse this feature (just check its usage with GitHub search, and you'll see). Just a few cases of wrong usage in a single mod can have a quite noticable effect on fps (my What the Hack mod slowed down the game considerably due to it, while the fix was super easy). 

Maybe if all modders had as much knowledge of Harmony as you do, they would never have misused the feature, but they don't, so in my opinion it wouldn't hurt to make the documentation of Traverse a bit more fool proof.
