### ISSUE TITLE
Ability to remove/untrack empty patches

### ISSUE THREAD

**Issue by LecrisUT** [pardeike/Harmony#292]
**Is your feature request related to a problem? Please describe.**
Related to #284, i.e. ability to search/output the transpiled IL at a given instance in the code (before deciding to patch or not). Since a search function would be hard to implement, the alternative is to use a transpiler and unpatch it. The problem is that it leaves behind empty `PatchInfo`s that logs pick up on. Hence the request for the ability to remove empty `PatchInfo`s. 

**Describe the solution you'd like**
The solution would be to remove from the `HarmonySharedState` dictionary. [Relevant code](https://github.com/pardeike/Harmony/blob/315db07cdcdd7955a67477bdc0860c76bfdf7536/Harmony/Internal/HarmonySharedState.cs#L92-L95). Simply check if all the patches in the `patchInfo` are empty, if so remove from the dictionary. As for the interface, either a separate `RemoveIfEmpty` method or add a `bool` flag to the unpatch methods.

**Comment by pardeike** [comment]
How would you differentiate between a never patched method and an empty patched one?

**Comment by LecrisUT** [comment]
We can assume that the modder unpatching and removing the method from the log, either they are the author of the original patch and decided it is irrelevant, or otherwise has the decency of informing the original author.

A more robust method would be to keep a patching history and accept the remove only if all unpatchers agree to remove it from the log.

Other possible conflicts I can think of are:
- Author A has unsuccessful patch or unnecessary patch. Author B also patches the same method but then unpatches and decides keeping in the log is irrelevant. In this case Author A would still know their patch didn't go through when the method is missing in the log.

**Comment by pardeike** [comment]
Sorry but I have other users of Harmony that do completely different things with it than the RimWorld modding community. They are very much interested to know if a method was detoured and on the other hand don’t care about it being reported empty. 

I personally don’t see why the log is of such an importance. It does show the truth correctly.

**Comment by LecrisUT** [comment]
It is mostly to keep the log files readable. Here is an [example log](https://gist.github.com/LecrisUT/06eb1fa54ff48f714022e0cb35e704ef) where it can become overwhelming. Search functions would still be ok to use, but it is still an eyesore. For the other communities, I do not think this will be an issue since it would be just an option for the modder who unpatches `Unpatch(... , bool remove_from_log=false)`.

**Comment by pardeike** [comment]
I close this issue for now. Harmony 2.0.1 has a new method that gives you the code instructions including all or selected changes of existing transpilers. This allows for a pre-patch decision of if you want to patch the method or not.

**Comment by LecrisUT** [comment]
That's great, thanks. Can you link to it or ping when you've added its documentation?

**Comment by LecrisUT** [comment]
Thank you very much :) . I'll give it a try soon
