### ISSUE TITLE
Name of generated methods

### ISSUE THREAD

**Issue by Trojaner** [pardeike/Harmony#296]
The names of generated patch methods in Harmony look like this: 
```cs
[Exception] Rocket.Unturned >> Exception in Update: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) SDG.Unturned.VehicleManager.DMD<DMD<save_Patch1>?-548581376::save_Patch1>()
  at SDG.Unturned.SaveManager.save () [0x00062] in <9f4f953307a14568b0ad80e23d7dc383>:0 
  at Rocket.Unturned.Utils.AutomaticSaveWatchdog.checkTimer () [0x00036] in <59f13c7b8fd2452db84433be578fe6c9>:0 
```
> SDG.Unturned.VehicleManager.DMD<DMD<save_Patch1>

This makes it hard to figure out what plugin or mod caused this.

It would be great if the generated name could be something like e.g. save_Patch1_\<patching assembly name or maybe HarmonyID\>

**Comment by pardeike** [comment]
Since this is part of MonoMod.Common it would be good to ask @0x0ade about it. Also, I recently got the request to somehow incorporate the harmony ID into the patch name and I think it will help when patches conflict.

**Comment by Pathoschild** [comment]
I think adding the Harmony IDs to [this bit in `HarmonyLib.MethodPatcher`](https://github.com/pardeike/Harmony/blob/v2.0.1.0/Harmony/Internal/MethodPatcher.cs#L62) would work? Then we'd have something like this:
> SDG.Unturned.VehicleManager.DMD<DMD<save_PatchedBy_SomeHarmonyId_AnotherId>>

**Comment by pardeike** [comment]
I am not very confident that this scales well. My Harmony IDs are like “net.pardeike.rimworld.mods.zombieland”. Now imagine a method being patched 8 or more times and everyone has such a long id - hard to read and maybe there is a real limit on the length too.

**Comment by Trojaner** [comment]
Since ids contain dots, that might not work as well (not sure if method names can technically have dots in .NET)

**Comment by pardeike** [comment]
That if course is the least problem. Replacing all illegal characters with underscores solves this.

**Comment by Pathoschild** [comment]
Apparently [Roslyn limits method names to 1024 characters](https://stackoverflow.com/a/426008/262123). If the method name would be longer than some reasonable limit, we could just fall back to something like `PatchedBy{count}`.

**Comment by 0x0ade** [comment]
I've just pushed a commit to MonoMod.Common to allow fully overriding the DynamicMethodDefinition name. The generated methods won't contain any additional info in their method names. In the past, that info was necessary for debugging, but it's no longer needed at all times.

Creating a DMD using `new DynamicMethodDefinition("NameHere", ...)` will now also use the given name, which means that once you've updated, your method names should be "cleaner" no matter what.

https://github.com/MonoMod/MonoMod.Common/commit/d1b845cf31e897ef1511297d0077d30055c5057b

The matching version number is `20.5.24.1`. It might take a while until it's available on nuget.org

**Comment by pardeike** [comment]
Ok, so with the addition of DynamicMethodDefinition honoring the name we will get back to how Harmony named replacement methods. Nice.

But the *name patch methods after harmony id* is flawed. If user A and B both patch the same original - A adds a prefix, B adds a postfix and later user C adds a transpiler then at which point will the single replacement method that results from that be called? A, B, A+B, C or A+B+C. Sorry, that doesn't make sense, does not scale and will not be done.
