### ISSUE TITLE
UnitTest fail

### ISSUE THREAD

**Issue by hcoona** [pardeike/Harmony#30]
There are 4 unit tests failed for latest master branch (05e5b66), please fix them to ensure the quality.

* Traverse_Types
* Traverse_SilentFailures
* Traverse_Missing_Method
* AccessCache_Method

**Comment by hcoona** [comment]
Add 2 more tests failed on Mono.
* `StaticPatches::TestMethod1`
* `StaticPatches::TestMethod2`

**Comment by pardeike** [comment]
I just started to clean up all pull requests in before I start adding some small features to the core functionality (and some bug fixes myself). So I will have a look at those test cases too.

**Comment by pardeike** [comment]
Since https://github.com/pardeike/Harmony/commit/608a358d761ac75857b178f9f59499ac1c0ee952 I all tests pass.
