### ISSUE TITLE
PatchTools.GetPatchMethods returns every method, not just the ones to be patched

### ISSUE THREAD

**Issue by GeluHUN** [pardeike/Harmony#304]
**Describe the bug**
PatchTools.GetPatchMethods should only return results that are to be patched, instead it returns every method it could found in the source type class.

Reason is the _Where(attributePatch => attributePatch != null)_ because _AttributePatch.Create_ can never return null, only _AttributePatch.type_ can be null to indicate a not-to-be-patched method.

One consequence is that when one uses Prepare returning true it will try to also patch Prepare it self.

**To Reproduce**
Create a patch class with a Prefix (annotated or named) method and put also a none annotated static methods whatever named in to the class. The PatchAll will throw an exception because it tries to patch the none annotated whatever methods too not just the prefix.

**Expected behavior**
PatchClassProcessor should not try to patch aux and other (none-harmony) methods, it should ignore those.

**Comment by pardeike** [comment]
The current logic is that methods without attributes inherit the class attributes and therefore can be possible candidates. That or that they have special names like `Prefix`.

The error you see comes from the fact that your patch class has no methods at all and I assume that you get the same problem regardless if there is a Prepare returning true or non at all.

**Comment by pardeike** [comment]
It is a user error to use annotations like `[HarmonyPrefix]` on a class level. I can see a possible use case where one would like to have many prefixes in a class and annotates each with annotations defining the target method but putting the prefix annotation at the class level instead of repeating it. That would mark all aux methods as prefixes as well but I consider this an edge case that is solved by moving the class annotation to each patch method and keeping an empty [HarmonyPatch] annotation at the class to mark it for PatchAll.

**Comment by GeluHUN** [comment]
The class in question looked like this. I have several more similar. Harmony tries to patch both the static property get-er, the Prepare and the Initialize_Configuration.

    [HarmonyPatch(typeof(Formation))]
    class GreaterDefensiveness
    {
        static float Defensiveness => _stuff_;

        [HarmonyPatch("UpdateAgentDrivenPropertiesBasedOnOrderDefensiveness")]
        [HarmonyPrefix]
        public static bool UpdateAgentDrivenPropertiesBasedOnOrderDefensiveness_Prefix(Formation __instance)
        {
            _stuff_
            return false;
        }

        static internal bool Prepare()
        {
            return _stuff_;
        }

        static internal void Initialize_Configuration()
        {
            _stuff_
        }
    }

**Comment by pardeike** [comment]
Alright, I can reproduce the problem. Just not sure why my own mods don't fail when I have an extra static method in there that I am calling from a transpiler. Going to investigate.

**Comment by pardeike** [comment]
Latest commit on `master` fixes this problem by making `AttributePatch.Create` return `null` for any non-patch methods. I think that was a regression from an earlier refactoring.

**Comment by GeluHUN** [comment]
Thank you! :-)
