### ISSUE TITLE
Throw Exception when  changing the content of the original

### ISSUE THREAD

**Issue by konglongbt** [pardeike/Harmony#306]
I copy the code of  the sample  from  [Changing the content of the original](https://harmony.pardeike.net/articles/reverse-patching.html#changing-the-content-of-the-original). When I run harmony.PatchAll(), it throw  the  exception  below

```
HarmonyLib.HarmonyException
  HResult=0x80131500
  Message=Patching exception in method null
  Source=0Harmony
  StackTrace:
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at Harmony.Program.Main(String[] args) in C:\Users\Match\source\repos\Harmony\Harmony\Program.cs:line 16
  
Inner Exception 1:
ArgumentException: Undefined target method for patch method static System.Collections.Generic.IEnumerable`1<HarmonyLib.CodeInstruction> Harmony.Patch2::<StringOperation>g__Transpiler|0_0(System.Collections.Generic.IEnumerable`1<HarmonyLib.CodeInstruction> instructions)
```

This is the code：
  ```
 class Program
    {
        static void Main(string[] args)
        {
            var harmony = new HarmonyLib.Harmony("test");
            harmony.PatchAll();
            OriginalCode originalInstance = new OriginalCode();
            Patch.MyTest(originalInstance, 100, "hello");
            Console.ReadKey();
        }
    }
    class OriginalClass
    {
        private string SpecialCalculation(string original, int n)
        {
            var parts = original.Split('-').Reverse().ToArray();
            var str = string.Join("", parts) + n;
            return str + "Prolog";
        }
    }
```

    [HarmonyPatch]
    public class Patch2
    {
        // When reverse patched, StringOperation will contain all the
        // code from the original including the Join() but not the +n
        //
        // Basically
        // var parts = original.Split('-').Reverse().ToArray();
        // return string.Join("", parts)
        //
        [HarmonyReversePatch]
        [HarmonyPatch(typeof(OriginalClass), "SpecialCalculation")]
        public static string StringOperation(string original)
        {
            // This inner transpiler will be applied to the original and
            // the result will replace this method
            //
            // That will allow this method to have a different signature
            // than the original and it must match the transpiled result
            //
            IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
            {
                var list = Transpilers.Manipulator(instructions,
                    item => item.opcode == OpCodes.Ldarg_1,
                    item => item.opcode = OpCodes.Ldarg_0
                ).ToList();
                var mJoin = SymbolExtensions.GetMethodInfo(() => string.Join(null, null));
                var idx = list.FindIndex(item => item.opcode == OpCodes.Call && item.operand as MethodInfo == mJoin);
                list.RemoveRange(idx + 1, 3);
                return list.AsEnumerable();
            }

            // make compiler happy
            _ = Transpiler(null);
            return original;
        }
    }

**Comment by pardeike** [comment]
The example might not compile perfectly without tweaking. Please check this actual test code: https://github.com/pardeike/Harmony/blob/423ae0a9cc17337fe696cb2e35c1fa29edcc3777/HarmonyTests/ReversePatching/ReverseTranspiling.cs

If you can find the difference I would appreciate your feedback so we can change the example code.

**Comment by konglongbt** [comment]
I use the test code and it run correct. It seems that it can't use harmony.PatchAll(), and the example need to add 
`list.Add(new CodeInstruction(OpCodes.Ret)); `  
 in  `Transpiler` method  before it return. Here is the correct code for the example which can run without error.
```
static void Main(string[] args)
{

    var harmony = new HarmonyLib.Harmony("test");
    
    var originalClass = typeof(OriginalClass);
    var originalMethod = originalClass.GetMethod("SpecialCalculation");           

    var patchClass = typeof(Patch);
    var standin = new HarmonyMethod(patchClass.GetMethod("StringOperation"));

    var reversePatcher = harmony.CreateReversePatcher(originalMethod,standin);
    _ = reversePatcher.Patch();
    
    var result = new OriginalClass().SpecialCalculation("al-gin-Ori", 456);
    Console.WriteLine(result); 
    Console.ReadKey();
}

class OriginalClass
{
    public string SpecialCalculation(string original, int n)
    {
        var parts = original.Split('-').Reverse().ToArray();
        var str = string.Join("", parts) + n;
        return str + "Prolog";
    }
}


[HarmonyPatch]
public class Patch
{
    // When reverse patched, StringOperation will contain all the
    // code from the original including the Join() but not the +n
    //
    // Basically
    // var parts = original.Split('-').Reverse().ToArray();
    // return string.Join("", parts)
    //
    [HarmonyReversePatch]
    [HarmonyPatch(typeof(OriginalClass), "SpecialCalculation")]
    public static string StringOperation(string original)
    {
        // This inner transpiler will be applied to the original and
        // the result will replace this method
        //
        // That will allow this method to have a different signature
        // than the original and it must match the transpiled result
        //
        IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
        {
            var list = Transpilers.Manipulator(instructions,
                item => item.opcode == OpCodes.Ldarg_1,
                item => item.opcode = OpCodes.Ldarg_0
            ).ToList();
            var mJoin = SymbolExtensions.GetMethodInfo(() => string.Join(null, null));
            var idx = list.FindIndex(item => item.opcode == OpCodes.Call && item.operand as MethodInfo == mJoin);
            list.RemoveRange(idx + 1, list.Count - (idx + 1));
            // add return IL code 
            list.Add(new CodeInstruction(OpCodes.Ret));
            return list.AsEnumerable();
        }

        // make compiler happy
        _ = Transpiler(null);
        return original;
    }
}
```

**Comment by pardeike** [comment]
The reason for the differences is that `master` right now contains a few fixes for Issues regarding this functionality.
