### ISSUE TITLE
Suggestion - Prefix ref __result 

### ISSUE THREAD

**Issue by Sunrunner37** [pardeike/Harmony#31]
Does __result have a purpose for prefix?  It would be really nice if it was a pass by reference so we can return a nice result to the original caller if the method was skipped.

**Comment by pardeike** [comment]
You can. It is actually common to write

static bool Prefix(ref SomeType __result)
{
   __result = ...;
   return false;
}

**Comment by Sunrunner37** [comment]
Thanks! Can you update the documentation to say that?

**Comment by pardeike** [comment]
The documentation tells you about the use of “ref” on any argument and that s prefix can return false to skip the original.
