### ISSUE TITLE
How To: Patch Constructor To Create Instance Of Other Class

### ISSUE THREAD

**Issue by fauxnik** [pardeike/Harmony#318]
[Over on #63](https://github.com/pardeike/Harmony/issues/63#issuecomment-377984388), it's suggested that `__result` might be used to change what class a constructor creates, but [over on #78](https://github.com/pardeike/Harmony/issues/78#issuecomment-386195689), it's mentioned that:
> …you cannot use __result because constructors have a void return type.

Since `__result` is not available in constructors, how does one go about patching a constructor so that it returns an instance of a different class?

For my use case in particular, I'd like to return a subclass of the patched class. Since the subclass' constructor calls the base constructor, I imagine I'll have to do some checking to make sure it doesn't wind up in an infinite loop trying to replace each subclass too. My guess is something like this should suffice; do you agree?

```C#
if (__instance.GetType() != typeof(SubClass))
{
    // TODO: whatever needs to happen to replace the created instance
}
```

**Comment by pardeike** [comment]
Unfortunately, C# doesn’t work intuitive here. A constructor in C# is compiled into the following IL code:
```
newobj instance void Test::.ctor();
```
And the `newobj` IL code is defined to
`The newobj instruction allocates a new instance of the class associated with ctor and initializes all the fields in the new instance to 0 (of the proper type) or null references as appropriate. It then calls the constructor ctor with the given arguments along with the newly created instance. After the constructor has been called, the now initialized object reference (type O) is pushed on the stack.`

So a constructor is just an initialiser method that gets the newly empty obj as an argument to set the values of fields. 

All the “create object of type T” logic is in the IL code and the internal logic of the C# runtime. 


Which means you cannot change the type from within the constructor. All you can do is to manipulate the place where the constructor is called (the operand of newobj or some extra IL after it that changes the value on the stack).

**Comment by poizan42** [comment]
You could in theory patch out the MethodTable pointer as long as both classes have the same size (i'm not sure if it can cause problems if the the new class is smaller. I think this may cause some type-confusion problems even if the new class derives from the original because of de-virtualization though.

**Comment by pardeike** [comment]
fixed in master
