### ISSUE TITLE
How to get FieldInfo for backing field of Property?

### ISSUE THREAD

**Issue by evorios** [pardeike/Harmony#319]
subj

**Comment by pardeike** [comment]
After compilation, a property will become two merhods:

get_NameOfProperty
set_NameOfProperty

which both are optional depending if there is a getter/setter. Those methods sometimes refer to a field but not necessarily. 

If such a field exists you can use it like any other field. If not, you need to patch or use the get/set methods. 

Patching such a property handles with an extra argument of type MethodType

**Comment by evorios** [comment]
Thanks, but I found more reliable methods:
- `Mono.Reflection` package with `GetBackingField` extension for `PropertyInfo`
- `AutoPropertyExtensions` [gist](https://gist.github.com/NickStrupat/39e659e53a7aa000b737)  with `GetBackingField` extension for `PropertyInfo`
