### ISSUE TITLE
How to add an if check with a transpiler?

### ISSUE THREAD

**Issue by Keelhauled** [pardeike/Harmony#32]
I'm very new to this so an example of this would be most helpful. 
The code goes like this
```
protected virtual bool InputKeyProc()
{
    // things that should run normally
    if(speed > 0f) // new check
    {
        // things I want block sometimes
    }
    // more things that should run normally
}
```
And thanks for this great library of course, it's gonna make a lot of things easier.

**Comment by pardeike** [comment]
Right now, I can’t post a full example but in general, you loop through the instructions to find the point where you would want to insert the condition and the jump. Then you do the same to find the jump destination. You inject the ILGenerator by adding it to the arguments of the transpiler method and use it to define a new label (DefineLabel just creates it) then add it to the “label” list field of the instruction you find while searching for the jump destination. 

A few things I recommend: 

- find a good decompiler to study the original methods IL code

- download LinqPad to write some c# and see its IL code on the fly with a simple button press

- check out my example mods for RimWorld here on GitHub. They all use Harmony extensively

I also made a small transpiler tutorial here: https://gist.github.com/pardeike/c02e29f9e030e6a016422ca8a89eefc9

**Comment by Keelhauled** [comment]
Thanks for the help. Finally got everything working and learned a bit of IL in the process too.
Here's the final result in case you're curious (I hope it's not that bad)
```c#
private static IEnumerable<CodeInstruction> Transpiler(ILGenerator ilGenerator, MethodBase original, IEnumerable<CodeInstruction> instructions)
{
    List<CodeInstruction> codes = new List<CodeInstruction>(instructions);
    Label label = ilGenerator.DefineLabel();
    bool codeFound = false;

    for(int i = 0; i < codes.Count; i++)
    {
        if(codes[i].opcode == OpCodes.Ldc_I4 && (int)codes[i].operand == 275)
        {
            FieldInfo field = AccessTools.Field(typeof(Studio.CameraControl), "moveSpeed");
            CodeInstruction thisWithLabels = new CodeInstruction(OpCodes.Ldarg_0) { labels = codes[i].labels };
            codes[i].labels = new List<Label>();

            List<CodeInstruction> newCodes = new List<CodeInstruction>()
            {
                thisWithLabels,
                new CodeInstruction(OpCodes.Ldfld, field),
                new CodeInstruction(OpCodes.Ldc_R4, 0f),
                new CodeInstruction(OpCodes.Ceq),
                new CodeInstruction(OpCodes.Brtrue, label),
            };

            codes.InsertRange(i, newCodes);
            i += newCodes.Count;
            codeFound = true;
        }

        if(codeFound && codes[i].opcode == OpCodes.Ldc_R4 && (float)codes[i].operand == 10f)
        {
            codes[i].labels.Add(label);
            break;
        }
    }

    return codes.AsEnumerable();
}
```

**Comment by pardeike** [comment]
Excellent!
