### ISSUE TITLE
Using a patch factory for generic methods

### ISSUE THREAD

**Issue by araex** [pardeike/Harmony#320]
I've got a patch factory `DynamicMethod GetPrefix(MethodBase original)` that i use to generate patches:

```
prefixMap[original] = GeneratePrefix(original);
MethodInfo factoryMethod = typeof(MethodPatchFactory).GetMethod(nameof(GetPrefix));
HarmonyMethod patch = new HarmonyMethod(factoryMethod);
HarmonyInstance.Patch(original, patch);
```

That works fine for non-generic methods. However, i would like to generate patches for generic functions as well. I can explictly name the generic types `original.MakeGenericMethod` that i need to patch. **Is there a way to do that with harmony?**

I did try to just create a patch without any adjustemts. But expectedly that doesn't magically work. Call stack:

```
System.ComponentModel.Win32Exception: Attempt to access invalid address
  at at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
  at at HarmonyLib.PatchProcessor.Patch()
  at at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
```

Debug info:
```
Memory.DetourMethodAndPersist(original, (MethodBase) replacement);

original:= TaleWorlds.CampaignSystem.MobileParty CreateObject[MobileParty](System.String)
replacement:= TaleWorlds.CampaignSystem.MobileParty DMD<DMD<CreateObject_Patch1>?65522174::CreateObject_Patch1>(TaleWorlds.ObjectSystem.MBObjectManager, System.String)
```

**Comment by araex** [comment]
After a lot more testing, i'm fairly certain that harmony actually does what i wanted it to do. It works in an isolated test environment using the same code and the same types. But if i run it during initialization of my mod, i get an `Attempt to access invalid address` originating from 
```
HarmonyLib.Memory.WriteJump(long memory, long destination)
HarmonyLib.Memory.DetourMethodAndPersist(MethodBase original, MethodBase replacement)
HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
MonoMod.RuntimeDetour.DetourHelper.MakeWritable(this IDetourNativePlatform plat, NativeDetourData detour)
```

I'm at a loss what's going on or what i'm looking for. Can anyone point me in the right direction?

**Comment by pardeike** [comment]
In general, patching generics is rather tricky and often does not work as expected. The main reason is that the assembler code that glues the runtime to the native code of the jitted method is totally a mess and undocumented and writing a simple jump into that code can easily fail. For example if the dispatch logic in that assembler code is shared with other calls - likely in the case of generics where similar implementations are called with a common entry. 

So generics is

- very platform, .NET version and runtime dependent
- not very predictable
- highly experiemental when patching

There is currently no known workaround for this behaviour so patching comes with a "what works, works. if it does not work, sorry" disclamer.

**Comment by araex** [comment]
That's a shame. I guess that means i'll have to patch the control flow without thouching any generics.

Thank you for taking the time to answer!
