### ISSUE TITLE
Get parameters with removed names.

### ISSUE THREAD

**Issue by DenJur** [pardeike/Harmony#33]
Is there a way currently to get parameters from original method in prefix if their names were removed (by obfuscator for example)? Perhaps just getting an array of objects that contains all parameters in order or specific parameters by index?
I ended up just patching in some names as I only needed this for debugging but in some cases you actually might need that stuff.

**Comment by pardeike** [comment]
Harmony now has renamed parameter support (with the HarmonyParameter attribute). Arrays do not work due to lots of corner cases with ref and out parameters as well as speed penalties with boxing.
