### ISSUE TITLE
Wrong generic constructor prefix method called

### ISSUE THREAD

**Issue by cdjc** [pardeike/Harmony#332]
**Describe the bug**
If there are two prefix patches on a generic constructor, each with a different generic type, only the prefix method patched 2nd will get called, regardless of the generic type in the call.

**To Reproduce**
See example code. The wrong prefix patch gets called leading to the exception.

**Expected behavior**
The correct prefix patch (the one matching the generic type) should be called.

**Screenshots / Code**
``` csharp
using System;
using System.Text.Json;
using HarmonyLib;

namespace HarmonyGenericBug
{
	public class Message<T>
	{
		public Message(string name, params T[] data)
		{
			Name = name;
			Data = data;
		}

		public string Name { get; set; }
		public T[] Data { get; set; }
	}

	public sealed class DataType1
	{
		public string Message { get; set; }
	}

	public sealed class DataType2
	{
		public int Size { get; set; }
	}

	class Program
	{
		class DummyMessage<T>
		{
			public string Name { get; set; }
			public T[] Data { get; set; }
		}
		public static void Prefix<T>(string name, params T[] data)
		{
			var dummy = new DummyMessage<T>
			{
				Name = name,
				Data = data
			};
			/*
			 * On next line, get:
			 * System.InvalidCastException: 'Unable to cast object of type 'HarmonyGenericBug.DataType1' to type 'HarmonyGenericBug.DataType2'.'
			 */
			var msg = JsonSerializer.Serialize(dummy);
			Console.WriteLine(msg);
		}

		static void Main(string[] args)
		{
			var harmony = new Harmony("harmony-bug");

			var hm_orig1 = typeof(Message<>).MakeGenericType(typeof(DataType1)).GetConstructors()[0];
			var hm_prefix1 = AccessTools.Method(typeof(Program), "Prefix", generics: new[] { typeof(DataType1) });
			harmony.Patch(hm_orig1, new HarmonyMethod(hm_prefix1));

			var hm_orig2 = typeof(Message<>).MakeGenericType(typeof(DataType2)).GetConstructors()[0];
			var hm_prefix2 = AccessTools.Method(typeof(Program), "Prefix", generics: new[] { typeof(DataType2) });
			harmony.Patch(hm_orig2, new HarmonyMethod(hm_prefix2));

			var d1 = new DataType1
			{
				Message = "Spam"
			};
			var msg = new Message<DataType1>("Bob", d1);
		}
	}
}
```

**Runtime environment (please complete the following information):**
 - OS: Windows 10 Enterprise Version 2004 (build 19041.330)
 - .NET version: .net core 3.1
 - Harmony version 2.0.2

**Comment by pardeike** [comment]
Generics are weird and hard to patch. All kind of strange non-consistent results happen.

**Comment by cdjc** [comment]
> Generics are weird and hard to patch. All kind of strange non-consistent results happen.

Fair enough. I'm impressed that Harmony let me get as far as I did.

The workaround is to assume that the T[] of the data being passed in is not necessarily the same T of the method.
I changed DummyMessage to be non-generic, and DummyMessage.Data to be dynamic to avoid relying on the type of T.
