### ISSUE TITLE
Harmony patching (for virtual methods?) fails silently in .NET Core 3.0+ (incl .NET 5) when OptimizeCode=true

### ISSUE THREAD

**Issue by Timovzl** [pardeike/Harmony#337]
I'm aware that support for .NET Core is still being tested. I thought I'd help things along by reporting some specifics.

**Description**
Using `harmony.Patch(originalMethod, prefix: new HarmonyMethod(prefixMethod), postfix: new HarmonyMethod(postfixMethod))` works in .NET Core 3.1 when `OptimizeCode` is disabled, as is default in debug mode. As soon as `OptimizeCode` is enabled (such as when we switch to release mode, but also if we stay in debug mode and simply enable this setting in the csproj), **the replacement has no noticeable effect whatsoever**. This is true for both the prefix and the postfix.

**To Reproduce**
To reproduce, just take any working sample invocation of `Harmony.Patch`. Make sure that prefix or postfix method does something measurable, such as write to the console or throw. Notice how this logic works without `OptimizeCode` but is not executed when it is enabled.

**Expected behavior**
The prefix and postfix methods are executed.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version: .NET Core 3.1
 - Harmony version: 2.0.2

**Comment by lbmaian** [comment]
Investigation in discord showed that this also fails in .NET Core 3.0 and .NET 5.0 (#315). This likely needs a fix from MMC side (https://github.com/MonoMod/MonoMod.Common/pull/4 might be it when finished).

**Comment by pardeike** [comment]
This issue can now be tested and verified on master since 718b979a212e4edab9e3d2e99c67fd5f6739fc0d and the bump of MonoMod Common in 89fe6dac8551e87588d01798021053add133abb3

**Comment by GmeduoyeClaymore** [comment]
Hi Pardeike are you suggesting this issue is resolved ? I too am experiencing some problems in .NET Core 5

**Comment by pardeike** [comment]
As I wrote, this can now be *tested*. I cannot say it's resolved before it was at least tested by those experiencing the original problem.

**Comment by Timovzl** [comment]
Since I am not making use of Harmony at the moment, anyone relying on this may feel free to test it instead.

**Comment by harvey-k** [comment]
After updating to version 2.1.0 from 2.0.4, this appears to be working now. Thank you!
