### ISSUE TITLE
Method "Prefix" not execute for OpenApiOperation class, but Transpiler was called

### ISSUE THREAD

**Issue by devmedvedev** [pardeike/Harmony#338]
**Describe the bug**
Method "Prefix" not execute for OpenApiOperation class, but Transpiler was called

**To Reproduce**
See cleaned [example](https://github.com/devmedvedev/HarmonyOpenApiExample) (code: [Program.cs](https://github.com/devmedvedev/HarmonyOpenApiExample/blob/master/HarmonyOpenApiExample/Program.cs))

**Expected behavior**
When called `operation.SerializeAsV2(new OpenApiJsonWriter(writer));` I was expecting a call to the Prefix method

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - netcoreapp3.1
 - Harmony version : 2.0.2
 - Project for support Microsoft Power Automate

P.S. The problem stems from the use of Swagger and Microsoft.OpenApi. If there is a solution to the problem, it will help many developers. I will post a variant of the solution using your library in similar Issues. Thanks!

P.P.S. Sorry for my English

**Comment by devmedvedev** [comment]
maybe it's related to [Harmony cannot patch other Assemblies loaded in another AppDomains](https://github.com/pardeike/Harmony/issues/322)

**Comment by pardeike** [comment]
Most likely the method is inlined and thus neither the prefix nor the transpiler patch is called. When you say “the transpiler is called” you are actually talking about it being called to modify the original which it did. In this case you are mixing up the time the patch is generated and the time it is executed.

**Comment by pardeike** [comment]
If you start your .NET Core app without runtime optimization (it will be super slow) the inlining will not happen and I bet your prefix will run.
