### ISSUE TITLE
Branch instructions do not accept offset arguments

### ISSUE THREAD

**Issue by asquared31415** [pardeike/Harmony#340]
**Describe the bug**
Previously, in Harmony 1, an integer offset was a valid argument to the branch instructions and would be used as an offset in **bytes** for the program counter from the position before the next instruction.  For example, `Br 5` would skip over instructions like call or ldfld that have a one byte operand and a 4 byte argument.

Currently, in Harmony 2.0.2, trying to use an integer as an argument to a branch instruction crashes Harmony with `Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: opcode` in some code related to reflection and ILGenerator.

**To Reproduce**
This happens when inserting any branch instruction with an integer argument.  In the examples given, `br 0` is used for simplicity.

Original code:
```cs
class Stuff
{
	public static void Method1()
	{
		var a = 1;
		var b = 2;
		var c = a + b;
		Console.WriteLine(c);
	}
}
```

Non-functional transpiler:
```cs
public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> codes)
{
	// A branch with offset zero should do nothing
	yield return new CodeInstruction(OpCodes.Br, 0);

	foreach(var codeInstruction in codes)
	{
		yield return codeInstruction;
	}
}
```

Functional transpiler:
```cs
public static IEnumerable<CodeInstruction> TranspilerLabels(IEnumerable<CodeInstruction> codes, ILGenerator generator)
{
	var label = generator.DefineLabel();
	yield return new CodeInstruction(OpCodes.Br, label);

	var next = codes.Take(1).First();
	next.labels.Add(label);

	foreach(var codeInstruction in codes)
	{
		yield return codeInstruction;
	}
}
```

Stack trace:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: opcode
   at Mono.Cecil.Cil.Instruction.Create(OpCode opcode, Int32 value)
   at Mono.Cecil.Cil.ILProcessor.Create(OpCode opcode, Int32 value)
   at MonoMod.Utils.Cil.CecilILGenerator.Emit(OpCode opcode, Int32 arg)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MonoMod.Utils.Cil.ILGeneratorShimExt.DynEmit(ILGenerator il, Object[] emitArgs)
   at MonoMod.Utils.Cil.ILGeneratorShimExt.DynEmit(ILGenerator il, OpCode opcode, Object operand)
   at HarmonyLib.MethodBodyReader.<>c__DisplayClass21_0.<FinalizeILCodes>b__2(CodeInstruction codeInstruction)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.MethodBodyReader.FinalizeILCodes(Emitter emitter, List`1 transpilers, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodCopier.Finalize(Emitter emitter, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at HarmonyBug.Program.Main(String[] args) in C:\Users\andre\Desktop\HarmonyBug\HarmonyBug\Program.cs:line 29
```

**Expected behavior**
I expected the behavior to match Harmony 1 where an integer offset branch functioned as expected and branched over the given number of bytes.  When using the fixed transpiler in the example, the output reflects the expected behavior, however it requires defining labels and does not work very well with the enumerator approach to transpilers.

**Screenshots / Code**
Full test code: https://gist.github.com/asquared31415/e82d7f950f19facf7888ed6d57c0bcee

**Runtime environment:**
 - OS: Windows 10 64bit
 - .NET Framework 4.8
 - Harmony version 2.0.2

**Additional context**
There is a bug in Harmony 1's implementation where all short branches are converted to long branches to avoid issues with code being out of range of a short branch, however if the argument passed to an inserted short jump is a `byte` offset (as expected of a short branch) it is not converted to a 4 byte integer.  Passing an integer functions in Harmony 1, but passing a byte crashes with a confusing `invalid IL code` error because it's parsed as 4 bytes.  Ideally this issue would be fixed as well in Harmony 2 to allow the short opcodes to work as expected.

**Comment by pardeike** [comment]
The old behavior was removed in favor of the more robust way to jump by using labels. There was strong feedback from the community to simplify jumping by always using labels which makes it easier to write transpilers that run correct after other transpilers.

**Comment by asquared31415** [comment]
That makes sense, labels do simplify a lot in most cases.  I simply came across this issue when trying to look at a bug in Harmony 1.  Would it be possible to check for that or emit a different exception or do something else that makes it more obvious that the problem is attempting to use a numerical argument for a branch where a label should have been used instead?

**Comment by pardeike** [comment]
Operands for opcodes is in general not documented enough. Until we have a more complete way to check all values passed to the emitter I don’t think it’s very useful to only handle this specific case.

**Comment by pardeike** [comment]
fixed in master

**Comment by asquared31415** [comment]
Wow, that documentation is great, and has lots of information that I would have liked to have available when starting out.  Documentation of the utility methods is also great.  Perhaps adding something telling users to NOT use `ILGenerator.emit()` would be helpful, because you talk about it and link the reference as help for figuring out operand types.

There's also one minor grammar error in [labels](https://harmony.pardeike.net/articles/patching-transpiler-codes.html#labels),
> When you want to create a jump, you specific the jump Opcode

here `specific` should be `specify`.

**Comment by pardeike** [comment]
Great feedback. You know, you could edit the markdown in https://github.com/pardeike/Harmony/tree/master/Harmony/Documentation/articles and create a pull request. The documentation builds automatically into the website when pushed to master (so don’t edit /docs). ;-)
