### ISSUE TITLE
Visual Studio Debug Support?

### ISSUE THREAD

**Issue by martinrhan** [pardeike/Harmony#341]
**Is your feature request related to a problem? Please describe.**
I am used to visual studio 's debug function as it provide a lot of convinience for debuging, however the breakpoints cannot be hit when I try to do so.

**Describe the solution you'd like**
I would be glad to see the breakpoints working.

**Describe alternatives you've considered**
N/A

**Additional context**
Maybe there is already suching thing but just I don't know? If so, please tell me.

**Comment by pardeike** [comment]
Since your debugger has no idea about patches, it is virtually impossible to make this work.
