### ISSUE TITLE
Pass objects to Pre/Postfix methods while patching

### ISSUE THREAD

**Issue by joshua211** [pardeike/Harmony#349]
Hello, I'm not sure if this is already implemented in some sort, but I have a use case where I patch different methods with the same Pre/Postifx but each patch requires a different context .

**Is your feature request related to a problem? Please describe.**
No option to pass additional parameters to patch methods

**Describe the solution you'd like**
Being able to pass a variable (primitive or object) to the harmony.Patch method and reference the same variable in the patch method signature

Solution would look something like this:

`harmony.Patch(original, prefix, postfix, transpiler, finalizer, additionalParameter)`

and using it in a patch:

`public static void Prefix(out string __state, object __instance, object __additionalParameter);`

I would try to implement this myself, but I dont know much about IL Code or how Emiters work.

**Comment by pardeike** [comment]
If you can explain where the contents of that variable will come from, I am happily implementing that. See, the patch is called somewhere deep in the execution of the patched program, on an instance of some class that is impossible to find from outside. And you don’t need more support to simply use a static variable that you add yourself.

Btw, adding fields to classes is not possible during runtime.
