### ISSUE TITLE
Question about Harmony and generic class methods.

### ISSUE THREAD

**Issue by Entoarox** [pardeike/Harmony#35]
Hi, I am a modder in Stardew Valley, and have come across the situation where I need to patch a method in a class, where the class itself has 2 generic arguments that I need to work with in that same method.

How, if at all, could I do such a thing with harmony?

**Comment by pardeike** [comment]
Due to the nature of .NET and Harmony pointing methods to new methods, the only possible way to patch a generic method is by patching all generic types (or a subset of them) you are interested in separately.
