### ISSUE TITLE
.NetCore inconsistent patching when no debugger attached

### ISSUE THREAD

**Issue by apobekiaris** [pardeike/Harmony#352]
I am looking for feedback if any on why my patches do nothing when no debugger is attached. I use a recompiled latest source against netstandard2.0 which I consume from a .NetCore3.1 exe. I am noticing inconsistent behavior, many times my patches simply do nothing while other times work. When debugger is attached they always work. I cannot trace why the patches fail, they are simple postfix on static methods.

**Comment by pardeike** [comment]
Most likely inlining: See [this](https://harmony.pardeike.net/articles/patching-edgecases.html#inlining) part of the documentation.
