### ISSUE TITLE
Borked on Linux

### ISSUE THREAD

**Issue by sTiKyt** [pardeike/Harmony#353]
**Describe the bug**
Harmony looks for files that aren't delivered with Linux version of game which causes mods to crash and break the game.

**To Reproduce**
1. Disable all mods
2. Enable Core and Royalty (everything is still good)
3. Enable Harmony
4. Get lot of missing .so files in log...

**Expected behavior**
I expected it to work, my game crashes when i kill anything

**Screenshots / Code**
When only `Core` and `Royalty` are enabled log looks like this:
![image](https://media.discordapp.net/attachments/257987178834034688/765719640067801098/unknown.png?width=922&height=644)

When i enable `Harmony` as well:
![image](https://media.discordapp.net/attachments/257987178834034688/765719979282530324/unknown.png?width=886&height=643)

**Runtime environment (please complete the following information):**
 - OS: Arch Linux, 64bit
 - .NET version - I have no idea how to check that, isn't steam supposed to take care of that?
 - Harmony version: Lib 2.0.2.0, Mod 1.0.4.0
- RimWorld 1.2.2753 rev715

Harmony looks for libraries in `RimWorldLinux_Data/Mono/` but there is no `Mono` in `RimWorldLinux_Data`

Full log:
[rimworld_log_1000.zip](https://github.com/pardeike/Harmony/files/5374750/rimworld_log_1000.zip)

**Comment by pardeike** [comment]
Harmony works on Linux. I tested it myself and have users that use it. Something in your installation seems corrupted. Have you tried to reinstall the game and the Harmony mod?

Btw, where did you get your Harmony mod from? There are "modified" versions out there that contain dubious changes and are of course not supported at all.

**Comment by pardeike** [comment]
Also, this rather belong to https://github.com/pardeike/HarmonyRimWorld

**Comment by sTiKyt** [comment]
> Harmony works on Linux. I tested it myself and have users that use it. Something in your installation seems corrupted. Have you tried to reinstall the game and the Harmony mod?


Yes i did reinstall game and mod. i got it from steam workshop. After installing this [unofficial fix](https://steamcommunity.com/sharedfiles/filedetails/?id=2149016328) game stopped to crash but still throws lot of errors about missing .so files if we look at log. It seems to work as supposed but generates errors in log.

**Comment by pardeike** [comment]
Since this is about mods using Harmony and not Harmony itself, I will close this issue. You need to talk to the mod authors.
