### ISSUE TITLE
[HELP] How to patch a method from an internal class?

### ISSUE THREAD

**Issue by cmd430** [pardeike/Harmony#356]
Hello, i am using Harmony from MelonLoader to patch Green Hell I was wondering how to patch a method that is located inside an internal class? (Using Harmony 1.2.01)

any help would be much appreciated I would like to be able to create a prefix patch for the method and being able to use the `__Instance` parameter within my patch 

Here is a stub of the class and method i would like to edit

```cs
internal class HUDCoopPlayer : MonoBehaviour
{
    private void UpdateSizeAndOpacity()
    {
        // Original Method code
        ....
    }
}
```

and what i would like to achieve 

```cs
[HarmonyPatch(typeof(HUDCoopPlayer), "UpdateSizeAndOpacity")]
class Patch
{
  private static bool Prefix(HUDCoopPlayer __Instance)
  {
      // My Method code
      ....
      return true;
  }
}
```

this is the issue i am having currently 
![image](https://user-images.githubusercontent.com/2668906/96415830-9feeb300-124b-11eb-8853-53760656d596.png)

**Comment by pardeike** [comment]
You cannot patch private types from attributes. But you can use a combination of attributes and a method called `TargetMethod`:
```cs
[HarmonyPatch] // keep at least one empty attribute to mark the class for processing
class Patch
{
    static MethodBase TargetMethod()
    {
         // use reflections (with or without AccessTools) to return the MethodInfo of the original method
         var type = AccessTools.TypeByName(“The.Namespace.HUDCoopPlayer”);
         return AccessTools.Method(type, “UpdateSizeAndOpacity”);
    }

    static bool Prefix(HUDCoopPlayer __Instance) ...
}
```

**Comment by pardeike** [comment]
I recommend reading the documentation: https://harmony.pardeike.net/articles/patching-auxilary.html#targetmethod
