### ISSUE TITLE
Patching a private field whose type is sub private struct

### ISSUE THREAD

**Issue by wansyu** [pardeike/Harmony#359]
In the game Oxygen Not Included, there are, in CircuitManager.cs

```
public class CircuitManager{
  ...
  private struct CircuitInfo
  {
    ....
  }
  ....
  private List<CircuitManager.CircuitInfo> circuitInfo = new List<CircuitManager.CircuitInfo>();
  ....
public void Rebuild(){
  ....
}
  ....
}
```
I want to patch the method "Rebuild" and modify the field "circuitInfo " inside it. But I failed to access "circuitInfo ".
Could you give examples of how to use the Harmony to access  these kind of private field?
Those private field whose type is sub private class may have the same issue.

Thank you very much!

**Comment by pardeike** [comment]
You would need to inject `IList ___ circuitInfo` and then access elements via the methods on IList which returns `object`. Using methods in AccessTools or via normal reflections you can create and access fields inside the private type.

**Comment by pardeike** [comment]
Also: please use the official Discord for support questions like this and Issues here for specific problems and bugs with Harmony.
