### ISSUE TITLE
Documentation improvement suggestion

### ISSUE THREAD

**Issue by yoeyyutch** [pardeike/Harmony#365]
I just want to suggest a minor edit to a page in the documentation to make it easier to understand.  
[https://harmony.pardeike.net/articles/patching-prefix.html#changing-the-result-and-skipping-the-original](url)

Original version: (Portion to edit in bold)

> Changing the result and skipping the original
> To change the result of the original, use __result as an argument of your prefix. It must match the return type or be assignable from it. Changing the result of the original does not make sense if you let the original run so skipping the original is necessary too.
> 
> **To skip the original, let the prefix return a bool and return true to let the original run after all prefixes or false to stop executing prefixes and skip the original.**

Suggested edit:

> To stop executing prefixes and skip the original, let the prefix return a bool that returns false. 
> To let the original run after all prefixes, return a bool that returns true.

I misread it a couple times because it starts by saying "To skip the original.... return true".  The part about running the original is kind of awkwardly squeezed in there.

**Comment by pardeike** [comment]
Thanks for the feedback. I’ll change it but have you considered doing the change yourself and submitting it as a pull request. It’s a nice way to get started. 

The change would be made in /Harmony/Documentation/articles/patching-prefix.md

**Comment by yoeyyutch** [comment]
Hey man. Thanks for bringing that up. I did consider it but I wimped out. I really did want to though, exactly for the reason you mentioned. Ok time for me to get one of these pull requests under my belt.  

Thank again for the encouragement!
