### ISSUE TITLE
Xamarin + Android stack via Harmony

### ISSUE THREAD

**Issue by duraki** [pardeike/Harmony#366]
During the penetration testing engagement I've been put in a position to reverse engineer a clients//vendor app. which has been developed in Xamarin. Obviosuly I went for Frida at first, but all the libraries are now obsolete (ie. `fridax`, or `frida-mono-api`). I only saw one such issue raised by a long time ago at #16 (so maybe @alicint can join discussion).  

This closed topic & especially this comment never referenced the PR https://github.com/pardeike/Harmony/issues/16#issuecomment-300134026 therefore new issue.

How is support now for Android / Xamarin. Can you reference to other resource that might help PR this feature.

**Comment by pardeike** [comment]
Harmony 2.0.4 has a “HARMONY_LOG_FILE” env variable so this should help with the logging problem. Afaik those issues all look like user errors with emitting correct IL code which is not specific to Android.
