### ISSUE TITLE
Export transpiled methods to DLL

### ISSUE THREAD

**Issue by cseelhoff** [pardeike/Harmony#368]
**Is your feature request related to a problem? Please describe.**
When debugging transpiled methods, it is hard to find out what line or IL offset certain errors occurred on. It would also be nice to export the IL code to a compiled DLL, so that it can be run through a friendly IL->C# decompiler.

**Describe the solution you'd like**
It looks like it is already possible to export dynamically generated methods to a DLL using this code snippet. But I am unsure if Harmony could support this somehow.

```csharp
AssemblyName assemblyName = new AssemblyName("RimWorld");
AssemblyBuilder assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(assemblyName, AssemblyBuilderAccess.RunAndSave);
ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule(assemblyName.Name, assemblyName.Name + ".dll");
TypeBuilder typeBuilder = moduleBuilder.DefineType("PathFinder", TypeAttributes.Public);
MethodBuilder methodBuilder = typeBuilder.DefineMethod("FindPath", MethodAttributes.Public, typeof(PawnPath), new Type[] { typeof(IntVec3), typeof(TraverseParms) });
FieldBuilder fieldBuilder = typeBuilder.DefineField("field1", typeof(int), FieldAttributes.Public);
iLGenerator = methodBuilder.GetILGenerator();
iLGenerator.Emit(OpCodes.Ldfld, fieldBuilder);
iLGenerator.Emit(OpCodes.Ret);
typeBuilder.CreateType();
assemblyBuilder.Save(assemblyName.Name + ".dll");
```

**Comment by pardeike** [comment]
Harmony uses its debug log functionality instead. At this point I am not sure how to facilitate the dll export.

**Comment by NaoUnderscore** [comment]
That's dope af.
