### ISSUE TITLE
Is impossible to describe method containing ref or out argument using HarmonyPatchAttribute

### ISSUE THREAD

**Issue by krypt-lynx** [pardeike/Harmony#37]
By Ref argument type defined as `typeof(SomeType).MakeByRefType()`

For example: 
``` 
public static bool TryParse(string s, out Int32 result);
```
```
new Type[] { typeof(string), typeof(Int32).MakeByRefType() }
```
But it will not work with attributes, because it wants constant expression:
An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

**Comment by pardeike** [comment]
Yes, the constant restriction applies to attributes. Luckily, you can work around this either with manual patching or, my personal choice, using the TargetMethod method inside the patch class you normally would annotate.
