### ISSUE TITLE
Hello! What is the cause of this? The game is unturned.

### ISSUE THREAD

**Issue by 2629180692** [pardeike/Harmony#370]
Hello! What is the cause of this? The game is unturned.

![123](https://user-images.githubusercontent.com/37955351/102459398-81a50800-4080-11eb-869a-1fbaae72931c.jpg)

**Comment by 2629180692** [comment]
Here is the code
![2](https://user-images.githubusercontent.com/37955351/102459543-b4e79700-4080-11eb-967b-561327585f1e.jpg)
![3](https://user-images.githubusercontent.com/37955351/102459548-b618c400-4080-11eb-8876-f3d9eda1c963.jpg)

**Comment by pardeike** [comment]
This does not seem to be related to Harmony as the failing call is a simple reflection method `Assembly.GetName()`. I would guess the appdomain has some corrupt dll loaded or the domain assembly resolver is not working.
