### ISSUE TITLE
Private valuetypes passed by ref cannot be injected into patches

### ISSUE THREAD

**Issue by pardeike** [pardeike/Harmony#371]
Given an original method that has an argument that fulfilles the following criteria:
- argument type is valuetype
- argument type is private and cannot be used in code
- argument is passed by ref

Given a patch that tries to receive that argument, it must used `object` or `ref object` as argument since original argument type is inaccessible. This creates the need to box the value but the code at <https://github.com/pardeike/Harmony/blob/0b13bdaeba40e36559639d7a1669743a1c3af6ae/Harmony/Internal/MethodPatcher.cs#L537> does not support boxing.

Solution: implement boxing for the scenarios where it is required.

**Comment by 0x0ade** [comment]
Would exposing the raw IntPtr work? Users could then use the IntPtr as a
reference to a lookalike struct bypassing visibility rules.

Andreas Pardeike <notifications@github.com> schrieb am Di., 22. Dez. 2020,
13:12:

**Comment by pardeike** [comment]
Thanks for the tip but I rather want to implement it the correct way. It’s just a matter of constructing the right IL for all cases. Previous versions of Harmony simply did not consider all cases. This [gist](https://gist.github.com/pardeike/7ecb8cd866feb3480d0843b45765bfbc) lists them all.

**Comment by pardeike** [comment]
Fixed
