### ISSUE TITLE
Manual patching seems does not work for some methods and it is breaking the flow...

### ISSUE THREAD

**Issue by albgen** [pardeike/Harmony#373]
**Describe the bug**
it seems that the original method is skipped because the behavior it is like it is skipped and also nothing is logged...

**To Reproduce**
1. The original method and its signature and class

Not Available

2. The patch code

```
        public static void Dopatching()
        {
            var harmony = new Harmony("com.example.patch.justapatch");

            object k = false;
            var mOriginal = AccessTools.Method("The.Full.Namespace:TheMethodToPatch");
            if (mOriginal == null)
            {
                Log.Error("Cannot Patch, {@stack} !", Environment.StackTrace);
                return;
            }
            var mPrefix = SymbolExtensions.GetMethodInfo(() => MyPrefixMethod(ref k, 0,0));

            harmony.Patch(mOriginal, new HarmonyMethod(mPrefix));

        }

        static bool MyPrefixMethod(ref object __result, object objType, object objNo)
        {
            Log.Information("MyPrefixMethod, {@__result}, {@objType}!", __result, objType, objNo, Environment.StackTrace); 
            return true;
        }
```

3. The output of the Harmony debug log
4. The stacktrace or other errors
No errors at all!

**Expected behavior**
Just to log the messagge, but nothing is shown...

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: [e.g. Windows 10, 64bit]
 - .NET version [ 4.8]
 - Harmony version [2.0.4]
- Name of game or host application [custom]

**Additional context**
creation of the logger and it is working because a see messagges logged when calling Log.info before calling Dopatching...
  ```
             Log.Logger = new LoggerConfiguration()
            .Enrich.WithProperty("Patcher.NET", "1.0.0.0")
            .WriteTo.Seq("http://localhost:5341")
            .CreateLogger();
```

**Comment by pardeike** [comment]
Hello,

Please complete step 3 (The output of the Harmony debug log) by adding `Harmony.DEBUG = true` before you instantiate Harmony. The log will be created at your desktop. 

/Andreas

**Comment by albgen** [comment]
hello,

it is not working even the debug. 
The exe is running as service...i gave the account which the service is running, full permission on the desktop folder but nothing.
what could be the issue?

**Comment by pardeike** [comment]
Get logging going first. Add a `FileLog.Log("test");` after the `Harmony.DEBUG = true;` and it should generate at least one line.

**Comment by albgen** [comment]
nothing...it dows not create even with

```
            Harmony.DEBUG = true;
            FileLog.Log("test");
            var harmony = new Harmony(....
```

**Comment by pardeike** [comment]
Are you sure your code is executed at all? Maybe it throws an exception or a dependency isn't available at runtime?

**Comment by albgen** [comment]
yes, of course i'm sure it is executed. Some other logs are still visibile on Seq logger but some others are not.
Most probably there is an exception but currently i have no visibility. Will try to run a profiler to understand what is happening.
I don't think i have other options...

**Comment by pardeike** [comment]
Closed due to inactivity
