### ISSUE TITLE
HarmonyPatchAttribute with string type

### ISSUE THREAD

**Issue by Trojaner** [pardeike/Harmony#378]
Suggestion is to support patching by specifying type as string, e.g. 
`[HarmonyPatch("SomeAssemblyFullName",  "SomeThing.SomeType")]` (this overload does not exist already).
Harmony would then just use Type.GetType() to resolve the type when patching is done. 

Sometimes its not possible to reference a type at compile time or during runtime, especially when dealing with optional dependencies. For this reason the call to `Type.GetType()` must not happen at the constructor of the attribute but when patch function is called.

In my case the problem is that the assembly I want to patch gets loaded after my assembly. Since assembly.GetTypes() is done for my assembly by some other code, the related patch classes will fail to load as they are directly referencing the yet to be loaded target assembly. With mono, if some type fails to load at some point, it is impossible to recover from this without a restart (related bug: [AssemblyResolve event not triggered if Assembly already failed to load](https://xamarin.github.io/bugzilla-archives/60/60100/bug.html)). 

This might sound like a too specific bug, and a workaround by using harmony.Patch() directly also exists. But the fix is also very easy to implement, hence the proposal.

**Comment by pardeike** [comment]
I am not so sure if you can easily use a string to specify a method. It works for the simple cases but for a tool like Harmony that is not enough. 

Without a clear plan on how to do that for *all* cases this will just result in users trying to use it and fail for:

- methods with `ref` arguments
- methods with generic types
- extension methods
- differences between static/non-static, constructors, params arguments, etc

Not worth the trouble I think.

**Comment by pardeike** [comment]
BTW: There is `TargetMethod()` as a good workaround that works with annotated classes.

**Comment by Trojaner** [comment]
I am a bit confused. This proposal is only for replacing [HarmonyPatch(Type type)] with [HarmonyPatch(string assemblyFullName, string typeFullName)] so it does not need a compile time reference.

**Comment by pardeike** [comment]
Sorry, I was assuming you wanted a one liner with all the information to find the original method. 

So just the type? Previously I rejected the idea because there is already a (String) overload for the method name. So you suggest (String, String) instead where the first argument defines the assembler name?!

I'm fine with the second argument following the same rules as AccessTools.TypeByName but what is the first string exactly?

**Comment by Trojaner** [comment]
> So just the type? Previously I rejected the idea because there is already a (String) overload for the method name. So you suggest (String, String) instead where the first argument defines the assembler name?!
Assembly name. A type could be defined in multiple assemblies hence it needs a way to distinguish this. It seems like `AccessTools.TypeByName` ignores this. Aside this there need to be two string parameters otherwise it would conflict with the method name overload

**Comment by pardeike** [comment]
Can you point me to the documentation that shows how to look up a type in a specific assembly? To my knowledge you can only have one unique type per AppDomain, but I am standing happily corrected.

**Comment by Trojaner** [comment]
[Assembly.GetType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.gettype) would be the correct way of getting a type from a specific assembly.  Another way is using Type.GetType with the [AssemblyQualifiedName](https://docs.microsoft.com/en-us/dotnet/api/system.type.assemblyqualifiedname) e.g. `System.Array, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.` but this does not work with dynamic assemblies (e.g. System.Reflection.Emit).

> To my knowledge you can only have one unique type per AppDomain, but I am standing happily corrected.

It is possible to have the same class name and namespace inside the same AppDomain, but these would be different instances. This is also why the [extern alias](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias) keyword exists in case they conflict during compile time.

**Comment by pardeike** [comment]
Closed in favor of using TargetMethod. Overloading annotations is already at its limit and adding more would confuse users.
