### ISSUE TITLE
Pseudo manual patching with annotated patch classes

### ISSUE THREAD

**Issue by podostro** [pardeike/Harmony#380]
**Is your feature request related to a problem? Please describe.**
Due to the problem described in issue [376](https://github.com/pardeike/Harmony/issues/376) and its workaround.
I have a new need to be able to patch several times, in multiple game states. i.e: 

1. Doorstop => assembly entrypoint => low level patches
2. `SceneManager.sceneLoaded` event => high level patches

This is possible already by having my patches in multiple assemblies and calling Harmony.PatchAll(Assembly); but this makes the distribution of mod cluttered by having multiple assembly files, and the chance of final user error is high.

**Describe the solution you'd like**
Two new Patch() methods in Harmony class:

```csharp
public MethodInfo PatchClass<T>() where T: class
```
This method would make Harmony analyze the class's annotations for patches.

```csharp
public IEnumerable<MethodInfo> PatchClasses(IEnumerable<Type> types)
```
This method would do the same as the one above, but for multiple classes.

**Describe alternatives you've considered**
The only other alternative I thought of would be to use Emit to create the assemblies on runtime, but that beats the purpose, because having to recreate the patch classes inside the dynamic assemblies, is even more work than just manually calling Patch() for each method I want to patch.

**Additional context**
EDIT: Figured `Harmony.CreateClassProcessor(Type type)` exists for this kind of situation.
But it would still be great to have a "direct" method. It would make cleaner code. i.e:
```csharp
	harmony.PatchClass<MyClassPatch>();
```
instead of 
```csharp
	harmony.CreateClassProcessor(typeof(MyClassPatch)).Patch();
```

Also realized I missed IEnumerable in the return type for my suggested PatchClasses method, so I just added it.

**Comment by pardeike** [comment]
I find the existing API sufficiently non-verbose for the purpose and will close the feature request. An API should not contain 500 ways to do the same thing.
