### ISSUE TITLE
harmony.log.txt appears on the desktop

### ISSUE THREAD

**Issue by corhsin** [pardeike/Harmony#382]
**Describe the bug**
A text file appears on the desktop.

**To Reproduce**
1. Playing RimWorld

**Screenshots / Code**
e. g. https://pastebin.com/f7r9CnLs is the first ~512kb /3MB+ (pastebin limit)

**Runtime environment (please complete the following information):**
 - OS: Windows 10 Pro, 64bit 20H2
 - .NET version 3.5
 - Harmony version 1.2.0.1
- Name of game or host application RimWorld

**Additional context**
Please advise.  Can the file creation be disabled?

**Comment by pardeike** [comment]
One of your mods ships with debugging flag on. Probably the first mentioned one at the top of the file. 

Harmony provides the functionality but mods need to use it wisely. 

Nothing to fix in Harmony
