### ISSUE TITLE
.net5.0 native support

### ISSUE THREAD

**Issue by Cn-mjt44** [pardeike/Harmony#383]
in some scene we need to do the method patch in .net5.0 and .net core, I try to patch native .net program but It fail.And I hope It can support .net native program.

**Comment by pardeike** [comment]
With the latest MonoMod.Common release we will get .NET 5 support. Updates soon, meanwhile you can try compiling master yourself.

**Comment by n3b** [comment]
@pardeike unfortunately master with the latest MonoMod.Comon (or even with 20.12.10.1) causes memory corruption (net5.0 core)

**Comment by 0x0ade** [comment]
Do you have an isolated minimum test case to replicate the memory corruption? I'd like to debug it and am unable to replicate this with MonoMod.RuntimeDetour.

**Comment by n3b** [comment]
@0x0ade unfortunately I can't. So far I've traced it down to 3 consecutive methods that app invokes. Patched all of them with simple console output and, surprisingly, the second method is invoked when I run app with debugger (JetBrains Rider), but it's not when I do regular run. Not sure where to move from this point.

**Comment by n3b** [comment]
I've refactored all my patches from Harmony to MonoMod.RuntimeDetour (21.1.11.1) and now everything works fine

**Comment by pengweiqhca** [comment]
[v20.12.25.01 Implement JIT hooks for .NET Core 3.1+ tiered compilation support](https://github.com/MonoMod/MonoMod/releases/tag/v20.12.25.01)

**Comment by pardeike** [comment]
Now implemented in 718b979a212e4edab9e3d2e99c67fd5f6739fc0d, can you verify on master?

**Comment by Cn-mjt44** [comment]
@pardeike I Think you can try to use the unsafe method like you was:

		public static string WriteJump(long memory, long destination)
                {
			Memory.UnprotectMemoryPage(memory);
			bool flag = IntPtr.Size == 8;
			if (flag)
			{
				bool flag2 = Memory.CompareBytes(memory, new byte[]
				{
					233
				});
				if (flag2)
				{
					int num = Memory.ReadInt(memory + 1L);
					memory += (long)(5 + num);
				}
				memory = Memory.WriteBytes(memory, new byte[]
				{
					72,
					184
				});
				memory = Memory.WriteLong(memory, destination);
				memory = Memory.WriteBytes(memory, new byte[]
				{
					byte.MaxValue,
					224
				});
			}
			else
			{
				memory = Memory.WriteByte(memory, 104);
				memory = Memory.WriteInt(memory, (int)destination);
				memory = Memory.WriteByte(memory, 195);
			}
			return null;
                 }

Decode from DnSpy

**Comment by Cn-mjt44** [comment]
public unsafe static long WriteByte(long memory, byte value)
		{
			byte* ptr = memory;
			*ptr = value;
			return memory + 1L;
		}

**Comment by pardeike** [comment]
@Cn-mjt44 And for what reason?

**Comment by sep2** [comment]
Sorry to bother, but I faced the very same issue in .net6. In Debug mode the patches were working properly, when in Release mode the first time patches worked, but the second time the patches are reverted automatically.

**Comment by pardeike** [comment]
@0x0ade is this the re-JIT hook not working?

**Comment by sep2** [comment]
Btw I'm using postfix patches only. Would it be helpful to switch to transpiler? Since the docs said that transpiler will replace the original method op code, and the original method is destroyed. Will it mean that jit can only do with the transpiled code then?

**Comment by pardeike** [comment]
It means that Harmony has overwritten the beginning of the original, native method and so nobody, not even your patch code can ever call it again after you patched it. You basically replace it. Probably not what you want.

**Comment by sep2** [comment]
I want my modified version always run, replacing the original one, no matter what jit/inline does. Sounds like a transpiler can do this as you said it replaces the original method?

**Comment by pardeike** [comment]
Just create a small transpiler that ignores the IL input and only outputs the IL that makes up a call to one of your static methods that contains the code you want to run instead of the native original. 

See the transpiler tutorial in the documentation or use GitHub search to find examples.

**Comment by sep2** [comment]
Unfortunately, I tried the transpiler method, the result is same: in Debug mode it always works, but in Release mode it starts calling the original method after several calls.

**Comment by pardeike** [comment]
That’s inlining

**Comment by sep2** [comment]
I saw the [document](https://harmony.pardeike.net/articles/patching-edgecases.html#inlining) said:

> Besides that, you can only resort to some clever redesign of your patch and find a spot higher up in the call chain that is not inlined. This sometimes requires mass-patching all occurances of all methods that call the inlined method and patching there (TargetMethods() is your friend).

and tried to patch a larger method instead, but it still gets inline after several calls. Seems like there are no way to do a patch reliably for the time being in .net6. Anyway, thank you for your help!

**Comment by 0x0ade** [comment]
The JIT hook is supposed to work on .NET Core 3.1+, but there are some platform-specific edge cases which had been taken into account recently / have yet to be taken into account.

What platform are you running on? x86, x64, arm64?
What operating system? Windows, Linux, macOS?
What _exact_ runtime version are you _running_ on? I'm not talking about the target framework you're compiling against, but rather what `dotnet --list-runtimes` gives you.

**Comment by sep2** [comment]
it's Linux x64.
```shell
> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
