### ISSUE TITLE
Acessing and changing private values

### ISSUE THREAD

**Issue by pokegustavor** [pardeike/Harmony#387]
I am trying to override a method that contains private values and protected objects, the only problem beeing that using the three underscores (___InstanceName) My compiler (visual studio 2019) will create a error saying that was unable to locate given instance
![imagem_2021-03-04_100404](https://user-images.githubusercontent.com/74270307/109968046-f3304200-7cd0-11eb-8136-f8c75960dde4.png)

**Comment by pardeike** [comment]
If you inject a variable with a three underscore prefix it will be sufficient to use it directly and not on __instance. Harmony sets the value of those arguments for you and if you add `ref` to the arguments then you can even assign values back to them. Not need to use __instance

**Comment by pokegustavor** [comment]
> ![devenv_tRJtJwfUPt](https://user-images.githubusercontent.com/63492966/172025324-879c52f1-8e96-4071-bc56-4a0c32a8b88a.png)
> ![devenv_TS2hEzYlNt](https://user-images.githubusercontent.com/63492966/172025332-e2dc2e13-aece-4b93-953a-d0cf58524127.png)
> 
> 

He means you get the field with 3 underscores, like float ref ___privatefloat
