### ISSUE TITLE
Allow methods to match with argument name '_'

### ISSUE THREAD

**Issue by PhilPJL** [pardeike/Harmony#389]
If I have a method like this

![image](https://user-images.githubusercontent.com/271656/110783700-afa17f00-8260-11eb-8bca-e34bd6d44ac7.png)

I would like to change it to 

![image](https://user-images.githubusercontent.com/271656/110783758-bf20c800-8260-11eb-9bd4-ac1204bad7a8.png)

Unfortunately this fails because Harmony is expecting parameter names to match exactly.

**Comment by pardeike** [comment]
Use [argument annotations](https://harmony.pardeike.net/api/HarmonyLib.HarmonyArgument.html) that allow you to match the name in the annotation.
