### ISSUE TITLE
Generic Classes Bug

### ISSUE THREAD

**Issue by CannibarRechter** [pardeike/Harmony#39]
Hi. The following attached C# console program illustrates a bug in the processing of generic classes in C#.

The program was compiled and tested from the most recent source release of Harmony, using Visual Studio Enterprise 2017.

[Program.zip](https://github.com/pardeike/Harmony/files/1315136/Program.zip)

**Comment by FrodoOf9Fingers** [comment]
As an additional test (done inside of a rimworld mod):
```
            Type[] Types = new Type[] { typeof(ThingOwner<Thing>), typeof(ThingOwner<ThingWithComps>), typeof(ThingOwner<Apparel>), typeof(ThingOwner<Pawn>) };
            foreach (Type t in Types)
            {
                FileLog.Log(Memory.GetMethodStart(t.GetMethod("Remove", new Type[] { typeof(Thing) })).ToString());
            }
```
logs the same address for all 4 types, and this address is used to write the jumps for the actual swapping of code control from the original function to the new function. I'll poke around a little more to see if there's any potential fix (Unless pardeike knows the solution off the bat).

**Comment by pardeike** [comment]
It's actually quite simple. Generic methods exist only once in the dll. If you look up the IL code for the method you use, @FrodoOf9Fingers. Since Harmony works by point methods pointers, you cannot point "one of them" to something else. Instead, you need to live with the fact that you are patching the generic method and you need to deal with the types inside.

**public** override bool Remove(Thing **item)**
```
.method public hidebysig virtual 
	instance bool Remove (
		class Verse.Thing item
	) cil managed 
{
	// Method begins at RVA 0x20da38
	// Code size 72 (0x48)
	.maxstack 2
	.locals init (
		[0] int32
	)

	IL_0000: ldarg.0
	IL_0001: ldarg.1
	IL_0002: call instance bool Verse.ThingOwner::Contains(class Verse.Thing)
	IL_0007: brtrue IL_000e

	IL_000c: ldc.i4.0
	IL_000d: ret

	IL_000e: ldarg.1
	IL_000f: ldfld class Verse.ThingOwner Verse.Thing::holdingOwner
	IL_0014: ldarg.0
	IL_0015: bne.un IL_0021

	IL_001a: ldarg.1
	IL_001b: ldnull
	IL_001c: stfld class Verse.ThingOwner Verse.Thing::holdingOwner

	IL_0021: ldarg.0
	IL_0022: ldfld class [mscorlib]System.Collections.Generic.List`1<!0> class Verse.ThingOwner`1<!T>::innerList
	IL_0027: ldarg.1
	IL_0028: unbox.any !T
	IL_002d: callvirt instance int32 class [mscorlib]System.Collections.Generic.List`1<!T>::LastIndexOf(!0)
	IL_0032: stloc.0
	IL_0033: ldarg.0
	IL_0034: ldfld class [mscorlib]System.Collections.Generic.List`1<!0> class Verse.ThingOwner`1<!T>::innerList
	IL_0039: ldloc.0
	IL_003a: callvirt instance void class [mscorlib]System.Collections.Generic.List`1<!T>::RemoveAt(int32)
	IL_003f: ldarg.0
	IL_0040: ldarg.1
	IL_0041: call instance void Verse.ThingOwner::NotifyRemoved(class Verse.Thing)
	IL_0046: ldc.i4.1
	IL_0047: ret
} // end of method ThingOwner`1::Remove
```

**Comment by FrodoOf9Fingers** [comment]
Though, to clarify, doesn't this only happens with reference types, as all reference types are treated the same in IL? Or do value types also point to the same exact function address as well?

**Comment by pardeike** [comment]
I think its more complicated than that. I’ve seen generic methods being duplicated by the compiler. It might depend on the compiler and the optimisation it does. In the end, the decompile of the dll answers the question.
