### ISSUE TITLE
Patching ``UnityEngine.Ray.get_origin`` breaks raycasting / everything that accesses the ray origin

### ISSUE THREAD

**Issue by marwie** [pardeike/Harmony#390]
**Describe the bug**
Patching ``UnityEngine.Ray.get_origin`` breaks raycasting / everything that accesses the ray origin. Unpatching seems to be not working.

**To Reproduce**
Add a postfix or transpiler (haven't tried with prefix) to ``UnityEngine.Ray.get_origin``. I uploaded a minimal project. See below

**Screenshots / Code**
Minimal repro: https://github.com/marwie/harmony-patch-raycast (see video below)

https://user-images.githubusercontent.com/5083203/111507395-e4bf3d00-874a-11eb-965f-cdb62b331a8f.mp4

Patch
```csharp
        [HarmonyPatch(typeof(Ray))]
	public class Patch
	{
		[HarmonyPostfix]
		[HarmonyPatch(MethodType.Getter)]
		[HarmonyPatch("origin")]
		public static void Postfix()
		{
		}
	}
```

``` 
IL_0000: Local var 0: UnityEngine.Vector3
IL_0000: // start original
IL_0000: nop
IL_0001: ldarg.0
IL_0002: ldfld      UnityEngine.Vector3 UnityEngine.Ray::m_Origin
IL_0007: stloc.0
IL_0008: br =>      Label0
IL_000D: Label0
IL_000D: ldloc.0
IL_000E: // end original
IL_000E: ret
DONE
```

Unity code
![image](https://user-images.githubusercontent.com/5083203/111507253-c0636080-874a-11eb-932b-1139bbb76414.png)
![image](https://user-images.githubusercontent.com/5083203/111507303-ce18e600-874a-11eb-9101-dbf79458e0ca.png)

**Runtime environment (please complete the following information):**
 - OS: Win10
 - .NET 4.5
 - Harmony 2.0.4
- Unity Editor 2020.3.0f1

**Comment by marwie** [comment]
Tried latest dev version (381b72c48a9929c55e3469d2bd50b3176a6d5f89) but still happens

**Comment by pardeike** [comment]
I don't have access to my PC right now but I find it suspicious that the getter on the right side in the IL view has no IL code. 

Harmony uses the IL to construct the replacement.
