### ISSUE TITLE
Prefix of Generic Method is not executed when the type of Generic is System.String

### ISSUE THREAD

**Issue by comet7360** [pardeike/Harmony#391]
Hi Pardeike,
I can not execute PrefixStr() before OriginalMethod().
Please let me know if there are any mistakes in my code.
I think the cause is the difference in type(reference type vs value type).

>Windows 10 Pro 64bit  (19041.867)
>Visual Studio 2019 Pro v 16.9.2
>.NET Core 3.0
>Lib.Harmony v2.0.4
```C#
using System;
using System.Reflection;
using HarmonyLib;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var harmony = new Harmony("hogehoge");

            // Insert Prefix to OriginalMethod<int>
            MethodInfo prefixInt = typeof(MyPatches).GetMethod("PrefixInt");
            MethodInfo originalnt = typeof(Dummy).GetMethod("OriginalMethod").MakeGenericMethod(typeof(int));
            harmony.Patch(originalnt, new HarmonyMethod(prefixInt));

            Dummy.OriginalMethod<int>("hode");     // ← ★OK "PrefixInt is Called."

            // Insert Prefix to OriginalMethod<string>
            MethodInfo prefixStr = typeof(MyPatches).GetMethod("PrefixStr");
            MethodInfo originaStr = typeof(Dummy).GetMethod("OriginalMethod").MakeGenericMethod(typeof(string));
            harmony.Patch(originaStr, new HarmonyMethod(prefixStr));

            Dummy.OriginalMethod<string>("hode"); // ← ★NG "This is OriginalMethod."
        }
    }

    class Dummy
    {
        public static T OriginalMethod<T>(string param)
        {
            Console.WriteLine("This is OriginalMethod.");

            return default(T);
        }
    }

    class MyPatches
    {
        public static bool PrefixInt()
        {
            Console.WriteLine("PrefixInt is Called.");
            return false;
        }

        public static bool PrefixStr()
        {
            Console.WriteLine("PrefixStr is Called.");
            return false;
        }
    }
}
```

**Comment by pardeike** [comment]
The way .NET calls are dispatched to generic methods makes it hard or nearly impossible to patch them deterministic. Sometimes the patch is called for all T even though you only specified  specific T. Sometimes, it’s not called at all. I suspect inlining in this case. The JIT compiler uses heuristics to determine when to inline and it’s likely it decides different for the two generic implementations. Add a dummy try/catch inside your original to force non-inlining and see what happens.

**Comment by pardeike** [comment]
Also, please try with a `master` build if you can. It uses tiered compilation protection and is still under evaluation. So your feedback is appreciated.

**Comment by comet7360** [comment]
Thank you for your quick response.
I add try/catch and retried. But still I couldn't do execute PrefixStr().
```C#
try{
    Dummy.OriginalMethod<string>("hode"); // ← ★NG "This is OriginalMethod."
}catch{}
```
Also, I builded the master solution(2.0.5.0). And I install the local package and retried above code.
But the result was same.

**Comment by comet7360** [comment]
This is my workaround.
Instead of string type, I used struct Hoge, which has member of string type.
I think this way can handle everything related to reference type, not just string type.
```C#
struct Hoge { string strHoge; }

class Program
{
	static void Main(string[] args)
	{
		var harmony = new Harmony("hogehoge");

		// Insert Prefix to OriginalMethod<Hoge>
		MethodInfo prefix   = typeof(MyPatches).GetMethod("Prefix");
		MethodInfo original = typeof(Dummy).GetMethod("OriginalMethod").MakeGenericMethod(typeof(Hoge));
		harmony.Patch(original, new HarmonyMethod(prefix));

		Dummy.OriginalMethod<Hoge>("hode"); // ← ★OK "Prefix is Called"
	}
}
```

**Comment by pardeike** [comment]
Yes, that’s what I meant with undefined. I just ran a few test cases and it is completely different for Mono and .NET. In Mono, any type T that is based on `object` is patched together (your prefix will be called for multiple types) and in .NET everything that is a valuetype seems to work and everything based on object isn’t. Or at least isn’t in this case.
