### ISSUE TITLE
How to use Traverse to call a private method which has an argument with 'ref' keyword?

### ISSUE THREAD

**Issue by aloneangel34** [pardeike/Harmony#393]
### **Describe the question** (not sure if it's a bug or not)

Traverse.Method(string name, params object[] arguments)
seems unable to find a private method which has 'ref' argument

### **To Reproduce**

1. Create a new **C# ConsoleApp** project in VS  (choose **.NET Core 3.0.1** or **.NET 5.0** , both have the same result) 
Add **Harmony 2.0.4.dll** to the project
Add **using HarmonyLib;**

2. Write a **static class**, inside the class, write a **private static method** with a **'ref' argument** (no return value)
_Such as:_
```C#
    public static class Age
    {
        private static void Change(ref int age)      //no other method, no method overloading
        {
            age++;
        }
    }
```
3. In Main method, using Traverse to call the **private static method** with a **'ref' argument**
but when running the app, got Exception: cannot get method value without method
_Such as:_
```C#
    class Program
    {
        public static void Main(string[] args)
        {
            int playerAge = 1;
            
            Traverse.CreateWithType("Age").Method("Change",playerAge).GetValue(playerAge);
            //run code in the above line will got
            //Exception: cannot get method value without method
            
            Console.WriteLine(playerAge);
            Console.ReadKey();
        }
    }
```

4. Also tried to add 'ref' keyword in codes, which got Compiler Errors in VS
_Such as:_
```C#
    Traverse.CreateWithType("Age")
    .Method("Change",ref playerAge)	//Error CS1615: The 2nd argument should not be passed with the 'ref' keyword
    .GetValue(ref playerAge);	//Error CS1615: The 1st argument should not be passed with the 'ref' keyword
```

### **Runtime environment:**

OS: Windows 10, 64bit
**.NET Core 3.0.1** or **.NET 5.0** (both have the same result)
Harmony version: 2.0.4.0 

### **Additional context**

1. I have read the article of [Harmony / Utilities](https://harmony.pardeike.net/articles/utilities.html#traverse)
and [API Documentation / HarmonyLib / Traverse](https://harmony.pardeike.net/api/HarmonyLib.Traverse.html)
Seems **argument with 'ref' keyword** wasn't be **specifically** metioned.

2. I have checked CONTRIBUTING.md
but I can't open Discord, and was thinking that a long text might better be write down slowly and carefully
so I posted here, sorry if that is not allowed
> Asking Questions
> Have a question? Rather than opening an issue, please ask away on the Discord Server.

3. I am not good at English.
Sorry if my description cause confuse, or if having any misspellings / gammar errors.

-------
###Edited
-------
1. What about **argument with 'out' keyword** ?**
Try using Traverse to call a method that has **argument with 'out' keyword**
Get same result as 'ref' keyword
_Such as:_
```C#
    public static class Age
    {
        private static void Change(int age, out int output)      //no other method, no method overloading
        {
            age++;
            output = age;
        }
    }

    class Program
    {
        public static void Main(string[] args)
        {
            int playerAge = 1;
            int outnum = 100;
            
            Traverse.CreateWithType("Age").Method("Change", playerAge, outnum).GetValue(playerAge, outnum);
            //run code in the above line will got
            //Exception: cannot get method value without method
            
            Console.WriteLine(outnum);
            Console.ReadKey();
        }
    }
```

2. I don't know how to use the method below:
Traverse.Method(string name, Type[] paramTypes, object[] arguments = null)
Maybe it has the solution. Or, maybe I missed something...

**Comment by pardeike** [comment]
Traverse was never meant to work in all cases. It’s a simple wrapper for simple cases. Harmony has many more advanced ways to deal with private fields or methods. 

Sorry but this is a case of WONTFIX

**Comment by Neutron3529** [comment]
> ### **Describe the question** (not sure if it's a bug or not)
> 
> Traverse.Method(string name, params object[] arguments)
> seems unable to find a private method which has 'ref' argument
> ### **To Reproduce**
> 
>     1. Create a new **C# ConsoleApp** project in VS  (choose **.NET Core 3.0.1** or **.NET 5.0** , both have the same result)
>        Add **Harmony 2.0.4.dll** to the project
>        Add **using HarmonyLib;**
> 
>     2. Write a **static class**, inside the class, write a **private static method** with a **'ref' argument** (no return value)
>        _Such as:_
> 
> 
> ```cs
>     public static class Age
>     {
>         private static void Change(ref int age)      //no other method, no method overloading
>         {
>             age++;
>         }
>     }
> ```
> 
>     1. In Main method, using Traverse to call the **private static method** with a **'ref' argument**
>        but when running the app, got Exception: cannot get method value without method
>        _Such as:_
> 
> 
> ```cs
>     class Program
>     {
>         public static void Main(string[] args)
>         {
>             int playerAge = 1;
>             
>             Traverse.CreateWithType("Age").Method("Change",playerAge).GetValue(playerAge);
>             //run code in the above line will got
>             //Exception: cannot get method value without method
>             
>             Console.WriteLine(playerAge);
>             Console.ReadKey();
>         }
>     }
> ```
> 
>     1. Also tried to add 'ref' keyword in codes, which got Compiler Errors in VS
>        _Such as:_
> 
> 
> ```cs
>     Traverse.CreateWithType("Age")
>     .Method("Change",ref playerAge)	//Error CS1615: The 2nd argument should not be passed with the 'ref' keyword
>     .GetValue(ref playerAge);	//Error CS1615: The 1st argument should not be passed with the 'ref' keyword
> ```
> 
> ### **Runtime environment:**
> 
> OS: Windows 10, 64bit
> **.NET Core 3.0.1** or **.NET 5.0** (both have the same result)
> Harmony version: 2.0.4.0
> ### **Additional context**
> 
>     1. I have read the article of [Harmony / Utilities](https://harmony.pardeike.net/articles/utilities.html#traverse)
>        and [API Documentation / HarmonyLib / Traverse](https://harmony.pardeike.net/api/HarmonyLib.Traverse.html)
>        Seems **argument with 'ref' keyword** wasn't be **specifically** metioned.
> 
>     2. I have checked CONTRIBUTING.md
>        but I can't open Discord, and was thinking that a long text might better be write down slowly and carefully
>        so I posted here, sorry if that is not allowed
> 
> 
> > Asking Questions
> > Have a question? Rather than opening an issue, please ask away on the Discord Server.
> 
>     1. I am not good at English.
>        Sorry if my description cause confuse, or if having any misspellings / gammar errors.
> 
> 
> ## ###Edited
> 
>     1. What about **argument with 'out' keyword** ?**
>        Try using Traverse to call a method that has **argument with 'out' keyword**
>        Get same result as 'ref' keyword
>        _Such as:_
> 
> 
> ```cs
>     public static class Age
>     {
>         private static void Change(int age, out int output)      //no other method, no method overloading
>         {
>             age++;
>             output = age;
>         }
>     }
> 
>     class Program
>     {
>         public static void Main(string[] args)
>         {
>             int playerAge = 1;
>             int outnum = 100;
>             
>             Traverse.CreateWithType("Age").Method("Change", playerAge, outnum).GetValue(playerAge, outnum);
>             //run code in the above line will got
>             //Exception: cannot get method value without method
>             
>             Console.WriteLine(outnum);
>             Console.ReadKey();
>         }
>     }
> ```
> 
>     1. I don't know how to use the method below:
>        Traverse.Method(string name, Type[] paramTypes, object[] arguments = null)
>        Maybe it has the solution. Or, maybe I missed something...

I've met the same issue, but I'm fortunately enough to find a dirty fix.
(在足够多次作死之后我找到了一个很脏的解法)
```
            var m=typeof(StorageComponent).GetMethods();
            MethodInfo method_to_patch=m[0];
            foreach(var i in m)if(i.Name=="TakeTailItems" && i.ReturnType==typeof(void)){
                method_to_patch=i;
                break;
            }
            if(method_to_patch.Name!="TakeTailItems" || method_to_patch.ReturnType!=typeof(void)){return;}
            var prefix = typeof(StorageComponentTakeTailItemsPatch).GetMethod("Prefix");
            harmony.Patch(method_to_patch, new HarmonyMethod(prefix));
```
我们的主要问题是，GetMethod找到了两个同名函数
而解法，大概是手工处理这些同名函数的区别
比如我这里用了` || method_to_patch.ReturnType!=typeof(void)`来确保我找到的函数的确是我需要的函数
如果你遇到的问题需要处理其他函数，或许可以使用其他条件进行筛选
