### ISSUE TITLE
Harmony.PatchAll()'s use of StackTrace.GetFrame(1) is prone to inlining issues

### ISSUE THREAD

**Issue by chriswa** [pardeike/Harmony#395]
**Is your feature request related to a problem? Please describe.**
I just spent a few hours chasing down a bug in some of my mods' release builds which weren't patching. I believe it was caused by JIT inlining of my method which calls `harmony.PatchAll();`, resulting in Harmony.PatchAll()'s `new StackTrace().GetFrame(1)` finding my caller's assembly (instead of mine!) and resulting in a silent failure to patch.

**Describe the solution you'd like**
I'd like to recommend that `harmony.PatchAll()` be removed from Harmony's API so that others don't stumble into this gotcha. Users can call `harmony.PatchAll(Assembly.GetExecutingAssembly());` instead.

**Describe alternatives you've considered**
Applying the following annotation to my method also works:
`[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]`

**Additional context**
Thanks for the awesome library! I've been quite effectively to mod Vintage Story. <3

**Comment by pardeike** [comment]
In many cases this still works fine so I am not going to remove it and break a ton of client code. 

However, I will add a warning to the api documentation to describe the gotcha with inlining.

**Comment by pardeike** [comment]
Documentation added in the upcoming 2.1 release
