### ISSUE TITLE
Provide feedback from PatchAll about what was done

### ISSUE THREAD

**Issue by chriswa** [pardeike/Harmony#396]
**Is your feature request related to a problem? Please describe.**
While debugging why my patches weren't working in production, it would have been nice to get some programmatic feedback about `Harmony.PatchAll`'s activity instead of needing to grep the Harmony.DEBUG log. Even just a count of patches applied would help me sanity check my own code.

**Describe the solution you'd like**
I'd like `Harmony.PatchAll` to return a `List<MethodInfo>` of the patches it successfully made (i.e. a concatenation of the results of all its calls to `PatchClassProcessor.Patch()`), so that users can easily check the `.Count` to sanity check that their patches were applied.

**Describe alternatives you've considered**
Switching to the Manual Patching system temporarily was tedious.

**Additional context**
I ran into this while dealing with the issue described in https://github.com/pardeike/Harmony/issues/395

**Comment by pardeike** [comment]
There are already two ways to verify the result: either set `Harmony.DEBUG = true` before patching to get a log of patches to your desktop. Or use [GetPatchedMethods](https://harmony.pardeike.net/api/HarmonyLib.Harmony.html#HarmonyLib_Harmony_GetPatchedMethods) and [GetPatchInfo](https://harmony.pardeike.net/api/HarmonyLib.Harmony.html#HarmonyLib_Harmony_GetPatchInfo_System_Reflection_MethodBase_) and filter by your Harmony ID.

**Comment by pardeike** [comment]
If you don’t like PatchAll there is also just Patch() that returns the replacement method. Unfortunately, changing the signature of PatchAll isn’t an option because it isn’t backwards compatible and overloads cannot differ by return type only.

**Comment by chriswa** [comment]
I suppose I should have dug a little deeper and found GetPatchedMethods and GetPatchInfo!
