### ISSUE TITLE
Extra "0" in assembly name?

### ISSUE THREAD

**Issue by llaughlin** [pardeike/Harmony#4]
https://github.com/pardeike/Harmony/blob/master/Harmony/Harmony.csproj#L11 has this:
```
<AssemblyName>0Harmony</AssemblyName>
```
Should it be this?
```
<AssemblyName>Harmony</AssemblyName>
```

**Comment by pardeike** [comment]
That is on purpose. Many games load assemblies in alphabetical order and that way it has less conflicts. I recommend using ILMerge if you're picky about the name and merge everything into a single dll. That way, the name does not matter.

**Comment by llaughlin** [comment]
Ah, that makes sense. Thanks for the explanation!
