### ISSUE TITLE
Problem compiling Transpilers.cs with Visual Studio 2017

### ISSUE THREAD

**Issue by CannibarRechter** [pardeike/Harmony#40]
Using Visual Studio 2017 Enterprise, when attempting to compile Transpilers.cs, it issues he following error:

Severity   Code   Description   Project   File   Line   Suppression State
Error   CS0252   Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'MethodBase'   Harmony   H:\joe.kraska\Artifacts\Mods\Harmony-master\Harmony\Transpilers.cs   13   Active

**Comment by pardeike** [comment]
Fixed.
