### ISSUE TITLE
HarmonyPatch cannot deal with `ref` due to my poor knowledge.

### ISSUE THREAD

**Issue by Neutron3529** [pardeike/Harmony#401]
**Describe the bug**
I tried to patch some function like
```
void TakeTailItems(ref int count, ref int itemId, bool flag)
```
(which MethodInfo is `Void TakeTailItems(Int32 ByRef, Int32 ByRef, Boolean)`, but a similar MethodInfo
`Boolean TakeTailItems(Int32 ByRef, Int32 ByRef, System.Int32[], Boolean)` exists.)
I tried
`[HarmonyPatch(typeof(StorageComponent), "TakeTailItems",new Type[]{typeof(int) ,typeof(int) ByRef,typeof(bool)})]`
but nothing was found.

I further tried `typeof(&int) typeof(*int) typeof(int[]) typeof(ref int) ref typeof(int)`, but various of errors are generated
```
-(89,93): error CS1525: Invalid expression term 'ref'
-(89,116): error CS1031: Type expected
-(89,116): error CS1026: ) expected
-(89,117): error CS1525: Invalid expression term 'int'
-(89,120): error CS1003: Syntax error, ',' expected
```

AFAIK, there is no wiki or tutorial treating with `ref`.

So I open this issue to find some help.

**Comment by Neutron3529** [comment]
Sorry but I found some different things.
In my issue, the main difficult is that, there is no wiki about how to using HarmonyPatch with functions have a `ref` keyword, it is not what happened with Transverse.

It could be easily solved by adding one or two line in the wiki.
Thus, I reopen this issue, since my bypass code is very dirty(using .GetMethods() and then find the correct one).

**Comment by pardeike** [comment]
You should start using the auto completion feature of your IDE more. Most modern IDEs give you lots to choose from. Here for example it suggests extra arguments to annotations that should make you curious about them:

<img src="https://i.imgur.com/w7fNrNc.png" />

`argumentVariations` of type `ArgumentType` are easy to explore at the full API documentation:
https://harmony.pardeike.net/api/HarmonyLib.ArgumentType.html

which results in this:

<img src="https://i.imgur.com/EXadtCm.png" />

**Comment by Neutron3529** [comment]
> You should start using the auto completion feature of your IDE more. Most modern IDEs give you lots to choose from. Here for example it suggests extra arguments to annotations that should make you curious about them:
> 
> ![](https://camo.githubusercontent.com/30d94e23af8601b0a7fafc2df7dddd6193ae72ab8afe59129fa61d447e90ce8d/68747470733a2f2f692e696d6775722e636f6d2f7737664e724e632e706e67)
> 
> `argumentVariations` of type `ArgumentType` are easy to explore at the full API documentation:
> https://harmony.pardeike.net/api/HarmonyLib.ArgumentType.html
> 
> which results in this:
> 
> ![](https://camo.githubusercontent.com/61dde2507d8ec0205cb6a2f8fa37172f770922c41d97740d55d69ae4062e5d71/68747470733a2f2f692e696d6775722e636f6d2f4558616474436d2e706e67)

Thank you for your reply.
Since Linux have no Visual Studio installer, my IDE is kate.. I don't know how to enable the auto completion feature.

Using `[HarmonyPatch(typeof(StorageComponent), "TakeTailItems",new Type[]{typeof(int) ,typeof(int),typeof(bool)},new ArgumentType[]{ArgumentType.Ref,ArgumentType.Ref,ArgumentType.Normal})]`, my patch works.
