### ISSUE TITLE
BinaryFormatter serialization and deserialization are disabled within this application

### ISSUE THREAD

**Issue by apobekiaris** [pardeike/Harmony#402]
BinaryFormatter usage is obsolete in .net5.0 https://aka.ms/binaryformatter. 

I am unable to use Harmony in my Blazor projects there is a NotSupportedException, unless i modify my project with 

```xml
<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
```

**Comment by pardeike** [comment]
At this point there is no good alternative method to serialize the patch information across different assemblies. 

The article takes up scenario that don't apply to ours because Harmony only does serialization in memory and never saves it or makes it available to the outside.

**Comment by apobekiaris** [comment]
hmm not good news at all, applying the workaround is not something my users will do, they probably drop the efforts thinking that .net5.0 support is buggy or something.

Wondering if u just copy the source of BinaryFormatter and use that so .net won't through, might be an alternative
