### ISSUE TITLE
Question: Get targeted method name from generated patch?

### ISSUE THREAD

**Issue by bembarna** [pardeike/Harmony#404]
Hello, I am patching a very large portion of methods within a class, my goal is to just make a patch, that logs before the method runs(Prefix) with the method name that is being patched against, and the same with after it runs (Postfix).

I am using reflection to get all methods within the targeted class and using a loop to apply a basic Pre and Postfix patch for each of the methods, problem is, is being able to get the target method name inside of my Prefix and/or Postfix method, so I can log what method is actually hit. 

I tried using reflection to get the current method, but obviously this just gives me the Prefix method when logged, and not the method I am actually patching.

I am extremely new to this, but have been reading over the API documentation and looking through issues here, I have not been able to figure out if this is possible or not, but in a last effort, I am asking here because I am starting to think this may not be possible? Only thing is, is whenever I add the "[HarmonyDebug()]" attribute to both my Prefix and Postfix, it gives me everything I need on the "### Patch:" line, it shows the method being patched and the class its from, only issue with this is, it gives other information I don't need (which is fine, I could parse this out), and it only does this logging once (assuming it only does it while its generating the patch itself), but not through out the usage of the application during runtime.

Any insight or help on this matter would be greatly appreciated, thanks!

**Comment by pardeike** [comment]
https://harmony.pardeike.net/articles/patching-injections.html#--the-original
