### ISSUE TITLE
Implement Reverse Patching [was: Disable Harmony for specific calls]

### ISSUE THREAD

**Issue by FrodoOf9Fingers** [pardeike/Harmony#41]
I'm working on some parallelization, and I need to be able to call the patched function from within the patch itself without creating a recursive loop of patches. Can this be done? Or would it require a complete bypass of the original function? If that's requried, can we make an annotation for function bypassing as an alternative to transpilling?

**Comment by pardeike** [comment]
The best way to handle this is what I call a reverse patch. If you could patch one of your own methods with the original IL code you could execute that method instead of the original regardless of how the original is patched later by you or someone else. 

Some of the api you need for that is currently private so I am going to open this up in an upcoming release of Harmony. You could use reflections on the current API to get the same result now if you are impatient.

**Comment by FrodoOf9Fingers** [comment]
I'm not entirely sure if that would work. I would need the patched method to work with a specific instance, even though the type of that instance does not have the patched method as a member. 

For instance, here is the offending call:
            finder.FindPath(start, dest, traverseParms, peMode);

I don't believe it's possible to do:
            finder.My_rPatched_function(start, dest, traverseParms, peMode);
Where My_rPatched_function's IL code has been replaced with findPath. 

I can't find a way to call a function within the context of a specific class instance, even though the IL code would be that of one of the type's member functions. My current solution, albeit crude, is to completely copy the entire class definition and create instances of that type to call findPath on.

Here is what the broken patch looks like as for better context (I'm somewhat new to C#, I'm professionally a Java programmer, so excuse any convention violations):
`    [HarmonyPatch(typeof(PathFinder), "FindPath", new Type[] { typeof(IntVec3), typeof(LocalTargetInfo), typeof(TraverseParms), typeof(PathEndMode) })]
    static class FindPathPatch
    {
        [HarmonyPrefix]
        public static bool FindPath(PathFinder __instance, IntVec3 start, LocalTargetInfo dest, TraverseParms traverseParms, PathEndMode peMode = PathEndMode.OnCell)
        {
            FieldInfo mapField = typeof(PathFinder).GetField("map", BindingFlags.NonPublic | BindingFlags.Instance);
            Map map = (Map) mapField.GetValue(__instance);

            PathFinder finder = PathFinderInstanceContainer.GetInstance().requestFinder(map);
            finder.FindPath(start, dest, traverseParms, peMode);
            PathFinderInstanceContainer.GetInstance().returnPathFinder(map, finder);
            return false;
        }
    }`

**Comment by pardeike** [comment]
I don’t see why you could not write it like this:
```csharp
static class ReversePatches
{
	static void MyFindPath(this PathFinder __instance, IntVec3 start, LocalTargetInfo dest, TraverseParams traverseParams, PathEndMode peMode)
	{
		//... to be replaced
	}
}
```

To then, after reverse patching, call it like
```csharp
PathFinder finder = ...;
finder.MyFindPath(start, dest, trvParams, peMode);
// or
MyFindPath(finder, start, dest, trvParams, peMode);
```

**Comment by FrodoOf9Fingers** [comment]
Thank you for fixing my ignorance, Java doesn't have Extension Methods, and I didn't realize they existed in C#. Thanks!

**Comment by pardeike** [comment]
Great. Especially since I think we can even throw in transpiler support to get full flexibility. I.e. if you want to split an existing method into parts to call separately. I have to think about the signature and if and how to alter it.

**Comment by pardeike** [comment]
Since I am used to manipulating methods with transpilers, I thought you could do this:

Original method -> transpiler1 -> SomePartMethod

Original method -> transpiler2 -> SomeOtherPartMethod

then patch the original method to be

// some code
SomePartMethod()
// more code
SomeOtherPartMethod()
// even more code

where the first two reverse patches are onto your own methods and the last one is a normal patch or just a subroutine in your code.

**Comment by pardeike** [comment]
A reflection on `[HarmonyReversePatch(SourceMode)]`. I can think of four types:

**SourceMode.Unpatched**
Just uses the IL code of the original unmodified method

**SourceMode.Patched**
Uses the IL code as all registered prefix/postfix/transpilers would return right now. If you patch the method yourself, you probably want to use the Before/After annotation to archive the desired result.

**SourceMode.Wrapped**
Would only work for calling the whole method. It patches your local method with a new method that basically calls the original. That means all future patches would affect the function of your local method. Mainly useful to make private method available and when you want your local method to be like a exact proxy for the original even after others have patched it.

**Comment by pardeike** [comment]
Progress on this can be seen here:
https://github.com/pardeike/Harmony/tree/master/HarmonyTests/ReversePatching

**Comment by pardeike** [comment]
In the end, it came down to two modes:
- Original
- Snapshot

Both apply the originals code onto the standin and provide support for an optional transpiler that is embedded in the standin. That transpiler can alter the originals code and the standin must match the resulting signature.

The difference between Original and Snapshot is that Snapshot applies all currently existing transpilers on the original before the codes come to the embedded transpiler or become the replacement of the standin. In that sense, it represents a "snapshot" of the method as it is at the moment of patching.

The planned Wrapped mode is actually easier to do with a delegate or with FastMethodAccess.

Implemented as of now in master.
