### ISSUE TITLE
Harmony not finding CodeInstructions for override of virtual method

### ISSUE THREAD

**Issue by BigBadE** [pardeike/Harmony#411]
**Describe the bug**
Transcompilers on a method overriding a virtual method will get the instructions from the virtual method, not the overriding one.

**To Reproduce**
Simple test case w/ RimWorld:
```
    [HarmonyPatch(typeof(WorldLayer_Hills), "Regenerate")]
    public class WorldLayerHillinessIceHills
    {
        public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions, MethodBase methodBase)
        {
            Log.Message("Total instructions: " + instructions.Count());
            yield break;
        }
    }
```

**Expected behavior**
The instructions enumerable has the correct instructions for WorldLayer_Hills.Regenerate, which is ~60 lines of code.

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version: 4.7.2
 - Harmony version: 2.1.0
- Name of game or host application: RimWorld

**Additional context**
This happens both with manual and annotation patches. methodBase seems to have the correct method (it says it's virtual but it has the correct DeclairingType).

**Comment by BigBadE** [comment]
I've just realized this is a yield break method, so that's probably the problem not Harmony passing the wrong method's instructions.

**Comment by pardeike** [comment]
For methods that are generator functions (returning IEnumerable) the code you see in the compiler is not what actually happens at runtime. Patching requires low level understanding of how things are at runtime and you need to learn that the only thing the compiler puts into that method is the creation of an instance of a hidden class that contains all the code you see in C# in one big switch statement that is in a MoveNext method in that hidden class.

**Comment by BigBadE** [comment]
Yeah, I made the assumption that CIL looks anything like Java's Bytecode. Gonna have to dig into it more sooner or later.
