### ISSUE TITLE
Patch failed and caused AmbiguousMatchException was thrown

### ISSUE THREAD

**Issue by ForeverTianyi** [pardeike/Harmony#417]
**Describe the bug**
I try to get some methods, but when code is running, there is an error that Ambiguous matching in method resolution

**To Reproduce**
1. I look over the code of Assembly-CSharp.dll in DnSpy. And it seems like this:
![image](https://user-images.githubusercontent.com/79823959/127180698-f6926919-ac9b-4149-8bf9-5bd09687c20a.png)
2. There are two methods named "LoadFromName" but I want to get the generic method. This is my patch code :
```cshape
class LoadFromNamePatch
    {
        static MethodInfo TargetMethod()
        {
            return typeof(Assets.Scripts.PeroTools.AssetBundles.AssetBundleManager).GetMethod("LoadFromName", BindingFlags.Public | BindingFlags.Instance,null,new Type[] {typeof(string) },null).MakeGenericMethod(typeof(UnityEngine.GameObject));
        }
        [HarmonyTranspiler]
        public static IEnumerable<CodeInstruction> Patch(IEnumerable<CodeInstruction> instructions)
        {
            var MethodInfo = AccessTools.Method(typeof(EntryPoint), nameof(EntryPoint.LoadCustomAssetProxy));
            var codes = System.Linq.Enumerable.ToList(instructions);
            codes[21].opcode = OpCodes.Ldarg_1;
            codes.Insert(21, new CodeInstruction(OpCodes.Call, MethodInfo));
            return codes.AsEnumerable();
        }

    }
```
3. This is the output of the debug log. I used to try add BindingFlags and types parameters but it doesn't work at all. So how can I solve this problem?
![image](https://user-images.githubusercontent.com/79823959/127181160-70db5e2b-9af7-4c09-89a9-d2d9fb8ebea3.png)

**Expected behavior**
I just want to patch the generic method named "LoadFromName" and my patch code could work. 

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version: 3.5
 - Harmony version: 2.0.0.0
- Name of game or host application: Muse Dash

**Additional context**
I used Bepinex as the mod loader.

**Comment by pardeike** [comment]
You need to loop through all methods: https://stackoverflow.com/questions/588149/referencing-desired-overloaded-generic-method
