### ISSUE TITLE
Adding a case to a switch statement

### ISSUE THREAD

**Issue by LoganDark** [pardeike/Harmony#420]
**Is your feature request related to a problem? Please describe.**
Using a transformer, I can't figure out how to add a case to a switch statement. Labels existing makes this a little easier, I _think_ I can just inject some instructions before the end of the switch and all of the break instructions will adjust to the new position of the label... however, I don't know how to add my new case to the switch instruction itself.

**Describe the solution you'd like**
Document how to add a case to a switch statement

**Comment by pardeike** [comment]
It's not part of the functionality of Harmony to solve specific coding cases for you. There is a library that extends Harmony with useful function and this feature request is better served there.

As a general tip, I can recommend using LINQPad and writing some similar code to what you want to patch or even copy/paste that code into it. Then you add some dummy classes or even the original references to make that code compiler (does not necessarily need to run correctly, just compile). Finally, you can show the IL for that code and make your changes to it to then show the new IL again to learn what differences there will be.

That is what your transpiler needs to do.

**Comment by LoganDark** [comment]
> It's not part of the functionality of Harmony to solve specific coding cases for you. There is a library that extends Harmony with useful function and this feature request is better served there.

Sorry, I guess I should have been more clear. This is a request for *documentation* / guidance. You already have documentation on how you need to use labels for jumps and such.

> As a general tip, I can recommend using LINQPad and writing some similar code to what you want to patch or even copy/paste that code into it. Then you add some dummy classes or even the original references to make that code compiler (does not necessarily need to run correctly, just compile). Finally, you can show the IL for that code and make your changes to it to then show the new IL again to learn what differences there will be.

> That is what your transpiler needs to do.

That's generally a good tip, but even if I know what I need to do, I don't know how to achieve it. Look here:

![image](https://user-images.githubusercontent.com/4723091/132077089-5988e169-a484-471b-99c1-8bb79aedd7df.png)

I need to add the new case to this instruction. However, when I have a CodeInstruction, I don't know how to access the cases or add a new one. Is it CodeInstruction.blocks? Or perhaps I have to cast the operand to something?

**Comment by LoganDark** [comment]
I'm just going to inject a conditional statement after the end of the switch
