### ISSUE TITLE
Publish StrongName package

### ISSUE THREAD

**Issue by pengweiqhca** [pardeike/Harmony#422]

**Comment by pardeike** [comment]
Why can’t you sign it yourself?

**Comment by pardeike** [comment]
Also, see https://stackoverflow.com/questions/5678068/should-open-source-libraries-be-digitally-signed

**Comment by pengweiqhca** [comment]
> Why can’t you sign it yourself?

First, I think it should maintain by author, not myself.
Secondly, if sign by myself, I need to sign every new version.

If have no StrongName, I need modify my project property `SignAssembly` from true to false.

**Comment by apobekiaris** [comment]
the lib offers compatibility with dynosaurs :) e.g. .net3.5, not so sure why this is needed. I would also be very happy with a netstandard2 version so I do not have to support this myself. 

I agree with the SO post however real world is not perfect u have to compromize for e.g. projects that use 3rd party comercial dependecies suffer when not all libs are not signed.

But in any case you can find a harmony signed version (4 months old) for netstandard2 at 
[Xpand.Pather](https://www.nuget.org/packages/Xpand.Patcher/) . I do not follow the Harmony releases as they come out but the package is used extensively from my framework.

**Comment by pardeike** [comment]
I will never sign it myself because as an open source project I don’t “own” the legal part of it (what if I quit and someone else takes over). And putting the private key into the repository defeats the purpose.

**Comment by jameswestgate** [comment]
"And putting the private key into the repository defeats the purpose."

The assembly cannot be loaded by other strongly signed assemblies. This creates a significant barrier to organisations who often have a existing product using strongly signed assemblies for various reasons and decisions outside the control of the developer. 

Signing the assembly with a key that was part of the source code would allow people to use this package without the significant overhead of having to resign any new releases and maintain documentation and an additional step in the build pipeline, without taking anything away from the current release.

Hopefully a helpfully insight, not a criticism.
