### ISSUE TITLE
FatalExecutionEngineError on invoked patched method (Stardew Valley)

### ISSUE THREAD

**Issue by b-b-blueberry** [pardeike/Harmony#423]
**Describe the bug**
When invoking some particular method targeted by `harmony.Patch()`; regardless of patch type (prefix/postfix), return type (bool/void), parameters, or contents; program runtime will end after the target method and all patches are invoked and have completed execution. When running with debugging, a `FatalExecutionEngineError` will be thrown. No error is printed to SMAPI logs in either case.

**To Reproduce**
1. The original method and its signature and class:
```cs
// StardewValley.Locations.CommunityCenter.cs
private Point getNotePosition(int area)
{
	return area switch
	{
		0 => new Point(14, 5), 
		2 => new Point(40, 10), 
		1 => new Point(14, 23), 
		3 => new Point(63, 14), 
		4 => new Point(55, 6), 
		5 => new Point(46, 11), 
		_ => Point.Zero, 
	};
}
```

2. The patch code:
```cs
// HarmonyPatchMod.ModEntry.cs
public override void Entry(IModHelper helper)
{
	string id = ModManifest.UniqueID;
	Harmony harmony = new Harmony(id: id);
	harmony.Patch(
		original: AccessTools.Method(typeof(CommunityCenter), "getNotePosition"),
		prefix: new HarmonyMethod(typeof(ModEntry), nameof(GetNotePosition_Patch)));
}
public static void GetNotePosition_Patch(
	CommunityCenter __instance,
	ref Point __result,
	int area)
{
	// No code required within the patch in order to cause fatal error
}
```

3. The output of the Harmony debug log:
SMAPI log, close enough?
Test 1: Only the fatal error occurred with no other effects:
https://smapi.io/log/621920486b874ac0957c1f7bd9a9d7f1
Test 2: Instance or member of target type `CommunityCenter` seems to have become null before the fatal error occurred:
https://smapi.io/log/25669fcfdc774075ab104f67a5a6ba79

4. The stacktrace or other errors:
While running with debugging, this method will cause a fatal error to crash Stardew Valley. When running without debugging, the program crashes anyway, with no error printed to the SMAPI log. I've been told this is at least known to the developer of SMAPI, and I've noticed other FatalExecutionEngineError issues on the tracker, though if the particular method or calling context is of note or use to you then this will have been worthwhile.
`Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x62044ee1, on thread 0x1d98. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'`

**Expected behavior**
Other instance and static methods with a similar return type (`valuetype [Microsoft.Xna.Framework]`), parameter list (`[int32]`), accessibility (`private`), and a similar body (switch expression of return calls including default case) have not yet caused similar issues, eg. `StardewValley.Locations.CommunityCenter.cs:getAreaBounds(int32 area)`, nor have other similar methods, eg. `StardewValley.Menus.Bundle.cs:getColorFromColorIndex(int32 color)`. Other than the `.maxstack` directive, there's even very little difference in the CIL between the three as far as I can tell.

**Screenshots / Code**
The full ModEntry.cs file running the tests used for the SMAPI log files above can be found here:
http://hastebin.com/uxosiwoceh.csharp
The solution containing the above code can be found here:
[HarmonyPatchMod (Solution).zip](https://github.com/pardeike/Harmony/files/7161239/HarmonyPatchMod.Solution.zip)
And the compiled HarmonyPatchMod can be found here:
[HarmonyPatchMod.zip](https://github.com/pardeike/Harmony/files/7161252/HarmonyPatchMod.zip)
The solution above contains SMAPI console commands to invoke each patch, using `bb.harmony.invoke <0~3>`.
Non-static methods require that the game have a save file loaded before invoking.

**Runtime environment:**
 - OS: Windows 7, 64bit
 - .NET version: 4.5.2
 - Harmony version: 2.1.0
 - Stardew Valley version: 1.5.4
 - SMAPI version: 3.12.6

If there's any further info needed, feel free to ask. Thanks!

**Comment by b-b-blueberry** [comment]
Test from a user in the public Stardew Valley 1.5.5 beta, running SMAPI 1.13.0-beta.20210915, migrated to .NET 5.0... runs WITHOUT debugging with no errors! Patches and target method are executed successfully and correct values are returned. Program does not crash, was not tested with a debugger attached.
https://smapi.io/log/1ceb47a1d5de4020abe23d9d690d504b

**Comment by pardeike** [comment]
I assume that the debugger cannot handle the unexpected flow redirection of a patched method.
