### ISSUE TITLE
InvalidProgramException: 公共语言运行时检测到无效的程序。

### ISSUE THREAD

**Issue by cbwang505** [pardeike/Harmony#434]
ystem.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=调用的目标发生了异常。
  Source=mscorlib
  StackTrace:
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetMethodHandle(MethodBase method)
   在 MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetIdentifiable(MethodBase method)
   在 MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetIdentifiable(MethodBase method)
   在 MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.Pin(MethodBase method)
   在 MonoMod.RuntimeDetour.DetourHelper.Pin[T](T method)
   在 HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions) 在 E:\git\MyActiveX\HookS7\Harmony-master\Harmony\Internal\MethodPatcher.cs 中: 第 221 行
   在 HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) 在 E:\git\MyActiveX\HookS7\Harmony-master\Harmony\Internal\PatchFunctions.cs 中: 第 37 行
   在 HarmonyLib.PatchProcessor.Patch() 在 E:\git\MyActiveX\HookS7\Harmony-master\Harmony\Public\PatchProcessor.cs 中: 第 148 行
   在 HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer) 在 E:\git\MyActiveX\HookS7\Harmony-master\Harmony\Public\Harmony.cs 中: 第 134 行
   在 FakeHook.FakeHookTest.Hook() 在 E:\git\MyActiveX\HookS7\Harmony-master\FakeHook\FakeHookTest.cs 中: 第 33 行
   在 FakeKZT.Program.Main(String[] args) 在 E:\git\MyActiveX\HookS7\Harmony-master\FakeKZT\Program.cs 中: 第 16 行

内部异常 1:
InvalidProgramException: 公共语言运行时检测到无效的程序。

**Comment by pardeike** [comment]
I need more info

**Comment by pardeike** [comment]
Too little information. Closing it.
