### ISSUE TITLE
(Question) Transpiler - How to remove if check block, and replace function call with return

### ISSUE THREAD

**Issue by FiftyTifty** [pardeike/Harmony#435]
Background info: Have some basic experience with modifying assembly instructions, have made plenty of basic Lua, Delphi, and CSharp projects.

I'm patching a class, which has a bunch of if checks, and function calls. In particular, there's one if check block I want to remove entirely, or at least, remove the function call when the if check passes. Removing the entire if check is ideal, as it's constantly ran. Here is the pastebin of the instructions and their neighbours: https://pastebin.com/raw/TLhgErCn

Using a postfix/prefix/what have you, is not usable, as they utterly destroy performance when I patched them that way.

The specific CSharp code is: 

`	if (_world.worldTime >= this.respawnTime)
	{
		this.Reset();
	}`
	
How do I remove the instructions, and update any necessary addresses to keep the rest of the code functioning? Failing that, how do I replace `this.reset();` with a `return;`? I see that the stack is being modified with instruction 31, and by instruction 33. What's the approach here?

**Comment by pardeike** [comment]
Using GitHub Issues for support questions is not very ideal. I recommend using the official discord server. 

Other than that I strongly suggest to get the free LINQPad application that lets you write dummy code and see the IL without the need to create a full project. Fake all the dependencies besides the code you want to transpile and compare it with and without your changes.

**Comment by FiftyTifty** [comment]
The problem with Discord, is that it's a chatroom. It's awful for collection information, and searching for information. I'll ask on there though, thanks for the heads up.

**Comment by pardeike** [comment]
The advantage is that there is a large community (1600+ members) from all kind of time zones that can answer your questions. It also allows me to focus my answers on a specific channel. Issues on GitHub are mainly for potential bugs and stuff related to the source code of the project.
