### ISSUE TITLE
How to patch method of abstract class

### ISSUE THREAD

**Issue by diptisheth** [pardeike/Harmony#441]
I'm trying to apply patch to a method belonging to abstract class. Neither any patch is applied nor any error is shown. 

**To Reproduce**
I'm using `MethodBase TargetMethod()` for patching as it is generic method. 

Following is the code I tried : 
```
        static MethodBase TargetMethod()
        {
            Console.WriteLine ("In TargetMethod");
            return AccessTools.Method(typeof(foo), "bar", new[] { typeof(Request), typeof(int)}).MakeGenericMethod(new[] { typeof(TResponse)});             
        }

        static void Prefix(foo __instance, Request request, int  options)
        {
            Console.WriteLine ($" In Prefix for bar ");            
        }
```

And this is the abstract class :   
          
                  public abstract class foo : IDisposable
                  {
                       protected System.Threading.Tasks.Task<TResponse> bar<TResponse>(Request request,  Int options)            
                            where TResponse : ServiceResponse, new()
                       {
                              ThrowIfDisposed();                            
                               //returns some response
                        }
                  }

I've previously used harmony patch and it worked fine for other public classes. But , not working in this case.
Can anyone please guide me how to patch abstract class?

Thanks,
Dipti S

**Comment by pardeike** [comment]
Abstract methods patch just like normal methods. However you need to be aware that in case a method is overwritten you need to patch the overwriting method as well (unless it’s calling base). 

Generic methods are a different kind of problem. Generics are always hard to patch because of how the runtime implements and dispatches control to them. This can only be answered when you know the runtime version and the hardware that is used. 

Finally if the original method is too small then inlining might render your patch unused.

**Comment by diptisheth** [comment]
Thanks for the quick response ! 

Want to share one more thing. In this case, method is not getting overwritten. It is being called from derived class. 
Any other way to patch ?

**Comment by pardeike** [comment]
No, unless something else is wrong (try `[HarmonyDebug]` to verify) this is as good as it gets.

**Comment by diptisheth** [comment]
Hey .. thanks for the pointer. 

Started looking at logs. Getting this at the very beginning : 
**AccessTools.TypeByName: Could not find type named System.Runtime.InteropServices.RuntimeInformation**

**Comment by pardeike** [comment]
Then your runtime has no such class loaded. Either not yet because you are patching too early or because your runtime does not have those libs implemented.

**Comment by diptisheth** [comment]
Hey.. sorry for late response . Fixed issues with System.Runtime.InteropServices.RuntimeInformation library, still not able to patch. Logs show no error . I'm not able to understand why it is not patching particular method.
