### ISSUE TITLE
Patching iterator methods

### ISSUE THREAD

**Issue by Strdate** [pardeike/Harmony#443]
When patching iterator methods (containing yield keyword), all postfixes and finalizers run before the body of the method is actually executed. I wouldn't consider it a bug because under the hood the method really only returns the iterator and the code itself is somewhere else, but it prevents me from patching such methods with postfixes and finalizers.

I've created a simple example here - https://github.com/Strdate/HarmonyIteratorMethods

Is there a way to patch the actual body of the method? Alternatively, could this somehow be added as a feature to harmony?

**Comment by Strdate** [comment]
When I was using the [old detour library](https://github.com/sschoener/cities-skylines-detour), I handled this logic myself, as seen [here](https://github.com/Strdate/UndoMod/blob/a4b8f3726bfc6a87a467d5c34113e3a1659c51f0/UndoMod/Patches/BuildingToolPatch.cs#L55). Just after obtaining the original method in the patch (line 55), I created an async task and executed the body. Then at the bottom of the patch I mimicked behavior of the original method (lines 72,73).
The truth is it would be much harder to handle the logic in the patch, if the yield logic would be more complicated than this. This was just a simple method containing the `yield` keyword just twice at the bottom.

**Comment by pardeike** [comment]
There is no simple high level way to patch an iterator. The only supported ways to deal with it are 

- passthrough postfix
- creating a proxy iterator
- transpiling the MoveNext method

**Comment by Strdate** [comment]
Kian.zarrin pointed me to a few places where he deals with iterators in his C:S mods. I'll put the links here for future reference.
Util method:
https://github.com/kianzarrin/KianCommons/blob/148a28078f42e7e38f1e2ded8863a6404686f93e/KianCommons/Patches/TranspilerUtils.cs#L82
Usage:
https://github.com/kianzarrin/LoadOrder/blob/7665f13ce2ba60bc6f278b634a4f7ec2cd8fc130/LoadOrderMod/Patches/LoadLevel/LoadCustomContentPatch.cs#L12

**Comment by pardeike** [comment]
Transpiling the MoveNext method is kind of low level. You can do a lot with https://harmony.pardeike.net/articles/patching-postfix.html#pass-through-postfixes

**Comment by Strdate** [comment]
Thanks. I didn't know about this chapter in the documentation.
