### ISSUE TITLE
Unable to patch methods which DeclaringType is null

### ISSUE THREAD

**Issue by GeorgyPorgy** [pardeike/Harmony#445]
**Describe the bug**

When a target method is resolved via _Module.ResolveMethod(int Token)_ its _DeclaringType_ property is null and future attempt to patch the method triggers "System.NullReferenceException: Object reference not set to an instance of an object" at CreateDynamicMethod(MethodBase original, String suffix, Boolean debug)

In fact, the problem described is similar to that described in an already closed ticket.  : ["Unable to patch methods located inside the GlobalType (aka. <Module>) #235 "](https://github.com/pardeike/Harmony/issues/235)

**To Reproduce**
1. Resolve a method inside the GlobalType via  _Module.ResolveMethod (int Token)_ 
2. Apply patch to it ( Transpiler type in my case )
3. The last line in the Harmony debug log reports : ### Patch: static System.UInt32 MethodBlaBlaBla(System.Byte* arg1, System.Byte* arg2 , System.Int32 arg3, System.SByte* arg4, SomeStruct* arg5)
4. The target app errors log reports : 
ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
at HarmonyLib.MethodPatcher.CreateDynamicMethod(MethodBase original, String suffix, Boolean debug)
at HarmonyLib.MethodPatcher..ctor(MethodBase original, MethodBase source, List`1 prefixes, List`1 postfixes, List`1 transpilers, List`1 finalizers, Boolean debug)
at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
at HarmonyLib.PatchProcessor.Patch()

**Expected behavior**
The patch gets applied.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version 4.7.2
 - Harmony version  2.2.0.0

**Comment by pardeike** [comment]
Can you please verify with master that the issue is solved and reopen it if it isn't?

**Comment by pardeike** [comment]
Ping @GeorgyPorgy

**Comment by GeorgyPorgy** [comment]
I checked the behavior with the new changes and it seems some of the problems have already been fixed, but the patching has not yet ended successfully. 
Patching work finished with following error : _System.InvalidCastException: Unable to cast object of type 'ModifierType' to type 'System.Type'_.

The last line in the Harmony debug log reports : 
_### Replacement: static System.UInt32 GLOBALTYPE::GLOBALTYPE.MethodBlaBlaBla(System.Byte* arg1, ...._ 

while in the application log the messages list is as follows : 
_ERROR - System.InvalidCastException: Unable to cast object of type 'ModifierType' to type 'System.Type'.
   at HarmonyLib.InlineSignatureParser.<ImportCallSite>g__ReadTypeSignature|0_4(<>c__DisplayClass0_0& )
   at HarmonyLib.InlineSignatureParser.<ImportCallSite>g__ReadMethodSignature|0_0(InlineSignature method, <>c__DisplayClass0_0& )
   at HarmonyLib.InlineSignatureParser.ImportCallSite(Module moduleFrom, Byte[] data)
   at HarmonyLib.MethodBodyReader.ReadOperand(ILInstruction instruction)
   at HarmonyLib.MethodBodyReader.ReadInstructions()
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()_


Runtime environment :

-     OS: Windows 10, 64bit
-     .NET version 4.7.2
-     Harmony version 2.2.0.0-master branch

**Comment by pardeike** [comment]
Right now, I can only guess the problem because I have no idea how to write a test for such a method. If you know a way to reference such a method in a test please let me know.

**Comment by pardeike** [comment]
Also the stacktrace indicates that your original method has some very unusual IL codes that trigger the InlineSignature parser. Could you tell me more about your original method and maybe list it’s IL code. Parsing inline IL is still new and not much tested either and has nothing to do with the method being without type.

**Comment by pardeike** [comment]
On further inspection, the stacktrace isn’t helpful because there are several casts to `Type` that could fail so if you could be so kind to make your debugger stop at the exception and maybe give us some overview of what bytes the reader is reading, then me and @0x0ade who wrote the code can help you better.

**Comment by GeorgyPorgy** [comment]
Thanks for your efforts, Andreas.

The method IL code can be seen at the link below : 
https://drive.google.com/file/d/1Jq3teFou0PC4ZW0jnGvxcAaMZopZGJYr/view?usp=sharing

**Comment by pardeike** [comment]
At this point it is unclear if it is at all possible to create the correct result from this calli due to my possible limitations in the c# reflection api. 

I spoke with @0x0ade and it looks like there might be a very convoluted way to support this but at this point it’s unclear if and who could implement this. It’s a rather difficult topic.

**Comment by GeorgyPorgy** [comment]
Hello Andreas, 

https://www.codeproject.com/Articles/1244372/Reflecting-Within-a-Method-Body
section 'InlineSig'

Would this article help us ?  

regards

**Comment by pardeike** [comment]
That article just shows the basics. Our code here handles this case already: <https://github.com/pardeike/Harmony/blob/3c4cd7fdea35258f7622fe7c4565758f705d1e60/Harmony/Internal/MethodCopier.cs#L381>

It’s the parser that fails the case because it is more complicated than the article suggests.
