### ISSUE TITLE
Need help in transpilers !

### ISSUE THREAD

**Issue by diptisheth** [pardeike/Harmony#448]
Hi,

This is my code file : 
                    
             
              namespace harmony_test
              {
                  class Program
                  {
                      static void Main(string[] args)
                      {
                          Harmony.DEBUG = true;
                          var harmony = new Harmony("co.test.patch");
                          Assembly asm = Assembly.GetExecutingAssembly();
                          string path = System.IO.Path.GetDirectoryName(asm.Location);
                          string[] files = System.IO.Directory.GetFiles(path, "*.dll");
                          foreach(string file in files){
                              Assembly current_Asm = Assembly.LoadFile(file);
                              harmony.PatchAll(current_Asm);
                          }              
                          CreateProxy();
                      }
              
                     public static void CreateProxy(){
                          Console.WriteLine("in create proxy");
                          AmazonS3Client client = new AmazonS3Client();           
                      }
                  }
              }

This is transpiler code :
                   
                   namespace harmony_test
                   {
                      [HarmonyPatch(typeof(Program))]
                      [HarmonyPatch("CreateProxy")]                
                      public class Patch
                      {
                          public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions, ILGenerator generator, MethodBase original)
                          {            
                              List<CodeInstruction> instructionList = instructions.ToList();
                  
                              for (int i = 0; i < instructionList.Count; i++)
                              {
                                  if (instructionList[i].opcode == System.Reflection.Emit.OpCodes.Ldstr)
                                  {
                                      instructionList[i].operand = "updated text!!";
                                  }                
                              }           
                              for (int i = 0; i < instructionList.Count; i++)
                              {
                                  Console.WriteLine("updated instructionList::" + instructionList[i]);
                              }            
                              return instructionList.AsEnumerable();
                          }
                      }
                  }

When I run this code and execute `CreateProxy();` from `Main()` method, it doesn't print updated text that I've patched through transpiler. 
These are my logs from `harmoy.log.txt` :
                                                                  
                                  ### Harmony id=co.test.patch, version=2.1.1.0, location=/harmony-test/bin/Debug/netcoreapp3.1/0Harmony.dll, env/clr=3.1.13, platform=Unix, ptrsize:runtime/env=8/Bits64, Linux
                                  ### Started from static System.Void harmony_test.Program::Main(System.String[] args), location /harmony-test/bin/Debug/netcoreapp3.1/harmony-test.dll
                                  ### At 2022-01-19 11.08.29
                                  ### Patch: static System.Void harmony_test.Program::CreateProxy()
                                  ### Replacement: static System.Void harmony_test.Program::harmony_test.Program.CreateProxy_Patch0()
                                  IL_0000: Local var 0: Amazon.S3.AmazonS3Client
                                  IL_0000: // start original
                                  IL_0000: nop
                                  IL_0001: ldstr      "updated text!!"
                                  IL_0006: call       static System.Void System.Console::WriteLine(System.String value)
                                  IL_000B: nop
                                  IL_000C: newobj     System.Void Amazon.S3.AmazonS3Client::.ctor()
                                  IL_0011: stloc.0
                                  IL_0012: // end original
                                  IL_0012: ret
                                  DONE

It seems that instruction is being updated in log file, but when I call that method explicitly, my changes are not reflected. 

This is the output that I get printed on console : 
                         
                          updated instructionList::nop NULL
                          updated instructionList::ldstr "updated text!!"
                          updated instructionList::call static System.Void System.Console::WriteLine(System.String value)
                          updated instructionList::nop NULL
                          updated instructionList::newobj System.Void Amazon.S3.AmazonS3Client::.ctor()
                          updated instructionList::stloc.0 NULL
                          updated instructionList::ret NULL
                          in create proxy

Please help in pointing what I'm doing wrong here.

Thanks

**Comment by pardeike** [comment]
Most likely your CreateProxy method is being inlined. Your can verify if this is the case by adding

```
[MethodImpl(MethodImplOptions.NoInlining)]
public static void CreateProxy(){
}
```

**Comment by diptisheth** [comment]
Added inlining attribute, but same result .
Can you please share some working example of transpiler , how it is being executed after method is being transpiled ?

**Comment by pardeike** [comment]
Your example looks correct and logs the correct thing. The “DONE” in the log and the fact that it does not throw an exception all point to the fact that it has applied the transpiler correctly. 

Running CreateProxy after PatchAll should execute the modified method. I don’t know why it does not.

**Comment by pardeike** [comment]
Here is the same example a bit shorter and it works for me:
```cs
void Main()
{
	var harmony = new Harmony("test");
	harmony.PatchAll();
	Program.CreateProxy();
}

[HarmonyPatch(typeof(Program), "CreateProxy")]
class Patch
{
	static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
	{
		var list = instructions.ToList();
		foreach(var code in list)
			if(code.opcode == OpCodes.Ldstr)
				code.operand = "updated text!!";
		return list.AsEnumerable();
	}
}

class Program
{
	public static void CreateProxy()
	{
		Console.WriteLine("in create proxy");
		AmazonS3Client client = new AmazonS3Client();
	}
}

// fake AmazonS3Client
class AmazonS3Client { }
```

**Comment by pardeike** [comment]
One thing I noticed is that in your original example, you are patching dll's you just loaded but the CreateProxy() method is in the same code (and not in any of the loaded dlls) and thus is not patched. I assume you do have a CreateProxy method in one of the loaded dlls but since you call your local one it might be the non-patched version.

**Comment by diptisheth** [comment]
May be you are right. I tried your code and it works. I think that's the only difference in mine and your code. Thanks for sharing working example as well as your input !!
