### ISSUE TITLE
Patch classes dynamically

### ISSUE THREAD

**Issue by diptisheth** [pardeike/Harmony#451]
Hi,

I'm trying to patch class dynamically under some assembly. My patch file looks as below 
                          
            using System;
            using System.Reflection;
            using Amazon.S3;
            using Amazon.S3.Model;
            using HarmonyLib;
            using System.Collections.Generic;
            using System.Linq;
            
            namespace aws_proxy_class_customer_function
            {
                [HarmonyPatch]
                public class AWSPatch 
                {
                    static IEnumerable<MethodBase> TargetMethods()
                    {
                        var meth = from m in typeof(Amazon.S3.AmazonS3Client).GetMethods()
                                        where m.ReturnType.ToString().Contains(".Model")
                                        select m;           
                        return meth.Cast<MethodBase>();
                    }        
            
                    public static void Prefix(MethodBase __originalMethod)
                    {
                        Console.WriteLine("\n In harmony prefix of class AmazonS3Client");              
                        Console.WriteLine($"apiname - {__originalMethod.Name}");                      
                    }
                }
            }
         
It works good . Even patch is applied when I call any of the methods from  AmazonS3Client. But, If I'm trying to patch it dynamically by passing class name as variable (as I want to patch some other classes from the same API) , but it doesn't work.

`Type s3Type = assembly.GetType(assemblyClassName);` where `assemblyClassName = AmazonS3Client`. When I use below, it doesn' work 

              var meth = from m in s3Type.GetMethods()
              where m.ReturnType.ToString().Contains(".Model")
              select m;

I checked log file too , can't see any error/exception there. Can you please guide me how to patch methods dynamically ?

Thanks,
Dipti Sheth

**Comment by pardeike** [comment]
Issues here on GitHub are mainly for bugs and feature requests. User support is done on the official Discord server.
