### ISSUE TITLE
Performance difference between Pre/Post fixes and transpilers?

### ISSUE THREAD

**Issue by gallickgunner** [pardeike/Harmony#453]
Hello pardeike, nice library you have here. I'm trying to make a mod for Bannerlord and want to understand properly the performance implication, if any, of a pre/post fix and the transpiler. I haven't found any discussion in the docs on this matter or perhaps I missed it.

Assuming that what I want to achieve can be done every approach (Transpiler, prefix, postfix) I'm comparing

1) Is transpiler always faster than the pre/post fix?

2) Which one is faster Prefix or Postfix?

3) Does skipping original increases performance when using prefixes. (at the cost of compatibility)?

4) If what I want to achieve can be done with all 3 approaches, which should I go with for maximum performance and compatibility?

5) Do prefixes (not skipping the original), postfixes and transpilers all provide the same compatibility? I still don't understand how multiple postfixes for the same method merge? If one changes the result, then the other one will surely overwrite it.

Thanks.

**Comment by pardeike** [comment]
Transpiler only is fastest. 
Adding prefix/postfix adds overhead of calling the method you defined as static (the patch method itself) which includes the usual IL to put arguments on the stack, a CALL and potentially handling the returned bool of a prefix to do an IL jump over the original’s IL. 

In summary: overhead of patching is minimal add includes an assembler jump instruction from the original assembler to the replacement methods assembler (generated by the JITer from the dynamic method that Harmony creates).

**Comment by pardeike** [comment]
Of course you get logical conflicts if multiple patches change state after each other. There is no way around this. If you want blue and I want red, one of us have to loose. Harmony manages to allow non-conflicting changes to be applied at the same time (which ordinary hooking won’t do).

**Comment by pardeike** [comment]
Discussions about how Harmony works are better done in the official Discord. Using GitHub Issues is for bugs and feature requests.
