### ISSUE TITLE
Replacing function's argument type with object doesn't work

### ISSUE THREAD

**Issue by Geecko16** [pardeike/Harmony#454]
So, i'm trying to make a plugin that doesn't reference any of game's DLLs and loads them during runtime instead and then just gains access to whatever it needs using reflection. I do it to reuse it in any other game without recompilation. Problem is: when i patch some function function, it seems that arguments' type should always match original one, which is impossible in my case. 
For example, if original method is like that:
```c#
void somefunc(SomeType t)
{ 
    ...
}
```
And my patch is like that:
```c#
bool somefunc_prefix(ref object t)
{
    t = Activator.CreateInstance(SomeAssembly.GetType("SomeType"), somevalue);
    ...;
    return false;
}
```
Will throw NullReferenceException from *inside* of patch, but variable itself seems to be fine, because i tried printing it and it displays exactly what it was supposed to. Referencing assembly that has this type inside of it makes it stop to throw exception, but, as i said, i'd like to avoid directly referencing it. What might cause an exception? Also apologize if i described my problem poorly, my lack of English knowledge makes it hard for me to explain certain things sometimes.

**Comment by Geecko16** [comment]
For example, if original method is like that:
``
void somefunc(SomeType t)
{
    ...
}
``
And my patch is like that:
``
bool somefunc_prefix(object t)
{
    //do something with t
    ...
    return false;
}
``
It won't work.

**Comment by pardeike** [comment]
Which of the following overloads are you using inside your code?
https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netframework-2.0

If adding the reference to the dll fixes the problem but loading it at runtime is problematic, you might want to check how you resolve types when loading extra dlls. Maybe you need to write an assembly resolver: https://docs.microsoft.com/en-us/dotnet/standard/assembly/resolve-loads

**Comment by Geecko16** [comment]
> Which of the following overloads are you using inside your code? https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netframework-2.0
> 
> If adding the reference to the dll fixes the problem but loading it at runtime is problematic, you might want to check how you resolve types when loading extra dlls. Maybe you need to write an assembly resolver: https://docs.microsoft.com/en-us/dotnet/standard/assembly/resolve-loads

I'm using this overload:
```c#
public static object CreateInstance (Type type, params object[] args);
```

Also i'm completely sure that DLLs are loading fine, i'm always checking if assembly i've loaded is null. Also i'm patching multiple methods and all of them are working fine except this one.

**Comment by pardeike** [comment]
I am sure your dll loading works fine. What I said was that you don’t resolve the types in them correctly. Depending on how you load assemblies you are responsible for resolving. 

The NRE probably comes from SomeAssembly.GetType("SomeType") returning null but without more details I can only guess.

**Comment by pardeike** [comment]
Do you have a full stacktrace of the exception?

**Comment by Geecko16** [comment]
Well, i'll also tell what exactly i'm doing then, because from stacktrace it's already obvious. I'm cracking games, i'm doing it just for myself just for fun and i'm probably not going to distribute it. All games i'm cracking have been paid for or received by any other legitimate way(giveaways, etc.). Also sorry for taking that much time to answer.
Here's stacktrace:
```
NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Steamworks.SteamApps.Steamworks.SteamApps.BGetDLCDataByIndex_Patch1 (int,Steamworks.AppId_t&,bool&,string&,int) <0x00094>
SteamSocial.Update () <0x0017e>
SocialManager.Update () <0x0003c>
```

**Comment by pardeike** [comment]
Still not related to Harmony. You need to understand type resolving when loading assembly.

**Comment by Geecko16** [comment]
Oh, i see. Thanks for answering and for pointing in right direction.
