### ISSUE TITLE
Request: Function like postfix, but for Thrown Exceptions

### ISSUE THREAD

**Issue by FrodoOf9Fingers** [pardeike/Harmony#46]
I know there's been some discussion about dealing with exception code within code being modified, I'm not sure if this is the same or different.

We have prefix, transpiler, and postfix. Can we get a function for catching thrown exceptions? I would imagine that once the exception is hijacked, that we'd also want the ability to send it on its merry way to where it was originally going.

**Comment by pardeike** [comment]
This is twofold:

1) I am working on making Harmony preserve exception handling. This includes of course the ability to edit exception handling inside a transpiler.

2) You can always have your own exception handling inside your prefix/postfixes since these are just executed as methods (obvious but I state it here just to be complete).

So in the end, as you will be able to control exception blocks from within a transpiler, you will be able to add it to wrap the existing contents of a method with your own try-catch-finally handler and that will give you what I think you want.

**Comment by FrodoOf9Fingers** [comment]
While it would be possible to accomplish this using a transpiler, I prefer to try and stay away from CIL as much as possible for maintainability reasons. In my use case, I'm just trying to ensure that resources are returned properly. I could call the target method from a prefix, wrap it inside an exception, and then return false, but I fell that is bad practice for working with other mods on the same function.

I would like to have a prefix grab the resource, return true, and have the postfix return the resource. But uncaught exceptions fly past post-fixes, hence the idea of grabbing those exceptions with a [HarmonyExceptionCatch] annotation. 

(The resource in my specific case is a lock on the object).

**Comment by pardeike** [comment]
Low prio but I will look into adding this when I run out of issues.

**Comment by pardeike** [comment]
Update: this will most likely not make it into v1.1.1 but I will start working on it for the next version.

**Comment by alexb5dh** [comment]
Any update on this? 1.2 is out but no news for exception handling.

Also, if someone has a generic solution for try-catch via transpiling I would be grateful for it as my knowledge of MSIL is quite limited.

**Comment by pardeike** [comment]
I am working on a lot of bug fixes and improvements in 2.0. The reason this hasn't made it into a feature yet is that it's rather tricky to implement right. My main concern isn't just to make sure that Postfixes are called but also what to do with the exception result. Maybe if you add a new argument to your Postfix like

```cs
static void Postfix(Foo foo, SomeType __result, Exception __exception) { }
```

you will get the postfix called always as it will wrap the original in a try/catch and deliver the result to `__exception` (or `null` if no exception was thrown).

**Comment by pardeike** [comment]
New proposal:
```cs
var __result = default(T);
var __exception = null;
var __state = default(T);
try
{
    // normal harmony logic start
    Prefix(__instance. ref __state);
    if (Prefix(ref __result))
    {
        __result = Original();
    }
    Postfix(__state, __result);
    return __result;
    // normal harmony logic end
}
catch(e)
{
    __exception = e;
}
finally
{
    Finally(__result, __state);
}
```

**Comment by pardeike** [comment]
After a long discussion on my discord, this is the new approach:
```cs
bool called = false;
try
{
}
catch (Exception ex)
{
   bool rethrow = InvokeFinalizers(ex);
   called = true;
   if (rethrow)
      throw;
}
finally
{
   if (!called)
      InvokeFinalizers();
}
```

**Comment by pardeike** [comment]
I started working on https://github.com/pardeike/Harmony/tree/add-finally in case anybody wants to follow the progress. More details on the design can be found in this gist: https://gist.github.com/pardeike/db627ffbb3c004a7ae01850dbc7517cd

**Comment by pardeike** [comment]
The question is if it's enough to call them inside `finally` as described in the gist.

**Comment by pardeike** [comment]
Also, the gist has no try-catch around each Finalizer() call. If a finaliser throws, it has the same effect as a `void` finaliser (non, execution goes to next finalizer without any change).

**Comment by pardeike** [comment]
Proposed structure:

```cs
using System;

public static class Program {
    public static void Main() {
        var s = Run();
        Console.WriteLine("RESULT = " + s);
    }
    
    public static string Run() {
        Exception ex = null;
        string result = default;
        
        // main try-catch for original content + prefixes/postfixes
        try {
            bool runOriginal = true;
            
            // all prefixes
            if (runOriginal)
                Prefix1(ref result);
            if (runOriginal)
                runOriginal = Prefix2(ref result);
            
            // original
            if (runOriginal)
            	result = Original();
            
            // all postfixes
            Postfix1(ref result);
            result = Postfix2(result);
            
            // done
            return result;
            
        } catch (Exception e) {
            // save the exception
            ex = e;
            // this return is required for correct syntax
            return result;
        }
        finally {
            
            var stackinfo = GetStackInfo(ex);
            
            // all finalizers
            try { Finalizer1(ex); } catch(Exception e)
            {
                // log errors in finalizer
                Console.WriteLine("finalizer1: " + e);
            }
            try { ex = Finalizer2(ex); } catch(Exception e)
            {
                // log errors in finalizer
                Console.WriteLine("finalizer2: " + e);
            }
            
            // re-throw (also apply stackinfo to ex to keep stack)
            if (ex != null)
            {
                ApplyStackInfo(ex, stackinfo);
                throw ex;
            }
        }
    }
    
    public static string Original() {
        return "Hello World";
    }
    
    public static void Prefix1(ref String __result) {
        Console.WriteLine("prefix1: from " + __result + " to Bar"); 
        __result = "Bar";
    }
    
    public static bool Prefix2(ref String __result) {
        Console.WriteLine("prefix2: from " + __result + " to Foo"); 
        __result = null;//"Foo";
        return false;
    }
    
    public static bool Postfix1(ref String __result) {
        if (__result != null)
            __result += "!";
        return true;
    }
    
    public static string Postfix2(String result) {
        return result.ToUpper();
    }
    
    public static void Finalizer1(Exception ex) {
        Console.WriteLine("ex1: " + ex);
        var c = ex.Message[200];
    }
    
    public static Exception Finalizer2(Exception ex) {
        Console.WriteLine("ex2: " + (ex == null ? "null" : ""+ex));
        return new ArgumentException("arg");
    }
    
    public static string GetStackInfo(Exception ex) { return ""; }
    public static void ApplyStackInfo(Exception ex, string stackinfo) { }
}
```

**Comment by Pathoschild** [comment]
Being able to change the method's return value when it throws an exception would be really useful.

(For example, [SMAPI](https://github.com/Pathoschild/SMAPI) prevents a crash when mods add invalid cutscene data. It does that by prefixing the call to `checkEventPrecondition`, calling `__originalMethod` within a try..catch block with a static flag to avoid a patch loop, and handling the error in the outer call if an exception is thrown. See [code](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI/Patches/CheckEventPreconditionErrorPatch.cs).)

So something like a postfix for exceptions would be great:
```cs
harmony.Patch(
   original: AccessTools.Method(typeof(GameLocation), "checkEventPrecondition"),
   onException: new HarmonyMethod(this.GetType(), nameof(OnException))
);
```
```cs
public static void OnException(ref Exception __exception, ref int __result)
{
   __exception = null; // suppress exception
   __result = -1; // set new return value
}
```
(Could maybe just call the postfix methods if they have an `__exception` argument, instead of having a separate onException?)

**Comment by pardeike** [comment]
The problem with this is that I want the Finalizers to be run in the finally block and there you cannot manipulate the result anymore.

Moving them to the catch block removes the ability to have them as cleanup handlers for resources and I rather not want to introduce two new patch types.

**Comment by pardeike** [comment]
The only (brute force) solution would be to run the list of finalizers in both: the catch block **and** the finally block. Add a flag to the first part that skips the second part and it would work. Except that the finalizers referencing the result variable would not be able to change the result in the second case. That might be solved by running them in the try block after the postfixes but at this point I am sure we are missing a case where they are ran in finally only and you would have a hard time identifying that case inside the finalizer.

**Comment by pardeike** [comment]
New approach:
Gist: https://gist.github.com/pardeike/d75d609b842d793b0e4e938d86ed8e27
SharpLab: https://sharplab.io/#gist:d75d609b842d793b0e4e938d86ed8e27

**Comment by Pathoschild** [comment]
Looks good to me! Seems like that approach covers replacing/suppressing exceptions, resource cleanup, and changing the return value.

**Comment by pardeike** [comment]
I want a clear indication that a finalizer wishes to manipulate the exception. Returning it will make this clearer as it can be used at patch time to see if any finalizer changes the original exception and thus it could simply be rethrown if not changed. It also allows for a more intuitive suppression of the original exception by returning null. Finalizers are not like normal patches and thus don’t have to match prefixes and postfixes exactly. Postfixes already have pass-through mode and in that sense, finalizers can act the same.

**Comment by Pathoschild** [comment]
Makes sense. Looking forward to this!

**Comment by pardeike** [comment]
More refinements (same gist): https://gist.github.com/pardeike/d75d609b842d793b0e4e938d86ed8e27

**Comment by pardeike** [comment]
The branch [add-finally](/pardeike/Harmony/tree/add-finally) has a working implementation for the upcoming 2.0. Please give it a try and get back with feedback. It's based on the design of [this gist](https://gist.github.com/pardeike/d75d609b842d793b0e4e938d86ed8e27).

**Comment by lust4life** [comment]
@pardeike  hi, is there any 2.0 prerelease version on nuget that we can give it a try?

**Comment by pardeike** [comment]
Not yet. Simply build from master and use that instead.

**Comment by lust4life** [comment]
got it, thanks

**Comment by pardeike** [comment]
I close this for now. Open new Issues if necessary.
