### ISSUE TITLE
Harmony patch report?

### ISSUE THREAD

**Issue by Vectorial1024** [pardeike/Harmony#463]
**Is your feature request related to a problem? Please describe.**
It is awkward to admit, but currently there seems to have no easy way for me to verify whether my patch is completed. For example, I may have marked `HarmonyPrepare`, but at the same time forgot to mark a corresponding `HarmonyPrefix`, and so the intended `HarmonyPrefix` patch was never executed.

I could only launch the program and test whether the behavior of my intended patch can be shown.

**Describe the solution you'd like**
Having some sort of applied patch printout would be nice. Either a string printout, list printout, or a file printout works.

**Describe alternatives you've considered**
Not too familiar with HarmonyLib to find alternatives...

**Additional context**
I currently use the style of `Harmony.PatchAll()` to apply patches.

**Comment by pardeike** [comment]
Use `Harmony.DEBUG` or `[HarmonyDebug]` for that purpose. Log file will be related at your Desktop and is called `harmony.log.txt`

**Comment by Vectorial1024** [comment]
Thank you for the answer!
