### ISSUE TITLE
Is it possible to patch all methods of a Specified class?

### ISSUE THREAD

**Issue by chinasmu** [pardeike/Harmony#468]
If a class has tens of methods and I just want to patch all the methods to just check out the  execution sequence.
And all the pathes Prefix and Postfix are same like below:
`static void Prefix()
	{
		// write log the Method "name" beigin
	}

	[HarmonyPostfix]
	static void MyOwnName()
	{
		// write log the Method "name" end
	}`
I think this function would be helpful when devirtualizing some codes protected by virtualization.
THANKS

**Comment by pardeike** [comment]
1) use TargetMethods() inside the class that contains your prefix/postfix to return an enumeration of members you want to patch. 

2) Add `MethodBase __originalMethod` to your patches to get the name of the patched method

**Comment by mitchcapper** [comment]
I use a set of helpers for exactly this.  This has some manual patching code but would not be that different with thee attribute TargetMethods mentioned.
```csharp
private static void PatchMethodToGetPreInfo(String typeColonName) {
	PatchMethodToGetPreInfo(AccessTools.Method(typeColonName));
}
private static void PatchMethodToGetPreInfo(MethodInfo orig) {
	try {

		var prefix = GetMethod(() => InfoPrePatchFunc);
		harmony.Patch(original: orig, prefix: prefix);
		FileLog.Log($"DebugInfo patched method: {orig.Name} on class: {orig.DeclaringType}");
	} catch (Exception ex) {
		FileLog.Log($"Failed to patch: {orig.Name} due to: {ex.Message}");
	}
}
private static void InfoPrePatchFunc(object __instance, object[] __args, MethodBase __originalMethod) {
	FileLog.Log($"InfoPrePatchFunc called before method {__originalMethod.DeclaringType}:{__originalMethod.Name} on instance of class type: {__instance?.GetType()} it is taking an arg array: {String.Join(", ", __args.Select(a => $"{a}({a?.GetType()})"))}");
}
```

And to call it is as easy as `PatchMethodToGetPreInfo("Some.Class:Method");` or
and if you want to get really crazy you can use `typeof(SomeClass).GetMethods()`  to get all the methods and programmatically determine at runtime which you want to hook and call `PatchMethodToGetPreInfo` with `(MethodInfo);`
