### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by chenguaguaa** [pardeike/Harmony#469]
**Describe the bug**
An error occurred while using the in-game movie footage，In the report, let me contact you here
[error.log](https://github.com/pardeike/Harmony/files/8472508/error.log)
[output_log.txt](https://github.com/pardeike/Harmony/files/8472509/output_log.txt)

**To Reproduce**
1. The original method and its signature and class
2. The patch code
3. The output of the Harmony debug log
4. The stacktrace or other errors

**Expected behavior**

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: [e.g. Windows 10, 64bit]
 - .NET version [e.g. 3.5]
 - Harmony version [e.g. 1.2.0.1]
- Name of game or host application [e.g. RimWorld]
Windows 10, 64bit
**Additional context**

**Comment by pardeike** [comment]
And how is this related to Harmony?

**Comment by chenguaguaa** [comment]
Harmony is Harmony 2.2-0 (Mod Dependency)

**Comment by pardeike** [comment]
That screenshot does not show how Harmony fails in any way. I can’t guess your issue, sorry

**Comment by chenguaguaa** [comment]
ok，thank you
