### ISSUE TITLE
TargetMethod Documentation incorrect?

### ISSUE THREAD

**Issue by FrodoOf9Fingers** [pardeike/Harmony#47]
Your documented example for HarmonyTargetMethod uses MethodInfo:

static MethodInfo TargetMethod()
static MethodInfo TargetMethod(HarmonyInstance instance)
// or
[HarmonyTargetMethod]
static MethodInfo CalculateMethod(...)

Should it not be listed as return a MethodBase object? Allows for ConstructorInfo in addition to MethodInfo.

**Comment by pardeike** [comment]
Good catch

**Comment by pardeike** [comment]
Fixed
