### ISSUE TITLE
Patching a struct method that implements an interface

### ISSUE THREAD

**Issue by compasslg** [pardeike/Harmony#470]
I have a struct that implements an interface like below

```csharp
interface IGeneralAction{
    public void CheckValid(Character srcChar, Character targetChar);
    public void ApplyChanges(Character srcChar, Character targetChar);
}

public struct SomeAction : IGeneralAction{
    public void CheckValid(Character srcChar, Character targetChar){
        // Do something
    }

    public void ApplyChanges(Character srcChar, Character targetChar){
        // Do something else
    }
}
```
I'm using harmony (2.4.2) to patch the methd ApplyChanges in the struct. and when the other method CheckValid() is called, the program ends with "Fatal error. Internal CLR error. (0x80131506)"

If I change the struct to a class, it worked just fine.

**Comment by pardeike** [comment]
Harmony patches methods. Since interfaces only exist for the compiler, you cannot patch a thing that does not exist at runtime. 

Rule of thumb: everything that a decompiler shows as a method can be patched.

**Comment by compasslg** [comment]
@pardeike 
But the method is implemented by a struct, and decompiler (ILViewer in Rider) does show it as expected... not to mention changing the struct to class would work.
