### ISSUE TITLE
Elaborate on how to use Postfix in manual mode

### ISSUE THREAD

**Issue by shadow7412** [pardeike/Harmony#471]
[This example](https://github.com/pardeike/Harmony/blob/master/Harmony/Documentation/examples/intro_manual.cs?name=example) is shown in the documentation as an alternative to using attributes.

As the class I'm attempting to patch is internal, I don't think it's possible to use attributes as they require a Type which I'm unsure how to provide. So doing it this more dynamic way seemed like the way to go - except the Postfix method (and even the Prefix one) don't have arguments. This means no access to the class it's supposed to be patching, and no ability to manipulate the return value.

Could the examples here be elaborated on? At the moment both bodies just contains `// ...`. A more useful example would be to copy the same functionality as shown in the [attribute example](https://github.com/pardeike/Harmony/blob/master/Harmony/Documentation/examples/intro_annotations.cs).

**Comment by pardeike** [comment]
Choosing which way to patch (manual or annotations) has no influence on how you design your patches and what parameters they can have. 

Also, you can use TargetMethod() together with annotations on a class for cases that cannot be expressed by annotations.

**Comment by shadow7412** [comment]
In the attribute form the instance of the class and the result are exposed through arguments to the method.
Given that `HarmonyMethod` which wraps the patching methods in the manual mode example only allows methods without any arguments, how do you access them?

**Comment by pardeike** [comment]
Does it though?
```cs
var privType1 = AccessTools.TypeByName(“Fully.Qualified.SomeType”);
var privType2 = …;
var m = AccessTools(privType1, “ThatMethod”, new [] { typeof(FirstArgType), privType2 });
var hm = new HarmonyMethod(m);
```

**Comment by mitchcapper** [comment]
@shadow7412 I just submitted PR #472 which should make manual mode more straightforward.  the method above certainly works, as does just feeding BS values to the parameters (as the method itself is never called just used to get info).  #472 however will allow you to pass just the method.

**Comment by pardeike** [comment]
I usually use `default` for everything that is not ref. Out parameters can be done with `out var`

**Comment by shadow7412** [comment]
The function I'm trying to mock actually lacks parameters. It returns an instance of an internal class it instantiates - which I want to change some attributes on prior to it being passed to the original caller.

Both your example above and mitchcapper's PR seem like good ways to identify a method, but I'm still at a bit of a loss about how one accesses the return type in the postfix method (called MyPostfix in the documentation) when in the example it has no parameters.

**Comment by pardeike** [comment]
```can
static void MyPostfix(object __result)
{
    // use reflection or other techniques to edit content of __result
}
```

**Comment by shadow7412** [comment]
It's now working - thanks :)
