### ISSUE TITLE
Empty patch throws a NRE, executes, then crashes the game. In that order.

### ISSUE THREAD

**Issue by zkxs** [pardeike/Harmony#474]
## Describe the bug

An empty patch is somehow throwing a NullReferenceException, but then executes anyways. And the game then subsequently crashes, so the exception certainly appears to be going somewhere and causing trouble. I'm really confused as to what's going on here, as I've done plenty of other patching in this game without seeing anything like this.

## To Reproduce
1. The original method and its signature and class

   The method I'm trying to patch is `DynamicVariableSpace.ValueManager<object>.SetValue(object)`, which has this definition:
   ```cs
   public class ValueManager<T> {
       public void SetValue(T value)
       {
            this.lastValue = value;
            foreach (IDynamicVariable<T> dynamicVariable in this.values)
            {
                if (!dynamicVariable.IsRemoved)
                    dynamicVariable.DynamicValue = value;
            }
       }

       /* other methods and fields omitted to avoid throwing a wall of irrelevant code at you */
   }
   ```

   There's nothing crazy going on in the class that I'm aware of. No static constructor, no weird logic in the regular constructor, etc.
2. The patch code

   ```cs
   private static void PatchSomething(Harmony harmony)
   {
       Harmony.DEBUG = true;
       Type type = typeof(DynamicVariableSpace.ValueManager<object>);
       MethodInfo original = AccessTools.DeclaredMethod(type, "SetValue");
       MethodInfo patch = AccessTools.DeclaredMethod(typeof(NeosModTest), nameof(DoNothingPostfix));
       harmony.Patch(original, postfix: new HarmonyMethod(patch));
   }
   
   private static void DoNothingPostfix()
   {
       Warn($"DoNothingPostFix has run");
   }
   ```

   What's interesting is I see lines saying `DoNothingPostFix has run` in the game log, despite the NREs also occurring (and crashing the game!). I've also tested a completely empty postfix, and a completely transparent transpiler just to see if there's something weird going on with logging or postfixing and they both exhibit the same NRE behavior (minus the `DoNothingPostFix has run` log obviously).
3. [The output of the Harmony debug log](https://gist.github.com/zkxs/828fd9ef4bd2296593e12e55bc5c59f4)
4. The stacktrace or other errors

   ```
   System.NullReferenceException: Object reference not set to an instance of an object
     at (wrapper dynamic-method) FrooxEngine.DynamicVariableSpace+ValueManager`1[System.Object].FrooxEngine.   DynamicVariableSpace+ValueManager`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral,    PublicKeyToken=b77a5c561934e089]].SetValue_Patch0(FrooxEngine.DynamicVariableSpace/   ValueManager`1<object>,object)
     at FrooxEngine.DynamicVariableHandler`1[T].UpdateLinking (System.String variableName, System.Boolean    hasLocalValue) [0x0013e] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 
     at FrooxEngine.DynamicVariableBase`1[T].UpdateLinking () [0x0001d] in    <a6ff441fca7c4a97bc5b9dca720b524b>:0 
     at FrooxEngine.DynamicVariableBase`1[T].OnChanges () [0x00000] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 
     at FrooxEngine.ComponentBase`1[C].InternalRunApplyChanges (System.Int32 updateIndex) [0x00017] in    <a6ff441fca7c4a97bc5b9dca720b524b>:0 
     at FrooxEngine.UpdateManager.ProcessChange (FrooxEngine.IUpdatable updatable) [0x00024] in    <a6ff441fca7c4a97bc5b9dca720b524b>:0 
     at FrooxEngine.UpdateManager.RunQueue[T] (System.Collections.Generic.Queue`1[T] queue, System.Action`1   [T] action) [0x00009] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 
   ```

## Expected behavior
I expected `DoNothingPostFix has run` to show up in the game log, and no strange NREs to be thrown.

## Screenshots / Code
See the To Reproduce section? This part of the issue template seems redundant to me.

## Runtime environment
- OS: Windows 10, 64bit
- .NET version: 4.6.2
- Harmony version: 2.2.1.0 (specifically the release targeting net45)
- Name of game or host application: Neos VR

## Additional context
The fact that the NRE is originating from a `SetValue_Patch0` method, in combination with the empty patches makes me suspect that this is a Harmony bug, but I can't help but wonder if this is more #407 shenanigans?

It's also possible that the `ValueManager<T>` class has some assumptions about the type of `T` that I'm violating by throwing an `object` patch at it. It might be expecting only value types, but that doesn't seem to jive with where the stack trace is originating, so I'm not sure.

**Comment by zkxs** [comment]
My assumption was that `typeof(Foo<Bar>)` and `typeof(Foo<>).MakeGenericType(new Type[] { typeof(Bar) })` are equivalent, and after adding some extra debug logging it appears that my assumption is true. Here's the altered patch:

```cs
private static void PatchSomething(Harmony harmony)
{
    Harmony.DEBUG = true;

    Type testType = typeof(DynamicVariableSpace.ValueManager<object>);
    Type type = typeof(DynamicVariableSpace.ValueManager<>).MakeGenericType(new Type[] { typeof(object) });
    Debug($"testType == type // {testType == type}");

    MethodInfo original = AccessTools.DeclaredMethod(type, "SetValue");
    Debug($"original.IsGenericMethod // {original.IsGenericMethod}");
    Debug($"original.IsGenericMethodDefinition // {original.IsGenericMethodDefinition}");

    MethodInfo patch = AccessTools.DeclaredMethod(typeof(NeosModTest), nameof(DoNothingPostfix));

    harmony.Patch(original, postfix: new HarmonyMethod(patch));
    Debug($"Method [{type} :: {original}] patched!");
}

private static void DoNothingPostfix()
{
    Warn("DoNothingPostFix has run");
}
```

And here's the output of the new debug logs:
```
testType == type // True
original.IsGenericMethod // False
original.IsGenericMethodDefinition // False
```

**Comment by pardeike** [comment]
See, you are not using the correct method. You might with the type but without MakeGenericMethod it won’t give you the correct original method.

**Comment by zkxs** [comment]
I think I'm not understanding what you're saying...

The [MakeGenericMethod docs](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.makegenericmethod) say that if `methodInfo.IsGenericMethodDefinition` returns `false` then calling `methodInfo.MakeGenericMethod(...)` will throw an `InvalidOperationException`, so taking my `MethodInfo original` variable and calling `MakeGenericMethod(new Type[] { typeof(object) })` on it is guaranteed to throw the exception. But after thinking about it some more, maybe that's not what you were suggesting? I can think one other thing you might mean, which I've tried:

```cs
// get the generic type definition, and never close it
Type type = typeof(DynamicVariableSpace.ValueManager<>);
Debug($"type: {type}");

// get the generic method definition
MethodInfo genericOriginal = AccessTools.DeclaredMethod(type, "SetValue");
Debug($"genericOriginal: {genericOriginal}");
Debug($"genericOriginal.IsGenericMethod // {genericOriginal.IsGenericMethod}");
Debug($"genericOriginal.IsGenericMethodDefinition // {genericOriginal.IsGenericMethodDefinition}");

// close the generic method
MethodInfo original = genericOriginal.MakeGenericMethod(new Type[] { typeof(object) });
Debug($"original: {original}");
Debug($"original.IsGenericMethod // {original.IsGenericMethod}");
Debug($"original.IsGenericMethodDefinition // {original.IsGenericMethodDefinition}");

MethodInfo patch = AccessTools.DeclaredMethod(typeof(NeosModTest), nameof(DoNothingPostfix));
harmony.Patch(original, postfix: new HarmonyMethod(patch));
```
yields
```
type: FrooxEngine.DynamicVariableSpace+ValueManager`1[T]
genericOriginal: Void SetValue(T)
genericOriginal.IsGenericMethod // False
genericOriginal.IsGenericMethodDefinition // False
System.InvalidOperationException: not a generic method definition
  at System.Reflection.MonoMethod.MakeGenericMethod (System.Type[] methodInstantiation) [0x00016] in <9577ac7a62ef43179789031239ba8798>:0 
  at NeosModConfigurationExample.NeosModTest.PatchSomething (HarmonyLib.Harmony harmony) [0x00087] in <e2665854964a4919b91b52b060c2d7f3>:0 
  at NeosModConfigurationExample.NeosModTest.OnEngineInit () [0x0000a] in <e2665854964a4919b91b52b060c2d7f3>:0 
  at NeosModLoader.ModLoader.HookMod (NeosModLoader.LoadedNeosMod mod) [0x0006a] in <295df5e6e2a84adb8f4bbf86d43d96ff>:0 
```

So I guess I'm missing something here...

**Comment by pardeike** [comment]
Yeah, I see it now. The method is generic in a wider sense but only because the type is generic. 

This is clearly a problem with Harmony patching generics and you simply can’t do what you want.

**Comment by zkxs** [comment]
Oof, while I suspected that this might be where this issue would end up, I'd hoped that this wouldn't end up being another case of arcane .NET generic handling shenanigans. Regardless, thanks for confirming it. I appreciate your time!
