### ISSUE TITLE
[Help] How to modify the parameter modifier of a patched method?

### ISSUE THREAD

**Issue by ArjixWasTaken** [pardeike/Harmony#478]
I made a transpiler ~~(well, more like *stole*)~~ to replace the calls of a dll imported function with my own, but since my own function is in c# and not c++
I can not modify the original parameter, but just a copy of it

I want to change the parameter to be a ref so that it directly modifies the original array.

This is how the function looks like:
![image](https://user-images.githubusercontent.com/53124886/167956097-464de157-e472-4ebf-92d6-41cecd8d6133.png)

I basically redirect the call to my function with
![image](https://user-images.githubusercontent.com/53124886/167956174-36c8fa8c-739b-47fc-a639-cf1e0c1f73ce.png)

But if I add the `ref` modifier to my replacement method I get invalid IL.

The replacement method in question:
![image](https://user-images.githubusercontent.com/53124886/167956343-845bbd7b-0793-45dd-bb96-38e00129178c.png)

Any help would be appreciated, even just a confirmation that this is not possible.

**Comment by ArjixWasTaken** [comment]
If what I am asking for is impossible, but you know of a workaround then please do tell.
I am new to C# and this is all confusing to be honest.

**Comment by pardeike** [comment]
Unfortunately, that’s not possible.
