### ISSUE TITLE
Problems with inner struct

### ISSUE THREAD

**Issue by Daron0407** [pardeike/Harmony#479]
I'm trying to patch a method that returns a list of inner class object

structure of code looks like this:
```
class HarvestablePOIConfig{
   private List<HarvestablePOIParams> GenerateConfigs(){ ... }
   
   public struct HarvestablePOIParams { ... }

}

[HarmonyPatch(typeof(HarvestablePOIConfig), "GenerateConfigs"]
class patch {
   public static bool Prefix() { ... }
   public static void Postfix(ref List<HarvestablePOIParams> __result) { ... }
}
```

And I get exception message:
System.Collections.Generic.List`1<HarvestablePOIParams> HarvestablePOIConfig::GenerateConfigs() cannot be patched. Reason: The type initializer for 'HarvestablePOIConfig' threw an exception.

For the life of me I cannot figure out how to deal with this

**Comment by pardeike** [comment]
Please provide the full stacktrace as well as all the information on what Harmony version etc you are using. 

If you’re not a programmer then I would like to refer you to the official discord as Issues on GitHub are only for bugs or enhancements of Harmony.
