### ISSUE TITLE
MethodReplacer might not work

### ISSUE THREAD

**Issue by minhhungit** [pardeike/Harmony#480]
**Describe the bug**
I want to replace a method by a method

**To Reproduce**
Reproduce code

```csharp
using HarmonyLib;

namespace Sample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var harmony = new Harmony("com.example.patch");
            harmony.PatchAll();

            new OriginalCode().DoNothing();

            Console.WriteLine("Hello, World!");
        }
    }

    public class OriginalCode
    {
        public void DoNothing()
        {
            Console.WriteLine("original text");
        }
    }

    public class ReplaceCode
    {
        public void ReplaceDoNothing()
        {
            Console.WriteLine("new text");
        }
    }

    [HarmonyPatch(typeof(OriginalCode), nameof(OriginalCode.DoNothing))]
    class MyPatch
    {
        static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
        {
            var from = AccessTools.Method(typeof(OriginalCode), nameof(OriginalCode.DoNothing));
            var to = AccessTools.Method(typeof(ReplaceCode), nameof(ReplaceCode.ReplaceDoNothing));

            return Transpilers.MethodReplacer(instructions, from, to);
        }
    }
}
```

**Expected behavior**
I guess it should print out "new text", but nothing change

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version: 6, I also tried with .net framework 4.6.2
 - Harmony version 2.2.1

**Comment by pardeike** [comment]
That’s not how transpilers or method replacers work. The code above searches for all methods named “DoNothing” inside the transpiled code of the method DoNothing (since your annotations say so) and replace it with ReplaceDoNothing. 

Obviously the method DoNothing does not contain any calls to itself and therefore your code does not work as you expect it to work.

**Comment by minhhungit** [comment]
Thank you for spending time to explain it
