### ISSUE TITLE
How to hook interface implementing void?

### ISSUE THREAD

**Issue by makarhuyaker** [pardeike/Harmony#481]
![devenv_oBDJw8NuZU](https://user-images.githubusercontent.com/63492966/171971410-a5c113b7-b4ab-40d0-888e-77f54a2814db.png)
![devenv_ZD4keKAmFe](https://user-images.githubusercontent.com/63492966/171971460-69f7aa7c-e1d4-43b3-9aaf-600cf0c0adf9.png)

Patching exception in method null
ArgumentException: Undefined target method for patch method static System.Boolean Client.Patches.HookTcpSocketConnect::Prefix(k.Net.Sockets.TcpSocket __instance, k.Net.RemoteAddress address)

**Comment by pardeike** [comment]
Please refer to the documentation on how to use attributes. The one you are using with two string parameters isn’t doing what you think it does. 

Also, Issues on GitHub are not for support. Please ask such questions in the official discord - it will also give you faster answers.
