### ISSUE TITLE
netstandard2.0 target

### ISSUE THREAD

**Issue by morcibacsi** [pardeike/Harmony#483]
**Is your feature request related to a problem? Please describe.**
I have an application which targets .NET Framework 4.8 I'll try to slowly migrate it to .NET core and the first step is the modify the common libraries to target netstandard 2.0 (which can be a common base for .NET Framework and .NET Core) 

**Describe the solution you'd like**
It would be nice if the library supported netstandard2.0

**Comment by pardeike** [comment]
There are several problems with Net Standard 2.0 and it’s definitely end of live. We decided to no longer support it but you can try one of the other releases to see if it runs on Net Standard 2.0
