### ISSUE TITLE
How to use HarmonyTranpiler to patch an anonymous method/delegate?

### ISSUE THREAD

**Issue by ArkaniaCN** [pardeike/Harmony#484]
Hi pardeike,Harmony is a great plugin and thank you for your efforts.

Recently, I just started learning how to use Harmony to make mods for games, and I learned a lot of useful knowledge on your personal website about Harmony, praising your efforts again.

But as the title describes, I found a lot of problems when I tried to patch a delegate with HarmonyTranspiler, so can you give me some advice or tips for this?

**Comment by pardeike** [comment]
Hi. I would like to refer you to the official discord as Issues on GitHub are only for bugs or enhancements of Harmony.
