### ISSUE TITLE
Is it possible using `TargetMethods` to patch methods in different class, with calling a class-related method?

### ISSUE THREAD

**Issue by Neutron3529** [pardeike/Harmony#486]
**Is your feature request related to a problem? Please describe.**

suppose I want to patch a "same" method with several different class:
```CSharp
// original code:
class Skill1{
    int atk;
    int cost;
    int cooldown;
...
}
class Skill2{/*omitted, almost the same to Skill1*/}
class Skill3{/*omitted, almost the same to Skill1*/}
...
// patch:
        [HarmonyPatch(typeof(Skill1), "Cast")]
        class Skill1_Cast_patch{
            static void Prefix(Skill1 __instance){
                __instance.atk=100;
                // other complex logic here
            }
        }
        [HarmonyPatch(typeof(Skill2), "Cast")]
        class Skill2_Cast_patch{
            ...
        }
```

we want to write the same patch as Skill1, but we could not just re-use the Prefix for Skill1, since we mark the __instance as "Skill1", not "Skill2".

I know that, it is possible using either `Transpiler` to overcome such problem, but Transpiler is too dangerous to write.

**Describe the solution you'd like**

Since the IL code should be the same, we may force Harmony ignore the type checking for `__instance` by a special flag

```CSharp
    #[HarmonyPatch(PseudoGenericInstance)]// wrote any legal instance here should be fine
    class Patch{
            static IEnumerable<MethodBase> TargetMethods(){yield return typeof(Skill2).GetMethod("Cast")}
            static void Prefix(Skill1 __instance){
                __instance.atk=100;
                // other complex logic here
            }
    }
```

**Describe alternatives you've considered**
transpiler might work, but it is very easy to write bugs and very hard to fix it.

**Additional context**
It might be a really silly question. And since we could use Transpiler, it is ok to just mark a "wontfix" flag.

**Comment by pardeike** [comment]
I strongly suggest to ask usage questions on the discord. It gives you quicker feedback. 

The answer here is to use the common base class for all three types. In this case `object __instance`
