### ISSUE TITLE
[Question] Usage

### ISSUE THREAD

**Issue by orcun9988** [pardeike/Harmony#488]
`
[HarmonyPatch(typeof(GhostInfo), nameof(GhostInfo.SyncValuesNetworked))]

class StringFileExists
{
    static bool Prefix(int param_1,int param_2,bool param_3,int param_4,int param_5,bool param_6, int param_7,int param_8,bool param_9,PhotonMessageInfo param_10)
    {
        Console.WriteLine(param_1.ToString(), param_2.ToString(), param_3.ToString(), param_4.ToString(), param_5.ToString(), param_6.ToString(), param_7.ToString(), param_8.ToString(), param_9.ToString(), param_10.ToString());
        return true;
    }

}
`

this is my code , I just want to know  when  ghostInfo.Syncvaluenetworked works  print the parameters to console   I don't want to patch that method  

it print's the parameteres  however  it's also patching the method  I don't want to patch thats why I added return true

cuz if u add return false  =  skip the orginial method   

do you know how I can get it to patch only if certain conditions are met?
for example
  if(checkbox.checked  == true )  patch(ghostInfo.SyncValuesNetworked)

**Comment by pardeike** [comment]
Hi. I would like to refer you to the official discord as Issues on GitHub are only for bugs or enhancements of Harmony.

You can either add/remove a patch dynamically by using manual patching or you check your condition inside your patch.
