### ISSUE TITLE
Unnamed HarmonyMethod parameter causing NullReferenceException

### ISSUE THREAD

**Issue by notpeelz** [pardeike/Harmony#490]
**Describe the bug**

If a harmony method is created via `System.Reflection.Emit`, its parameters might not be named, causing a NullReferenceException [here](https://github.com/pardeike/Harmony/blob/89a15f726307171fc0b36e37a6132a75245baed9/Harmony/Internal/MethodPatcher.cs#L507)

**Expected behavior**
Harmony should throw an exception about the unnamed parameter.

**Screenshots / Code**
```cs
MethodBuilder method = ...;
for (var i = 0; i < args.Length; i++)
{
    var name = args[i].Item1;
    method.DefineParameter(
        // BUG HERE: this should've been `i + 1` but I forgot that the params start at index 1,
        // so the last parameter ends up not having a name
        i,
        ParameterAttributes.None,
        name);
}

var myClass = typeBuilder.CreateType();
var methodInfo = myClass.GetMethod("MyPostfix", BindingFlags.Static | BindingFlags.Public);

// NRE thrown here
harmony.Patch(m, postfix: new HarmonyMethod(methodInfo));
```

**Comment by pardeike** [comment]
Harmony does not support dynamic patch methods. It’s will fail in other ways than just the NRE. This is unfortunately a WONTFIX

**Comment by notpeelz** [comment]
It seems to work for me. What problems can I expect with dynamic patch methods?

**Comment by pardeike** [comment]
I think the exception as thrown right now is fine. It clearly shows you the problem which is what an ex exception is suppose to do.
