### ISSUE TITLE
Fatal Crash on 32 bit

### ISSUE THREAD

**Issue by TonyValenti** [pardeike/Harmony#491]
**Describe the bug**
Patching a method works on x64 but causes a fatal crash on x32.

Please see the attached ZIP which will repo the issue.

[HarmonyBug.zip](https://github.com/pardeike/Harmony/files/9123817/HarmonyBug.zip)

**Comment by pardeike** [comment]
Please state more information about the involved environment, versions etc

**Comment by TonyValenti** [comment]
Sorry @pardeike !  Here you go:

The crash occurs on my dev machine which is:

Win11x64 running on .Net 6.0.

The patching works when using the x64 framework but hard crashes when using the 32-bit framework. 

I am using the latest version of harmony.

Did I leave anything out?

**Comment by pardeike** [comment]
As I can see in your project you are using net6. This is at the moment not supported.
