### ISSUE TITLE
Harmony and IIS pool

### ISSUE THREAD

**Issue by Karql** [pardeike/Harmony#492]
Hi!

I have application hosted by IIS.
When I patched anything and try restart application (e.g. by modifying Web.config) the pool crashed.
![image](https://user-images.githubusercontent.com/173098/179954029-55c2d1db-afdc-43a3-927c-bb62d2643828.png)

**Reproduce**

Empty ASP NET application. With `Global.asax` like this:
```
using HarmonyLib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;

namespace HarmonyWeb3
{
    public static class DateTimePatch
    {
        public static void PatchDateTime(this Harmony harmony)//, IDateTimeProvider dateTimeProvider)
        {
            var nowOriginalMethod = typeof(DateTime).GetMethod("get_Now");
            var nowPrefixMethod = typeof(DateTimePatch).GetMethod(nameof(DateTimePatch.NowPrefix), BindingFlags.Static | BindingFlags.NonPublic);

            harmony.Patch(nowOriginalMethod, prefix: new HarmonyMethod(nowPrefixMethod));
        }

        private static bool NowPrefix(ref DateTime __result)
        {
            __result = DateTime.UtcNow;
            return false; // skip original execution
        }
    }


    public class Global : System.Web.HttpApplication
    {
        protected const string HarmonyId = "id";

        protected void Application_Start(object sender, EventArgs e)
        {
            var harmony = new Harmony(HarmonyId);
            harmony.PatchDateTime();
        }

        protected void Application_End(object sender, EventArgs e)
        {
            var harmony = new Harmony(HarmonyId);
            harmony.UnpatchAll();
        }
    }
}
```

Sample project: [HarmonyWeb3.zip](https://github.com/pardeike/Harmony/files/9148704/HarmonyWeb3.zip)

- Add application to iis
- Open URL
- Chagne something in `Web.config`
- Open URL again

**My observations**
1) After change `web.config`  `w3wp.exe` process still exists. Probably when application start again tries bootstrap harmony and something fail.
2) Cannot check if any patches exists. Pool crashed before `Application_Start` method.
3) `UnpatchAll` on `Application_End` does not change anything.
4) After first start I've commented code related to harmony, rebuild application, enter url - still pool crashed.

Do you have any ideas how to prevent pool from crashing?

Best regards,
Mateusz

**Comment by Karql** [comment]
Hi,

I have more informations. Remote stacke trace:
```
   w System.Web.Compilation.BuildResult..ctor()
   w System.Web.Compilation.BuildResult.CreateBuildResultFromCode(BuildResultTypeCode code, VirtualPath virtualPath)
   w System.Web.Compilation.PreservationFileReader.ReadFileInternal(VirtualPath virtualPath, String preservationFile, Int64 hashCode, Boolean ensureIsUpToDate)
   w System.Web.Compilation.PreservationFileReader.ReadBuildResultFromFile(VirtualPath virtualPath, String preservationFile, Int64 hashCode, Boolean ensureIsUpToDate)
   w System.Web.Compilation.DiskBuildResultCache.GetBuildResult(String cacheKey, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   w System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   w System.Web.Compilation.ApplicationBuildProvider.GetGlobalAsaxBuildResult(Boolean isPrecompiledApp)
   w System.Web.Compilation.BuildManager.CompileGlobalAsax()
   w System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled()
   w System.Web.Compilation.BuildManager.CallAppInitializeMethod()
   w System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)
   w System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel)
```

This brings me here: https://referencesource.microsoft.com/#System.Web/Compilation/BuildResult.cs,201
![image](https://user-images.githubusercontent.com/173098/180191106-95328eda-9c94-400c-8104-813ed39bf629.png)

It looks like when application is restarted w3wp process holds method patched in first run.
When this method is called returns: `System.AccessViolationException`

To prevent this patching in second run must be done before calling method.
`Application_Start` event in `Global.asax` is too late.

When I moved patching to `PreApplicationStartMethod` it works fine.

```c#
[assembly: PreApplicationStartMethod(typeof(PreApplicationStart), "Start")]
namespace HarmonyWeb3
{

    public static class PreApplicationStart
    {
        public static void Start()
        {
            var harmony = new Harmony("id");
            harmony.PatchDateTimeNow();
        }
    }
}
```

btw.

Where Harmony stores information about patched methods?
When I have two application in Pool A & B.
A - patch DateTime.Now
B - does not patch anything

Patch from app A affects app B - seems logical because they share w3wp process.
But in app B  `Harmony.GetAllPatchedMethods()` returns Empty.

I am wonder it should work this way.

Best regards,
Mateusz

**Comment by pardeike** [comment]
Normally different mods in different assemblies share patches on the global methods of the application. When you are inside a container application that does funky loading/unloading this stops working as designed. 

State is stored in a dynamic in-memory assembly that should never be unloaded but the problem becomes that Harmony has no way to detect custom unloaded of application domains so Harmony’s global state gets out of sync with the loaded assemblies.

**Comment by Karql** [comment]
Thanks for the answer and great lib!

I have managed to resolve the problem 😉
