### ISSUE TITLE
Hooking a System method then using internally

### ISSUE THREAD

**Issue by mnns** [pardeike/Harmony#495]
I'm trying to hook a System method, that's working great:

```
  var harmony = new Harmony("com.example.patch");
            var mOriginal = AccessTools.Method(typeof(System.IO.File), "ReadAllText", new[] { typeof(string) }); // if possible use nameof() here
            string g = "";
            var mPrefix = SymbolExtensions.GetMethodInfo(() => HookStart(ref g, "1"));
            var mPostfix = SymbolExtensions.GetMethodInfo(() => HookEnd(ref g, "1"));
            harmony.Patch(mOriginal, new HarmonyMethod(mPrefix), new HarmonyMethod(mPostfix));
```

Inside the HookStart function, I'm trying to actually use ReadAllText() - but obviously this creates a circular reference.
Is there anyway of using ReadAllText inside and skipping the hook?

Thanks!

**Comment by pardeike** [comment]
You can use a ReversePatch to make one of your dummy methods work the same as ReadAllText and call it instead.
