### ISSUE TITLE
About mono-cecil Version...

### ISSUE THREAD

**Issue by SaNeOr** [pardeike/Harmony#496]
Many packages use "com.unity.nuget.mono-cecil" now, and it is easier to resolve conflicts by using dependencies.

(Most unfortunately, com.unity.nuget.mono-cecil does not support 10.4.0  : (

**Comment by pardeike** [comment]
A lot of mod-loader solutions or mods still only support a single dll. By adding a dependency to an external assembly there will be a significantly increased risk of breaking existing solutions.

**Comment by pardeike** [comment]
Harmony 2.3 will use dependencies (and that will confused a lot of people). But it solves this issue.
