### ISSUE TITLE
Patching a method to be executed multiple times

### ISSUE THREAD

**Issue by ST-Apps** [pardeike/Harmony#497]
Hi there, I'm the developer of [Parallel Road Tool](https://steamcommunity.com/sharedfiles/filedetails/?id=1440928803) for Cities: Skylines. My mod basically revolves around a simple idea: when a certain method is called we wait for it to execute and the we call it again many other times (depending on user's input) but with slightly different parameters.

I'm currently using Detours for it and the workflow can be summarized like that:
- Patch the method on game startup
- When original method is called my patch is executed
- My patch actually reverses the patch before doing anything
- My patch now calls the original method a certain amount of times
- Before returning, my patch reapplies the patch reverted before

While this works, it's not really ideal. Also, all the major mods in Cities: Skylines moved to Harmony and I'd like to move too for compatibility reasons.

What I'd like to know if is there a way to actually call the original method in Harmony.

**Comment by pardeike** [comment]
Sure, there is a better way to do this: using a reverse patch you can project the original method onto a stub in your own code and call the stub (which will because of the patch call the original). That kind of patch reconstructs the original method from IL code and is not affected by other patches.

**Comment by pardeike** [comment]
For more info and help, please use the official Discord for support questions. It’s better suited than Issues.
