### ISSUE TITLE
Setting __args[n] does not work

### ISSUE THREAD

**Issue by albgen** [pardeike/Harmony#499]
---

**Describe the bug**
Need to patch a method with the following signature
Result<T> MethodName(CompilationOutput compilationOutput, bool skipValidation = false, bool allowPublishInModifiableRange = false)
Tried with __args[1] = true because i want to change that skipValidation to true but does not works

**To Reproduce**
1. The original method and its signature and class
private static Result<T> MethodName(CompilationOutput compilationOutput, bool skipValidation = false, bool allowPublishInModifiableRange = false)
3. The patch code
static bool Patch(object[] __args)
        {
            __args[1] = true;
           __args[2] = true;      
           return true;// Continue the original method to execute itself
        }
5. The output of the Harmony debug log
no errors or strange things
7. The stacktrace or other errors
nothing

If i use the following patcher it works. So the problem is with args.
On both cases the patcher method is called so i have checked it!
        static bool patch(object compilationOutput, ref bool skipValidation, ref bool allowPublishInModifiableRange)
        {
        
            skipValidation = true;
            allowPublishInModifiableRange = true;
    
            return true;// Continue the original method to execute itself
        }
**Expected behavior**

**Comment by pardeike** [comment]
Currently, Harmony does not support writing to `__args`. I am investigating how to implement this the best way.
