### ISSUE TITLE
Not transforming Leave_S jumps

### ISSUE THREAD

**Issue by shroudedmods** [pardeike/Harmony#50]
`MethodCopier` transforms various short opcodes into their long versions, but not `Leave_S`. This can cause invalid instructions to be emitted.

**Comment by shroudedmods** [comment]
Never mind. I'm new to IL, and didn't realise this was part of the try-catch stuff that's not yet implemented.

**Comment by pardeike** [comment]
Actually, even though I work on a try/catch implementation (and have a working prototype that needs more testing before I can publish it) this is still a valid issue. 

Thanks for reporting!

**Comment by shroudedmods** [comment]
If anyone is needs try/catch/finally support right away, I have added a hacky implementation to my Harmony fork: https://github.com/shroudedmods/Harmony. C# exception handling seems to work OK, but fault and filter blocks are not yet dealt with properly.

One issue I encountered while implementing is that ILGenerator methods like `BeginCatchBlock` automatically emit Leave jumps. But since the copied IL will already contain a Leave in the same place, these new jumps are redundant. I thought maybe I could just filter out the original jumps, but they can have associated labels, so they can't be easily removed. I chose to just leave both jumps in place, the second being dead code, but harmless.

**Comment by pardeike** [comment]
I am working on my own implementation of this. A bit busy right now but as soon as I have a good enough version, we can compare and sync our efforts. Good job!

**Comment by pardeike** [comment]
Latest master has my implementation. Please verify.

**Comment by shroudedmods** [comment]
Sorry this took a while, but I was looking at this again last night. Seems to work great now! Thanks.
