### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80004005):Try visit invalid address

### ISSUE THREAD

**Issue by hxd123456** [pardeike/Harmony#509]
【BUG】
I try to patched a mysql method  in my program,
it is natural in vs2019 and rider,
but release to iis run it,the program has some error
【The original method and its signature and class】
`MySql.Data->MySql.Data.MySqlClient.MySqlCommand->ExecuteReader`
`System.Data->System.Data.SqlClient.SqlCommand->WriteBeginExecuteEvent/WriteEndExecuteEvent`
【The patch code】
```cs
        public MysqlClientDiagnosticProcessor(ILoggerFactory loggerFactory)
        {
            logger  = loggerFactory.CreateLogger(typeof(MysqlClientDiagnosticProcessor));
            logger.Information("Initializing ...");
            try
            {
                Type invoker = TypeHelper.GetTargetType("MySql.Data.MySqlClient.MySqlCommand", "MySql.Data");
                if (invoker != null)
                {
                    Harmony harmony = ServiceLocator.Current.GetInstance<Harmony>();
                    var target = invoker.GetMethod("ExecuteReader",
                            new Type[] {typeof(CommandBehavior)});
                    var prefix = typeof(MysqlClientDiagnosticProcessor).GetMethod(nameof(BeforeExecuteRequest));
                    var postfix = typeof(MysqlClientDiagnosticProcessor).GetMethod(nameof(AfterExcuteRequest));
                    var finalizer = typeof(MysqlClientDiagnosticProcessor).GetMethod(nameof(FinalizerHandle));
                    harmony.Patch(target, new HarmonyMethod(prefix),postfix:new HarmonyMethod(postfix),
                        finalizer: new HarmonyMethod(finalizer));
                    logger.Information("MySql.Data.MySqlClient.CommandInterceptor.ExecuteReader is patched");
                }
                else
                {
                    logger.Information("MySql.Data.MySqlClient.MySqlCommand is not found in Assembly[MySql.Data]");
                }
            }
            catch (Exception e)
            {
                logger.Error("注册mysql异常",e);
            }
            
        }

        public static void BeforeExecuteRequest(dynamic __instance)
        {
            
        }

        public static void AfterExcuteRequest(dynamic __instance)
        {
            
        }

        public static void FinalizerHandle(Exception __exception)
        {    
        }
```
4. The output of the Harmony debug log
【The stacktrace or other errors】
![image](https://user-images.githubusercontent.com/46563086/206679543-6352c902-3825-4034-b248-15dd600941e6.png)
【other】
 - OS: Windows 10, 64bit 
 - .NET  .NET Framework 4.5
 - Harmony version 2.2.2

**Comment by hxd123456** [comment]
hope your help

**Comment by pardeike** [comment]
I don't think `dynamic` is supported in arguments. Please note that the dynamic type in C# is something that makes your compiler generate a lot of hidden code in form of classes and other stuff. Harmony patch arguments are injected by Harmony and if you use dynamic this stops working.

Also, make sure your original method is well defined and visible in a decompiler and shows IL code. Native methods are not supported but I don't know what yours is because you did not post it.

**Comment by hxd123456** [comment]
I think the dynamic arguments is supported in my program,because the other dynamic arguments is natural.I don't  know what happened in the updateWapper,I can't repeat the problem in vs2019.You can tell me what this error message means                                                                                                                                                                                【original method】                                                                                                                                                                                  `public static void BeforeExecuteRequest(dynamic __instance)
        {
            try
            {
                var tracingContext = ServiceLocator.Current.GetInstance<ITracingContext>();
                string sqlStr = __instance.CommandText;
                string operationMethod = "";
                if (sqlStr != null && sqlStr.Length != 0)
                {
                    string[] strings = sqlStr.Split(' ');
                    if (strings.Length > 1 && sqlMethod.Contains(strings[0].ToLower()))
                    {
                        operationMethod = ":"+strings[0];
                    }
                }
                var operationName = "Mysql"+operationMethod;
                
                string port = "3306";
                string[] settings = __instance.Connection.ConnectionString.Split(';');
                for (var i = 0; i < settings.Length; i++)
                {
                    var pair = settings[i].Split('=');
                    if (pair[0].ToLower().Equals("port"))
                    {
                        port = pair[1];
                        break;
                    }
                }
                var networkAddress = $"{__instance.Connection.DataSource}:{port}";
                var context = tracingContext.CreateExitSegmentContext(
                    operationName,
                    networkAddress
                );
                context.Span.SpanLayer = SpanLayer.DB;
                context.Span.Component = Components.MYSQLCLENT;
                context.Span.AddTag(Tags.DB_STATEMENT, __instance.CommandText);
            }
            catch (Exception e)
            {
                logger.Error("BeforeExecuteRequest", e);
            }
        }

        public static void AfterExcuteRequest(dynamic __instance)
        {
            
        }

        public static void FinalizerHandle(Exception __exception)
        {
            var tracing = ServiceLocator.Current.GetInstance<ITracingContext>();
            var accessor = ServiceLocator.Current.GetInstance<IExitSegmentContextAccessor>();
            var context = accessor.Context;
            try
            {
                if (context != null)
                {
                    if (__exception != null)
                    {
                        context.Span.ErrorOccurred(__exception);
                    }
                    tracing.Release(context);
                }
            }catch (Exception e){
                logger.Error("ErrorHandle", e);
            }finally {
                if (__exception != null)
                {
                    throw __exception;
                }
            }
            
        }`
