### ISSUE TITLE
Obfuscated parameters

### ISSUE THREAD

**Issue by atomicwrangler** [pardeike/Harmony#51]
What if the method has obfuscated parameters that begin with # ? 

How could I access them?

Also how does it deal with multiple overloads?

**Comment by pardeike** [comment]
Right now, you can’t. I am working on an update that might have annotations for specifying parameter names, or a way to access all of them via an array. 

The best option you have for now is to use a transpiler. 

Regarding multiple overloads: you can only replace code that actually exists as IL in the dll. So basically any implementation. If you use a disassembler it becomes clear. In case of overloads you need to pick the class/method you want to change.

**Comment by atomicwrangler** [comment]
That's great! Harmony is currently the best hooking library for C#. I would be interested in a blog post describing how it all works. For example what happens if the method is already JITted ? From what I understand by reading the code it patches only IL and doesn't touch generated assembly at all?

**Comment by pardeike** [comment]
Actually, no. Harmony uses the known way to repoint a method to another method by inserting an assembler jump into the assembler methods start. What it does differently is that it has a high level way to define the new method. Where other solutions require you to write your own replacement method, Harmony does this by manipulating the original IL code. This has the advantage that multiple plugins can patch the same original method without overwriting each other. 

The unsolved problem with this is that inlined methods cannot be redirected. Already jitted code is not a problem because to insert the assembler jump, Harmony forces a jit anyway.

**Comment by shroudedmods** [comment]
One thing I'm not clear about: It seems to be quite complicated to clone the original method's IL and do all the rewriting of operands and branches and stuff. For non-transpiled cases, wouldn't it be easier to clone the original wholesale, without changing anything, then create a separate dynamic method that does the prefix and postfix stuff, with a call to the clone in the middle? Then make the second dynamic method the target of the hook?

**Comment by atomicwrangler** [comment]
Ah yes I see now it uses GetRuntimeMethodHandle to get a handle to JITted function in memory which is in native assembly by accessing the fields like mhandle for mono. So basically that part is just like a traditional jmp hook in native world. IL copying part like shroudedmods says is pretty complicated though.

 I was thinking of making my own hooking library before I found Harmony what I was planning to do is hooking JIT mono methods like mono_compile_method or mono_jit_runtime_invoke in C++ but that would work only for mono and I would have to think of a wrapper for C#/C++ CLR to actually make this work in high-level.

**Comment by pardeike** [comment]
Use Microsoft’s official documentation. CIL isn’t that hard to learn. It’s actually a very lean stack based byte code based language. 

The reason why I don’t do it the way you suggested is that it does not allow for advanced transpiler handling. It is also less useful in situations where you need performance and makes input parameter manipulations more complicated. Personally, I find the IL copying not that hard compared to all the rest you have to do anyway.

**Comment by atomicwrangler** [comment]
Yeah it would be much easier if microsoft provided something like inline IL ASM like __asm in MSVC. Your approach is good 

I think I just found the place needed to patch for obfuscated parameters support.
`static void EmitCallParameter(ILGenerator il, MethodBase original, MethodInfo patch, Dictionary<string, LocalBuilder> variables)`

Do you have time to work on it right now or could you accept a pull-request if I requested it?

**Comment by pardeike** [comment]
I have some things in my life that need attention so my work on Harmony is slow. I think the best would be to solve this in a fork and submit a pull request. I suggest method annotations. Also check the existing pull requests for what I think is a method array implementation. I’m not totally sure it is in there but I remember someone asking for it.

**Comment by pardeike** [comment]
See discussion in #20 too

**Comment by atomicwrangler** [comment]
The only problem with method attributes is that it's repeating. What could be cleaner is class attribute that applies renaming to all methods inside that class or actually we can add both or even three possibilities of renaming. What DoctorVanGogh proposed are parameter attributes. I'm just thinking what would be the cleaniest way to accomplish this. Manual patching must work with this as well.

**1. Class attributes**
```
[HarmonyParameter("#df", "renamedParam")]
class My_Patch {
    static void Prefix(int renamedParam) {
    }

    static void Postfix(int renamedParam) {
    }
}
```
**2. Method attributes**

```
class My_Patch {
    [HarmonyParameter("#df", "renamedParam")]
    static void Prefix(int renamedParam) {
    }

    [HarmonyParameter("#df", "renamedParam")]
    static void Postfix(int renamedParam) {
    }
}

```

3. Parameter attributes
```
class My_Patch {
    static void Prefix([HarmonyParameter("#df", "renamedParam")] int renamedParam) {
    }

    static void Postfix([HarmonyParameter("#df", "renamedParam")] int renamedParam) {
    }
}
```

**Comment by atomicwrangler** [comment]
Also for reflection it would be good to have some kind of cache, there are already existing implementations for fast reflection especially when we deal with games.

**Comment by pardeike** [comment]
Such a lib is already included in Harmony. Check out FastAccess

**Comment by atomicwrangler** [comment]
It could be improved by caching delegates.

**Comment by pardeike** [comment]
If you’re really into the ultimate performance you need to use transpilers and direct IL code access. That will jit into optimized assembler and is not too hard to accomplish. I do it all the time.

**Comment by atomicwrangler** [comment]
I've noticed there's some sort of reflection helper with cache already: https://github.com/pardeike/Harmony/blob/master/Harmony/Tools/Traverse.cs

Please see my PR: #52
