### ISSUE TITLE
MissingMethodException Just calling Harmony. PatchAll will crash

### ISSUE THREAD

**Issue by XLjiangA** [pardeike/Harmony#511]
Just calling Harmony. PatchAll will crash
```cs
    [HarmonyPatch(typeof(AttackSpellController))]
    [HarmonyPatch("OnProcessTaskList")]
    class OepnPatch
    {
        [HarmonyTranspiler]
        static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> ils)
        {
            foreach (var il in ils)
            {
                if (il.opcode == OpCodes.Ldc_R4)
                {
                    if ((float)il.operand == 2f)
                    {
                        il.operand = 3f;
                    }
                }
                yield return il;
            }
        }
    }

static void main(){
   new Harmony("task.patch").PatchAll();
}
```
System.MissingMethodException: System.Type[] System.Reflection.ReflectionTypeLoadException.get_Types()
  at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <5c856fb19ddb469d99459756a2e14341>:0 
  at HarmonyLib.Harmony.PatchAll () [0x0001b] in <5c856fb19ddb469d99459756a2e14341>:0

**Comment by pardeike** [comment]
What .NET runtime are you using? Harmony only supports runtimes that off the Reflection.Emit namespace.

**Comment by XLjiangA** [comment]
Reflection. Emit has nothing to do with this. I tried HarmonyPrefix,
The same error will occur
```cs
    [HarmonyPatch(typeof(AttackSpellController))]
    [HarmonyPatch("OnProcessTaskList")]
    class OepnPatch
    {
        [HarmonyPrefix]
        static void Transpiler(AttackSpellController __instance)
        {
             __instance.speed = 3f
        }
    }
```

**Comment by XLjiangA** [comment]
```AccessTool``` does not work in this game
Method is always not found
But ```typeof(type).getMethod``` works normally

**Comment by XLjiangA** [comment]
```cs
sourceMethod = typeof(x).getmethod("a")
//sourceMethod = a , not null
patchMethod = typeof(myClass).getmethod("a")
//patchMethod  not null
new harmony("patch.tu").patch(sourceMethod,prefix:patchMethod )
```
Same does not work
get error
``` System.MissingMethodException```

**Comment by pardeike** [comment]
Then your Harmony library isn’t loaded so it’s methods aren’t available

**Comment by XLjiangA** [comment]
what  mean

**Comment by XLjiangA** [comment]
How to load Harmony library correctly
