### ISSUE TITLE
Indexers on HarmonyLib.Code members do not work (certainly not as expected)

### ISSUE THREAD

**Issue by DoctorVanGogh** [pardeike/Harmony#513]
**Describe the bug**
`HarmonyLib.Code` members do not work properly. Although documentation is ~~nonexistant~~ "sparse" :wink: the signatures and return types suggest a certain use case. That obvious use case (shortforms for `CodeMatch` [sequences]) totally does not work 😢 

**To Reproduce**
Try doing using any `CodeMatch` via `Code.Foo[...]` and supply indexer arguments.
```cs
    internal class Program {
        static void Main(string[] args) {

            var miFoo = AccessTools.Method(typeof(Program), nameof(Program.Foo));
            var miBar = AccessTools.Method(typeof(Program), nameof(Program.Bar));

            var m = new CodeMatcher(
                new[] {
                    new CodeInstruction(OpCodes.Call, miFoo)
                })
                .MatchStartForward(
                    Code.Call[miBar]
                );

            Console.WriteLine($"Match found: {m.IsValid}?!?");  
        }

        static void Foo() {
        }

        static void Bar() {
        }
    }
```
will output
```
Match found: True?!?
```
The CodeMatch seems to _only_ match via the `opcode` and totally ignore any operand.

**Expected behavior**
`Code.Foo` indexers should actually return `CodeMatch` instances where the indexer arguments have been properly set on the returned instance.

`Code.Foo[bar, baz]` should be functionally equivalent to `new CodeMatch(OpCodes.Foo, bar, baz)`.

**Screenshots / Code**
-see above- 

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version 4.6.1
 - Harmony version 2.2.2
 - Name of game or host application: any/all

**Comment by pardeike** [comment]
Closed due to lack of feedback
