### ISSUE TITLE
Hook Dictionary generic function "containskey" not work!

### ISSUE THREAD

**Issue by wanghualei2** [pardeike/Harmony#515]
I need to hook the containskey method of many different Dictionary objects, such as:
Dictionary<string,int> s1;
Dictionary<string,bool> s2;
Then I hooked these two different containskey methods, but I found some problems:
1) The addresses of the two containskey methods are the same? Of course, it doesn't matter, it's probably because of method sharing.
2) The key question is that the containskey method of the hook has not been executed, or it will be executed occasionally. Why is this because the containskey method has the same address?
3) Is there any way I can make sure the hook generic function is correct? For example, to hook through the function address, but from the documentation, I did not find the relevant method.

**Comment by pardeike** [comment]
Please see [Documentation: Edge cases - Generics](https://harmony.pardeike.net/articles/patching-edgecases.html#generics)

**Comment by wanghualei2** [comment]
I had seen the documentation.
If the generic includes a value type, such as int, in most (but not all) cases, the method will not be shared. Patching a method which uses a value type parameter will patch only that specific method. Conversely, patching a generic with an object type will not patch the value type method, so both may have to be patched.
For the specific type, the two different generic methods of hooking are indeed hooked according to the document, but the result is that it is triggered occasionally. Do you have any ideas for me?

**Comment by wanghualei2** [comment]
I really want your help

**Comment by pardeike** [comment]
There is no solution

**Comment by wanghualei2** [comment]
I read the docs and I thought the problem with generic function hooks was already solved? Isn't that so?

**Comment by pardeike** [comment]
Where did you read that? I wrote the docs and I say that there is no solution for patching generics that exists right now.
