### ISSUE TITLE
Double assembly after patching

### ISSUE THREAD

**Issue by deltaone** [pardeike/Harmony#516]
1. Load target assembly through Assembly.Load(File.ReadAllBytes(targetPath));
2. Apply PatchAll()
3. We get two same loaded assembly: one unpatched loaded from memory and one patched loaded  from disk

How to patch assembly loaded from memory ?
As workaround - i rename assembly on disk and apply path, then patch apply on assembly loaded from memory ...

THX!

**Comment by pardeike** [comment]
Harmony does not load any assemblies. This must be an oversight on your side.

**Comment by deltaone** [comment]
Look in code ...

Assembly game = Assembly.Load(File.ReadAllBytes(Path.Combine(AssemblyFolder, "target.exe")));
 //Assembly game = Assembly.LoadFile(Path.Combine(AssemblyFolder, "target.exe"));

[double.zip](https://github.com/pardeike/Harmony/files/11060796/double.zip)

**Comment by pardeike** [comment]
How is this related to Harmony. The code you posted is not part of Harmony. Please use the official discord for support questions and leave GitHub Issues for bugs in the library.

**Comment by deltaone** [comment]
https://github.com/pardeike/Harmony/files/11060796/double.zip
