### ISSUE TITLE
Patching of serializeable array object didnt seems to have effect.

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [pardeike/Harmony#520]
**Describe the bug**
So firstly the game will run and serialize it,then in game when a new character* generation is triggered the patched constructor gets called and the moded sizes should be effective in game. 
However even after 100 rolls none of them have that moded size,which means the moded array is not actually the same object /reference used?I think?

**To Reproduce**
1. The original method and its signature and class
Original class w Constructor>

`[Serializable]
	public class Dragonian : Female
	{
public override CharacterData Data
		{
			get
			{
				return GameManager.DragonianData;//this will just get the DragonianData
			}
		}

public Dragonian(int unitId)
			: base(unitId)
		{
			this.m_Figure = EFigure.Woman;.........`

the CharacterData which has int[] ___m_TitsTypeList
`[Serializable]
	public class CharacterData : Data
	{.........................
        [SerializeField]
		protected int[] m_TitsTypeList;`

2. 
`[HarmonyPatch(typeof (Dragonian),new Type[]{typeof(System.Int32)})]
	[HarmonyPatch(MethodType.Constructor)]
	[HarmonyPostfix]
	public static void patchdragondatatitsnonzerov3(ref Dragonian __instance){
			int[] temptitstypearr=Traverse.Create(__instance.Data).Field("m_TitsTypeList").GetValue() as int[];
			float[] temptitstypechancearr=Traverse.Create(__instance.Data).Field("m_TitsTypeChanceList").GetValue() as float[];
				//to add 0 size
				if(!Misllutil.Arrutils.onedimensionarrContains(temptitstypearr,0)&&addzerosizetitstodragonraceifnotexist){
					temptitstypearr=Misllutil.Arrutils.insertintoarr(temptitstypearr,0,0);
					temptitstypechancearr=Misllutil.Arrutils.insertintoarr(temptitstypechancearr,(float)rndengine.NextDouble(),0);
				}}.....`

3. The output of the Harmony debug log.no error it patches successfully.

**Expected behavior**
The variable/reference gets properly accessed or patched and then has effect.

**Screenshots / Code**
I can confirm the patches is running but it just doesnt have effect,for example adding this code
`while(e<maxl){
					ins.AddSystemMessage("temptitstypearr size"+e.ToString()+" value>"+temptitstypearr[e].ToString()+"\ntemptitstypechancearr value>"+temptitstypechancearr[e].ToString());
					e++;
				}`
shows
![core](https://user-images.githubusercontent.com/122155102/229596408-dca16f7c-0be0-434c-a28e-94cdcdb498d1.png)

Or maybe its my own way of modding the array which is wrong?for reference here is my code.
`public static int[] insertintoarr(int[] a, int val,int insertpos)
    {
		int e=0;
		int outlen=a.Length + 1;
		int[] newarr = new int[outlen];
		int tempval=0;
		bool inserted=false;
		
		while(e<outlen){
			if(e<(outlen-1)){
				if(e==insertpos){newarr[e]=val;tempval=a[e];inserted=true;}else{
					if(inserted){newarr[e]=tempval;tempval=a[e];}else{newarr[e]=a[e];}
				}
			}else{
				if(e==insertpos){newarr[e]=val;inserted=true;}else{
					if(inserted){newarr[e]=tempval;}
				}
			}
			e++;
		}
        return newarr;
    }`

I also once moded the file that is used serialize those variables and I can confirm it actually changes the size.

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET version 7.0.0& TargetFrameworkVersion:v4.7.2
 - Harmony version,bleeding edge
- Name of game or host application [Monster Black Marketv2+]

**Comment by pardeike** [comment]
Please reformat your question or, better yet, use the official Discord server for programming questions. The GitHub Issues are for bugs and feature requests in Harmony itself. Normal usage questions are much better answered in the discord.

**Comment by Banane9** [comment]
For the record, the problem is, that you're creating a new array to insert your value into - so you have to write it back to the fields. Otherwise your change just exists in a void.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
> For the record, the problem is, that you're creating a new array to insert your value into - so you have to write it back to the fields. Otherwise your change just exists in a void.

i see,hmm will try to find other ways to implement resizing and adding nre values in.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
> Please reformat your question or, better yet, use the official Discord server for programming questions. The GitHub Issues are for bugs and feature requests in Harmony itself. Normal usage questions are much better answered in the discord.

i know its kinda weird to say this but it would be great to create a group in [matrix.io](https://matrix.org/) or generally a matrix group you can pick any public free hosting server you want and it doesnt needs your phone number or even force you to update apps.most matrix client has implemented the open verified encryption and the open source client android app like Element dont have any tracker instead of discord having google analytics in it.

Its just a suggestion because I think you deserve to keep your chats private and secure.
Anyway thanks will try to look more on my own scripts and see if I can fix it.
