### ISSUE TITLE
Harmony cannot apply patches in a single-file publish context

### ISSUE THREAD

**Issue by Nihlus** [pardeike/Harmony#530]
**Describe the bug**
When using Harmony to patch assemblies in a single-file context, patching fails with a reference to a failure to load the clrjit library.

**To Reproduce**
1. Create a project that patches a method
2. Publish the project as a single file
3. Run the single-file binary
4. Observe crash with a reference to clrjit

**Expected behavior**
Harmony should apply the patch successfully.

**Screenshots / Code**
[log.txt](https://github.com/pardeike/Harmony/files/11524656/log.txt)

**Runtime environment (please complete the following information):**
 - OS: Linux Mint 21 (x86_64)
 - .NET 7
 - Harmony 2.3-alpha.5
 - NeosVR

**Additional context**
The assemblies being patched are not part of the single-file publication, but it appears that Harmony is failing earlier than that. I have tried to publish for specific runtime identifiers, with and without compression, and with native libraries included in the extract.

**Comment by pardeike** [comment]
Can you supply more technical information about the moment it "crashes"?

**Comment by Nihlus** [comment]
Is there anything specific you want me to look for or clarify? It happens the moment I run PatchAll, with the attached log as the only output.

**Comment by pardeike** [comment]
No idea why that library is required when you compile IL at runtime. Seems the single file packing is not adding it. Nothing Harmony itself can fix.

**Comment by Nihlus** [comment]
According to some knowledgeable people, the clrjit library is present in single-file publish, just linked into the main binary. Is there a way for me to get a more in-depth stack trace of where the issue is happening, or some way for you to try and reproduce it on your end?

**Comment by Nihlus** [comment]
I spoke a bit with the MonoMod people and identified exactly where the issue stems from. They're going to look into it, but no promises. Closing this for now.
