### ISSUE TITLE
Native async patching is not available in .NET Standard or .NET

### ISSUE THREAD

**Issue by Nihlus** [pardeike/Harmony#533]
**Describe the bug**
The Async method type and its associated helpers are not available outside of .NET Framework due to the use of the `NET45_OR_GREATER` compile-time definition. This define is not set in .NET Standard or modern .NET despite the name suggesting as such at first glance. These targets support asynchronous code and should have the code available.

Adding `NETSTANDARD1_0_OR_GREATER` and `NETCOREAPP1_0_OR_GREATER` as `||` options to the `#if` clauses should resolve the issue.

**To Reproduce**
1. Install Harmony's prerelease in a .NET Standard or .NET project (not .NET Framework)
2. Attempt to use an Async method target or `AccessTools.AsyncMoveNext`
3. Observe compile error

**Expected behavior**
The functionality should be available.

**Screenshots / Code**
If applicable, add material to help explain your problem.

**Runtime environment (please complete the following information):**
 - OS: Linux Mint 21
 - .NET 7
 - Harmony 2.3.0-prerelease.2

**Comment by pardeike** [comment]
Can you verify with `master` that this is no longer a problem?

**Comment by Nihlus** [comment]
Yep, seems to work fine.
