### ISSUE TITLE
How to patch a override method using Transpiler

### ISSUE THREAD

**Issue by TL0SR2** [pardeike/Harmony#540]
I have a method like this
![image](https://github.com/pardeike/Harmony/assets/101415208/b22478d1-69af-4619-bdbf-3267b93c7f5f)
and i want to change some of the code using Transpiler.
but it looks like this in IL
![image](https://github.com/pardeike/Harmony/assets/101415208/3efdaa1d-1f69-4e1d-b005-3ddd29b5b9ef)
and the real code is this 
![image](https://github.com/pardeike/Harmony/assets/101415208/8e24d341-dafd-4529-b558-1d554c407e92)
it is in this strange class
![image](https://github.com/pardeike/Harmony/assets/101415208/b08037d3-317a-460d-9127-aea991c800f7)
I can't get it in my code for it looks like this
![image](https://github.com/pardeike/Harmony/assets/101415208/02e3bb40-9b86-449d-b3f3-5445150ee7b3)
how do I solve this problem?
(and if i just patch the "LoadItems" method i would just get the code in the picture No.2)

**Comment by pardeike** [comment]
Please don't use GitHub issues for support. See MethodType attribute argument for targeting MoveNext method.
