### ISSUE TITLE
AccessTools.Constructor behaving unexpectedly

### ISSUE THREAD

**Issue by bbradson** [pardeike/Harmony#547]
A RimWorld mod ran into a memory leak due to an `AccessTools.Constructor(typeof(Pawn_SkillTracker))` call returning `System.Void System.Object::.ctor()`. The target class has one declared constructor with `Pawn` argument, no parameterless constructors and the intended result was to harmony patch that constructor.  
  
I believe there are two issues at play here:  
- AccessTools.Constructor goes all the way up to System.Object when searching for constructors. This technically lines up with its description of searching in the type and all its super types, but is likely never the intended return value. This even happens for static classes, which do still derive from object in IL, but cannot be instantiated using this constructor in C#. The result is useless.  
- AccessTools.Constructor only looks for parameterless constructors when not supplying an array with parameter types. This isn't mentioned anywhere in its documentation, which instead describes the argument as optional, and does not line up with the behaviour of other AccessTools methods. The usual behaviour is to try look for matches with any number of parameters in the declared type first, and generally even to throw AmbiguousMatchExceptions when multiple are found.  
  
Having the method use `type.GetConstructors` when `null` is passed in for the parameter array and returning `null` when there's only `System.Object.ctor` as possible match for any type other than `typeof(object)` would lead to the behaviour that I think is likely to be the common expectation here.

**Comment by pardeike** [comment]
Sorry for the late response. While I do agree with some of the conclusions, my biggest question is: why not using `AccessTools.GetDeclaredConstructors()` ?

**Comment by pardeike** [comment]
For backwards compatibility (and for allowing low level use of AccessTools.Constructor which is expected to return object.ctor() I cannot change the behaviour. This is unfortunately a WONTFIX.
