### ISSUE TITLE
Reverse patch for private class?

### ISSUE THREAD

**Issue by Release** [pardeike/Harmony#549]
There is an example in the [Reverse Patch](https://harmony.pardeike.net/articles/reverse-patching.html) section:
```
private class OriginalCode
{
    private void Test(int counter, string name)
    {
        // ...
    }
}

[HarmonyPatch]
public class Patch
{
    [HarmonyReversePatch]
    [HarmonyPatch(typeof(OriginalCode), "Test")] // <= Compiler Error CS0122 'ClassName' is inaccessible due to its protection level
    public static void MyTest(object instance, int counter, string name)
    {
        // its a stub so it has no initial content
        throw new NotImplementedException("It's a stub");
    }
}
```

**[HarmonyPatch(typeof(OriginalCode), "Test")]** // <= Compiler Error CS0122 'ClassName' is inaccessible due to its protection level
How should this work for a class with a restrictive access modifier?

**Comment by pardeike** [comment]
Support questions are best done on the official discord. You get faster and better feedback. Documentation tells you how to deal with inaccessible types: you use `TargetMethod()`

**Comment by Release** [comment]
> Support questions are best done on the official discord. You get faster and better feedback. Documentation tells you how to deal with inaccessible types: you use `TargetMethod()`

This is a sample code from the documentation, there is a link to the corresponding section in the header. So it's incorrect?
**I created the issue to draw attention to the documentation.**

I know how to specify the required method for a regular patch, but not for a reverse patch.

Will the code below work correctly?
```
private class OriginalCode
{
    private void Test(int counter, string name)
    {
        // ...
    }
}

[HarmonyPatch]
public class Patch
{
    public static MethodBase TargetMethod()
    {
        return AccessTools.FirstMethod(AccessTools.TypeByName("OriginalCode"), m => m.Name.Contains("Test"));
    }

    [HarmonyReversePatch]
    public static void MyTest(object instance, int counter, string name)
    {
        // its a stub so it has no initial content
        throw new NotImplementedException("It's a stub");
    }
}
```

**Comment by 18107** [comment]
> Support questions are best done on the official discord

Discord is not searchable using a search engine, GitHub is.

@Release Thanks for the updated code. This was the only example of how to use `TargetMethod` that I've found using search engines.

**Comment by Shadowfita** [comment]
> > Support questions are best done on the official discord
> 
> Discord is not searchable using a search engine, GitHub is.
> 
> @Release Thanks for the updated code. This was the only example of how to use `TargetMethod` that I've found using search engines.

Glad you found a solution for your problem. I thought the docs covered this pretty well however?

https://harmony.pardeike.net/articles/patching-auxiliary.html

**Comment by Release** [comment]
> I thought the docs covered this pretty well however?
> 
> https://harmony.pardeike.net/articles/patching-auxiliary.html

Documentation is good, but…
It's been a year since I called attention to the wrong example in the documentation. But nobody has ever bothered to fix the access modifiers in the example.

**Comment by pardeike** [comment]
> Documentation is good, but… It's been a year since I called attention to the wrong example in the documentation. But nobody has ever bothered to fix the access modifiers in the example.

It’s easy to file an Issue or even add a PR to fix it. I regularly get PRs for documentation updates.

**Comment by Release** [comment]
> It’s easy to file an Issue or even add a PR to fix it. I regularly get PRs for documentation updates.

I did, didn't I? Right here, no?
I didn't think about PR, but only because fixing one word in two lines doesn't merit creating a fork to make a PR. Or rather it's not a contribution that deserves it.
Though I am very grateful to the author and everyone who had a hand in it for this great thing.

**Comment by pardeike** [comment]
Maybe I missed it. Can you find it and give me its Issues number?

**Comment by Release** [comment]
Maybe I'm missing something, but right in this issue thread is my first (and third) post about it. I even gave a link to the documentation page where the example is taken from.
Or maybe I'm not thinking straight and you're talking about something else?

**Comment by pardeike** [comment]
Your feedback is about other parts of the documentation that are explained elsewhere and have nothing to do with the documentation of a reverse patch. These are all basic reflection and visibility questions that are out of scope for Harmony and are solved by simply googling or looking up stackoverflow. The documentation covers attributes and why they only work with public types and members. They are not meant to work in all cases. The typical answer to this is “use a publiziser” or “use reflections or (for convenience) AccessTools”.

**Comment by Release** [comment]
My feedback refers to the “[Reverse Patch](https://github.com/pardeike/Harmony/blob/f54b3794d63981789be21039bc0cc94d332d052b/Harmony/Documentation/examples/reverse-patching.cs#L15)” **documentation page** with an example of its implementation. How can it refer to something else, if it is **your code** (not mine from my head, but yours) on the **documentation page** that explains how to implement Reverse Patch. Isn't it hard to open the link in the first sentence of the first post and see for yourself?<br>
**The original question in this thread was not how to access members of a closed class. It was about why the code in the documentation does not work. And will using the `TargetMethod()` method with the **[HarmonyReversePatch]** attribute work? Because the documentation doesn't have that, but rather non-working code.<br>**
The **code in your documentation** that you have as an **example simply doesn't compile**, which is what I wrote in my first post. Even if the error is not directly related to the topic of the documentation page, i.e. a reverse patch, it is still an error.<br>
Microsoft has the same documentation for C# and they also provide examples there, which you can even execute right on the page. What would it look like if the given code, for example from this [page](https://learn.microsoft.com/en-us/dotnet/api/system.type.getmethod?view=net-8.0#system-type-getmethod(system-string)) did not compile?

**Comment by Release** [comment]
> The whole point of a reverse patch is to make the original accessible because it’s either private or you can’t call it directly because it’s an overloaded base method. Maybe the use of annotations isn’t a great use and may be misleading. The top part of the code represents some code that is not part of your code base so it was never meant to be compiled together with the bottom part.

I think most who come here or to the Reverse Patch documentation section should understand why it's needed. So I don't see why it needs to be explained? But, if we're going to talk about it, the Reverse Patch is essentially needed as an alternative to this code:
`AccessTools.FirstMethod(AccessTools.TypeByName("OriginalCode"), m => m.Name.Contains("Test")).Invoke(originalInstance, new object[] { 100, "hello" });`
Or similar using the methods of the Net system libraries.

The top part although it is an abstract example and should belong to the code in the original assembly, is bug free and compiles perfectly. Even though the upper part is not complete, it presents a simplified version.
The lower one though is not the code of the same assembly as the upper one, but must be compiled with a reference to it. And this will not happen by an obvious error in the code.
 
> It’s kind of hard to represent these advanced concepts in like 20 lines of demo code but I rather have something than nothing. Making the original public would mean you could simply use it directly and would make for a bad example for a reverse patch.

Why should the choice be between “either this or nothing”? If I can make the original public, I don't need a reverse patch at all, since invoking private causes a compilation error, not an execution error.
We are talking about an abstract but working example. Again, even if this example is incomplete.  It is one thing when the code is not compiled if it is incomplete and another when it is obviously written incorrectly taking into account the peculiarities of language logic.

For example, I didn't pick on the `originalInstance` variable acting as a parameter in this code block:
```
class Main
{
    void Test() =>
        // here we call OriginalCode.Test()
        Patch.MyTest(originalInstance, 100, "hello");
}
```
Because, it indicates that the code is incomplete. And if you add it correctly by declaring and initializing the variable, it will work. At the same time, using HarmonyPatch(typeof(OriginalCode), “Test”) will not work in any way, no matter how you add the code.
And once again, understating something in a certain place, assuming that the interested party will find the missing information elsewhere, is not the same as misrepresenting and misleading the information in the first place.

> Ultimately I think it might be better to use a TargetMethod in the code example but that might distract more than it helps.

I don't see how an extra 4 lines (excluding the empty one), of which only two are significant, can be distracting when they create a fully working example.
Don't like the 4 lines from my post above, make the example into one:
`public static MethodBase TargetMethod() => AccessTools.FirstMethod(AccessTools.TypeByName("OriginalCode"), m => m.Name.Contains("Test"));`
Don't like it as above, specify part of it, but with a comment:
`public static MethodBase TargetMethod() { // see section Auxiliary methods }`
This code, if augmented, will work.

The way I see it, example code, even abstract code, should serve as a template, some or all of which can be used for further refinement simply by copying it into your own code. And with most of the examples in the documentation of this tool you can do that, but not with this particular one.

**Comment by Release** [comment]
Since this is already turning into an argument for argument's sake and I'm tired of writing huge posts in an attempt to convince you of the necessity of correcting the example, I propose to end our discussion here, if its topic is "need-not-need" and not "how best to correct".
These changes are not worth the time spent. I just wish that an excellent tool had quality documentation that helps to implement a particular action as easily as possible without being misleading.
