### ISSUE TITLE
Publish on NuGet

### ISSUE THREAD

**Issue by antiufo** [pardeike/Harmony#55]
Have you published Harmony on NuGet? That would make it simpler to add Harmony to an existing project..

**Comment by Kittyfisto** [comment]
Not sure if this should be a different issue, but I would also prefer it if the published version were strong name signed (not that I'm a fan of SNS, but my stuff is used in applications which use SNS).

**Comment by pardeike** [comment]
I’ll look into adding signing. Thanks.

**Comment by pardeike** [comment]
I would like to do it but hadn't had the time to find a good article about signing. If I have multiple projects, are those signed with the same identity? What if, two users use two different signed Harmony versions because they build from source themselves? Lots of questions. Harmony was designed from the start with a multi-user perspective and can co-exist with other versions of itself. But signing (beside the basics) is new to me.

**Comment by antiufo** [comment]
> If I have multiple projects are those signed with the same identity

That's how things are usually done, but even if you use different keys, it will still work.

> What if, two users use two different signed Harmony versions because they build from source themselves

You can either:
* Add the .snk to the repository (that's what I personally do for my open source projects, and what I think most people do)
* Let users sign with a "fake key" (but I don't know much about this option)

> Harmony was designed from the start with a multi-user perspective and can co-exist with other versions of itself

That won't change. If you are able to load different versions of the assembly now, it will still be possible after you add a strong name.

In order to set a strong name for your `.csproj`s, go to the project settings page in Visual Studio and create the .snk from there. Then you can reuse it in other `csproj`s.

Note that all the assemblies that a strong named assembly uses must also be strong named. (But assemblies that use your strong named assembly don't have to be strong named)

**Comment by wasabii** [comment]
I got NuGet package support added. But the author will have to publish it.

I also picked the package name "Harmony". And it appears this package name is already taken.

@pardeike Any preference on what you might pick?

**Comment by wasabii** [comment]
No ya don't. You just create an account, and upload a package.

**Comment by pardeike** [comment]
I see. I upload it as soon as 1.1.1 is released.

**Comment by pardeike** [comment]
Now available as Lib.Harmony
