### ISSUE TITLE
Is it possible to patch ALL the methods/properties/... in the given assembly/scope for the sake of ad-hoc execution logging?

### ISSUE THREAD

**Issue by Krupek20** [pardeike/Harmony#550]
Hi,

Assuming that the given application has the Harmony engine already set up and running (I am using Harmony.2.2.1.0\net45\0Harmony.dll)...

Is is possible to write a generic "patch" that is applied to each and every method/property/etc... in the given assembly (or some narrowed scope like e.g. given C# Namespace) and just logs the invoked method name/parameters/parameters' values/etc... to a file? 

The idea behind this question is to have, raw, ad-hoc, ability to generate a log file which traces application execution flow, and helps finding bugs on production environments - for application that does not have its own native tracing/logging of methods entering/exiting.

Can this be achieved with Harmony? Will it work (and would it be efficient) if hundreds of methods/properties are patched in a large application? Is this a good idea to do/try it?

I reviewed the topics below:
https://harmony.pardeike.net/articles/patching-auxiliary.html#targetmethods
https://harmony.pardeike.net/articles/annotations.html#patching-multiple-methods
and looks like they can be used as a starting point for what I need.

The problems that I encountered (for a very small application) were:
1.
NotSupportedException: Specified method is not supported.
HarmonyException: Patching exception in method `static System.Void Project1.Class1::InvokeIfRequired(Class1.T obj, System.Action'1<Class1.T> action)`
The method is like:
`public static void InvokeIfRequired<T>(this T obj, Action<T> action) where T : Control { ... }`
2.
Exception: Methods without body cannot have prefixes. Use a transpiler instead.
HarmonyException: Patching exception in method `static System.IntPtr Project1.Class1::GlobalLock(System.IntPtr handle)`
The method is like:
`public static extern IntPtr GlobalLock(IntPtr handle);`

Thank you,
Marcin

**Comment by pardeike** [comment]
If you mass-patch methods you need to exclude some unpatchable methods: methods without body, external methods, generic methods etc.

**Comment by pardeike** [comment]
In general this is possible with the current API. Since this isn't a bug or a feature request I close this issue. Support is done via the official discord.
