### ISSUE TITLE
Is it possible to apply all, but specified, patches? Alternative solution to [HarmonyPatchCategory] for Harmony < v2.3?

### ISSUE THREAD

**Issue by Krupek20** [pardeike/Harmony#551]
Hi,

I found [HarmonyPatchCategory] attribute added in:
https://github.com/pardeike/Harmony/pull/498
commit 7a241fd, v2.3-prerelease.3, on Sep 8, 2022

but...
I am using Harmony.2.2.1.0\net45\0Harmony.dll where this feature is not available.

Is there some workaround to patch all except selected set of patches (which can be applied later, on request, during application lifetime)?

Thank you,
Marcin

**Comment by pardeike** [comment]
No. That's why it was added to the next release.
