### ISSUE TITLE
Is it possible to insert a delegate into IL code?

### ISSUE THREAD

**Issue by w-while** [pardeike/Harmony#554]
Like (https://github.com/tModLoader/tModLoader/wiki/Expert-IL-Editing#approach-1---modifying-evaluation-stack)
In MonoMod mechod EmitDelegate can insert a delegate into IL code.It's very convenient.
How can I do Something like that with harmony.(Maybe introducing MonoMod?But how to use it in transpiler)

**Comment by pardeike** [comment]
That's not part of Harmony's way of doing things. Harmony requires static methods because they will be reused whenever some other mod.
