### ISSUE TITLE
Add strongname to make all projects can use this library

### ISSUE THREAD

**Issue by CreateAndInject** [pardeike/Harmony#555]
Suggestion from Microsoft:
> You should strong name your open-source .NET libraries. Strong naming an assembly ensures the most people can use it, and strict assembly loading only affects .NET Framework.

Signed project can be used in both signed or unsigned project, but unsigned project can only be used in unsigned project.

**Comment by pardeike** [comment]
I build on many platforms and signing is currently only possible on Windows. You can sign the unsigned dependency yourself. See https://github.com/dotnet/sign

**Comment by CreateAndInject** [comment]
> I build on many platforms and signing is currently only possible on Windows. You can sign the unsigned dependency yourself. See https://github.com/dotnet/sign

Why only support on windows? Other platform cant build a .net project with a .snk file?
