### ISSUE TITLE
Seemingly random NOP invalid IL errors

### ISSUE THREAD

**Issue by Aidanamite** [pardeike/Harmony#558]
Context:
basically I'm creating a system that will act as a simple way to define direct calls to private methods. An example of my system's implementation is as follows:
```cs
public static class ExtensionMethods {
        [Accessor(AccessorType.Field, typeof(TargetType), "target_field")]
        public static FieldType WhateverName(this TargetType obj) => default;
}
```
and the system will use harmony transpilers to replace the body of `Accessor` methods with a get/set of the field or call to the method specified

The bug:
For an unknown reason, a specific set of the patches (the same ones each time, but no noticable pattern between them) fail with the exact same error: `System.FormatException: Method METHOD_NAME cannot be patched. Reason: Invalid IL code in METHOD_NAME: IL_0007: nop`

every single one of the errors has the same IL offset of this invalid `nop`.

in an attempt to figure out what was happening, I tried enabling harmony's `DEBUG` and the logs didn't show any `nop` opcodes in the IL. The only thing I noticed from those logs is that every single patch that ended at IL offset 7 errored and no others, so this maybe the key condition for this to occur.

If you want, I can attach the harmony log and error log for the attempted patches (the `harmonyInstance.Patch` call is in a try catch so it tries to patch all the `Accessor` methods even if one fails).

the header information of the harmony patch log is:
### Harmony id=com.aidanamite.BenevolentSprites.Accessors, version=2.2.2.0, location=D:\Steam\steamapps\common\data-000001DEE1070080, env/clr=4.0.30319.42000, platform=Win32NT, ptrsize:runtime/env=8/Bits64, Windows

Attempted fix:
As an attempt to fix the issue with the method size in mind, I tried adding a `nop` to the start of methods that were that size and it didn't change what methods errored but it did change the errors slightly to say that IL offset 8 was now the problem and that the problem opcode is now some random other opcode (most of them just saying `unused32` or `unused66` or some other number)

**Comment by Aidanamite** [comment]
After many attempts to fix the issue I found what was needed to fix the issue by looking at compiler generated methods.

basically there were 2 issues that were causing the same error.
First issue, when replacing the code of a method that has the return type `void`, there must be a `nop` `ret` at the end, like you're returning `nop`.
Second issue, you must add exactly enough of the `pop` opcode to empty the stack before the `ret` (except for the value being returned of course)

So this was _not_ a bug with harmony, just that the error messages appeared to be complaining about something being there when in fact they were complaining that it wasn't there

**Comment by pardeike** [comment]
Yes. You need to handle the stack very correctly. There is a static checker in CIL that complains otherwise. You can also only have a RET without a previous NOP.

**Comment by Aidanamite** [comment]
for me, I needed to have the `nop`. if I didn't, it had the error

**Comment by pardeike** [comment]
That makes no sense. According to the documentation a NOP is a filler used for debugging. It has no effect. Maybe you have weird jumps and the CIL static preflight check does not like that (documented behaviour). Or your runtime is seriously weird.
