### ISSUE TITLE
Correct way to patch TWindow GetWindow<TWindow>()

### ISSUE THREAD

**Issue by AMacro** [pardeike/Harmony#559]
Ok, first off, I'm a hobby level programmer, newish to C#.

I'm trying to patch the below method, but I believe this would fall into the class of a 'generic' and therefore is not easy to patch?

```
public TWindow GetWindow<TWindow>()
{
	foreach (object obj in base.transform)
	{
		TWindow component = ((Transform)obj).GetComponent<TWindow>();
		if (component != null)
		{
			return component;
		}
	}
	throw new ArgumentException("Couldn't find TWindow");
}
```

What I am trying to do with my patch is iterate over a different object first, if nothing is found, then the original code is executed, so the effect is essentially:

```
public TWindow GetWindow<TWindow>()
{
	foreach (object obj in myObj.transform)
	{
		TWindow component = ((Transform)obj).GetComponent<TWindow>();
		if (component != null)
		{
			return component;
		}
	}

	foreach (object obj in base.transform)
	{
		TWindow component = ((Transform)obj).GetComponent<TWindow>();
		if (component != null)
		{
			return component;
		}
	}
	throw new ArgumentException("Couldn't find TWindow");
}
```

Normally I'd use a Prefix to redirect, run my code and either run the original or return __result, but my attempts have resulted in the patch failing with error: 

> HarmonyLib.HarmonyException: Patching exception in method UI.Common.TWindow UI.Common.WindowManager::GetWindow() ---> System.NotSupportedException: Specified method is not supported.

Is this a bug, am I doing something wrong, or is this just not possible with this type of method?
If it's not possible, could I use the transpiler to insert some instructions?

e.g.:
```
TWindow component = MyGetWindow<TWindow>()
if (component != null)
	return component

```

**Comment by pardeike** [comment]
Dokumentation says that generics are not supported. 

Do **NOT** use this form to send support questions. If you send things like "How do I do X" or "It does not patch Y" your submission will be closed and you will be forwarded to the official Harmony Discord channel anyway.

**OFFICIAL DISCORD:** https://discord.gg/xXgghXR
