### ISSUE TITLE
Harmony CANNOT be used in Godot!!!!

### ISSUE THREAD

**Issue by SavingPot** [pardeike/Harmony#566]
Harmony can't be used!
Godot 4.1 with Harmony 2.2.2 CANNOT RUN;
Godot 4.2 with Harmony 2.3 CANNOT RUN, too!

2.2.2 and 2.3 have different errors.
Help!

**Comment by pardeike** [comment]
More information please

**Comment by pardeike** [comment]
Closing this due to lack of feedback
