### ISSUE TITLE
Any restriction to hook .Net service?

### ISSUE THREAD

**Issue by yangboyd** [pardeike/Harmony#567]
Hook fail, No log file  generated.

**Comment by pardeike** [comment]
More information please

**Comment by yangboyd** [comment]
The code hang at line: type.GetCustomAttributes(true).
HarmonyLib.HarmonyMethodExtensions
		/// <summary>Gets all annotations on a class/type</summary>
		/// <param name="type">The class/type</param>
		/// <returns>A list of all <see cref="T:HarmonyLib.HarmonyMethod" /></returns>
		// Token: 0x060001F4 RID: 500 RVA: 0x0000B51C File Offset: 0x0000971C
		public static List<HarmonyMethod> GetFromType(Type type)
		{
			return (from attr in type.GetCustomAttributes(true)<<<<===============
				select HarmonyMethodExtensions.GetHarmonyMethodInfo(attr) into info
				where info != null
				select info).ToList<HarmonyMethod>();
		}

**Comment by pardeike** [comment]
Do you have a stacktrace?
What .NET version?
What Harmony version?
What operating system?
On what hardware?
Is this for a game or a web server container?
When do you start the patch operation?
Could it be that the class that contains the method you want to patch has a static initializer that runs when you patch the method but that is not suppose to run so early?

Answer to all questions are required or else I can’t help

**Comment by yangboyd** [comment]
More info:
Harmony 2.1.0.
.Net 4.3
Windows 10.
X86_64
web server.
Use Extreme Injector v3 , follow this sample https://github.com/AmmarHourani/Simple-Harmony-2.

The target function is in a dll.
Succeed bypassing this error by manual load and manual patch.
The patch seems OK, but not triggered.
The call stack in dnSpy is like this:
![捕获](https://github.com/pardeike/Harmony/assets/37931362/05fd7eb8-034e-4cf9-9546-660a90e3fcb5)

It looks like the target method is called in unnormal way. Can this kind of method be hooked?

**Comment by pardeike** [comment]
There are few possible reasons why your patch isn’t called:
1) the original method is too short and is inclined at runtime
2) due to this being a webserver things that normally work can be quite restricted due to security reasons
3) you are using an outdated Harmony version

**Comment by yangboyd** [comment]
The call stack is the way how the original method is called. It's called via reflection.
Our hook is implemented via reflection too? 
Maybe they conflicted.

**Comment by yangboyd** [comment]
Fixed, It's the app domain isolation, need inject to the specific app domain.

**Comment by pardeike** [comment]
Yeah, see my second guess. Nice
