### ISSUE TITLE
Getting an instance from the TargetMethod patch

### ISSUE THREAD

**Issue by cry-1337** [pardeike/Harmony#568]
I have internal class Glazier_uGUI. I need to patch method UpdateCursor to do custom in-game cursor.
I wrote code for this but i have no idea how to get instance of it.

```
static MethodBase TargetMethod()
{
     var type = AccessTools.TypeByName("Glazier_uGUI");
     return AccessTools.Method(type, "UpdateCursor");
}

private static bool Prefix()
{
      return false;
}
```

**Comment by pardeike** [comment]
Have you checked out the documentation? You simply inject the instance into your patch. Issue tracking is not for support questions so please use the official discord.
