### ISSUE TITLE
Using GeneratedRegex causes failed compile due to ReadOnlySpan

### ISSUE THREAD

**Issue by DubyaDude** [pardeike/Harmony#570]
**Describe the bug**
When attempting to utilize dotnets `GeneratedRegex` with the Harmony lib being imported, the generated regex class causes a compile time error as of Harmony 2.3.0 prerelease 6.

**To Reproduce**
Code:
```csharp
public partial class PlayGround
{
    [GeneratedRegex(@"\w+")]
    private static partial Regex GetGeneratedRegex();
}
```
Error on compile:
Code CS0433
```The type 'ReadOnlySpan<T>' exists in both '0Harmony, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'```

**Expected behavior**
No compile time error.

**Screenshots / Code**
![devenv_sCFRdbI5Jj](https://github.com/pardeike/Harmony/assets/13679909/9ea008b6-ae3c-4b82-a2f3-c524a291c16e)
![image](https://github.com/pardeike/Harmony/assets/13679909/56a23ccb-6ea6-4c88-bc26-2e51930df3d5)

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET 8
 - Harmony 2.3.0-prerelease.7

**Additional context**
Was not an issue prior, started as of updating from Harmony 2.3.0-prerelease.5 -> 2.3.0-prerelease.7

**Comment by DubyaDude** [comment]
Sorry, was not aware of the change of the main NuGet package becoming a `Fat` version, switching to `Thin` resolved it.

**Comment by Aragas** [comment]
The issue should be resolved for the Fat version once the next version is out
