### ISSUE TITLE
Companion project promotion: Harmony Tools

### ISSUE THREAD

**Issue by DarkDaskin** [pardeike/Harmony#603]
I have created a companion project for the Harmony library - [Harmony Tools](https://github.com/DarkDaskin/HarmonyTools). It currently consists of an extensive set of Roslyn static analysis rules for attribute-based patching and is available as a NuGet package as well as Visual Studio extension.

Maybe you'll want to mention it in the Harmony documentation.

**Comment by pardeike** [comment]
Would love to but I think you first need to work a bit on your documentation. Also, if you come up with a PR on how you want the promotion to look like you make my life easier and better get what you want.

**Comment by Aragas** [comment]
Great work! I was also doing a Harmony analyzer, it's main focus was to make sure that dynamic types (basically string based reflection) was statically checked. Perhaps it might give you some new ideas 😊
https://github.com/BUTR/BUTR.Harmony.Analyzer

**Comment by pardeike** [comment]
The VS link is broken (https://marketplace.visualstudio.com/items?itemName=darkdaskin.HarmonyTools) and there is no documentation. For now, I close this. If you ever get this into a proper release you can reopen this issue or create a new one.
