### ISSUE TITLE
PatchFunctions.UpdateWrapper NotImplementedException on MacOS

### ISSUE THREAD

**Issue by AqlaSolutions** [pardeike/Harmony#607]
This exception occurs when launching from Rider:
![image](https://github.com/pardeike/Harmony/assets/3465565/546cc69c-81b2-413d-ab53-99f23e12c671)

We don't have this problem on Windows or inside asp.net linux docker containers.

The exception occurs even when launching without debugging.

The patch code:

```
[HarmonyPatch(typeof(ClassName), "MethodName")]
[UsedImplicitly]
static class Patch
{
    [UsedImplicitly]
    [HarmonyPrefix]
    static bool Prefix(ClassName __instance)
    {
        if (__instance.Property is AnotherClass { AnotherProperty: true })
            return false;
        return true;
    }
}
```

**Runtime environment (please complete the following information):**
 - OS:  MacOS Ventura 13.3.1 (a)
 - .NET version 7.0.402
 - Harmony version 2.3.3 (thin)
 
Our host application is ASP.NET Web Api app.

**Comment by pardeike** [comment]
For reference, I am as I type, using Harmony 2.3.3 on my MacBook Air M2 with RimWorld just fine.

**Comment by AqlaSolutions** [comment]
The non-thin doesn't work for us (exception when debugging from Rider). What are the dependencies? The docs mentions that we one may need to add them but what exactly to add?

**Comment by pardeike** [comment]
If you use an IDE (like Visual Studio, don’t know about Rider, never used it) it will automatically download the dependencies. The nuget package also lists the dependencies as does a decompiler like dnSpy

**Comment by AqlaSolutions** [comment]
These are nuget package dependencies:

    <dependencies>
      <group targetFramework=".NETFramework3.5">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.5.2">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.7.2">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.8">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp3.0">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp3.1">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
      <group targetFramework="net5.0">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="5.0.2" exclude="Build,Analyzers" />
      </group>
      <group targetFramework="net6.0">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="6.0.9" exclude="Build,Analyzers" />
      </group>
      <group targetFramework="net7.0">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="7.0.4" exclude="Build,Analyzers" />
      </group>
      <group targetFramework="net8.0">
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="8.0.1" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Lib.Harmony.Ref" version="2.3.3" exclude="Build,Analyzers" />
        <dependency id="MonoMod.Core" version="1.1.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>

The assembly explorer it shows more:
![image](https://github.com/pardeike/Harmony/assets/3465565/996a9a93-3a15-4463-9e1c-9518718a35c3)


So for .NET 7 I need to manually add the nuget packages `System.Text.Json` and `MonoMod.Core`, correct?

**Comment by AqlaSolutions** [comment]
We've found the cause of this exception. MonoMod doesn't support ARM architecture on MacOS.
![image](https://github.com/pardeike/Harmony/assets/3465565/0e0614c8-ff59-4326-aa9a-a93e0e742fd2)
Is there something we can do to make it work there?

**Comment by pardeike** [comment]
Contribute to the complex task of patching low level architecture in the MonoMod repository? Or simply use MacCatalyst for now?

**Comment by AqlaSolutions** [comment]
Excuse me, what do you mean by using MacCatalyst? I'm not a Mac user, how MacCatalyst can help to solve this? 

Do you know any Harmony-like library that supports MacOS ARM?

**Comment by pardeike** [comment]
You missed my comment earlier: https://github.com/pardeike/Harmony/issues/607#issuecomment-2061115901

**Comment by AqlaSolutions** [comment]
Perhaps RimWorld works because Unity uses its own fork of dotnet runtime based on Mono and it may also use something like rosetta emulation. I haven't found a way to do it with dotnet.

**Comment by pardeike** [comment]
I close this issue as the real work has to be done in MonoMod (and is picking up a bit lately)
