### ISSUE TITLE
How do i change valuetype

### ISSUE THREAD

**Issue by Arales03482** [pardeike/Harmony#608]
I would like to know how to edit the valuetype in a transpiler patch

![image](https://github.com/pardeike/Harmony/assets/69711892/c77cd161-0050-497b-997c-dbcd16d3bf5a)

I want to edit the 1311IL instruction to a different function

**Comment by pardeike** [comment]
You modify the `CodeInstruction` at that point before you emit it. There are plenty of examples of transpilers when you search Github for transpiler C# code. I recommend to check out the official discord for more help.
