### ISSUE TITLE
Hooking Dotnet framework dlls

### ISSUE THREAD

**Issue by danturn** [pardeike/Harmony#61]
Hi, 

I'm trying to hook a call to a method in a .net framework class ("Open" in the SqlConnection class in System.Data.dll to be precise).

I've got harmony working with a dummy class example but i get a "Common Language Runtime detected an invalid program." when i try and use the real SqlConnection class.

Any ideas why this might be?

Dan

**Comment by pardeike** [comment]
It could be that your environment or container application does not allow runtime manipulations. It really depends. Base classss are often protected by some mechanism. Harmony was designed to manipulate applications that don’t try to protect themselves against modding/changes.

**Comment by danturn** [comment]
ok, cool. thanks for that. I've moved to patching at a different level and that is working fine in debug mode... however in release mode it is not calling the patches. It seems to be to do with the "optimize code" checkbox... i have marked my patches as  [MethodImpl(MethodImplOptions.NoInlining)]...  Do you have any other ideas?

Dan

**Comment by pardeike** [comment]
Unfortunately, if the compiler inlines methods, then there is nothing to patch. The NoInlining annotation is AFAIK not respected in most cases.
