### ISSUE TITLE
Harmony AccessTools.MakeDeepCopy fails when target contains a constant or static readonly field

### ISSUE THREAD

**Issue by xADDBx** [pardeike/Harmony#619]
**Describe the bug**
When using AccessTools.MakeDeepCopy on a class which contains a constant field, Harmony will cause a `System.FieldAccessException: Cannot set a constant field`.

**To Reproduce**
1. Create an executable program
2. Create another class with a constant field in it
3. In the Main method, create an instance of the class and call MakeDeepCopy on it
4. 
```
System.FieldAccessException: Cannot set a constant field.
   at System.Reflection.MdFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at HarmonyLib.Traverse.SetValue(Object value)
   at HarmonyLib.AccessTools.<>c__DisplayClass102_0.<MakeDeepCopy>b__0(String name, Traverse src, Traverse dst)
   at HarmonyLib.Traverse.<>c__DisplayClass39_0.<IterateFields>b__0(String f)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at HarmonyLib.Traverse.IterateFields(Object source, Object target, Action`3 action)
   at HarmonyLib.AccessTools.MakeDeepCopy(Object source, Type resultType, Func`4 processor, String pathRoot)
   at HarmonyLib.AccessTools.MakeDeepCopy[T](Object source)
   at Harmonyissue.Program.Main(String[] args) in D:\Programming\Projects\Modding\HarmonyStuff\Harmonyissue\Harmonyissue\Program.cs:line 16
 ```

**Expected behavior**
Const fields should be ignored when creating a DeepCopy

**Screenshots / Code**
![grafik](https://github.com/user-attachments/assets/63bf2416-ca0d-490c-8e6b-44883246b4a2)
![grafik](https://github.com/user-attachments/assets/0beedb56-8ee2-4c87-8e08-8f6a686608b9)

**Runtime environment (please complete the following information):**
 - `OS:` Windows 10, 64bit
 - `.NET Version:` I've managed to reproduce this error in .NET Framework 4.8.1 (Unity and non-Unity runtime), .NET 6.0 and .NET 8.0. I assume it's an issue on all versions
 - `Harmony Version:` Tested on Harmony 2.3.3 and Harmony 2.3.1.1.
 - `Runtime:` I've reproduced it in both `Pathfinder: Wrath of the Righteous` and `Warhammer 40,000: Rogue Trader` additionally I can reproduce this in a simple console application

**Comment by xADDBx** [comment]
Doing a quick test, the following seems to have fixed my local issue:

```cs
[HarmonyPatch]
public static class Patches {
    [HarmonyPatch(typeof(Traverse), nameof(Traverse.SetValue)), HarmonyPrefix]
    public static bool SetValue(object value, ref Traverse __result, Traverse __instance) {
        var infoField = AccessTools.Field(typeof(Traverse), "_info");
        var methodField = AccessTools.Field(typeof(Traverse), "_method");
        var rootField = AccessTools.Field(typeof(Traverse), "_root");
        var paramsField = AccessTools.Field(typeof(Traverse), "_params");
        MemberInfo _info = infoField.GetValue(__instance) as MemberInfo;
        MethodBase _method = methodField.GetValue(__instance) as MethodBase;
        object[] _params = paramsField.GetValue(__instance) as object[];
        object _root = rootField.GetValue(__instance);
        if (_info is FieldInfo fi) {
            bool isConst = fi.IsLiteral && !fi.IsInitOnly;
            Console.WriteLine(isConst);
            if (!isConst)
                ((FieldInfo)_info).SetValue(_root, value, AccessTools.all, null, CultureInfo.CurrentCulture);
        }
        if (_info is PropertyInfo)
            ((PropertyInfo)_info).SetValue(_root, value, AccessTools.all, null, _params, CultureInfo.CurrentCulture);
        if (_method is not null)
            throw new Exception($"cannot set value of method {_method.FullDescription()}");
        __result = __instance;
        return false;
    }
}
```

That is, checking whether the FieldInfo IsLiteral and is not IsInitOnly seems to suffice as a const check. I haven't tested whether this would break existing behaviour however.

**Comment by xADDBx** [comment]
I just tried testing the different possible combinations of IsLiteral, IsInitOnly and IsStatic. At the same time I noticed that static readonly fields will also cause an exception:
![grafik](https://github.com/user-attachments/assets/c9fc34d8-5407-4713-b6d7-3089fd930f6a)


FieldModifiers  | IsLiteral | IsInitOnly | IsStatic
                       | False     | False         | False
readonly          | False     | True          | False
static               | False     | False         | True
**static readonly | False     | True          | True** 
**const               | True      | False         | True**

**Comment by pardeike** [comment]
I know its late but I am *finally* getting to this. I have a slighly different approach. I added this to `Traverse`:

```cs
/// <summary>Checks if the current field or property is writeable</summary>
/// <returns>true if writing is possible, false otherwise</returns>
///
public bool IsWriteable()
{
	if (_info is FieldInfo)
	{
		var fi = (FieldInfo)_info;
		var isConst = fi.IsLiteral && fi.IsInitOnly == false && fi.IsStatic;
		var isStaticReadonly = fi.IsLiteral == false && fi.IsInitOnly && fi.IsStatic;
		return isConst == false && isStaticReadonly == false;
	}
	if (_info is PropertyInfo)
	{
		// check if there is a setter
		var pi = (PropertyInfo)_info;
		return pi.CanWrite;
	}
	return false;
}
```

since its of general interest and add a check in the copy loop of `MakeDeepCopy`.
