### ISSUE TITLE
Method overloading

### ISSUE THREAD

**Issue by Edsparr** [pardeike/Harmony#62]
Hi! I got a problem with trying to make so when a method gets called (example: method1) that is overloaded harmony can't register the correct method of them any help?

Example:

public void method1(string h){}
public void method1(){}

    [HarmonyPatch(typeof(TheClass), "method1")]
    public class AskAttackPatch
    {

        [HarmonyPrefix()]
        public static bool Prefix(string h)
        {
            Console.WriteLine("fdsdfsfd");
            return true;
        }
    }

This throwws an error, any help?

**Comment by pardeike** [comment]
Overloading is a concept a Compiler understands. Harmony operates on IL code level after the compiler has been making instructions of your class methods. What you need is to find the overloaded method or it’s base and patch that instead. Rule of thumb: if a method does appear in a disassembler output then you can patch it.
