### ISSUE TITLE
Request: Access a method's local variable from patch

### ISSUE THREAD

**Issue by CiarenceW** [pardeike/Harmony#624]
A lot of the times, a method might have a local variable that I want to access and manipulate (for example a GameObject that has been instantiated), but this variable doesn't get assigned to anything, so I have to write a whole Transpiler in order to access it.

I thought adding a `__localVariable_X` patch parameter, where X is the local variable's index, would solve this problem.   
So to test it, I wrote a Transpiler that patches the EmitCallParameter in Harmony and adds support for this feature, and it worked!

I forked the master and [added support for it](https://github.com/CiarenceW/Harmony/commit/f709c6096734efad271f3455264aab835ea8ef05), along with [a bunch of tests](https://github.com/CiarenceW/Harmony/commit/eed49038e05df6b2b6b921f3eef8cf3acd305f70), I'm assuming there's some edge cases I haven't thought of, but the basics are there.

**Comment by pardeike** [comment]
People have asked for this many times. Unfortunately there is a problem with this approach: it is very limited. It does not work in a prefix. It is also weird that the variable scope is wrong when being accessed in a postfix. It has many edge cases where it makes no sense to use the local variable. 

So I have to weight the benefits of implementing this and giving a solution to some users that find it useful against the problems it creates: it will confuse users. They will try to use it, abuse it, or come with support questions about it. If the local variable is assigned conditionally then it might not work as expected sometimes. 

To me it is a promise that is hardly ever hold and that is bad software design. And that’s why I so far have not considered adding it.

**Comment by CiarenceW** [comment]
Fair enough, thanks for the detailed explanation!
