### ISSUE TITLE
Debug mode fails

### ISSUE THREAD

**Issue by robert94p** [pardeike/Harmony#625]
After updating Lib.Harmony to version 2.3.3, an error occurs when launching the project in debug mode
`System.TypeLoadException: Could not load type 'CORINFO_METHOD_INFO' from assembly 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

**Comment by pardeike** [comment]
Duplicates: https://github.com/pardeike/Harmony/issues?q=is%3Aissue+CORINFO_METHOD_INFO
