### ISSUE TITLE
Unable to load shared library due to executable stack permission denied

### ISSUE THREAD

**Issue by robert94p** [pardeike/Harmony#626]
An error occurs when attempting to add the patch:

`Unhandled exception. HarmonyLib.HarmonyException: Patching exception in method System.Void Npgsql.NpgsqlCommand::TraceCommandStart(Npgsql.Internal.NpgsqlConnector connector)
Unhandled exception. HarmonyLib.HarmonyException: Patching exception in method System.Void Npgsql.NpgsqlCommand::TraceCommandStart(Npgsql.Internal.NpgsqlConnector connector)
---> System.DllNotFoundException: Unable to load shared library '/tmp/mm-exhelper.so.QBfWQg' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /tmp/mm-exhelper.so.QBfWQg: cannot enable executable stack as shared object requires: Permission denied
---> System.DllNotFoundException: Unable to load shared library '/tmp/mm-exhelper.so.FfwESi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /tmp/mm-exhelper.so.FfwESi: cannot enable executable stack as shared object requires: Permission denied
at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
--- End of inner exception stack trace ---
at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
--- End of inner exception stack trace ---
at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
at HarmonyLib.PatchClassProcessor.Patch()`

Is there any way to bypass this? without disabling the security mechanism

**Comment by pardeike** [comment]
Can you please state a bit about your environment and all versions of software involved?

**Comment by pardeike** [comment]
Closed due to inactivity
