### ISSUE TITLE
Issue with patching constructors

### ISSUE THREAD

**Issue by mrdmrd** [pardeike/Harmony#63]
Hi.
i can use prefix on constructor but cant access any fields or properties via Access Tools.
Field is always null.
(FieldNames is accessible from AccessTools.GetFieldNames()

is anyone have solution for patching constrcutors or sample to patch constructors ?

**Comment by pardeike** [comment]
You need to understand how constructors work. Have a look at a typical IL code for a constructor. They are in fact no constructor but instead a combination of empty object creation and then an initialise phase that executes the code in your constructor to prepare the empty object.

As a result, it isn't feasible to use a Prefix. You should use a transpiler or a Postfix instead.

**Comment by mrdmrd** [comment]
thank you for answer @pardeike 
i use postfix for changing fields after original constructor executed.

this is sample of using postfix on constructor and work like a charm
`void StartPatch() {
				var method_Org_Constructor = (MethodBase)(typeof("Class").GetMember(".ctor", AccessTools.all)[2]);
				var method_Patch_PostFix = typeof(Constructor_Patch).GetMethod("Method_CTOR_Postfix", AccessTools.all);
				harmony.Patch(method_Org_Constructor, null, new HarmonyMethod(method_Patch_PostFix));
			}
			
			
			
			static bool Method_CTOR_Postfix(ref string __result, HarmonyInstance __instance, ref string parm1, ref string parm2)
			{
				FieldInfo fieldInfo_myFieldName = AccessTools.Field(typeof(OrgClass), "myFieldName");
				fieldInfo_myFieldName.SetValue(__instance, "MyValue");
			}`

**Comment by pardeike** [comment]
Great that you solved it. Enjoy

**Comment by RayKoopa** [comment]
Is it possible to hook up the postfix method with the `HarmonyPatchAttribute`? I tried the following for a constructor with a `ModeGame` parameter:

        [HarmonyPatch(typeof(GameFramework), ".ctor", new[] { typeof(ModeGame) })]
        public class GameFrameworkCtorPatch
        {
            private static void Postfix(GameFramework __instance, ModeGame mode)
            {
                Loader.CreateHook<GameFrameworkHook>(__instance, mode);
            }
        }

But I only got the exception

    System.ArgumentException: No target method specified for class Syroot.PacManCE2.GameFrameworkHook+CtorPatch
      at Harmony.PatchProcessor.ProcessType () [0x00000] in <filename unknown>:0 
      at Harmony.PatchProcessor..ctor (Harmony.HarmonyInstance instance, System.Type type, Harmony.HarmonyMethod attributes) [0x00000] in <filename unknown>:0 
      at Harmony.HarmonyInstance.<PatchAll>b__6_0 (System.Type type) [0x00000] in <filename unknown>:0 
      at Harmony.CollectionExtensions.Do[Type] (IEnumerable`1 sequence, System.Action`1 action) [0x00000] in <filename unknown>:0 
      at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <filename unknown>:0 
      at Syroot.PacManCE2.Core.Loader.Initialize (.Framework framework) [0x00000] in <filename unknown>:0

**Comment by pardeike** [comment]
The way to patch a constructor in Harmony is to not specify a method. Example:
```csharp
[HarmonyPatch(typeof(GameFramework)
[HarmonyPatch(new[] { typeof(ModeGame) })]
public class GameFrameworkCtorPatch
{
}
```

**Comment by RayKoopa** [comment]
Excellent! I must've missed it in the documentation, sorry!

**Comment by pardeike** [comment]
I think it's not in there ;-)

**Comment by RayKoopa** [comment]
On another note, how would I append something to a static constructor?

**Comment by pardeike** [comment]
Can you refine "append"? If you just want to execute code after the constructor ran, you create a Postfix that gets the instance and can work on it. Adding fields is not possible unless you try to create a subclass of the type of the returned instance and return an instance of that subclass. That might fail with code that checks for the exact type of the returned instance.

But a bit like this pseudo code:

```csharp
// original code:
class Foo {}
var foo = new Foo();
//
// your subclass:
class Foo2 : Foo
{
   public Foo2(Foo original) {}
}
//
// patch constructor foo:
static Postfix(ref Foo __result)
{
   __result = new Foo2(__result);
}
```
Not totally sure if this works but I think I used it once in my own code somewhere.

**Comment by RayKoopa** [comment]
What I meant is a postfix to _static_ constructors, e.g. .**c**ctor, not .ctor. I wonder if it's possible to "append" code to them that way. :thinking:

**Comment by pardeike** [comment]
Here is a simple static constructor in RimWorld:
```csharp
// RimWorld.StealAIUtility
static StealAIUtility()
{
  StealAIUtility.StealThresholdValuePerCombatPowerRange = new FloatRange(2f, 10f);
  StealAIUtility.tmpToSteal = new List<Thing>();
}
```
and it's IL code. Looks like you can simply append code there:
```
.method private hidebysig specialname rtspecialname static void .cctor () cil managed 
{
  .maxstack 8

  IL_0000: ldc.r4    2
  IL_0005: ldc.r4    10
  IL_000A: newobj    instance void Verse.FloatRange::.ctor(float32, float32)
  IL_000F: stsfld    valuetype Verse.FloatRange 
RimWorld.StealAIUtility::StealThresholdValuePerCombatPowerRange
  IL_0014: newobj    instance void class [mscorlib]System.Collections.Generic.List`1<class Verse.Thing>::.ctor()
  IL_0019: stsfld    class [mscorlib]System.Collections.Generic.List`1<class Verse.Thing> RimWorld.StealAIUtility::tmpToSteal
  IL_001E: ret
} // end of method StealAIUtility::.cctor
```

**Comment by RayKoopa** [comment]
Alright, thanks :D I just wondered if there's a HarmonyPatchAttribute usage for it :o

**Comment by pardeike** [comment]
No, it seems not. For now, just keep using attributes and add a `MethodBase TargetMethod()` method to that class.

**Comment by shdwp** [comment]
Anyone wondering why pardeike responses aren't working anymore, refer to the annotations documentation, you also need to specify `MethodType`:  https://harmony.pardeike.net/articles/annotations.html

**Comment by trabetti-hcl** [comment]
hi @pardeike , Referring to a previous comment here: https://github.com/pardeike/Harmony/issues/63#issuecomment-361929450

You advised that only Postfix and Traspilers are possible on Constructor.
I have attempted to add patch on a String Constructor and found that Postfix is also no longer possible. Is Transpiler the only way I can add a patch to String Constructor? It is possible at all? Thank You!
