### ISSUE TITLE
Tow Path problem while namespace be different from path or name

### ISSUE THREAD

**Issue by Lioncky** [pardeike/Harmony#631]
**Describe the bug**
```
For example:
My program name: myprog.dll My namesapce: myprog => The everything is gona be fine.
My program name: 123456.dll My namesapce: myprog => Patch not found
The Assembly should judge with namesapce instead of excuteable file because `mono` will identify Assembly name, not file name.

Another problem:
:) My program Path: C:/Game/managed/myprog.dll My namesapce: myprog => The everything is gona be fine.
:( My program Path: C:/myprog.dll My namesapce: myprog => Patch not found
Is the memory assembly hook affected by paths?

```
**Expected behavior**
Using assembly name to judge and load.
Assembly in memory can patch from unsame folder.

**Runtime environment (please complete the following information):**
 - OS:  Windows 11 22621 x64
 - .NET version 4.72
 - Harmony version 2.3.3

**Comment by pardeike** [comment]
Not sure how this is related to Harmony. For support, use the discord. GitHub issues are for bugs in Harmony - this is not a bug in Harmony.

**Comment by Lioncky** [comment]
Have discord, Sum up: 
1.HKnight.exe in game Managed dir-> Harmany ok 
2.HKnight.exe in game exe dir -> Harmany ok 
3.HKnight.exe in other dir -> Harmany error 
4.HKnight.exe->`HKnight.tmp` in any dir -> Harmany error 
Assem was loaded in CSharp Domain but Harmany knows the function method but can't apply hook.
HKnight is just a word name.

**Comment by pardeike** [comment]
Not enough information. Can you provide logs with errors? This looks like a dependency loading problem.

**Comment by pardeike** [comment]
It seems your stacktrace is missing the description or it occurs in a part that does not belong to Harmony directly. `ReportException` reports exceptions in user code and that part is not listed in the log. If you are using transpilers then the exception is likely inside your transpiler code.

**Comment by pardeike** [comment]
You can see that Harmony just handles a user exception and reports it. It’s up to you to make sure your own code does not throw exceptions: https://github.com/pardeike/Harmony/blob/f54b3794d63981789be21039bc0cc94d332d052b/Harmony/Public/PatchClassProcessor.cs#L293

**Comment by Lioncky** [comment]
![image](https://github.com/user-attachments/assets/c8195356-ad24-48a0-b1f5-dac7ef0e4b90)
No dep error, Harmony throw error only by file name

**Comment by pardeike** [comment]
Can you try the following: as early as possible, before PatchAll(), set `Harmony.DEBUG = true;` and run your program. Now Harmony should have created a file called `harmony.log.txt` on your Desktop folder. Please post this file here.

**Comment by pardeike** [comment]
Also, what is `Internal_ActiveSceneChanged()`? Is it one of your patch methods? Can you list it and its class here?

**Comment by Lioncky** [comment]
![image](https://github.com/user-attachments/assets/d61cc0cc-d541-4f7c-9288-6bdd80bddb63)
### Harmony id=com.example.scenechange, version=2.3.3.0, location=D:\Cookie\GM\0Harmony.dll, env/clr=4.0.30319.17020, platform=Win32NT
### Started from static System.Void HKnightCS.Program::OpenDevMenu(), location D:\Cookie\GM\Managed\XEBLA.exe
### At 2024-11-13 09.40.24
### Patch: static System.Void UnityEngine.SceneManagement.SceneManager::Internal_ActiveSceneChanged(UnityEngine.SceneManagement.Scene previousActiveScene, UnityEngine.SceneManagement.Scene newActiveScene)
### Replacement: static System.Void UnityEngine.SceneManagement.SceneManager::UnityEngine.SceneManagement.SceneManager.Internal_ActiveSceneChanged_Patch1(UnityEngine.SceneManagement.Scene previousActiveScene, UnityEngine.SceneManagement.Scene newActiveScene)
IL_0000: Local var 0: System.Boolean
IL_0000: Local var 1: System.Boolean
IL_0000: ldc.i4     0
IL_0005: stloc      1 (System.Boolean)
IL_0009: ldc.i4.1
IL_000A: stloc      1 (System.Boolean)
IL_000E: ldloc      1 (System.Boolean)
IL_0012: brfalse => Label1
IL_0017: ldarg      0
IL_001B: ldarg      1
IL_001F: call       static System.Boolean HarmonySceneManager::Prefix(UnityEngine.SceneManagement.Scene previousActiveScene, UnityEngine.SceneManagement.Scene newActiveScene)
IL_0024: stloc      1 (System.Boolean)
IL_0028: Label1
IL_0028: nop
IL_0029: ldloc      1 (System.Boolean)
IL_002D: brfalse => Label0
IL_0032: // start original
IL_0032: nop
IL_0033: ldsfld     UnityEngine.Events.UnityAction`2<UnityEngine.SceneManagement.Scene, UnityEngine.SceneManagement.Scene> UnityEngine.SceneManagement.SceneManager::activeSceneChanged
IL_0038: ldnull
IL_0039: cgt.un
IL_003B: stloc.0
IL_003C: ldloc.0
IL_003D: brfalse => Label2
IL_0042: nop
IL_0043: ldsfld     UnityEngine.Events.UnityAction`2<UnityEngine.SceneManagement.Scene, UnityEngine.SceneManagement.Scene> UnityEngine.SceneManagement.SceneManager::activeSceneChanged
IL_0048: ldarg.0
IL_0049: ldarg.1
IL_004A: callvirt   virtual System.Void UnityEngine.Events.UnityAction`2<UnityEngine.SceneManagement.Scene, UnityEngine.SceneManagement.Scene>::Invoke(UnityEngine.SceneManagement.Scene arg0, UnityEngine.SceneManagement.Scene arg1)
IL_004F: nop
IL_0050: nop
IL_0051: // end original
IL_0051: Label2
IL_0051: Label0
IL_0051: ret
DONE

**Comment by pardeike** [comment]
Ok, and I also would like to see the contents of `harmonyscenemanager::Prefix` and if possible the whole `harmonyscenemanager` or at least list all its methods without their body.

**Comment by Lioncky** [comment]
![image](https://github.com/user-attachments/assets/7904b9fc-91d2-48dd-9d89-2c3728d7639d)

```
[HarmonyPatch(typeof(UnityEngine.SceneManagement.SceneManager), "Internal_ActiveSceneChanged")]
class HarmonySceneManager
{
    [HarmonyPrefix]
    public static bool Prefix(Scene previousActiveScene, Scene newActiveScene)
    {
        Console.WriteLine($"[{previousActiveScene.name}]=>[{newActiveScene.name}]");

        return false;
    }
}

```

**Comment by pardeike** [comment]
Just saw the exception message in the last error you posted in https://github.com/pardeike/Harmony/issues/631#issuecomment-2472136952
```
Could not load file or assembly 'HKnightCS, ….' or one of its dependencies
```

That there is your problem. During patching not all dependencies are available and thus the runtime throws the exception because it cannot resolve a meta token to the actual type or member.

**Comment by Lioncky** [comment]
Right, actually it's mono's problem, HKnightCS is loaded just not called that name

**Comment by Lioncky** [comment]
After my research, the problem appeared bacause I gank the funciton of mono called `mono_assembly_invoke_search_hook_internal` and cause Harmony throw error.
