### ISSUE TITLE
Doc doesn't work on mobile 

### ISSUE THREAD

**Issue by scarletquasar** [pardeike/Harmony#632]
![Screenshot_20241114_072630_Samsung Internet.jpg](https://github.com/user-attachments/assets/5e63dbfb-bc28-4842-b50c-43ff90645012)

**Comment by pardeike** [comment]
This is how it looks on my iPhone:
![IMG_1383](https://github.com/user-attachments/assets/6e94e77a-2e70-497d-9897-d2a38ee7b7f3)

All you need to do is to open the table of contents and choose a class/type to see the API

**Comment by scarletquasar** [comment]
Thats okay but I suggest making everything open by default, I had to find 2 steps that can be confusing to other people

Steps:

![Screenshot_20241114_094106_Samsung Internet.jpg](https://github.com/user-attachments/assets/8d4b0973-8781-4fd5-9f50-4cd73741ba7c)

![Screenshot_20241114_094121_Samsung Internet.jpg](https://github.com/user-attachments/assets/d7762835-b7f7-4d95-ab67-c5eab53e3fbd)

**Comment by pardeike** [comment]
I am only using docfx and the default template. Not really much focus on that right now, I’m happy that I got automatic documentation generated at all.

**Comment by pardeike** [comment]
I just fixed the documentation. Hope you like it.
