### ISSUE TITLE
Is it possible to add values to an enum using Harmony?

### ISSUE THREAD

**Issue by ahk1221** [pardeike/Harmony#64]
What the title says ^

**Comment by pardeike** [comment]
Definitely not possible directly. Enums are converted to integer constants litter all over the place in compiled CIL code so the only way is to find all occurrences and change them manually.

**Comment by ahk1221** [comment]
I meant adding a new definition, not changing an existing one.

**Comment by pardeike** [comment]
That is within the answer I gave. That would just be using the new number (let’s say 5 on an enum that had only 1..4 values) in methods the enum is actually used. You can already use integer in CIL in enum assignments or comparisons so all you need to do is to use higher numbers there. On the CIL level it is no longer an object.

**Comment by Vlad-00003** [comment]
So - there is literraly nothing we can do?
I want to add some values to enum to handle them later, but as long as I can't... I think creating a patch would be the only way.... Shame =(

**Comment by pardeike** [comment]
An enum becomes a simple integer after compiling. So you really need to find all use cases and change that number. There is no other way since the original information is lost during compiling.

**Comment by Vlad-00003** [comment]
it has > 300 use cases, so... yeah =_=
