### ISSUE TITLE
Please, push NET9.0 fixes to NUGET

### ISSUE THREAD

**Issue by noverd** [pardeike/Harmony#641]
I can't use Harmony in 9.0.

**Comment by pardeike** [comment]
I don’t update Harmony too often because it’s a basic component and releasing it while it still has some serious crashing bugs is not ok.

If you’re in such a hurry you can always simply build it yourself.

**Comment by noverd** [comment]
I tried to update and added Harmony as a submodule. Alas, I got NU1008

**Comment by pardeike** [comment]
I think you need to build the thin version and supply the dependencies yourself. It’s weird that you get that error because when I release it on nuget, all I do is to Pack the three different versions.

**Comment by noverd** [comment]
Harmony.Thin + new version of MonoMod.Core helped

**Comment by apobekiaris** [comment]
fyi I also am in need for a .NET9 version what i did is simply remove all other framework targets and build with no issues. That fat client is simply amazing work, saved a lot of m,y time many thnks @pardeike. 

All tests are green for my framework
