### ISSUE TITLE
MonoMod.Utils throws exception in exported Godot build, and the solution.

### ISSUE THREAD

**Issue by EvilMask** [pardeike/Harmony#642]
**Describe the bug**
In an exported Godot build, when attempting to patch a method with a prefix, postfix, or finalizer method, Harmony fails to patch the method and throws an exception.

**To Reproduce**
Please refer to #572.

**Expected behavior**
Please refer to #572.

**Screenshots / Code**
Please refer to #572.

**Runtime environment (please complete the following information):**
 - OS: Windows 11, 64bit
 - .NET version: .NET 8 / .NET 9
 - Harmony version 2.3.3
- Godot 4.3.stable.mono

**Additional context**

I think I encountered the same bug as #572 and found the reason for it and a possible solution when playing with MonoMod. I know Harmony is not ready for .NET 9 yet, but the solution works in .NET 8 and should work in .NET 9 as well.

The reason is that different from the editor, the exported Godot build loads assemblies in an isolated load context. When creating a Hook/Detour/HarmonyPatch, the lib will create a new module `MonoMod.Utils.Cil.ILGeneratorProxy` through `MonoMod.Utils.Cil.ILGeneratorShim.ILGeneratorBuilder.GenerateProxy()`.

 The assembly will be created in `MonoMod.Utils.ReflectionHelper.Load(Stream stream)` as follow:

``` C#
            if (stream is MemoryStream ms)
            {
                asm = Assembly.Load(ms.GetBuffer());
            }
            else
            {
                using (var copy = new MemoryStream())
                {
                    stream.CopyTo(copy);
                    copy.Seek(0, SeekOrigin.Begin);
                    asm = Assembly.Load(copy.GetBuffer());
                }
            }
```
Then `MonoMod.Utils.Cil.ILGeneratorShim.GetProxy()` will create an instance of `ILGeneratorProxy<T>`:
``` c#
public ILGenerator GetProxy()
{
	return (ILGenerator)ILGeneratorBuilder.GenerateProxy()
		.MakeGenericType(GetType()).GetConstructors()[0].Invoke(new object[1] { this });
}
```
Since `Assembly.Load` won't load the dynamically created module into that isolated load context, the `MakeGenericType()` will throw an exception.
```
System.ArgumentException: GenericArguments[0], 'MonoMod.Utils.Cil.CecilILGenerator', on 'MonoMod.Utils.Cil.ILGeneratorProxy[TTarget]' violates the constraint of type 'TTarget'.
```
And this is how I fix it.
``` c#
#if NET5_0_OR_GREATER
            if (AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly()) is AssemblyLoadContext alc)
            {
                asm = alc.LoadFromStream(stream);
            }
            else
#endif
            {
                if (stream is MemoryStream ms)
                {
                    asm = Assembly.Load(ms.GetBuffer());
                }
                else
                {
                    using (var copy = new MemoryStream())
                    {
                        stream.CopyTo(copy);
                        copy.Seek(0, SeekOrigin.Begin);
                        asm = Assembly.Load(copy.GetBuffer());
                    }
                }
            }
```

**Comment by pardeike** [comment]
At this point I would you rather test `master` as it is what I want to release soon. Check out the platform tests under Actions - they should have nuget artefacts you can use. Or pack the project yourself to get the nuget package.

**Comment by pardeike** [comment]
Also, you really should file this in the MonoMod repository, I can’t do anything about this bug

**Comment by EvilMask** [comment]
> At this point I would you rather test `master` as it is what I want to release soon. Check out the platform tests under Actions - they should have nuget artefacts you can use. Or pack the project yourself to get the nuget package.

I built and tested `master` on my PC and got this exception. (Windows 11, .NET 9 runtime)
```
PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at HarmonyLib.PatchInfoSerialization.Serialize(PatchInfo patchInfo) in C:\Project\Harmony\Harmony\Public\Patch.cs:line 77
   at HarmonyLib.HarmonySharedState.UpdatePatchInfo(MethodBase original, MethodInfo replacement, PatchInfo patchInfo) in C:\Project\Harmony\Harmony\Internal\HarmonySharedState.cs:line 146
   at HarmonyLib.PatchProcessor.Patch() in C:\Project\Harmony\Harmony\Public\PatchProcessor.cs:line 144
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer) in C:\Project\Harmony\Harmony\Public\Harmony.cs:line 166
   at TestMod.MyMod.ModAwake()
```
