### ISSUE TITLE
[?] "Non platform assembly" for Harmony

### ISSUE THREAD

**Issue by fiziologus** [pardeike/Harmony#65]
Met while test handmade mod (only one dll-patch, no more) for RimWorld. I remove dll from _Assemblies_ except 0Harmony.dll, but error remain (and Harmony not load).
If uncheck mod from Mode List, "no platform assemly" also vanish. If check appeare. This some strange 0Harmony.dll load error.
In [output_log.txt](https://github.com/pardeike/Harmony/files/1728146/output_log.txt) chain launch: with mod->main menu->w/o mod->main menu->with mod.

**Comment by pardeike** [comment]
Do you have other mods enabled while testing this? Maybe some of them use Harmony too? There is a mod with an old, outdated or broken Harmony lib out there but I only heard reports about it, not which name of the mod. It produces similar errors like this.

**Comment by pardeike** [comment]
Are you using the binary version of Harmony or did you build it yourself?

**Comment by fiziologus** [comment]
> Are you using the binary version of Harmony or did you build it yourself?

Binary, latest.
Anyway I test on default-working mod with Harmony, and this rise same error, but all work. Perhaps this some Unity's crazy internal behavior not Harmony error.
