### ISSUE TITLE
Can't change the result of the function in the prefix.

### ISSUE THREAD

**Issue by Vlad-00003** [pardeike/Harmony#67]
Heyo! (^^)/
I'm currently working on the project for Subnautica.
And, for some reason, I can't make the prefix work as I want.
It's working - I'm sure - I've added the debug messages there, and they are working...
Here is what I'm trying to do:
There is a function - DevConsole.HasUsedConsole:

	public static bool HasUsedConsole()
	{
		return DevConsole.instance && DevConsole.instance.hasUsedConsole;
	}

Injection:
       ```harmony.Patch(HasUsedConsoleOriginal,new HarmonyMethod(HasUsedConsolePatched), null);```

And here is my code:

        public static bool HasUsedConsolePrefix(bool __result)
        {
            __result = true;
            Utils.Log($"Has used console prefix called! Result = {__result}");
            return false;
        }

So, basicly it should be working. And it is - the log is being created. As I return false - the original function must not be called, if I'm right. So - this function must return true.
But it's returning false...

It's working - I see in the log that injuction was successfull, and upon the call of the function I see ```Has used console prefix called! Result = True```,
but the actuall response is false...

I'm sorry if I'm doing smthing wrong, but I found nothing about it on wiki. Maybe I'm just blind ¯\_(ツ)_/¯

**Comment by Vlad-00003** [comment]
Right now, as long as it's simple function I've switched to Transpiler, just making the finc return true, but still. I wanna know the reason =)

**Comment by Vlad-00003** [comment]
Ok. Got it. I have to make the __result be a ref.
Yep. I was unable to figure it out for quite a while, so... yeah. Case closed. 
But I think a bit more info on the page https://github.com/pardeike/Harmony/wiki/Patching would be usefull for the begginers =3
Sorry everyone for being such an idiot (^^)/

**Comment by Vlad-00003** [comment]
Resolved #67

**Comment by pardeike** [comment]
I thought that it is quite obvious that you cannot change the original by assigning to a non-ref parameter. But great that you found the solution. Happy patching!

**Comment by Vlad-00003** [comment]
I'm just a blind idiot, don't mind me =D
I didn't even notice that i haven't made it ref.....
