### ISSUE TITLE
CodeInstruction operand cast fails.

### ISSUE THREAD

**Issue by Vlad-00003** [pardeike/Harmony#68]
So - hello agin =)
I'm sorry if this is a dumb question, but I've never worked with the IL in the c# before, so.... yeah.
I have a part of the function - 

	ldloc.s LiveMixin (7)
	ldc.r4 4
	ldloc.1 
	ldc.i4.s 9
	ldnull 
	callvirt Boolean TakeDamage(Single, Vector3, DamageType, UnityEngine.GameObject)

And I need to find it in the instructions. the only thing I came up with - to just check the instruction and the next 6 to be what I'm looking for. Code below shows how I'm doing so:

	var codes = new List<CodeInstruction>(instructions);
	int found = -1;
	for (int i = 0; i < codes.Count; i++)
	{
		if (i + 5 < codes.Count &&
			codes[i].opcode == OpCodes.Ldloc_S &&
			codes[i + 1].opcode == OpCodes.Ldc_R4 && (float)codes[i + 1].operand == 4f &&
			codes[i + 2].opcode == OpCodes.Ldloc_1 &&
			codes[i + 3].opcode == OpCodes.Ldc_I4_S &&
			codes[i + 4].opcode == OpCodes.Ldnull //&&
			//codes[i + 5].opcode == OpCodes.Callvirt && ((MethodInfo)codes[i].operand)?.Name == "TakeDamage"
			)
		{
			found = i + 1;
			break;
		}
	}

And now - the problem. codes[i+1] works just fine - id did checks the operand to be required value. But I want to also check the called function (in case the sourcecode would be changed). And now - the fun part - using ```((MethodInfo)codes[i].operand)?.Name``` causes ```System.Reflection.TargetInvocationException:
Exception has been thrown by the target of an invocation.```

I'm out of ideas...

**Comment by Vlad-00003** [comment]
Utils.Log($"{codes[109]}");
            Utils.Log($"{codes[109].opcode}");
            Utils.Log($"{codes[109].operand}");
            Utils.Log($"{codes[109].opcode.OperandType}");
            Utils.Log($"{codes[109].opcode.OpCodeType}");

	callvirt Boolean TakeDamage(Single, Vector3, DamageType, UnityEngine.GameObject)
	callvirt
	Boolean TakeDamage(Single, Vector3, DamageType, UnityEngine.GameObject)
	InlineMethod
	Objmodel

**Comment by erdelf** [comment]
I suggest using a soft cast `(codes[i].operand as MethodInfo))?.Name`

**Comment by Vlad-00003** [comment]
Same with the ```ldc.i4.s 9``` - actually it's enum value,
Adding ```&&(sbyte)codes[i].operand == 9``` causes the same problem.

**Comment by Vlad-00003** [comment]
Goddamn it. ```(codes[i].operand as MethodInfo)?.Name == "TakeDamage"``` did the trick....
But what about sbyte?

**Comment by Vlad-00003** [comment]
But why? the cast did work, and there shouldn't be exception, as ``as`` worked...

**Comment by erdelf** [comment]
I suggest instead casting the other side to an object

`codes[i].operand == (object)9`

**Comment by Vlad-00003** [comment]
Casting to an object resulting in false result - tried it. But one again - why safe cast worked? O_o

**Comment by erdelf** [comment]
a safe cast returns null instead of throwing an error.

**Comment by Vlad-00003** [comment]
(codes[107].operand == (object)9) = False
But it's not null =D

**Comment by erdelf** [comment]
well I meant it returns null when the cast fails

**Comment by Vlad-00003** [comment]
That's the point. ``as`` returns null if the cast fails. ```(Type)``` throws exception. 
But the cast SHOULD work. And it works - with ```as```...
About the sbyte. I'm totally out of my mind.
```Utils.Log($"(sbyte) codes[107].operand == 9 - {(sbyte) codes[107].operand == 9}");```
Works.
```(sbyte)codes[i + 3].operand == 9``` Doesn't. i on that point is 104...

**Comment by erdelf** [comment]
can't help you with that.. seems to me like you misscounted something there.

**Comment by Vlad-00003** [comment]
Now it's finally done... For some reason simple cast doesn't work at all. The only way - using safecast. I have no idea why.

        public static IEnumerable<CodeInstruction> Transpiler(MethodBase original,
            IEnumerable<CodeInstruction> instructions)
        {
            var codes = new List<CodeInstruction>(instructions);
            int found = -1;
            for (int i = 0; i < codes.Count; i++)
            {
                if (i + 5 < codes.Count)
                {
                    Utils.Log(i.ToString());
                    var t = (codes[i + 3].operand as sbyte?);
                    var f = (codes[i + 1].operand as float?);
                    if (codes[i].opcode == OpCodes.Ldloc_S &&
                        codes[i + 1].opcode == OpCodes.Ldc_R4 && f.HasValue && f.Value == 4f &&
                        codes[i + 2].opcode == OpCodes.Ldloc_1 &&
                        codes[i + 3].opcode == OpCodes.Ldc_I4_S && t.HasValue && t.Value == 9 &&
                        codes[i + 4].opcode == OpCodes.Ldnull &&
                        codes[i + 5].opcode == OpCodes.Callvirt &&
                        (codes[i + 5].operand as MethodInfo)?.Name == "TakeDamage"
                    )
                    {
                        found = i + 1;
                        break;
                    }
                }
                else
                    break;
            }

            if (found == -1)
            {
                Utils.Log("Unable to patch IL in ExosuitDrillArm.OnHit!");
            }
            else
            {
                codes[found].operand = 16f;
            }
            return codes.AsEnumerable();
