### ISSUE TITLE
Add a "only override original method" option for prefix methods

### ISSUE THREAD

**Issue by tony56a** [pardeike/Harmony#7]
Hi,

I've been experimenting with Harmony in a mod for Cities:Skylines as a replacement for [another method swizzling/detouring/replacement technique](https://github.com/sschoener/cities-skylines-detour).

 It seems to work pretty well, but I have some concerns regarding multiple mods attempting to prefix the same method, since a lot of the scenarios involve skipping the original method. As the return value for prefix methods skips all remaining prefix methods from executing, this would be somewhat problematic, since it prevents other mods from running. 

Would it be possible to expose a separate flag that only skips execution of the original method, but allow other prefix methods to run?

**Comment by pardeike** [comment]
I rather advice to not use Prefixes to skip the original. Not unless you provide a logical bail-out in which case multiple mods doing this will have a logic conflict and there is no way to solve this without those mods coordinating (which is possible with Harmony's inspection and priority system. 

If you want your code to run for certain, use a postfix. The problem with your suggestion is that it does not handle the case where multiple prefixes want to skip/not skip the original which is equally conflicting as your original case.
