### ISSUE TITLE
Can't override property getter.

### ISSUE THREAD

**Issue by Vlad-00003** [pardeike/Harmony#70]
So... here I am again =)
And as always - If I'm dumb and this is a simple question, but I just doing everything wrong - just point me to the rigth direction, thanks (^^)/

So - the game has the class ```MapRoomFunctionality```. In this class there is a var - ```float hologramRadius```.
And property - 

	private float mapScale
	{
		get
		{
			return this.hologramRadius / 500f;
		}
	}

that I wanna override.

So, basicly, as I see it - I need to get the ```get_mapScale``` Method. And I get it.
Now - I want to override it's work. I've tried both - prefix that returns false and postfix that just changes the result. None worked. And, what is even more interesting - the patched method isn't being called at all.
Here is my code:

        private static readonly MethodInfo GetMapScale =
            typeof(MapRoomFunctionality).GetMethod("get_mapScale", BindingFlags.NonPublic | BindingFlags.Instance);

        private static readonly MethodInfo GetMapScalePatched =
            typeof(MapRoomFunctionalityPatch).GetMethod("MapScalePostfix", BindingFlags.Static | BindingFlags.Public);
        public static void MapScalePostfix(MapRoomFunctionality __instance, ref float __result)
        {
            __result = __instance.hologramRadius / 1000f;
            Utils.Log($"get_MapScale: {__instance}\n{__instance.hologramRadius} / {1000f} = {__result}");
        }
        internal static void Patch(HarmonyInstance harmony)
        {
            if(GetMapScale == null)
                Utils.Log("Unable to patch MapRoomFunctionality.get_mapScale - Method not found!");
            else
                harmony.Patch(GetMapScale,null, new HarmonyMethod(GetMapScalePatched));
         }

The log isn't being called at all.... Like the function if never used. But it is, I can tell it by changin it's body wia dnSpy.....

Anyone can help me out?)

**Comment by Vlad-00003** [comment]
Oh, and some logs - I've checked if the method is patched already(just in case), then called the patch myself, and then check the method patches again. Here it is:
	8:52 PM [MultiQMod] Method "Single get_mapScale()" is not patched!
	8:52 PM [MultiQMod] Patching "Single get_mapScale()" with "Void MapScalePostfix(MapRoomFunctionality, Single ByRef)"
	8:52 PM [MultiQMod] Logging Prefixes...
	8:52 PM [MultiQMod] Logging Postfixes...
	8:52 PM [MultiQMod] Patch 1:
		Owner: MultiQMod.mod
		Patched method: Void MapScalePostfix(MapRoomFunctionality, Single ByRef)
		Priority: 400
		Before: System.String[]
		After:System.String[]
	8:52 PM [MultiQMod] Loggind Transpilers...
	8:52 PM [MultiQMod] Done!

**Comment by pardeike** [comment]
Most likely that the compiler has inlined the method. Then there is nothing you can do, as the methods assembler code becomes part of the calling methods assembler when the IL code gets jitted

**Comment by Vlad-00003** [comment]
So where is literrally nothing I can do about it? Shame =(
I think I can change the variable, but it's been access from another part of the code, so cnahging it would cause behavour I don't need.... No idea.

**Comment by Vlad-00003** [comment]
Also - another method of patching also doesn't seems to work:

    [HarmonyPatch(typeof(MapRoomFunctionality))]
    [HarmonyPatch("mapScale", PropertyMethod.Getter)]
    class MapRoomFunctionality_getMapScale_Patch
    {
        public static bool Prefix(MapRoomFunctionality __instance, ref float __result)
        {
            FileLog.Log("get_mapScale called!");
            __result = __instance.hologramRadius / QMultiModSettings.Instance.ScannerBlipRange;
            return false;
        }
    }

the code above doesn't seems to do anything.

**Comment by pardeike** [comment]
Please verify that if you disassemble the dll/exe with i.e. ILSpy that the method has IL code. But that won't tell you if its inlined or not. For that, you need to actually look at the resulting assembler code in memory.

**Comment by Vlad-00003** [comment]
@pardeike, if I'm modifying the assembly using dnSpy - it works...

**Comment by Vlad-00003** [comment]
hm... but what can I do? I have no idea how to fight with it...

**Comment by pardeike** [comment]
There is not much you can do except two things:
- you modify the dll on disk
- you find all places in the code where your method is called and patch each of those methods
Both are no good solutions to your problem.

**Comment by Vlad-00003** [comment]
Yeah.... I see. 
Dll patching is not a thing, as we are trying to make that mod work on any game version (with the loader, ofc)
Patching every function? Well, as I remember there was at least.... 12? 15? No idea.
But thanks for the heads up!

**Comment by alexanderabramov** [comment]
I was wondering, is it in theory possible to extend Harmony to prevent JIT inlining?
If I understand correctly, Harmony typically gets executed pretty early, and JIT only inlines functions when it processes them, that is when they are about to be executed.
If that's the case, would dynamically adding [MethodImpl(MethodImplOptions.NoInlining)] to Harmonized methods/properties work to stop JIT inlining?

**Comment by pardeike** [comment]
Inlining is done at call sites. Which makes it tricky to tackle. Also, mono does not respect the no-inlining annotation. I am not sure it’s possible to modify the meta data that controls what gets jitted in which way and it probably is highly architecture dependent making it a nightmare to support for all platforms.
