### ISSUE TITLE
AccessViolation when patching a system class

### ISSUE THREAD

**Issue by fsackur** [pardeike/Harmony#72]
When I attempt to patch HttpClientHandler in System.Net.Http, I get an AccessViolation.

```System.AccessViolationException occurred
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Harmony.ILCopying.Memory.WriteBytes(Int64 memory, Byte[] values)
   at Harmony.ILCopying.Memory.WriteJump(Int64 memory, Int64 destination)
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at Harmony.PatchProcessor.Patch()
```

I am attempting to patch this method:
```private static void SetRequestHeaders(HttpWebRequest webRequest, HttpRequestMessage request)```

When I create my own class with a method of the same name and signature, patching works.

Is this expected behaviour?

**Comment by pardeike** [comment]
Depending on your environment and runtime some memory protection can prevent you from overriding core methods.

**Comment by fsackur** [comment]
Then, by all means, close this.

**Comment by HoLLy-HaCKeR** [comment]
Issue #21 and PR #28.
