### ISSUE TITLE
Incompatible method signature generation for instance methods returning structs

### ISSUE THREAD

**Issue by Zhentar** [pardeike/Harmony#77]
The generated patch method signature is incompatible with the original method for instance methods which return structs larger than 8 bytes, for 64-bit processes with .NET 4.5+. 

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md helpfully explains the cause for us:
> AMD64-only: Up to .NET Framework 4.5, the managed "this" pointer was treated just like the native "this" pointer (meaning it was the second argument when the call used a return buffer and was passed in RDX instead of RCX). Starting with .NET Framework 4.5, it is always the first argument.

Since the generated patch is static with the "this" pointer as the first declared parameter, the jitted code expects the return buffer to be the first parameter and our fake "this" to be the second parameter, but the jitted original method places "this" in the first parameter and the return buffer in the second. And so the jitted patch code inappropriately swaps the values in RCX and RDX, mayhem ensuing.

Repro code:
```cs
	static class Program
	{
		static void Main(string[] args)
		{
			new TestClass().MethodToPatch();
			HarmonyInstance.Create("Repro").PatchAll();
			new TestClass().MethodToPatch();
		}

		[HarmonyPatch(typeof(TestClass),nameof(TestClass.MethodToPatch))]
		class Patch { public static void Postfix() => Console.WriteLine("Evaluated Patch"); }

		public struct TestStruct { public long a, b; }

		public class TestClass
		{
			private readonly string Message = "Test Message";
			private void PrintMessage() => Console.WriteLine(this.Message);

			public TestStruct MethodToPatch()
			{
				this.PrintMessage();
				return new TestStruct() { a =1, b = 2};
			}
		}
	}
```

**Comment by pardeike** [comment]
I also noted that methods defined on `struct`s cannot be patched without corruption. Maybe a similar issue?

**Comment by 0x0ade** [comment]
Coincidentally, I've just fixed this issue independently in MonoMod.RuntimeDetour, and I've been told that Harmony still suffers from the same issue.

https://github.com/0x0ade/MonoMod/commit/4f0e12b00d180e67a79d149a81932b0abef86b3c#diff-e1efd0c033eb1e9cf50c9a64cf40f168R24

The specific changes in question boil down to the "selftest" in the `DetourRuntimeILPlatform` which requires access to the lowest-level detourer, and the `Glue:ThiscallStructRetPtr` `DynamicMethod` generated in the following `GetDetourTarget`.

The selftest runs once when the ILPlatform has been instantiated. It's responsible for testing whether the current runtime requires the fix or not.

I've noticed that the return buffer pointer is exposed as the second parameter, shifting all other parameters by one. The glue `DynamicMethod` thus uses the address provided by parameter 1 behavior (**not** the address of parameter 1), runs the target method and `stobj`s the returned struct into the return buffer.

Even though MonoMod's RuntimeDetour and HookGen components are still "competing" against Harmony, I wish I had more time and energy to port my changes and to submit a PR like I did with #14 and #19.

I've just joined your Discord server if there are any questions :)

**Comment by pardeike** [comment]
I think I roughly get the idea. At this point, i rather want full confidence in understanding the solution than help with the actual implementation. We can continue this discussion on discord. Thanks for the info!

**Comment by pardeike** [comment]
Just pushed changes to master that should fix this issue. I appreciate your work @0x0ade

**Comment by pardeike** [comment]
Seems testing fails with System.OverflowException so I am reopening this
https://gist.github.com/DenJur/1b93c7ad5951e19d004b9e93c7099c7a

**Comment by 0x0ade** [comment]
Replying from phone. Will get into more detail if needed when I get back from work in a few hours.

```
0xdeadbeef > 0x7fffffff
```

`0xdeadbeef` exceeds `int.MaxValue` and `IntPtr` is signed. The value implicitly becomes a signed long during compilation, which no longer fits when running on 32-bit environments.

Switching to `UIntPtr` (implicit `uint`) or a lower value should fix this.

https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwG4CwAUMgMyYBM6AwugN6HoOanYBsmALOgLICGYAdgAoAlLXqMJ2AJyDBASX7AACsABOw1AA8YAUx4wARjp0AzYfgISAvoStA==

**Comment by pardeike** [comment]
Fixed in https://github.com/pardeike/Harmony/commit/61bff7b21976baefc9f1d7c9999fbd7a555df9d0
