### ISSUE TITLE
Constructor patching docs would be great

### ISSUE THREAD

**Issue by protobeard** [pardeike/Harmony#78]
I was attempting to patch a constructor for RimWorld's Building_TrapRearmable class like so:

```
    [HarmonyPatch(typeof(Building_TrapRearmable), ".ctor")]
    public static class RearmThoseTrapsConstructorPatch {

         [HarmonyPostfix]
         public static void ModifyAutoRearmDefault(Building_TrapRearmable __instance) {
             Log.Message("We have a rearmable trap.");
             Traverse.Create(__instance).Field("autoRearm").SetValue(true);
         }
    }
```

which caused RimWorld to barf. On discord, I was informed that __instance isn't available when patching constructors with Harmony. Are there any other gotchas? I didn't see any discussion of constructors as special cases on the wiki, so assumed they would work similar to other methods. Some discussion of caveats and an example in the docs would be fantastic.

**Comment by pardeike** [comment]
It seems that annotations do not support constructors for some reason. Try using TargetMethod() as described in the docs and return the ConstructorInfo in it. I do not see why __instance wouldn’t be defined and working for constructors but keep in mind that you cannot use __result because constructors have a void return type.

**Comment by pardeike** [comment]
Actually, you can. Your code simply does not find the method ".ctor" because there is no such method. Simply omit the name and only supply the argument types to target the constructor:
```csharp
[HarmonyPatch(typeof(TestClass))]
[HarmonyPatch(new Type[] { })]
class Patch
{
	static void Postfix(TestClass __instance)
	{
		__instance.foo = "bar";
	}
}
```

**Comment by pardeike** [comment]
Docs are updated.

**Comment by protobeard** [comment]
Thank you -- that works for me. Doc update looks good as well.
