### ISSUE TITLE
NullReferenceException when patching method

### ISSUE THREAD

**Issue by pipe01** [pardeike/Harmony#80]
I'm trying to patch a static method, but when I try to I get the following error:

![image](https://user-images.githubusercontent.com/3885705/39676945-378d28fa-5173-11e8-9ddd-186f76b37036.png)

This is the original method and how I'm patching it:

```cs
using Harmony;
using System;

namespace DummyClient
{
    class Program
    {
        static HarmonyInstance Harmony = HarmonyInstance.Create("dummyclient");

        static void Main(string[] args)
        {
            Harmony.PatchAll(Assembly.GetExecutingAssembly());
        }

        public static void TestMethod()
        {
            Console.WriteLine("Not patched!");
        }
    }
}
```

Patch method:

```cs
    [HarmonyPatch(typeof(Program), "TestMethod")]
    static class Patch
    {
        static bool Prefix()
        {
            Console.WriteLine("Patched");

            return false;
        }
    }
```

From what I can tell, it looks like `DynamicMethod` doesn't have the method `CreateDynMethod`. I'm running the latest release at the time of writing (1.0.9.1).

**Comment by pardeike** [comment]
That is an old release. It has a lot of problems but it is used in a big modding community where it only runs on mono. I have not released a new version yet because I am still testing the current features/bug fixes. So the problem is sort of expected behavior in 1.0.9.1

Would you mind testing with the latest master?

**Comment by pipe01** [comment]
Yup, it works with when cloning the latest master. Thanks for the quick response!

**Comment by pardeike** [comment]
No problem. Enjoy
