### ISSUE TITLE
Can't patch UnityEngine.Time.time property getter

### ISSUE THREAD

**Issue by pipe01** [pardeike/Harmony#81]
Hey, it's me again. I'm trying to patch Unity's `Time.time` property in order to be able to use my mod assembly in testing but apparently that's not possible:

![image](https://user-images.githubusercontent.com/3885705/39677074-646cd3c8-5175-11e8-9d5c-db89a0aa0889.png)

It says that the method has no body, which when taking a look at the property's definition:
![image](https://user-images.githubusercontent.com/3885705/39677081-7ed59b32-5175-11e8-9b1f-82df0b476f95.png)
seems to be right. In that case, is there any way I can patch that getter?

Here's the patch class:

```cs
[HarmonyPatch(typeof(Time))]
[HarmonyPatch("time", PropertyMethod.Getter)]
static class GetTimePatch
{

}
```

**Comment by pardeike** [comment]
In general, Harmony only patches methods that have IL code in the dll. You can download a disassembled like dnSpy and see if in IL mode the method has content.

**Comment by pipe01** [comment]
Seems like it doesn't have a body. What I ended up doing is adding a dummy body to that method and successfully patching it with Harmony.

**Comment by pardeike** [comment]
Did you do that inside Harmony? I did not even think about that option. Of course you cannot rely on the original functionality in that case (like prefix it with some extra code and Kee the original but that’s better than nothing. Or are you doing something different?

**Comment by pipe01** [comment]
I used dnSpy in order to modify the UnityEngine.CoreModule.dll file and add the body.
