### ISSUE TITLE
Minor Wiki issues

### ISSUE THREAD

**Issue by dymanoid** [pardeike/Harmony#82]
There are some minor Wiki issues that should be fixed. They are sometimes misleading because incorrect terms are used which results in wrong understanding of how to use Harmony.

Page **Target Method Annotations**:

> **[HarmonyPatch(Type[])]** Defines the **attributes** of the method to be patched (only necessary if multiple methods with the same name exist)

Here, the term **attributes** is wrongly used. It should be:

> Describes the **parameters** of the method to be patched (only necessary if multiple methods with the same name or overloads exist, this is then used to find the correct method by its signature)

Further below:

> Patch classes can be public or private, static or not. Patch methods can be public or private but must be static...

What about internal classes? What about internal and protected methods?
Maybe just reword this sentence like this:

> Patch classes can have any access modifier (public, internal, private for nested classes) and can be static or not. Patch methods also can have any access modifier (public, internal, protected, private), but must be static...

Further below:

> It is impossible to patch a method in a generic way.

It's better to point out that the **open generic methods** cannot be patched:

> It is impossible to patch an open generic method.

**Comment by pardeike** [comment]
First part - fixed.

Second part: I think we need to focus on the main fact here: methods (prefix/postfix/transpiler) need to be static. Everything else is irrelevant.

Third: I get your point but the sentence is still very confusing for the average programmer. Can we find a simpler way to express the same thing?

**Comment by dymanoid** [comment]
Regarding the access modifiers: it's up to you, of course, but I would mention "can have any access modifier" anyway.
"Open generic type/method" is actually an established term, but you're right, beginners might still don't know it. Maybe we could explain this a little bit more:

> It is impossible to patch an open generic method. Only methods with provided concrete generic type arguments can be patched: **FooBar&lt;T&gt;(T baz)** cannot be patched while **FooBar&lt;int&gt;(int baz)** can.

**Comment by pardeike** [comment]
Fixed
