### ISSUE TITLE
Can Harmony add methods?

### ISSUE THREAD

**Issue by TonyValenti** [pardeike/Harmony#84]
Hi All,
I've never used harmony before but I've got a few questions.
We use DLL1 which references DLL2.  DLL2 is newer than DLL1 and sometimes DLL1 throws a MissingMethodException.

Can we use Harmony to add (not overwrite, actually add) a method to an existing class?

**Comment by TonyValenti** [comment]
Oh, and this is a mono mac project we're dealing with.

**Comment by jeason1997** [comment]
you can use mono.cecil to inject method into a class

**Comment by pardeike** [comment]
Or find all places in the first dll that call a missing method and replace them with dummies or other alternatives
