### ISSUE TITLE
Clarify the actual code for patching overloaded methods

### ISSUE THREAD

**Issue by saki7** [pardeike/Harmony#88]
We need to use `TargetMethod` specifier when patching overloaded methods. It's quite hard to tell in which case we actually need that specifier. It's nice to have a complete code on the wiki section too.

<https://github.com/pardeike/Harmony/wiki/Patching> :

here:

> TargetMethod (Optional)
> 
> Most of the times, you will use a combination of HarmonyPatch() annotations on the class to define the method you want to patch. **Sometimes though**, it is necessary to calculate the method with code. For this, ...

add:

> Those cases might be when:
> - The target method is overloaded *and* the method has reference parameters (`ref`, `out`)
>   - Note: `System.Type.MakeByRefType` is not constant
> - Switching between overloaded methods conditionally at runtime
> - All other situation which needs target method signature to be built at runtime
>
> C# allows only constant expression for annotations, but the required method information will not be a constant expression in such cases.

add:

```cs
class PatchTargetClass
{
	void TargetMethodName(float p1) { /* ... */ }
	void TargetMethodName(float p1, ref int p2) { /* ... */ }
}
```

```cs
[HarmonyPatch]
class MyPatchClass
{
	static MethodBase TargetMethod()
        {
		return AccessTools.Method(
			typeof(PatchTargetClass),
                	"TargetMethodName",
			new Type[] {
                    		typeof(float),
                    		typeof(int).MakeByRefType(), // note: this is not constant expression
			}
		);
	}
}
```

**Comment by pardeike** [comment]
Yes, this could need clarification. Maybe even featuring the Harmony class AccessTools for working with more extreme cases like private inner classes or compiler generated enumeration delegates and their methods.

**Comment by DoctorVanGogh** [comment]
I'm confused, doesn't a simple
```csharp
[HarmonyPatch(typeof(PatchTargetClass), nameof(PatchTargetClass.TargetMethodName), new[] {typeof(float), typeof(int)} ]
class MyPatchClass
{
	...
}
```
work?

**Comment by DoctorVanGogh** [comment]
Yes, but saki implied you _need_ to use a TargetMethod is you're patching an overloaded method...

> We need to use TargetMethod specifier when patching overloaded methods.

I'm not sure you actually need to do that.

**Comment by pardeike** [comment]
Yes, of course. I got distracted because the issue is pretty trivial in my opinion. The annotation interface has two simple restrictions: 1) you cannot use it on private types/methods and 2) it must be a constant expression. Those cases require a TargetMethod but everything else can be done with annotations.

**Comment by newman55** [comment]
Can you write an example of how to do this? 
Harmony doesn't work for me with ref even if running through the harmony.Patch().

**Comment by pardeike** [comment]
This issue is becoming two issues. I will keep the original title and encourage @newman55 to use the discord or create a new issue.

@saki7: Due to the improvements on the attribute system, this issue has become a bit dated but I keep it open to reflect that I need to update the documentation anyway.

**Comment by saki7** [comment]
@pardeike My original intent was to guide other people to avoid the same pitfalls (overloaded + ref param thingy) that I fell into. I'm happy with any kind of documentation improvements :+1:
