### ISSUE TITLE
Anonimous patch not work?

### ISSUE THREAD

**Issue by ivan-ra** [pardeike/Harmony#89]
this code raises System.ArgumentException:
```c#
	  [TestMethod]
	  public void AnonimousPatch()
	  {
		 var originalMethod = typeof(Class2).GetMethod("Method2");
		 MethodInfo prefix = (new Func<bool>(() => false)).Method;
		 var harmony = HarmonyInstance.Create("my.patches");
		 harmony.Patch(originalMethod, new HarmonyMethod(prefix), null);
	  }
```

**Comment by pardeike** [comment]
Check if `originalMethod` isn’t null. Also: prefix isn’t static (as required)

**Comment by ivan-ra** [comment]
Indeed, now all lambda [non-static](https://stackoverflow.com/a/31651531/4137546)

**Comment by pardeike** [comment]
Patch methods in Harmony need to be static because Harmony cannot serialize over different assemblies once a second assembly tries to patch the same method. Therefore it only serializes global information like MethodInfo that is stateless.
