### ISSUE TITLE
Issues patching property getter

### ISSUE THREAD

**Issue by CBornholdt** [pardeike/Harmony#90]
I was attempting to extend the RimWorld.MainTabWindow_Inspect.get_PaneTopY method, but I'm having difficulties. Attempted patching via both "get_PaneTopY" and the PropertyMethod.Getter as below. 
```c#
        [HarmonyPatch(typeof(MainTabWindow_Inspect))]
	[HarmonyPatch("PaneTopY", PropertyMethod.Getter)]
	public static class MainTabWindow_Inspect_Patch
	{
		private static IEnumerable<CodeInstruction> Transpiler (IEnumerable<CodeInstruction> instructions)
		{
			yield return new CodeInstruction (OpCodes.Ldc_R4, 5f);
			yield return new CodeInstruction (OpCodes.Ret);
		}
	}
```
During my subclass's (of MainTabWindow_Inspect) DoWindowContents method, I have the following code for testing
```c#
                        MethodInfo info = AccessTools.Method (typeof(MainTabWindow_Inspect), "get_PaneTopY");
			MethodInfo info2 = AccessTools.Property (typeof(MainTabWindow_Inspect), "PaneTopY").GetGetMethod ();
			Log.Message ("TopY: " + this.PaneTopY);
			Log.Message ("TopY: " + info.Invoke (this, new object[0]));
			Log.Message ("TopY: " + info2.Invoke(this, new object[0]));
```
The first log message appears to be calling the original unpatched property getter, however the 2nd and 3rd output '5' as expected. What is even more peculiar is after placing logging inside my patch, the patch is being reached even during the first call (which somehow then reaches the original unpatched method). At this point I'm fairly stumped and about to go another direction with this, but felt I should ask first.

Note, PaneTopY is not a virtual property but is defined in an interface (IInspectPane), could that be influencing this? 

Thanks for the great library BTW.

**Comment by pardeike** [comment]
I would guess that the method is inlined during runtime. But I am not 100% sure.

**Comment by pardeike** [comment]
In its current state and ambition level, inlining won’t work nicely with Harmony. And the attribute is only for enabling inlining and not the opposite and won’t work with i.e Unity and their .NET 3.5 compatibility. The only option left is a brute force all-methods patch that searches for call locations and patches the method call there.

**Comment by pardeike** [comment]
I will add a note to the documentation.

**Comment by pardeike** [comment]
Good luck. Let me know if you succerd!
